### ISSUE TITLE
[REQ] Add toggles that change the taskbar's icon, and others, when the launcher's icon is changed

### ISSUE THREAD

**Issue by TheRealSpriteMan1337** [bloxstraplabs/bloxstrap#1143]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?
Before all, this addition _**seems**_ like issue #576, but it **isn't**. Instead of replacing the taskbar icon with the user's chosen icon, without a way to disable it, this suggestion instead proposes something different: 

**A toggle.**
It would go under the selection for the icon. Enabling this would replace the Bloxstrapper icon with whatever icon has been selected from the drop-down menu (or with any custom `*.ico`s which have been provided). It could look something like this incorporated into the UI:
![taskbaricontoggle](https://github.com/pizzaboxer/bloxstrap/assets/78328959/8c28682b-51f2-4b88-ba34-5e988bbbc79e)
Like this in the Desktop:
![desktopicontoggle](https://github.com/pizzaboxer/bloxstrap/assets/78328959/a1db0d0c-af9b-40b1-bf53-dd4bdf14753e)
Like this in the Start Menu:
![startmenuicontoggle](https://github.com/pizzaboxer/bloxstrap/assets/78328959/5d4f4dff-e468-4d8f-aaf9-0a9d34d6abb9)
And like this in the taskbar:
![taskbariconchange](https://github.com/pizzaboxer/bloxstrap/assets/78328959/a9e45440-d84a-4ed9-ad10-a41db5be463a)

### Why should this be added?

**Consistency.** If someone selects an icon to use in the bootstrapper, it should also match the icon in the Desktop, Start Menu and taskbar. And, if the user wants to keep the default Bloxstrapper icon in those locations, they can choose to do so using the toggle.

**Comment by pizzaboxer** [comment]
Reasonable idea, I can take a look into this being a possibility.

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer I observed other software that has more than 1 icon inside their exe. For example, Brave has lots of icons inside their exe.

**Comment by pizzaboxer** [comment]
With how Bloxstrap is planned to work, I'm going to make it so people can have more control over the created shortcuts.

I can't embed the icons as native Win32 resources (which would've allowed you to easily pick it out from the Windows icon picker) without some serious downsides, so I'll just make it where you can choose to export the icons from a folder, where you can then edit the shortcut icon to use.
