### ISSUE TITLE
[REQ] "fake" byfron logo change

### ISSUE THREAD

**Issue by natejw** [bloxstraplabs/bloxstrap#1188]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

we should be able to change the logo in the top left to our own custom logos. then i think the "fake" byfron design would be complete.

**Comment by pizzaboxer** [comment]
I mean, if you want it, then sure.

**Comment by natewombwell** [comment]
ok cool!!!

**Comment by natewombwell** [comment]
shoot acientically closed it :/

**Comment by natewombwell** [comment]
sorry! i was so  close to clicking the normal comment button...
