### ISSUE TITLE
[REQ] Remove the whole fast flag page

### ISSUE THREAD

**Issue by bluepilledgreat** [bloxstraplabs/bloxstrap#1321]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It is joever

**Comment by pizzaboxer** [comment]
Should we have a 2.5.5 patch on standby?

**Comment by GoingCrazyDude** [comment]
![](https://tenor.com/view/drake-gif-5105344)

**Comment by GoingCrazyDude** [comment]
![drake](https://github.com/pizzaboxer/bloxstrap/assets/67791946/303dfde5-1968-435e-8660-249e8b6001c6)

**Comment by xM4rkHUN** [comment]
yeah, it should be better to hide it somehow like OhHeyYouFoundMe or make it to go in the ClientSettings.json and apply flags by there

**Comment by pizzaboxer** [comment]
itll literally do nothing if you try to use it lol whats the point

**Comment by pizzaboxer** [comment]
> man you should not have said anything

?? people already knew before i said anything

**Comment by bluepilledgreat** [comment]
> can you atleast keep the channel switcher if not fastflags

channel switcher isnt being removed. fflags are going to be removed and theres nothing we can do.

**Comment by xM4rkHUN** [comment]
> > can you atleast keep the channel switcher if not fastflags
> 
> channel switcher isnt being removed. fflags are going to be removed and theres nothing we can do.

why is it getting removed? is roblox doing something with fflags or yall just want to avoid the stupid issues caused by fflags?

**Comment by bluepilledgreat** [comment]
> why is it getting removed? is roblox doing something with fflags or yall just want to avoid the stupid issues caused by fflags?

roblox update

**Comment by xM4rkHUN** [comment]
> > why is it getting removed? is roblox doing something with fflags or yall just want to avoid the stupid issues caused by fflags?
> 
> roblox update

what roblox update? i never heard about any fflag update from roblox for a long time

**Comment by bluepilledgreat** [comment]
> what roblox update? i never heard about any fflag update from roblox for a long time

no more fflag update

**Comment by MikeyUsersREC** [comment]
@xM4rkHUN for more elaboration, basically Roblox is nullifying the local changes to FFLags and instead relying on the client settings api for them

**Comment by xM4rkHUN** [comment]
oh, then -1 fflags

**Comment by OrphanObliterator** [comment]
> horrible update atleast hide it behind OhHeyYouFoundMeAgain

i know how to fix it

step 1. 
get good
step 2. follow step 1

**Comment by githubberguy** [comment]
oh no!!! everyone GET CLIENTSETTINGS.JSON OR ROBLOX WILL FUCK YOU!!!!

**Comment by pizzaboxer** [comment]
> I assume roblox will lose many players when removing it

lol be serious now

**Comment by bluepilledgreat** [comment]
@Matthew-MBG We've been asked by staff to not include any workarounds.

**Comment by CatzRule81** [comment]
@bluepilledgreat No mention was ever made of you being contacted by Roblox staff regarding this issue up until now, do you have proof of these claims or are you afraid of something that may not even exist?

**Comment by Vlad55432** [comment]
welp, yhhh

**Comment by MHMHMHM121H** [comment]
A roblox moderator said themself they cant fix single fflags instead of removing them all, execpt they did that with the esp flag they could just do that for all the cheat ones instead of the ones that allow potato pcs to play any hard on the computer game.
