### ISSUE TITLE
[BUG] Weird Issue comes up with Bloxstrap after installing the .NET framework, runs something in the background and no warning.

### ISSUE THREAD

**Issue by kolyphonou** [bloxstraplabs/bloxstrap#1871]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime i try setting up bloxstrap, i have the .net framework, the correct one and the official one. after getting the .net framework bloxstrap randomly stopped launching and not warning me about anything, it starts to run something in my background, i have gotten the one from pizzaboxxer, i have tried several times reinstalling it and it hasn't worked. To this day it still doesn't work.

**Comment by pizzaboxer** [comment]
> after getting the .net framework bloxstrap randomly stopped launching

So it was working before you installed it? What specifically were you installing? What version?

**Comment by kolyphonou** [comment]
It wasn't working in the first place, i was installing the bloxstrap from the github. Yes the creator was pizzaboxer
Latest version, and some other versions. I'd say all of the versions won't work for me.

**Comment by pizzaboxer** [comment]
> It wasn't working in the first place, 

So what do you mean by "bloxstrap randomly stopped launching"? Was it working or not? What was it showing?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by kolyphonou** [comment]
It was showing nothing, not working either, just runs something in the background. It seems like it crashes or something, because whenever i try opening it, it opens up the administrator permission thing then just stops working entirely after i press yes.

**Comment by pizzaboxer** [comment]
Open a Command Prompt window and run this command:

`dotnet --info`

Show a screenshot of what appears

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
