### ISSUE TITLE
[BUG] bloxstrap displaying as context menu container on discord and can't detect presence.

### ISSUE THREAD

**Issue by nieddooooooooooo** [bloxstraplabs/bloxstrap#1940]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[BUG] bloxstrap displaying as context menu container on discord and can't detect presence. I've tried possible fixes and still isn't fixed.

**Comment by moyaimoment** [comment]
What do you mean by "context menu container"?

**Comment by pizzaboxer** [comment]
Is this still happening?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
