### ISSUE TITLE
There is a error on my bloxstrap for not opening it.

### ISSUE THREAD

**Issue by egehankralby** [bloxstraplabs/bloxstrap#2315]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

"System.InvalidOperationException: Cannot start process because a file name has not been provided." this is the error it opens bloxstrap and dosent opens roblox.
![image](https://github.com/pizzaboxer/bloxstrap/assets/133980608/a0fc6d5f-4135-46ab-8065-e45d6e604e01)

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by egehankralby** [comment]
[Bloxstrap_20240711T060007Z.log](https://github.com/user-attachments/files/16172115/Bloxstrap_20240711T060007Z.log)

here

**Comment by pizzaboxer** [comment]
Thanks, I see what's happening. By the way, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

**Comment by egehankralby** [comment]
Thanks for the help it now works properly the issue is: (a) (b) (d) (e) Software running on your computer is conflicting with Roblox
