### ISSUE TITLE
[REQ] Windows 11 3D emojis

### ISSUE THREAD

**Issue by xthemed** [bloxstraplabs/bloxstrap#2335]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

they made the emojis 3d
![image](https://github.com/user-attachments/assets/e5d8d9bc-4efb-4ac7-b0dc-9deeae2eda92)

**Comment by NikSavchenk0** [comment]
sorry roblox is can't support colrv1...

**Comment by MrT-tak** [comment]
wdym colrv1

I think the font for emoji is called [Fluent UI Emoji](https://github.com/microsoft/fluentui-emoji)

**Comment by MrT-tak** [comment]
ohh gradients, well that sucks...

**Comment by pizzaboxer** [comment]
oh damn

**Comment by MrT-tak** [comment]
@pizzaboxer  ty. this will probably go no where until Roblox implements roblox logo with gradient as emoji :(
