### ISSUE TITLE
Missing credits (german)

### ISSUE THREAD

**Issue by TeamLila** [bloxstraplabs/bloxstrap#2350]
i have realised that for some reason, over half of the german translators dont get any recognition in the credits section
![image](https://github.com/user-attachments/assets/c421cd64-09b8-42f9-b17d-f3d64c44b779)
![image](https://github.com/user-attachments/assets/5682046a-061d-45bb-88b6-e244fb16f4bc)

**Comment by pizzaboxer** [comment]
I probably missed those because of how early I captured the contributor list, sorry.

Also, can I ask how you get to that view of all the translators for a specific language? I've been trying to find that and can't.

**Comment by TeamLila** [comment]
https://github.com/user-attachments/assets/5a9b7d41-5c23-4c85-a455-cff912050bc5

(Hope i hit the right recording) this is how to do it on mobile, but same idea with PC

**Comment by TeamLila** [comment]
![image](https://github.com/user-attachments/assets/c6b2f525-fd98-4c7f-bd91-8fb55e332e20)
wanted to ask if this is still being recognised and fixed or if you forgot as its been a month since i heard anything

**Comment by pizzaboxer** [comment]
Yes, they'll be fixed. They'll need to be double-checked fixed for all language contributors, actually, not just German.
