### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PrivateServersGANG** [bloxstraplabs/bloxstrap#2430]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Shaw (Extremely popular internet provider in Canada) is blacklisting bloxstrap if the user has "Advanced Security" set on
![Screenshot_20240719_142148_HomeConnect](https://github.com/user-attachments/assets/f5f84f56-92a0-41d9-aaf7-19e0cca170b4)
Blacklists any URL with bloxstrap.*

Discord thread id "1263952551540166656"

**Comment by ShadowCodeX-debug** [comment]
bloxstrap.pizzaboxer.xyz is the real website these are just false-positives. However, bloxstrap.org is a fake website that... well I don't know actually, people say it literally is just a website that gives a real Bloxstrap installer.

**Comment by pizzaboxer** [comment]
I'd like to contact them but this happens for whatever reason: 

![image](https://github.com/user-attachments/assets/2092e268-7e5e-4f3b-a571-8d35a419a400)

So I can't really do anything about it. If you're willing to put forward a tip then that would be nice.

**Comment by PrivateServersGANG** [comment]
give me the message to send it to them

**Comment by pizzaboxer** [comment]
Just tell them something along the lines of "https://bloxstrap.pizzaboxer.xyz is falsely being blocked for being malicious, when it is a legitimate website as shown on https://github.com/pizzaboxer/bloxstrap"

**Comment by PrivateServersGANG** [comment]
done
