### ISSUE TITLE
[BUG] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SmokeyPlayz** [bloxstraplabs/bloxstrap#2468]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

gotten fflag list from an discord helper in the server my name is siri once i added that error popped up 
[Bloxstrap_20240723T182707Z.log](https://github.com/user-attachments/files/16353022/Bloxstrap_20240723T182707Z.log)
[Flemish Fps fflags .json](https://github.com/user-attachments/files/16353028/Flemish.Fps.fflags.json)

**Comment by pizzaboxer** [comment]
Flag list so shittily made that it somehow manages to crash the editor. Incredible. 

![image](https://github.com/user-attachments/assets/0a6e50f5-ebcf-4b13-980d-9a67b477cb17)

Genuinely, how?

While this is a bug on my side, you shouldn't be using this list anyway. You can get rid of it by going to `%localappdata%\Bloxstrap\Modifications\ClientSettings` and deleting ClientAppSettings.json.

**Comment by SmokeyPlayz** [comment]
do u have an better list that good for performance only since i gotten that from an helper i'm mainly focus on fps/performance smooth as possible i am running on AMD mid/low  end pc

**Comment by pizzaboxer** [comment]
No I don't, and I don't recommend you use any such lists.

**Comment by SmokeyPlayz** [comment]
ah quite sad actuallly since your the owner i kinda expected such knowledge of these and would've provide an custom list of fflags that will improve my performance i don't really care how ungly roblox is as long it would've been playable i play The strongest battle ground and my game be feeling chopping sometimes even on my mid end pc

**Comment by pizzaboxer** [comment]
> i kinda expected such knowledge of these and would've provide an custom list of fflags 

Given my very clear all-around advice regarding these is to not use lists whatsoever, I'm not sure why you'd think that.
