### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by flyingman-crypto** [bloxstraplabs/bloxstrap#2533]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when trying to run blox trap, an error appears Bloxstrap cannot connect to roblox. help solve this problem thanks in advance
![2024-07-31_20-36-26](https://github.com/user-attachments/assets/5167e9c7-7be1-4d82-9a09-cd3a5f9d5374)

**Comment by flyingman-crypto** [comment]
If anything, I have an internet connection

**Comment by pizzaboxer** [comment]
Get Bloxstrap's latest log file and send it here. If you're installing for the first time it'll be in `%temp%`, sort by newest to find it. If you're not, it'll be in `%localappdata%\Bloxstrap\Logs`

**Comment by flyingman-crypto** [comment]
Can't find it "C:\Users\User\AppData
Local\Bloxstrap\Logs". Check if the name is correct and try again.  returns this error when entering %localappdata%\Bloxstrap\Logs

**Comment by pizzaboxer** [comment]
Have you installed Bloxstrap? Where to? If not, get it from %temp% (sort by date modified)

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
