### ISSUE TITLE
[BUG] Error 268.

### ISSUE THREAD

**Issue by realcgcristi** [bloxstraplabs/bloxstrap#2601]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Even though i am not hacking i get this error, i reinstalled. i followed multiple guides, restarted multiple times, etc.

![image](https://github.com/user-attachments/assets/da8c1d84-a442-40bf-aef8-7e31c0f2d0c5)

**Comment by ShadowCodeX-debug** [comment]
What are you doing before this pop up appears?

**Comment by realcgcristi** [comment]
i wasnt doing anything else, i opened my computer, opened roblox and experienced this

**Comment by ShadowCodeX-debug** [comment]
I guess try doing a complete reinstall (Uninstalling through the control panel or settings app, then deleting the Bloxstrap folder)

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by realcgcristi** [comment]
Only with bloxstrap happens, I did do reinstall through control panel, and nothing.

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by realcgcristi** [comment]
[Settings.json](https://github.com/user-attachments/files/16821352/Settings.json)
[State.json](https://github.com/user-attachments/files/16821353/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16821355/ClientAppSettings.json)
here

**Comment by realcgcristi** [comment]
My antivirus is off though, same with firewall, and i dont have any 3rd party antivirus/firewall

**Comment by pizzaboxer** [comment]
You have a completely stock config, there isn't any real reason for variations like this to be happening unless something external was interfering.

**Comment by realcgcristi** [comment]
I'll look more into firewall, etc. and see what i can do

**Comment by pizzaboxer** [comment]
Assuming issue is resolved
