### ISSUE TITLE
[BUG] it doesnt close roblox when i close the game.

### ISSUE THREAD

**Issue by fartfacebill61** [bloxstraplabs/bloxstrap#2615]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when i leave the game, instead of putting me back to the website it brings me to the app! i have 2.7.0. installed. i have the "don't exit to roblox app" setting turned on. its been doing this for ages. please help

**Comment by pizzaboxer** [comment]
This happens reliably every time you play Roblox? Get the latest log file from `%localappdata%\Bloxstrap\Logs` and send it here please

**Comment by fartfacebill61** [comment]
I'm so sorry! I forgot to close this! Just after I posted this I realised nothing worked on bloxstrap and that it all worked on the Roblox studio client instead. I managed to fix it though - thanks for the help anyways

**Comment by pizzaboxer** [comment]
> it all worked on the Roblox studio client instead

What?

**Comment by fartfacebill61** [comment]
yeah anything I changed on the bloxstrap menu would affect Roblox studio instead.

**Comment by pizzaboxer** [comment]
Any settings in specific or was it literally all of them?

**Comment by fartfacebill61** [comment]
literally all of them. nothing I did made a difference. what happened is that I got a Roblox update and instead of bloxstrap booting up it was actual Roblox instead. and then once I realised it I just forced bloxstrap to open which in turn made it start updating.

**Comment by fartfacebill61** [comment]
> Give an example of a setting that would affect Roblox Studio since I'm still sorta confused

a setting that affected it was the menu settings and the look it had. I didnt test out the fps changer so I couldn't tell you about that. possibly brought back the oof sound. I think it changed my mouse cursor too.

sadly it stopped working the other day :'(

**Comment by pizzaboxer** [comment]
If you ever encounter this again for some reason, send me the latest log file.

**Comment by fartfacebill61** [comment]
> If you ever encounter this again for some reason, send me the latest log file.

will do
