### ISSUE TITLE
[BUG] .NET error

### ISSUE THREAD

**Issue by madder231** [bloxstraplabs/bloxstrap#2616]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I try to open Bloxtrap but it says I require a newer version of .NET framework, so I downloaded it. But I installed Bloxtrap after me downloading the framework and it still says I need version 6.0 even though I just installed it. No matter what i download it keeps saying that I need to download a newer framework. Thanks for your time.

**Comment by pizzaboxer** [comment]
Open a Command Prompt window, run this command:

`dotnet --info`

Show a screenshot of what appears

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
