### ISSUE TITLE
[REQ] Font Size should support negatives

### ISSUE THREAD

**Issue by OneBitOfHope** [bloxstraplabs/bloxstrap#2631]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### Why should they?

Font sizes can vary to the point that 0 isn't small enough to make a font fit properly. Also from what i've seen, setting a negative font manually with the fast flag works fine(though probably depends on the font you use)

Alternatively, maybe just make font size represent the actual font size instead of the fastflag input?

**Comment by ShadowCodeX-debug** [comment]
I would like to mention, Bloxstrap cannot modify the Roblox client.

**Comment by pizzaboxer** [comment]
> Also from what i've seen, setting a negative font manually with the fast flag works fine(though probably depends on the font you use)
