### ISSUE TITLE
[BUG] Game stays on loading screen for awhile despite me being able to drag the window and see it properly while also being able to hear audio

### ISSUE THREAD

**Issue by Slayercorpps** [bloxstraplabs/bloxstrap#2639]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

It doesnt load, instead it freezes without freezing my game and it has absurd waiting times for me to play especially when playing games where you teleport places alot like type soul

**Comment by Slayercorpps** [comment]
![image](https://github.com/user-attachments/assets/7b0305b6-bbaf-4e0c-8e4b-a2842d019135)

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Slayercorpps** [comment]
it only appears in a heavy loading game like type soul, even when entering the game for the first time

from the data i recorded yes because theirs a higher chance to load faster in light games like swfl

**Comment by pizzaboxer** [comment]
Just to be clear, this doesn't happen on any game at all with the original launcher?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
