### ISSUE TITLE
[BUG] Freezing

### ISSUE THREAD

**Issue by Freakuhzoidd** [bloxstraplabs/bloxstrap#2641]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

 My game keeps freezing and everything was fine before and i cant do nothing about it i have uninstalled and did everything and i still can do nothing ive tried restaring my pc and everything but i cant do anything for some reason please help im just tryning to play with my freinds

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
