### ISSUE TITLE
[BUG] Bloxstrap Roblox crashing after 20-30 minutes of playtime.

### ISSUE THREAD

**Issue by Andi998ro** [bloxstraplabs/bloxstrap#2645]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I play ROBLOX on the Bloxstrap launcher, it crashes after twenty to thirty moments, On the simple launcher, I don't experience any issues with it.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Andi998ro** [comment]
> Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

I have no FastFlags.

**Comment by Andi998ro** [comment]
> Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

{
  "BootstrapperStyle": 6,
  "BootstrapperIcon": 0,
  "BootstrapperTitle": "Bloxstrap",
  "BootstrapperIconCustomLocation": "",
  "Theme": 0,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "ConfirmLaunches": false,
  "Locale": "nil",
  "ForceRobloxLanguage": false,
  "UseFastFlagManager": true,
  "Channel": "LIVE",
  "EnableActivityTracking": true,
  "UseDiscordRichPresence": true,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}


{
  "ShowFFlagEditorWarning": true,
  "PlayerVersionGuid": "version-6fdcfe060c6440cd",
  "StudioVersionGuid": "",
  "PlayerSize": 432828,
  "StudioSize": 0,
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg"
  ]
}

{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7"
}

**Comment by pizzaboxer** [comment]
Strange. Just as a precaution, can you go into the Bloxstrap Menu, go to the Fast Flags tab, diasble the option to use fast flags, save and see if that changes anything?

**Comment by Andi998ro** [comment]
> Strange. Just as a precaution, can you go into the Bloxstrap Menu, go to the Fast Flags tab, diasble the option to use fast flags, save and see if that changes anything?

Did it a hour ago, and it still crashes, every crash it becomes more frequent until I don’t play for a long time.

**Comment by Andi998ro** [comment]
> Strange. Just as a precaution, can you go into the Bloxstrap Menu, go to the Fast Flags tab, diasble the option to use fast flags, save and see if that changes anything?

Updates

**Comment by pizzaboxer** [comment]
> Did it a hour ago, and it still crashes, every crash it becomes more frequent until I don’t play for a long time.

Does disabling the old death sound mod change anything?

**Comment by Andi998ro** [comment]
> > Did it a hour ago, and it still crashes, every crash it becomes more frequent until I don’t play for a long time.
> 
> Does disabling the old death sound mod change anything?

no

**Comment by pizzaboxer** [comment]
Well then I can't see what else could be causing this, you're basically on a stock config. Try opening the `%localappdata%\Bloxstrap\Versions` folder, directly run RobloxPlayerBeta.exe, see if that changes anything.
