### ISSUE TITLE
[BUG] Playing A roblox Game Status On Discord Is not showing, i did all steps but nothing works yet.

### ISSUE THREAD

**Issue by SanadPlays** [bloxstraplabs/bloxstrap#2646]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

The games i play using roblox dont show on discord, i use play roblox tab which is linked to bloxstrap. ive did all steps but nothing working

**Comment by pizzaboxer** [comment]
Thanks for reporting, can you send the latest log file from `%localappdata%\Bloxstrap\Logs` please?

**Comment by SanadPlays** [comment]
Issue solved

**Comment by cinaxdev** [comment]
> Issue solved
> […](#)

how?
