### ISSUE TITLE
[BUG] Cancel button is always greyed-out

### ISSUE THREAD

**Issue by PhoenixWhitefire** [bloxstraplabs/bloxstrap#2662]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

The "Cancel" button on the Bootstrapper popup menu is always greyed out and I never seem to be able to cancel startup. Happens regardless of whether I am launching a game or opening it directly with the "Play Roblox" shortcut it creates.

What led me to realize this was when I clicked a Join link someone had sent in Roblox Chat that opens to a Private Server, except there was no Play button and I assumed it would simply take me to that Private Server page without me actually joining it.

I am on version `2.7.0`.

**Comment by ShadowCodeX-debug** [comment]
It's purely cosmetic I think. I don't even think there's any process that waits for that button

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer why isn't it possible for you to make that cancel button work?

**Comment by PhoenixWhitefire** [comment]
@ShadowCodeX-debug it doesn't appear like it was intended to just be cosmetic:

https://github.com/pizzaboxer/bloxstrap/blob/de82349e5eeee80ad9475a2b2457c118b8f94b61/Bloxstrap/UI/Elements/Bootstrapper/Base/WinFormsDialogBase.cs#L106

There is also some code that attempts to _enable_ the cancel button, such as:

https://github.com/pizzaboxer/bloxstrap/blob/de82349e5eeee80ad9475a2b2457c118b8f94b61/Bloxstrap/Bootstrapper.cs#L612

So no, I don't think it was just meant to be cosmetic. Please, don't just say stuff like that. How do you know for sure?

**Comment by pizzaboxer** [comment]
The cancel button is only made available while Roblox is installing/upgrading (which is what line 612 is), i.e. tasks that actually take a long time. The stock bootstrapper behaves like this too. It's intentional.

I do plan to make it available all the time so it can abort a Roblox launch too instead of only applying to installs/upgrades, but not currently.

**Comment by ShadowCodeX-debug** [comment]
Well in this case, @pizzaboxer can you make- if bootstrapper window is focused, pressing a key will also cancel launch like ESC or something.
