### ISSUE TITLE
[REQ] Easy Bug Reporting

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [bloxstraplabs/bloxstrap#2666]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

A button (aptly named "Report bug") which when pressed, will send you to the github issue.. maker... with some metadata (or whatever the term is) like the log file and configuration, as well as the error message content.

I know this is possible because another software does this, Cider.

**Comment by Roblox-Thot** [comment]
I think it would be possible to do stuff like commit hash, version, and os version.
But I don't think the prefilled data supports auto uploading files since that would make the URL too long.

Cider for example auto fills OS, Commit hash, instance, and Build time.

**Comment by pizzaboxer** [comment]
That's true, it is possible, I didn't think about doing that.
