### ISSUE TITLE
[BUG] the game freezes for a few seconds when entering the menu

### ISSUE THREAD

**Issue by bulyoff** [bloxstraplabs/bloxstrap#2695]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

in some places, when you enter the menu, the game freezes for a few seconds

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
If so, upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
