### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'D:\Program Files\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by amirreal10** [bloxstraplabs/bloxstrap#2698]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'D:\Program Files\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
This is an issue with your system permissions. Do you want to keep it installed there or do you want to reinstall it somewhere else (like the default choice of the AppData folder)?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
