### ISSUE TITLE
[BUG] 2022 menu bugged

### ISSUE THREAD

**Issue by mrpiggy100** [bloxstraplabs/bloxstrap#2718]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I select 2022 menu on bloxtrap, it brings up the 2015 esc menu instead of the 2022 menu. I made sure that I had 2022 menu selected on fastflags and reinstalled my bloxtrap. The same issue still occurs. Some of my friends also are having this issue.
![image_2024-08-21_195225446](https://github.com/user-attachments/assets/8ce70e5d-44e3-46fd-bd44-afef6d724579)
![image_2024-08-21_195312062](https://github.com/user-attachments/assets/65f9f205-eaa7-42fd-bb0a-95007b53ae46)

**Comment by awsomeguy1445** [comment]
roblox updated prob

**Comment by dayanindo** [comment]
Hopefully it get fixed lol
Because i like the menu on the side

**Comment by bluepilledgreat** [comment]
Roblox has removed the V2 menu.

**Comment by pizzaboxer** [comment]
I'll reopen this to keep myself reminded that the option needs to be removed

**Comment by NoureldinK** [comment]
> I'll reopen this to keep myself reminded that the option needs to be removed

Hey Mr.Pizzaboxer, is there any way you could add it back to the options instead of removing it, it was my favourite escape menu and i really got used to it, I’d be glad if you could add it if not is there a way atleast to get it back or not 

thank you for your help!

**Comment by mrpiggy100** [comment]
There is a fast flag I found in the dev forum that can fix this problem
 https://devforum.roblox.com/t/how-to-get-the-new-roblox-menu/2398925

Just ignore the steps and paste it into the bloxtrap fastflags sections as a JSON and then set your ESC menu to default it worked for me

**Comment by pizzaboxer** [comment]
No kidding, `FFlagDisableNewIGMinDUA` may have been removed but `FStringNewInGameMenuForcedUserIds` still works. Wouldn't have caught that, thanks for that.

Though, that means that the user needs to enter their user ID if they want this to work. Maybe.
