### ISSUE TITLE
[BUG] Fast flag's arent working. 

### ISSUE THREAD

**Issue by momofr69** [bloxstraplabs/bloxstrap#2727]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Im trying to get accessory adjustments enabled but it isnt working pls help.
I've tried capatilzing the T and i've retried multiple times. Pls help

**Comment by pizzaboxer** [comment]
Isn't that something you adjust on the website?

**Comment by momofr69** [comment]
Idk bc the other fast flags I have set are working. Its just the accesory ones

**Comment by pizzaboxer** [comment]
Can you post them here please?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
