### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MichaelIrwin03** [bloxstraplabs/bloxstrap#2728]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

the menu of 2019 has been deleted in my bloxstrap, i can't use it anymore. can u help me update?

**Comment by pizzaboxer** [comment]
There's no 2019 menu?
