### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Suharick337** [bloxstraplabs/bloxstrap#2732]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when my account was blocked, I log into bloxtrap and bloxtrap freezes

**Comment by pizzaboxer** [comment]
Can you please clarify?

**Comment by Suharick337** [comment]
> Can you please clarify?

На экране бана аккаунта в роблоксе bloxtrap зависает

**Comment by pizzaboxer** [comment]
Try switching back to the original launcher, see if it works there, then switch back afterwards. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Suharick337** [comment]
> Try switching back to the original launcher, see if it works there, then switch back afterwards. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I just want you to fix this bug.

**Comment by pizzaboxer** [comment]
And I want you to see if it's a problem with Bloxstrap first. If it is, then I'll try to fix it. If it isn't, then it's not my problem. You're not being very helpful.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
