### ISSUE TITLE
[BUG] Cancelling is incredibly buggy

### ISSUE THREAD

**Issue by bluepilledgreat** [bloxstraplabs/bloxstrap#2758]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Please fix

**Comment by pizzaboxer** [comment]
ok buddy
