### ISSUE TITLE
[REQ] Rename 'Fast Flags' to 'Engine Settings'

### ISSUE THREAD

**Issue by bluepilledgreat** [bloxstraplabs/bloxstrap#2760]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

.

**Comment by Shavixinio** [comment]
Why if they **are** a FastFlag?

**Comment by BlueOutside** [comment]
> Why if they **are** a FastFlag?

The rename to Engine Settings is because of what FastFlag translates to in other lang which is weird compared to Engine Settings

**Comment by pizzaboxer** [comment]
Yes

**Comment by Shavixinio** [comment]
It still wouldn't make sense, the roblox config settings are called FastFlags and it would just be kind of misleading if you renamed it to something else, don't really see it as a needed change

**Comment by bluepilledgreat** [comment]
Not everyone knows what a "fast flag" is. Engine settings is more appropriate in my opinion.

**Comment by Shavixinio** [comment]
That's a much better point than "weird translation".

**Comment by ShadowCodeX-debug** [comment]
Even Better "Engine Configuration" (or Config).
