### ISSUE TITLE
[BUG] Bloxstrap updates when launching from website

### ISSUE THREAD

**Issue by PizzaGod873** [bloxstraplabs/bloxstrap#2770]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I have auto-update off
Sorry for few details

**Comment by pizzaboxer** [comment]
Like, it's updating to the latest version when you have auto-update off?

**Comment by PizzaGod873** [comment]
Yes. When launching from the website, it launches bloxstrap.exe which auto updates even if I have it off.

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by PizzaGod873** [comment]
I don't need this anymore.
