### ISSUE TITLE
[BUG] fast flags not working

### ISSUE THREAD

**Issue by yazu1** [bloxstraplabs/bloxstrap#2771]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.

### What problem did you encounter?

my fast flags don’t work they were working for a couple days the exact same ones and randomly they stopped working yesterday but my special cursor still shows up and my roblox logo but not my textures so i tried uninstalling and reinstalling it worked now im in the same problem uninstalling and reinstalling won’t work ive tried restarting my laptop losing roblox up diffrently nothing is working

**Comment by pizzaboxer** [comment]
What config are you using? https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by gamerpro2345** [comment]
[Settings.json](https://github.com/user-attachments/files/16797643/Settings.json)
[State.json](https://github.com/user-attachments/files/16797644/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16797646/ClientAppSettings.json)
This is the stuff I found in appdata.

**Comment by Tomloyo** [comment]
I have the same issue:
State.json
```
{
  "ShowFFlagEditorWarning": false,
  "PlayerVersionGuid": "version-d2bde6b0a05e4840",
  "StudioVersionGuid": "",
  "PlayerSize": 442485,
  "StudioSize": 0,
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg"
  ]
}
```
Settings.json
```
{
  "BootstrapperStyle": 2,
  "BootstrapperIcon": 2,
  "BootstrapperTitle": "bss simulator ahh game",
  "BootstrapperIconCustomLocation": "",
  "Theme": 2,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "ConfirmLaunches": false,
  "Locale": "en",
  "ForceRobloxLanguage": false,
  "UseFastFlagManager": true,
  "Channel": "LIVE",
  "EnableActivityTracking": true,
  "UseDiscordRichPresence": true,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}
```
Modifications (ffs)
```
{
  "FLogNetwork": "7",
  "FIntFullscreenTitleBarTriggerDelayMillis": "3600000",
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableInGameMenuControls": "True",
  "FFlagEnableInGameMenuModernization": "True",
  "FFlagEnableInGameMenuChrome": "False",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagEnableInGameMenuChromeABTest3": "False",

  
  "DFIntDataSenderMaxBandwidthBps": "600"
}
```

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
