### ISSUE TITLE
[BUG] Roblox Authentication Error code 403.

### ISSUE THREAD

**Issue by ToxicTDX** [bloxstraplabs/bloxstrap#2773]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I Try to launch roblox from the website and it shows that authentication error. I Tried whatever the other guy in the issues did, still didnt work. Help would be appreciated.

### Bloxstrap Log

N/A

**Comment by pexotiic** [comment]
You are banned from roblox on an account right

**Comment by NabHeyka22** [comment]
_"I have thoroughly looked through the available Wiki articles and could not find a solution to my problem."_

blind ass mother fucker
but if you didn't find it, **UPDATE!! FUCKING UPDATE!!** and if you want multi instance use roblox account manager

**Comment by Storm-930** [comment]
is the third checkbox a lie

**Comment by NabHeyka22** [comment]
yes

**Comment by ToxicTDX** [comment]
> _"I have thoroughly looked through the available Wiki articles and could not find a solution to my problem."_
> 
> blind ass mother fucker but if you didn't find it, **UPDATE!! FUCKING UPDATE!!** and if you want multi instance use roblox account manager

turns out i was updated :O i was banned on an alt account for spamming

**Comment by pizzaboxer** [comment]
oh, matt interpreted this as being the wrong error, sorry about that

This doesn't happen if you use the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ppgmg123** [comment]
still happening to me as of now. I tried deleting roblox completely also through appdata and reinstalled it, and my bloxstrap is 2.7.0. I need help with this.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
