### ISSUE TITLE
[REQ] Is there a fastflag to increase or lower Decals/Particles density?

### ISSUE THREAD

**Issue by NotNoxxie** [bloxstraplabs/bloxstrap#2779]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

example: when you increase/lower the graphics, more/less particles spawn. (With lower graphics the visual effects barely exist)

**Comment by pizzaboxer** [comment]
Good question, I don't know, and after a quick look, I can't really seem to find anything. I'll keep this open in case anyone has any input.
