### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'item')

### ISSUE THREAD

**Issue by 00000000000000000001ai** [bloxstraplabs/bloxstrap#2789]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### When I tried to change the value in FStringDebugShowFlagState to DFFlagRakNetDecoupleRecvAndUpdateLoopShutdown_DataCenterFilter

Name:**FStringDebugShowFlagState**
Value:**DFFlagRakNetDecoupleRecvAndUpdateLoopShutdown_DataCenterFilter**

### Bloxstrap Log

[Bloxstrap_20240831T173744Z.log](https://github.com/user-attachments/files/16825679/Bloxstrap_20240831T173744Z.log)

**Comment by Storm-930** [comment]
my oh my man
please elaborate the issue further
from my understanding you tried changing flag A to flag B but it didn't work?

**Comment by Storm-930** [comment]
also, next time, actually read the checkboxes and dont mark them all, we know you put in that last one

**Comment by Storm-930** [comment]
ok found the issue
AND I QUOTE, EN VERBATIM
`2024-08-31T17:37:49Z [Frontend::ShowMessageBox] You appear to be importing a very large configuration. You should only be importing configurations that you fully understand. Do NOT blindly paste in configurations made by other people. If you continue, you will very likely end up with stability issues and encounter unexpected changes.`

**Comment by Storm-930** [comment]
and now, i shall add my own ranting because of the huge flag copypaste
![image](https://github.com/user-attachments/assets/fad0ee90-0b8a-4ab7-8fd0-62b446192c40)

**Comment by pizzaboxer** [comment]
This is indeed a bug that needs to be fixed. However, Storm is right. Whatever you're importing is just complete junk. I suggest you don't use it.
