### ISSUE TITLE
[BUG] Bloxstrap Doesnt open

### ISSUE THREAD

**Issue by Soptan** [bloxstraplabs/bloxstrap#2794]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I Try To Open BloxStrap It Just opens Roblox In A mimimized Screen And Then Closes, i tried playing roblox without bloxstrap and it didnt close, This Happened When I Tried To Install Bloxshade, I Moved A File To Anothor Location, when i saw bloxstrap crashing i deleted bloxshade, i dont know what to do Now.

### Bloxstrap Log

N/A

**Comment by puertoricanprincess** [comment]
> Uninstall Bloxshade, and reinstall Bloxstrap. See if it works after then.

doesn't work

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
