### ISSUE TITLE
[BUG] Font Change Doesn't Remove Custom Font

### ISSUE THREAD

**Issue by Cosmeticaaaaa** [bloxstraplabs/bloxstrap#2797]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I try to remove a certain font using the "Use Custom Font" option the font doesn't go back to the default Roblox font.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
