### ISSUE TITLE
[BUG] bloxstrap not opening

### ISSUE THREAD

**Issue by puertoricanprincess** [bloxstraplabs/bloxstrap#2799]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when i try to install bloxstrap its loads up and doesn't launch

https://github.com/user-attachments/assets/01d2eeb9-0d6c-4a52-a038-0f4afa5175c9

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
