### ISSUE TITLE
[BUG] the .exe doesn't install bloxstrap

### ISSUE THREAD

**Issue by mccjjc** [bloxstraplabs/bloxstrap#2811]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When i execute the .exe, nothing appears, it loads and ends without opening the app.

### Bloxstrap Log

When i execute the .exe, nothing appears, it loads and ends without opening the app.

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
