### ISSUE TITLE
[BUG] Advanced graphics quality selector does not work

### ISSUE THREAD

**Issue by gaming18192** [bloxstraplabs/bloxstrap#2812]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The graphics quality bar stays at 10 no matter what. I have removed all custom fast flags, reinstalled Bloxstrap, restarted my computer, and made sure the "Allow Bloxstrap to manage fast flags" setting was checked.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
@pizzaboxer The flag has been removed in the latest release of Roblox. Can you please remove it from the launcher?

**Comment by pizzaboxer** [comment]
got it
