### ISSUE TITLE
[BUG] Bloxstrap not loading into roblox.

### ISSUE THREAD

**Issue by DANTCHY** [bloxstraplabs/bloxstrap#2814]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Trying to open roblox

### Bloxstrap Log

[Bloxstrap_20240904T093245Z.log](https://github.com/user-attachments/files/16868071/Bloxstrap_20240904T093245Z.log)

**Comment by bluepilledgreat** [comment]
Can you send the log file from when Bloxstrap did not open Roblox? The attached log file is you opening the menu.

**Comment by DANTCHY** [comment]
[Bloxstrap_20240905T065822Z.log](https://github.com/user-attachments/files/16885266/Bloxstrap_20240905T065822Z.log)
Here is the log when I open Roblox it just closes in the background apps section as soon as it says starting roblox can you please help me.

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
