### ISSUE TITLE
[BUG] my bloxstrap settings aren't loading in

### ISSUE THREAD

**Issue by cavaan** [bloxstraplabs/bloxstrap#2815]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

My bloxstarp settings didnt load after the new roblox update

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Can you send your log file?

**Comment by cavaan** [comment]
[Bloxstrap_20240904T095240Z.log](https://github.com/user-attachments/files/16868362/Bloxstrap_20240904T095240Z.log)

**Comment by bluepilledgreat** [comment]
> [Bloxstrap_20240904T095240Z.log](https://github.com/user-attachments/files/16868362/Bloxstrap_20240904T095240Z.log)

I'm not noticing any problems in here. By "bloxstarp settings" do you mean the settings inside the Roblox client or the actual Bloxstrap settings?

**Comment by cavaan** [comment]
> > [Bloxstrap_20240904T095240Z.log](https://github.com/user-attachments/files/16868362/Bloxstrap_20240904T095240Z.log)
> 
> I'm not noticing any problems in here. By "bloxstarp settings" do you mean the settings inside the Roblox client or the actual Bloxstrap settings?

bloxstrap settings
soprry for the poor grammar english is my second language

**Comment by pizzaboxer** [comment]
Give examples of some settings that aren't working

**Comment by cavaan** [comment]
> Give examples of some settings that aren't working

advanced graphics selector, see server location and old death sound

**Comment by pizzaboxer** [comment]
Advanced graphics selector is known to not be working, that's fine. Do you see the Bloxstrap launcher window show when you launch Roblox?

**Comment by cavaan** [comment]
> Advanced graphics selector is known to not be working, that's fine. Do you see the Bloxstrap launcher window show when you launch Roblox?

yeah

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by darinyoo** [comment]
i have same issue i change the fps it doesnt work even other settings it stays on the old one :/

**Comment by pizzaboxer** [comment]
> i have same issue i change the fps it doesnt work even other settings it stays on the old one :/

Do you see the Bloxstrap launcher show when Roblox launches?

**Comment by pizzaboxer** [comment]
Upload your configuration please, I need a better idea of what settings you're talking about: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by darinyoo** [comment]
> Upload your configuration please, I need a better idea of what settings you're talking about: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

![Screenshot 2024-09-22 161505](https://github.com/user-attachments/assets/25b227e1-7469-4608-88fe-ae836f82ac2a)
![Screenshot 2024-09-22 162035](https://github.com/user-attachments/assets/83ba20a4-d4ae-439f-9d88-7f9f75bf9e80)
done?

**Comment by pizzaboxer** [comment]
You didn't upload ClientAppSettings.json

**Comment by darinyoo** [comment]
> You didn't upload ClientAppSettings.json

sorry i was busy with school and i forgot to send cilentappsettings.json and i also have updated my settings in bloxstrap menu so im gonna send in once all again (new one)
![Screenshot 2024-10-03 181715](https://github.com/user-attachments/assets/1dfbc79c-9a16-4877-ba4d-7da485bb7633)
![Screenshot 2024-10-03 181750](https://github.com/user-attachments/assets/7111121e-a813-4f36-ae2c-4073ef303ba9)
![Screenshot 2024-10-03 181821](https://github.com/user-attachments/assets/8fb2c0d1-7a2a-4e65-9490-34a142e485b0)

**Comment by darinyoo** [comment]
> > You didn't upload ClientAppSettings.json
> 
> sorry i was busy with school and i forgot to send cilentappsettings.json and i also have updated my settings in bloxstrap menu so im gonna send in once all again (new one) ![Screenshot 2024-10-03 181715](https://private-user-images.githubusercontent.com/180763955/373312822-1dfbc79c-9a16-4877-ba4d-7da485bb7633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjkyOTQsIm5iZiI6MTcyNzk2ODk5NCwicGF0aCI6Ii8xODA3NjM5NTUvMzczMzEyODIyLTFkZmJjNzljLTlhMTYtNDg3Ny1iYTRkLTdkYTQ4NWJiNzYzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2Y2ZDI0NzU4NGVhODkwZDM5Zjk2MzhjYjZmZGRiNjgxZGM0ODkyMWNkYTRjNzgyODhhMmJlYjExMzBhM2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bd-8_ZB1pCw3S7Hp35z9Tv5M269UlAE3Dh3Rpm4RR7M) ![Screenshot 2024-10-03 181750](https://private-user-images.githubusercontent.com/180763955/373312851-7111121e-a813-4f36-ae2c-4073ef303ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjkyOTQsIm5iZiI6MTcyNzk2ODk5NCwicGF0aCI6Ii8xODA3NjM5NTUvMzczMzEyODUxLTcxMTExMjFlLWE4MTMtNGYzNi1hZTJjLTQwNzNlZjMwM2JhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTM0OGQ5MWMwZjRjNGE0ZTNlMjA5MzQzNWQwNGZkYmVlZWQwNWJlODM0ODgzNjEyZjgyYTNlZTA2ZGU2N2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-Z82luCHx8Mn_kTP6Wy17bzF016KeAm5hyLz7LxyiLI) ![Screenshot 2024-10-03 181821](https://private-user-images.githubusercontent.com/180763955/373312884-8fb2c0d1-7a2a-4e65-9490-34a142e485b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjkyOTQsIm5iZiI6MTcyNzk2ODk5NCwicGF0aCI6Ii8xODA3NjM5NTUvMzczMzEyODg0LThmYjJjMGQxLTdhMmEtNGU2NS05NDkwLTM0YTE0MmU0ODViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzFhZDk5NDZlNTdmYzZlYTAwYjhhM2Y5OTQyZjg4NWM1YTFiY2RhZTk5YmI0MjgzN2YzMjBlMzM4N2FmNWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PbOkLgJ3-sRbiWquLIGOUbfx-sjb1BowoQ93Lmn3M4o)

(update) i reinstalled my bloxstrap and now it got fixed (i was annoying for ya sry pizzaboxer)
