### ISSUE TITLE
[BUG] My "Play Roblox" and Bloxstrap menu isn't showing up in the search bar

### ISSUE THREAD

**Issue by StevethePr0** [bloxstraplabs/bloxstrap#2816]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I've installed Bloxstrap a few months ago but there's still this bug that I don't know how to fix. My "Bloxstrap menu" and "Play Roblox" applications that I can use to quickly open up Roblox in Bloxstrap and edit Bloxstrap isn't appearing in my search bar or anywhere on my PC. I've tried uninstalling, reinstalling and installing Bloxstrap multiple times and nothing has worked. Please help me out.

Screenshots:
https://drive.google.com/drive/folders/1EidNjSvfeDjXBMYJdtRNUc8rOIEkbUee?usp=sharing

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
no access to see image 💔

**Comment by NabHeyka22** [comment]
put %localappdata% in the bar of file explorer and check if there's a Bloxstrap folder
then tell me if there is or not

**Comment by StevethePr0** [comment]
> put %localappdata% in the bar of file explorer and check if there's a Bloxstrap folder then tell me if there is or not

Yes there is

**Comment by pizzaboxer** [comment]
Instead of using the search bar, can you find them if you just look through the Start Menu programs list?

**Comment by StevethePr0** [comment]
> Instead of using the search bar, can you find them if you just look through the Start Menu programs list?

No they're also not in there

**Comment by StevethePr0** [comment]
> > Instead of using the search bar, can you find them if you just look through the Start Menu programs list?
> 
> No they're also not in there

They're basically not installed on my computer

**Comment by StevethePr0** [comment]
Hello?

**Comment by StevethePr0** [comment]
Update: I just taught my friend how to use Bloxstrap. He just installed it and got the same bug as I did.

**Comment by NabHeyka22** [comment]
you installed the latest right?

**Comment by StevethePr0** [comment]
Yes

**Comment by StevethePr0** [comment]
;-;

**Comment by StevethePr0** [comment]
welp

**Comment by StevethePr0** [comment]
Oh and also my Bloxstrap things stopped loading in now

**Comment by pizzaboxer** [comment]
Run the Bloxstrap executable you downloaded once, which will launch Roblox. It should also try to reregister the Start Menu shortcuts. Look for them afterwards.

**Comment by pizzaboxer** [comment]
Assuming problem is now resolved
