### ISSUE TITLE
[BUG] the bloxstrap cannot be uninstalled

### ISSUE THREAD

**Issue by fazaadzima** [bloxstraplabs/bloxstrap#2823]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

-

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
what is the problem
is an error popping up or like WHAT'S HAPPENING!! EXPLAIN!!

**Comment by reeddone4** [comment]
> report not being able to uninstall bloxstrap
> refuse to elaborate

**Comment by fazaadzima** [comment]
Chill chill, the issue is like, i cannot uninstall the bloxstrap like i
already follow the tips how to uninstall the bloxstrap but its bugged, oh
yeah and other, the setting i change itu bloxstrap menu, din't change the
game 😐

Pada Jum, 6 Sep 2024 01.08, reeddone4 ***@***.***> menulis:

**Comment by pizzaboxer** [comment]
> but its bugged

Okay, can you explain what happens? What error do you get (if any)?

**Comment by fazaadzima** [comment]
Forget it, i already know about fflag gonna get removed, damn

Pada Sab, 7 Sep 2024 05.20, pizzaboxer ***@***.***> menulis:

**Comment by pizzaboxer** [comment]
If you're encountering a bug, I need to know what's happening. What's the issue?
