### ISSUE TITLE
[BUG] when trying to initialize Bloxstrap closes

### ISSUE THREAD

**Issue by realy66** [bloxstraplabs/bloxstrap#2837]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when trying to boot, it loads a bit and just closes

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
