### ISSUE TITLE
[REQ] Ship 2 new RDC24 FFlags with install

### ISSUE THREAD

**Issue by d9no** [bloxstraplabs/bloxstrap#2846]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

These FFlags just dramatically increased my performance with FPS using Bloxstrap and I want to see them being shipped in the stock installation. 

DFFlagUseVisBugChecks = true
FFlagEnableVisBugChecks27 = true

https://x.com/MaximumADHD/status/1832253457178493138

**Comment by pizzaboxer** [comment]
Chances are that this might already be rolled out by the time the next version of Bloxstrap comes out, but if not, I'll add them as an option.

**Comment by bluepilledgreat** [comment]
We take like 6 months to update. They'll likely be on prod by the time we release a new version.

**Comment by bluepilledgreat** [comment]
FFlagEnableVisBugChecks27 is enabled on prod and DFFlagUseVisBugChecks seems to be coming very soon. There is really no point in us adding this.
