### ISSUE TITLE
[BUG]] Roblox keeps changing back to the normal version when i open it

### ISSUE THREAD

**Issue by PlayboiSkibidi** [bloxstraplabs/bloxstrap#2852]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

 I've deleted bloxtrap and installed it a couple times before, but its always worked perfect, but this time when i reinstalled it and opened a game using the desktop shortcut, it switched back to the normal roblox and none of the fast flags or mods were saved. Idk what to do.

### Bloxstrap Log

N/A

https://github.com/user-attachments/assets/bbff82b9-c53c-4abf-ac82-b2887f1fbbf3

**Comment by pizzaboxer** [comment]
Bloxstrap isn't supposed to keep any data when you uninstall it. Were you expecting it to?

**Comment by PlayboiSkibidi** [comment]
I already know that, i think you misunderstood my issue. My issue is that after ive installed bloxstrap and set up my settings how i like them, when i open the game, all the roblox settings are normal. I dont see the fast flags settings in game like the graphics selector or the low textures that i set. It seems that it just switches to normal roblox when i open bloxstrap

**Comment by MHMHMHM121H** [comment]
https://github.com/user-attachments/assets/a335229b-38ac-4502-b07e-4b017a64ce4b

i have this exact same issue

**Comment by pizzaboxer** [comment]
@MHMHMHM121H Read the Wiki next time. https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-launch-with-Roblox

@PlayboiSkibidi Upload your configuration please: github.com/pizzaboxer/bloxstrap/wiki/uploading-your-Bloxstrap-configuration

**Comment by PlayboiSkibidi** [comment]
I will be able to do that on Friday, bc my pc is undergoing some repairs and upgrades at the moment

**Comment by PlayboiSkibidi** [comment]
[ClientAppSettings.json](https://github.com/user-attachments/files/16999876/ClientAppSettings.json)
[Settings.json](https://github.com/user-attachments/files/16999878/Settings.json)
[State.json](https://github.com/user-attachments/files/16999880/State.json)

**Comment by pizzaboxer** [comment]
To clearly get an idea of if your changes are applying, please open the flag editor and import this JSON:

```json
{"FFlagDebugDisplayFPS": "True"}
```

Launch again, and see if you get an FPS counter in the top left.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
