### ISSUE TITLE
[BUG] FastFlags Are not saving

### ISSUE THREAD

**Issue by viberblx83** [bloxstraplabs/bloxstrap#2864]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When i change value of the fastflag and save it it doesnt save it says it saved but its not

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
what fflag are you trying to put

**Comment by viberblx83** [comment]
> what fflag are you trying to put

FFlagDisablePostFx

the bug happening on every fastflag

**Comment by NabHeyka22** [comment]
did you check if bloxstrap is running and not the normal roblox

**Comment by viberblx83** [comment]
> did you check if bloxstrap is running and not the normal roblox

yes i did

**Comment by NabHeyka22** [comment]
hmm idk really

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Zacgamingpro1234** [comment]
> When i change value of the fastflag and save it it doesnt save it says it saved but its not

So first of all you did click save right. (am guessing yes). When you reopen the bloxstrap menu can you still see the fast flag in bloxstrap ff editor? Make sure that you did open bloxstrap using the tiny icon at the bottom on the taskbar.
![image](https://github.com/user-attachments/assets/35a8995b-db80-4c46-9fd7-429d7cce4628)

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
