### ISSUE TITLE
[REQ] A "Reset to Default" button

### ISSUE THREAD

**Issue by Encythe** [bloxstraplabs/bloxstrap#2865]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Currently, there is no way of resetting your Bloxstrap default to the defaults pre-packaged with the program. Hence, a button for resetting a specific configuration [if there are multiple profiles, that's for a future Bloxstrap update] in the "Installation" tab could be useful for some if they've experienced weird issues with Bloxstrap. 

This "Reset to Default" button can reset the following:
- Configured FastFlags [All of them, not just the ones within Bloxstrap]
- All user modifications

Optionally, there can be checkboxes for what should be reset [e.g. someone wants to reset their FFlags but nothing else] in a _"Controlled Reset"_.

**Comment by NabHeyka22** [comment]
you realize there's a button called Force Roblox reinstallation right

**Comment by Encythe** [comment]
??? This is related to Bloxstrap, not Roblox

**Comment by NabHeyka22** [comment]
![image_2024-09-09_205510669](https://github.com/user-attachments/assets/9b666990-2ad5-4be2-a3dc-9ea5a4999f27)

**Comment by Encythe** [comment]
This isn't related to what I'm suggesting.

**Comment by NabHeyka22** [comment]
from what i read, you want a button that resets stuff
well there's already one, and it's called Force Roblox reinstallation, which resets everything on the next launch, resetting basically everything

**Comment by Encythe** [comment]
Bloxstrap re-applies said "everything", which is the point of this request. It can also range from Custom Integrations to Mods and much more.

**Comment by NabHeyka22** [comment]
so,
- for mods, why don't you just delete the folders
- for fflags, why not select all of them and click delete selected?
- and for other stuff, why not disable it if there's a setting?

**Comment by Encythe** [comment]
Short answer: Quality of Life

I would like to wait for a Repo contributor to review this idea, please.

**Comment by NabHeyka22** [comment]
eh fair enough
