### ISSUE TITLE
[BUG] roblox doesnt show anymore in discord activity

### ISSUE THREAD

**Issue by Maxmaster34** [bloxstraplabs/bloxstrap#2873]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

roblox Was showing before on the discord activity, but when i removed the detection of the app it disappeared and i cant enable it again, PLS HELP ME FIND A FIX

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
so what you want to do is read the wiki

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Discord-Rich-Presence-does-not-work?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
