### ISSUE TITLE
[BUG] I can't open the blox trap menu

### ISSUE THREAD

**Issue by elum4** [bloxstraplabs/bloxstrap#2876]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I deleted the blox trap exe file and can no longer open the menu screen. Even after reinstalling it, I can't open the menu screen. What should I do?

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
go to %localappdata%, delete the Bloxstrap folder, then try reinstalling bloxstrap

**Comment by pizzaboxer** [comment]
What happens when you try to open it?

**Comment by ShadowCodeX-debug** [comment]
Open the Run dialog (Windows Key + R) then type the following:
`"%localappdata%\Bloxstrap\Bloxstrap.exe" -menu`

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
