### ISSUE TITLE
[BUG] bloxstrap freeze for 10 sec.

### ISSUE THREAD

**Issue by RandomBiatj** [bloxstraplabs/bloxstrap#2886]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

my bloxstrap just freeze for 10 sec. i already set the framerate to zero at the bloxstrap menu, but didin't worked. any suggestion?

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Is it Roblox or Bloxstrap freezing?

**Comment by RandomBiatj** [comment]
it's the Bloxstrap. i've tried use the Roblox app. and it's fine.

**Comment by bluepilledgreat** [comment]
Can you send your log file?

**Comment by RandomBiatj** [comment]
too late... i already uninstall the apps. is it okay if i download it again and play it?

**Comment by ShadowCodeX-debug** [comment]
If you are using Vulkan, remove it.

**Comment by pizzaboxer** [comment]
> too late... i already uninstall the apps. is it okay if i download it again and play it?

Yes, do that please.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
