### ISSUE TITLE
[BUG] Bloxstrap opens on startup without my input

### ISSUE THREAD

**Issue by PAMTerrie** [bloxstraplabs/bloxstrap#2901]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

So after clicking a private server game link, for whatever reason Bloxstrap now just opens up to that private server every time I turn my PC on and sign in, which is extremely annoying and I don't know what to do to have it not just open up roblox and such into the private server since obviously I can't just close the server due to it not being mine.
I just wanna be able to open up Roblox when I want rather than it for some reason opening itself without my input at all, and again this ONLY started happening after joining a private server game link.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Can you send your log file?

**Comment by PAMTerrie** [comment]
[Bloxstrap_20240920T035159Z.log](https://github.com/user-attachments/files/17078941/Bloxstrap_20240920T035159Z.log)
[Bloxstrap_20240917T175818Z.log](https://github.com/user-attachments/files/17078942/Bloxstrap_20240917T175818Z.log)
[Bloxstrap_20240918T022701Z.log](https://github.com/user-attachments/files/17078943/Bloxstrap_20240918T022701Z.log)
[Bloxstrap_20240918T023920Z.log](https://github.com/user-attachments/files/17078944/Bloxstrap_20240918T023920Z.log)
[Bloxstrap_20240919T022825Z.log](https://github.com/user-attachments/files/17078945/Bloxstrap_20240919T022825Z.log)
[Bloxstrap_20240919T031439Z.log](https://github.com/user-attachments/files/17078946/Bloxstrap_20240919T031439Z.log)
[Bloxstrap_20240919T162244Z.log](https://github.com/user-attachments/files/17078947/Bloxstrap_20240919T162244Z.log)
[Bloxstrap_20240920T031009Z.log](https://github.com/user-attachments/files/17078948/Bloxstrap_20240920T031009Z.log)
I got plenty. Again, I'd boot my PC up, and after any number of time boom it just THRUSTS me into the private server even WEEKS after first joining via that link

**Comment by NabHeyka22** [comment]
we only needed one

**Comment by pizzaboxer** [comment]
> Bloxstrap now just opens up to that private server every time I turn my PC on and sign in

Can you open the Run dialog (press Windows Key + R), enter in "shell:startup", and show what's in the folder please?

**Comment by PAMTerrie** [comment]
Well I feel one is too small of a sample size to explain what's going on.

**Comment by PAMTerrie** [comment]
> > Bloxstrap now just opens up to that private server every time I turn my PC on and sign in
> 
> Can you open the Run dialog (press Windows Key + R), enter in `shell:startup`, and show what's in the folder please?
![Screenshot 2024-09-23 125314](https://github.com/user-attachments/assets/bbd9eef9-80b5-4ab8-99e2-53c00b6d42fe)
It's as empty as anything. I don't understand why it opens on it's own anyway.

**Comment by pizzaboxer** [comment]
This is definitely weird something happening with your PC. We don't do anything that could cause something like this. 

Can you download and run [Sysinternals Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) and show everything that's listed there? (there'll be a lot)

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
