### ISSUE TITLE
[BUG] In-game menu V1 is broken

### ISSUE THREAD

**Issue by 7-7what** [bloxstraplabs/bloxstrap#2911]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i cant even close roblox, i cant use task manager to close it too, cause when i search it, it is missing, i have to restart my laptop in order to close it.

### Bloxstrap Log

N/A

### Note from the developers:

For now, please set FFlagFixReportButtonCutOff to false

**Comment by myusername450** [comment]
![image](https://github.com/user-attachments/assets/32385fb2-1df9-4c94-b878-e8f875bd3768)
the entire ui is missing

**Comment by 7-7what** [comment]
the only way to fix is either switching to the new gui, or just.. leaving it like this i guess, i had to switch to the new gui and it looks.. DESGUSTING!!.

**Comment by Deexe2137** [comment]
I also just encountered ui missing, i assume, that we'll have to wait for a patch or smth

**Comment by 7-7what** [comment]
> I also just encountered ui missing, i assume, that we'll have to wait for a patch or smth. For now you should use v4.

this could be roblox's fault ngl

**Comment by moosetwin0** [comment]
Also having this issue

**Comment by SilverT4** [comment]
Roblox pushed a new update recently that (likely unintentionally) broke the 2015 escape menu. For now, I suggest using the 2023 one.

**Comment by lunaris-moon** [comment]
![image](https://github.com/user-attachments/assets/de9b21de-9fb2-4025-a6cb-cc5f1ded04a5)
oh no wonder i cant leave any game, sux, i really liked it because reminds me of 2018's menu lol (+got used to it better)

**Comment by lunaris-moon** [comment]
if anyone finds a roblox forum talking about this issue lmk and update us, thanks!

**Comment by forgettableaccount123** [comment]
![RobloxScreenShot20240920_135433092](https://github.com/user-attachments/assets/58de13e7-97c7-4b60-ad44-707f9de018fb)

**Comment by Pagong27Gaming** [comment]
Did ROBLOX release an update that ended up breaking this?

**Comment by JoxZer** [comment]
> Did ROBLOX release an update that ended up breaking this?

correct

**Comment by JustDreaded** [comment]
Do I have to reset my computer because I tried switching my menu but it's not working, it's still the same 2015 one.

**Comment by JoxZer** [comment]
try this

{
  "FFlagFixReportButtonCutOff": "False"
}

if it doesn't work, there is no fix

**Comment by Mug87** [comment]
were do you input it?

**Comment by Orliminecraft** [comment]
Open bloxstrap installer
Go to fast flags
Go to the editor
Import JSON
Paste in his fix
Save

**Comment by d0nutbag** [comment]
i am also having this problem 😭

**Comment by NabHeyka22** [comment]
use another menu

**Comment by 7-7what** [comment]
this is crazy

**Comment by bluepilledgreat** [comment]
Workaround: set FFlagFixReportButtonCutOff to false

**Comment by Dima24162** [comment]
> {
> "FFlagFixReportButtonCutOff": "False"
> }

Thank you so much

**Comment by Logan-Roman2023** [comment]
> Open bloxstrap installer Go to fast flags Go to the editor Import JSON Paste in his fix Save

Thanks! you have NO idea how many lives you saved.

**Comment by 7-7what** [comment]
![image](https://github.com/user-attachments/assets/cd2605ee-d8b1-46b7-bd12-55c333655ec6)

whaat?

**Comment by 7-7what** [comment]
?

**Comment by PotatoKevinthegamer** [comment]
![RobloxScreenShot20240921_191238271](https://github.com/user-attachments/assets/a3cc5395-684d-4066-bfef-338649b2c123)

**Comment by PotatoKevinthegamer** [comment]
uhm is happening on mine now 😭

**Comment by NabHeyka22** [comment]
> uhm is happening on mine now 😭

{
"FFlagFixReportButtonCutOff": "False"
}
and if it doesn't work, use 2023 menu

**Comment by PotatoKevinthegamer** [comment]
bet

**Comment by PotatoKevinthegamer** [comment]
![image](https://github.com/user-attachments/assets/fe354a1d-8dd2-4612-b5e4-9136bb8825d4)

oh it works ty 👍

**Comment by RealS5** [comment]
You can still close roblox using task manager by going to details tab and end task
for some reason it just doesnt show up in the processes tab

![imsuchahackerman](https://github.com/user-attachments/assets/3d604d05-3467-472b-8b89-6273e0cdcf68)

**Comment by d0nutbag** [comment]
IT WORKS YAY
![Uploading Captura de tela 2024-09-21 143027.png…]()

**Comment by styalos** [comment]
happens to me too, execpt if i try and close and re open the menu the top options are gone. i can use task manager to close roblox but its really annoying and i dont wanna have to pin task manager to my taskbar

**Comment by Pagong27Gaming** [comment]
> > Did ROBLOX release an update that ended up breaking this?
> 
> correct

If that is the case, then what addition or change to existing ROBLOX features broke this?

**Comment by NabHeyka22** [comment]
change menu

**Comment by verbes4** [comment]
> {
> "FFlagFixReportButtonCutOff": "False"
> }

i love you

**Comment by New7G** [comment]
If you dont want to do fastflags then you can download the last version here (V2.6.1)
https://winstall.app/apps/pizzaboxer.Bloxstrap
this link has the current and previous versions of bloxstrap

**Comment by New7G** [comment]
for a dev: heres a console log detailing what went wrong
![Screenshot 2024-09-20 220842](https://github.com/user-attachments/assets/4f6c164a-c9c3-4cc1-ba05-bf3dccb859ba)

**Comment by New7G** [comment]
this is so stupid

**Comment by NabHeyka22** [comment]
Don't blame us. Blame Roblox for doing something that broke the V1 menu.

**Comment by New7G** [comment]
yeah

**Comment by roblosplaya** [comment]
> the only way to fix is either switching to the new gui, or just.. leaving it like this i guess, i had to switch to the new gui and it looks.. DESGUSTING!!.. in my opinion.

shut the fuck up v1 looks like actual dogshit. no one cares about your opinion.

**Comment by JustDreaded** [comment]
You obviously seem to care if you're replying to his opinion..

**Comment by rikarii** [comment]
> > uhm is happening on mine now 😭
> 
> { "FFlagFixReportButtonCutOff": "False" } and if it doesn't work, use 2023 menu

i can't switch back to the 2023 menu either. it's still using the 2015 menu and the bug is still happening.

**Comment by 7-7what** [comment]
> > the only way to fix is either switching to the new gui, or just.. leaving it like this i guess, i had to switch to the new gui and it looks.. DISGUSTING!!.. in my opinion.
> 
> shut the fuck up v1 looks like actual dogshit. no one cares about your opinion.

ok mr "roblosplaya" who cant seem to understand what the word "opinion" means it clearly states at the end, "DISGUSTING!!.. in my opinion." now read that again.. "in my opinion" so theres no need to yip yap about me going on why i dont like it. we all have opinions.

**Comment by Bruh2801** [comment]
> i can't switch back to the 2023 menu either. it's still using the 2015 menu and the bug is still happening.

same,gosh darn it.

**Comment by bluepilledgreat** [comment]
A fix for this is on it's way in the next release of Bloxstrap. Please wait.

**Comment by RealS5** [comment]
now the topbar and the menu does not work with V1

![RobloxScreenShot20241024_163238777](https://github.com/user-attachments/assets/0a7b48b8-ca89-45a9-9eb0-1791edd22d4b)

**Comment by Villdoes** [comment]
I dont know but i think roblox removed the Fflags for it

**Comment by Logan-Roman2023** [comment]
Use Roldblox 2016
