### ISSUE TITLE
[REQ] Option to remove "Playing" text from Discord RPC

### ISSUE THREAD

**Issue by Rawblocky** [bloxstraplabs/bloxstrap#2921]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Vencord has a custom plugin that'll allow you to swap the details and name in Discord's RPC called "ReplaceActivityTypes"

However, using this in combination with Bloxstrap makes the "Playing" text show up twice due to how it's formatted
![image](https://github.com/user-attachments/assets/b91892bc-bb07-42bf-a81b-25d2f4d6a140)

This is pretty niche thing, but would be nice if there was a way to just get rid of the "Playing" text, or even just don't have it entirely.

Right now, in order to get rid of it, I had to build Bloxstrap from source

**Comment by pizzaboxer** [comment]
I think in general we can just remove the "Playing" verb anyway, and just have the game name as it is.
