### ISSUE TITLE
[BUG] not opening

### ISSUE THREAD

**Issue by Transporteris** [bloxstraplabs/bloxstrap#2923]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

idk its no opening can someone help me

### Bloxstrap Log

N/A

**Comment by JoxZer** [comment]
we kinda need more information

**Comment by bluepilledgreat** [comment]
Can you send your log file?

**Comment by pizzaboxer** [comment]
Is it Roblox or Bloxstrap that isn't opening?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
