### ISSUE TITLE
[BUG] CAN'T OPEN THE MENU (didn't even open on installation)

### ISSUE THREAD

**Issue by Hotpotato55** [bloxstraplabs/bloxstrap#2924]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I can't open the Bloxstrap menu, it's not in the taskbar, control panel uninstall page or desktop and if I wanted to uninstall Bloxstrap I would have to go to the path and delete the folder manually, I tried reinstalling and it just installs Roblox instantly and launches Roblox, I read the wiki I tried everything and nothing worked, in short, please help me.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Launch Bloxstrap with the `-menu` argument.

**Comment by kirboispog** [comment]
> Launch Bloxstrap with the `-menu` argument.

how am i meant to do this? (i'm having almost the exact same issue, ill list my specs if needed)

**Comment by bluepilledgreat** [comment]
> > Launch Bloxstrap with the `-menu` argument.
> 
> how tho?

Command prompt. Navigate to the Bloxstrap directory and run `Bloxstrap.exe -menu`.
If you're having trouble with the uninstallation, you can run `Bloxstrap.exe -uninstall`.

**Comment by Hotpotato55** [comment]
> > > Launch Bloxstrap with the `-menu` argument.
> > 
> > 
> > how tho?
> 
> Command prompt. Navigate to the Bloxstrap directory and run `Bloxstrap.exe -menu`. If you're having trouble with the uninstallation, you can run `Bloxstrap.exe -uninstall`.

tysm It works now! I made the cmd into a bat file to open it quickly.

**Comment by pizzaboxer** [comment]
> it's not in the taskbar, control panel uninstall page or desktop 

Bloxstrap attemps to create Start Menu shortcuts every time you launch Roblox. Are you sure they're not there, even if you look through the programs list alphabetically?

**Comment by Hotpotato55** [comment]
> > it's not in the taskbar, control panel uninstall page or desktop
> 
> Bloxstrap attemps to create Start Menu shortcuts every time you launch Roblox. Are you sure they're not there, even if you look through the programs list alphabetically?

yes I'm really sure, I checked everywhere bro.

**Comment by bluepilledgreat** [comment]
Can you send your settings file?

**Comment by Hotpotato55** [comment]
[Settings.json](https://github.com/user-attachments/files/17089875/Settings.json)
there you go

**Comment by pizzaboxer** [comment]
> yes I'm really sure, I checked everywhere bro.

Open the `%appdata%\Microsoft\Windows\Start Menu\Programs` folder. Is there a Bloxstrap folder there?

**Comment by Hotpotato55** [comment]
no there is not.

**Comment by pizzaboxer** [comment]
I don't currently know how to explain this, but your start menu folder is vanishing into thin air.

Whatever though, the next version should address this nicely.

**Comment by Hotpotato55** [comment]
ok, thank you a lot man usually people don't get attention for small things like this, so I appreciate it!
