### ISSUE TITLE
[BUG] I can't access Bloxstrap Menu

### ISSUE THREAD

**Issue by chrisobad** [bloxstraplabs/bloxstrap#2951]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I can't access the Bloxstrap menu after installation. When I search in the Windows search bar, the Bloxstrap menu doesn't appear. When I right-click on the Bloxstrap icon in the taskbar, I only see three options: Discord Rich Presence, Close Roblox and Open log file. There's no option to access settings or the menu.

### Bloxstrap Log

N/A
![Bloxstrap versions 2 7 0](https://github.com/user-attachments/assets/e9dfffe4-e878-45da-91b8-d48c8400bb23)

**Comment by bluepilledgreat** [comment]
You have likely disabled your start menu shortcuts.
Launch Bloxstrap via the command prompt using `Bloxstrap.exe -menu` and enable shortcuts.

**Comment by chrisobad** [comment]
> You have likely disabled your start menu shortcuts. Launch Bloxstrap via the command prompt using `Bloxstrap.exe -menu` and enable shortcuts.

How to enable shortcuts ?

**Comment by ShadowCodeX-debug** [comment]
@chrisobad Make a shortcut and enter `"%localappdata%\Bloxtrap\Bloxstrap.exe" -menu`

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu?

**Comment by iveeltemuujin6-dev** [comment]
same
