### ISSUE TITLE
[BUG] Bloxstrap is unable to connect to Roblox

### ISSUE THREAD

**Issue by TanZil-Hello** [bloxstraplabs/bloxstrap#2955]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so today when i opened bloxstrap the above msg/pic was showing, now i think there is a reason but i am not sure. The reason is that i bought a new wireless USB adapter today this might be the problem BUT everything is working fine (youtube, discord etc)
now pls give me some solution to this problem

### Bloxstrap Log

![Uploading bloxstrap.png…]()

**Comment by ErikaXGH** [comment]
it can be a network issue. maybe it is affecting the network

**Comment by pizzaboxer** [comment]
Your screenshot didn't upload correctly. Upload it again.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
