### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gg287** [bloxstraplabs/bloxstrap#2962]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The game always freezes randomly and it unfreezes and the loophole continues

And I play the game at 144fps

### Bloxstrap Log

N/A

**Comment by ShadowCodeX-debug** [comment]
Please send your configuration, specifically your ClientAppSettings.json (FFlag list).

[Uploading your Bloxstrap configuration](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration)

Or through the Bloxstrap Menu go to FastFlags, FastFlag Editor and press Export JSON and paste it here.

**Comment by pizzaboxer** [comment]
> The game always freezes randomly and it unfreezes and the loophole continues

And does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
