### ISSUE TITLE
[BUG] Font file validation

### ISSUE THREAD

**Issue by mircik** [bloxstraplabs/bloxstrap#2982]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

the file you have chosen does not appear to be a valid font file what do i do?

### Bloxstrap Log

N/A

**Comment by Wanwood1** [comment]
Could you give us more information? and possibly send the font file your trying to use?

**Comment by bluepilledgreat** [comment]
What file are you trying to import?

**Comment by mircik** [comment]
> Could you give us more information? and possibly send the font file your trying to use?

I was trying to use the BMW Type Next font and it said the file you have chosen does not appear to be a valid font file.

**Comment by MHMHMHM121H** [comment]
> > Could you give us more information? and possibly send the font file your trying to use?
> 
> I was trying to use the BMW Type Next font and it said the file you have chosen does not appear to be a valid font file.

you have to unzip the file and click the font and download then import.

**Comment by pizzaboxer** [comment]
Send the font file here please

**Comment by mircik** [comment]
> Send the font file here please

i cant because it says something with the file is not supported or something

**Comment by pizzaboxer** [comment]
Upload it somewhere else and send a link here

**Comment by mircik** [comment]
I already solved it with Bloxstrap discord server

**Comment by pizzaboxer** [comment]
Relevant thread: https://discord.com/channels/1099468797410283540/1289834220931252257

Issue was that your font is actually a .otf font, but with a .ttf file extension. I'll address that.
