### ISSUE TITLE
(Ошибка) немагу зделать меню (v2) в место (v2) (v1)

### ISSUE THREAD

**Issue by NLMZ-A** [bloxstraplabs/bloxstrap#2985]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

я немагу зделать меню (v2)

### Bloxstrap Log

N/A

**Comment by NLMZ-A** [comment]
Исправте пажалуста

**Comment by internetzx** [comment]
sorry but what the fuck are you saying

**Comment by Wanwood1** [comment]
Вам необходимо выбрать меню V2 на вкладке fastflags
Если это не сработает, пожалуйста, предоставьте нам больше информации

**Comment by Naveandice** [comment]
@NLMZ-A Роблокс удалил меню V2, поэтому оно не работает. Меню V1 сейчас сломано, не используй его.
