### ISSUE TITLE
[BUG] UI Navigation Toggle and VR Toggle reverting back to On

### ISSUE THREAD

**Issue by ReallyPingable** [bloxstraplabs/bloxstrap#2993]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Everytime I Alt+F4 or leave the game and rejoin back the UI Navigation and VR Toggle will reset back to On eventhough I've set it to Off
![image](https://github.com/user-attachments/assets/e9d04a16-2e41-43fb-92a0-82327b6d5dcd)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Do any of your other settings save?

**Comment by ReallyPingable** [comment]
Yeah everything else saves it's only those 2 that always get reverted back to On, maybe there's a FF I can add which disables it permanently?

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ReallyPingable** [comment]
![image](https://github.com/user-attachments/assets/b387341c-e8f9-47b6-b9fc-f7f0eff89cc6)
Seems like it this is with the default Roblox launcher

**Comment by ReallyPingable** [comment]
[Settings.json](https://github.com/user-attachments/files/17209402/Settings.json)
[State.json](https://github.com/user-attachments/files/17209403/State
[ClientAppSettings.json](https://github.com/user-attachments/files/17209406/ClientAppSettings.json)
.json)

**Comment by pizzaboxer** [comment]
Seems to be fine. Nonetheless, can you try disabling the fast flag manager, launch again, and see if that changes anything?

**Comment by ReallyPingable** [comment]
Doesn't do anything, maybe theres a FF I can add which permanently disables them?

**Comment by pizzaboxer** [comment]
As far as I'm aware, no. I can't seem to replicate this either.

Can you try disabling the settings again, then close Roblox, and then upload GlobalBasicSettings_13.xml from `%localappdata%\Roblox\` please

**Comment by pizzaboxer** [comment]
Send copies of the file before and after opening Roblox so I can compare them, just in case there some other things changing too that might be relevant

**Comment by ReallyPingable** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">
<External>null</External>
<External>nil</External>
<Item class="UserGameSettings" referent="RBXE67EE6F4808940DB880E6FCF59DA3F4C">
<Properties>
<bool name="AllTutorialsDisabled">false</bool>
<BinaryString name="AttributesSerialize"/>
<token name="CameraMode">0</token>
<bool name="CameraYInverted">false</bool>
<SecurityCapabilities name="Capabilities">0</SecurityCapabilities>
<bool name="ChatTranslationEnabled">false</bool>
<bool name="ChatTranslationFTUXShown">true</bool>
<string name="ChatTranslationLocale">en_us</string>
<bool name="ChatTranslationToggleEnabled">false</bool>
<bool name="ChatVisible">true</bool>
<string name="CompletedTutorials"/>
<bool name="ComputerCameraMovementChanged">false</bool>
<token name="ComputerCameraMovementMode">0</token>
<bool name="ComputerMovementChanged">false</bool>
<token name="ComputerMovementMode">0</token>
<token name="ControlMode">0</token>
<string name="DefaultCameraID"/>
<bool name="DefinesCapabilities">false</bool>
<int name="FramerateCap">144</int>
<bool name="Fullscreen">true</bool>
<float name="GamepadCameraSensitivity">0.5</float>
<token name="GraphicsOptimizationMode">1</token>
<int name="GraphicsQualityLevel">21</int>
<float name="HapticStrength">0</float>
<bool name="HasEverUsedVR">false</bool>
<float name="MasterVolume">0.100000001</float>
<float name="MasterVolumeStudio">1</float>
<bool name="MaxQualityEnabled">false</bool>
<bool name="MicroProfilerWebServerEnabled">false</bool>
<float name="MouseSensitivity">0.5</float>
<Vector2 name="MouseSensitivityFirstPerson">
<X>0.5</X>
<Y>0.5</Y>
</Vector2>
<Vector2 name="MouseSensitivityThirdPerson">
<X>0.5</X>
<Y>0.5</Y>
</Vector2>
<string name="Name">GameSettings</string>
<bool name="OnScreenProfilerEnabled">false</bool>
<float name="PartyVoiceVolume">1</float>
<bool name="PerformanceStatsVisible">false</bool>
<float name="PlayerHeight">5.70000029</float>
<token name="PreferredTextSize">1</token>
<float name="PreferredTransparency">1</float>
<int name="QualityResetLevel">0</int>
<int name="RCCProfilerRecordFrameRate">1</int>
<int name="RCCProfilerRecordTimeFrame">1</int>
<bool name="ReducedMotion">false</bool>
<token name="SavedQualityLevel">10</token>
<int64 name="SourceAssetId">-1</int64>
<bool name="StartMaximized">true</bool>
<Vector2 name="StartScreenPosition">
<X>20</X>
<Y>20</Y>
</Vector2>
<Vector2 name="StartScreenSize">
<X>800</X>
<Y>600</Y>
</Vector2>
<BinaryString name="Tags">cF8zODQ0MDky</BinaryString>
<bool name="TouchCameraMovementChanged">false</bool>
<token name="TouchCameraMovementMode">0</token>
<bool name="TouchMovementChanged">false</bool>
<token name="TouchMovementMode">0</token>
<bool name="UiNavigationKeyBindEnabled">false</bool>
<bool name="UsedCoreGuiIsVisibleToggle">false</bool>
<bool name="UsedCustomGuiIsVisibleToggle">false</bool>
<bool name="UsedHideHudShortcut">false</bool>
<token name="VRComfortSetting">1</token>
<bool name="VREnabled">false</bool>
<int name="VRRotationIntensity">1</int>
<token name="VRSafetyBubbleMode">0</token>
<bool name="VRSmoothRotationEnabled">false</bool>
<bool name="VRSmoothRotationEnabledCustomOption">false</bool>
<bool name="VRThirdPersonFollowCamEnabled">true</bool>
<bool name="VRThirdPersonFollowCamEnabledCustomOption">true</bool>
<bool name="VignetteEnabled">true</bool>
<bool name="VignetteEnabledCustomOption">true</bool>
<string name="gaID"/>
</Properties>
</Item>
</roblox>

**Comment by ReallyPingable** [comment]
This is after I reopen Roblox
<img width="921" alt="{6C46E0DC-B4EE-4C15-91E4-A24CB07CFB88}" src="https://github.com/user-attachments/assets/58020706-d7b9-408f-aa48-2243825ecea8">

**Comment by pizzaboxer** [comment]
Okay, nothing else is changing.

I'm a little confused as to why this would somehow even be a problem, since Bloxstrap isn't really doing anything that could possibly cause something like this, and I can't replicate this issue.

I'll have to close this as wontfix given how it's not really possible for me to address it, sorry. It'd be nice if I could get some more light on this.
