### ISSUE TITLE
[BUG] Cant turn off Force Roblox Reinstallation

### ISSUE THREAD

**Issue by Slammpreal** [bloxstraplabs/bloxstrap#3003]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The "Force Roblox Reinstallation" wont turn off, its grayed out with the tab stuck on "on"
![Screenshot 2024-09-29 123038](https://github.com/user-attachments/assets/d7b98e1b-2e25-4419-b7ea-ef75c3e423ae)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Is it your first time installing Bloxstrap? If so, it's normal and it's set to default.

**Comment by Slammpreal** [comment]
> Is it your first time installing Bloxstrap? If so, it's normal and it's set to default.

No its not my first time, I turned it on and it was stuck on configuring and now I want to turn it off but I cant :/

**Comment by NabHeyka22** [comment]
You can't turn it off. Just launch roblox and it will reinstall. That's what the option does.

**Comment by Slammpreal** [comment]
> You can't turn it off. Just launch roblox and it will reinstall. That's what the option does.

Yes, but my roblox wont launch, as I said it is stuck on "Configuring Roblox"

**Comment by bluepilledgreat** [comment]
That only happens if you don't have Roblox installed

**Comment by bluepilledgreat** [comment]
> > You can't turn it off. Just launch roblox and it will reinstall. That's what the option does.
> 
> Yes, but my roblox wont launch, as I said it is stuck on "Configuring Roblox"

Can you send your log file?

**Comment by ValkryreMalachie** [comment]
I have the same issue I have no idea how to resolve it

**Comment by ValkryreMalachie** [comment]
But I assume uninstalling it will work, but initial download doesn't have it automatically activated, after turning it on does it effect Roblox, and cause a infinite configuration bug

**Comment by ValkryreMalachie** [comment]
Just reinstall bootstrap, it works for me

**Comment by pizzaboxer** [comment]
> Yes, but my roblox wont launch, as I said it is stuck on "Configuring Roblox"

Assuming issue is now resolved as of v2.8.0. If not, open a new issue please.
