### ISSUE TITLE
[REQ] "Save & Play" Button

### ISSUE THREAD

**Issue by AskaLangly** [bloxstraplabs/bloxstrap#3012]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

The option to "save and play" would be nice so that I could use Bloxstrap as a way to launch Roblox.
Currently, you change your settings, click "save", then have to hunt for the "Play Roblox" shortcut.
I'm one who pins Roblox to the taskbar. However, I have to have *two* for both Bloxstrap and Roblox.
I'm looking to have just one shortcut. 
We could add an option to *minimize Bloxstrap while Roblox is open*, then when it is closed, Bloxstrap could restore back, in the even you need to further tinker.

**Comment by Wanwood1** [comment]
"I'm one who pins Roblox to the taskbar. However, I have to have two for both Bloxstrap and Roblox."
It doesnt matter which one you choose, both will launch bloxstrap unless you go into the Roblox's files and launch the installer for default roblox.

And for the rest of the request, are you using web version of roblox or the roblox app?

**Comment by AskaLangly** [comment]
> And for the rest of the request, are you using web version of roblox or the roblox app?

Currently using the desktop app.

**Comment by pizzaboxer** [comment]
I might add a "test mode" system where it'll auto launch Roblox after closing the menu, and then auto open the menu after closing Roblox.

**Comment by pizzaboxer** [comment]
that idea is actually genius how have i never thought of that before
