### ISSUE TITLE
[BUG] Random stuttering

### ISSUE THREAD

**Issue by NoobNexus95** [bloxstraplabs/bloxstrap#3013]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Random stuttering happens in any game, TSB, JJS, HB, Etc. Please look into this issue.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by BigBowlORice** [comment]
I'm having this issue too, This appears to only happen in both but it appears to stutter more in bloxstrap.

**Comment by BigBowlORice** [comment]
after testing through it, it is happening when using Direct3D10

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
