### ISSUE TITLE
[BUG] tôi gặp vấn đề khi cài đặt bloxstrap và tôi không biết phải khắc phục nó như nào

### ISSUE THREAD

**Issue by zaixizzz** [bloxstraplabs/bloxstrap#3021]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

tôi gặp vấn đề khi cài đặt bloxstrap và tôi không biết phải khắc phục nó như nào
![461627958_952310606704501_4362187832626967695_n](https://github.com/user-attachments/assets/65d73f85-2dff-46d9-9c20-7327794bcf9c)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
What location did you choose?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity.
