### ISSUE TITLE
[BUG] i was playing roblox 6 hours ago, then i want to playing again, i cant there have some issue conecttivity error???

### ISSUE THREAD

**Issue by rasyalathea** [bloxstraplabs/bloxstrap#3066]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![bag](https://github.com/user-attachments/assets/80bd3017-6278-413b-9a79-843e4809338e)
i dont understand to fix it, can some helps? im do a afk griding some games hehe
note : i do what someone else report but i cant, and sorry for bad english 
im not using vpn or windows security and my located in indonesian 

thank, i wish i can play again

### Bloxstrap Log

N/A
System.Net.Http.HttpRequestException: The requested address is not valid in its context. (setup.rbxcdn.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: The requested address is not valid in its context.

**Comment by pizzaboxer** [comment]
This looks like an antivirus issue. Can you please check again?

**Comment by rasyalathea** [comment]
> This looks like an antivirus issue. Can you please check again?

im not using aplication antivirus, and my antivirus is disable

**Comment by TheOutsiter** [comment]
im having the same problem

**Comment by pizzaboxer** [comment]
> im not using aplication antivirus, and my antivirus is disable

I don't know what to tell you, this is an issue with your system in some way.
