### ISSUE TITLE
[BUG] Fast flags don't work

### ISSUE THREAD

**Issue by Tomloyo** [bloxstraplabs/bloxstrap#3074]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

https://github.com/pizzaboxer/bloxstrap/issues/2771#issuecomment-2393750797
i could't try fast flags without bloxstrap cause original roblox doesn't install

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Just to clarify, how can you tell it's not working? What are you noticing isn't taking effect properly?

**Comment by Tomloyo** [comment]
i still get the fullscreen title

**Comment by pizzaboxer** [comment]
Launch Roblox once, then upload Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs`

**Comment by Tomloyo** [comment]
[Bloxstrap_20241014T083001Z.log](https://github.com/user-attachments/files/17361310/Bloxstrap_20241014T083001Z.log)
[Bloxstrap_20241014T071914Z.log](https://github.com/user-attachments/files/17361312/Bloxstrap_20241014T071914Z.log)
[Bloxstrap_20241013T113611Z.log](https://github.com/user-attachments/files/17361313/Bloxstrap_20241013T113611Z.log)
diffirent logs

**Comment by pizzaboxer** [comment]
Seems like it's applying to Roblox just fine. If this is still happening, can you upload ClientAppSettings.json please? (detailed in https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration)

**Comment by Tomloyo** [comment]
i sent it in the previous issue
I have the same issue:
State.json
```
{
  "ShowFFlagEditorWarning": false,
  "PlayerVersionGuid": "version-d2bde6b0a05e4840",
  "StudioVersionGuid": "",
  "PlayerSize": 442485,
  "StudioSize": 0,
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg"
  ]
}
```
Settings.json
```
{
  "BootstrapperStyle": 2,
  "BootstrapperIcon": 2,
  "BootstrapperTitle": "bss simulator ahh game",
  "BootstrapperIconCustomLocation": "",
  "Theme": 2,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "ConfirmLaunches": false,
  "Locale": "en",
  "ForceRobloxLanguage": false,
  "UseFastFlagManager": true,
  "Channel": "LIVE",
  "EnableActivityTracking": true,
  "UseDiscordRichPresence": true,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}
```
Modifications (ffs)
```
{
  "FIntFullscreenTitleBarTriggerDelayMillis": "3600000"
}
```

**Comment by oliwierko678** [comment]
my fast flags also aint working
mainly the prefered menu version

**Comment by pizzaboxer** [comment]
To check whether they're applying, can you open the flag editor, import this JSON config:

```json
{"FFlagDebugDisplayFPS": "True"}
```

Save and join a game, and check to see if you get an FPS counter in the top left?

**Comment by SpaghettiBlox** [comment]
the fps counter fast flag just makes bloxstrap stuck on configuring roblox

**Comment by SpaghettiBlox** [comment]
![image_2024-10-17_160729533](https://github.com/user-attachments/assets/d4eac792-8035-4f7d-9545-7c7d76ca9297)
its been stuck like this for like ten minutes

**Comment by SpaghettiBlox** [comment]
its working now 😄

**Comment by Tomloyo** [comment]
works after update now
