### ISSUE TITLE
[BUG] Bloxstrap new icon issue.

### ISSUE THREAD

**Issue by user1126s** [bloxstraplabs/bloxstrap#3086]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/1b85574f-8c52-4316-a822-79b9067acdcc)
![image](https://github.com/user-attachments/assets/315964ab-5a5c-42d3-8ec4-2773136d7304)
so i'm in the 2.8.0 developer beta. i know you guys won't provide support for this but i am a developer. So looks like @pizzaboxer forgot to put the new bloxstrap icon in the taskbar. the new icon is everywhere but not in the taskbar icon. Let's hope this doesn't make it into Stable Release!

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
You're NOT a developer.

**Comment by internetzx** [comment]
vro is not a dev

**Comment by BlueOutside** [comment]
Keep dreaming on being a developer 😃

**Comment by Wanwood1** [comment]
This is not a developer beta and how did you get access to "2.8.0"?

**Comment by NabHeyka22** [comment]
> This is not a developer beta and how did you get access to "2.8.0"?

https://files.pizzaboxer.xyz/bloxstrap-debug/preview/Bloxstrap-v2.8.0-rc1.exe

**Comment by NabHeyka22** [comment]
Ok i realized i was not supposed to share that link.
Pretend like that didn't happen.

**Comment by pizzaboxer** [comment]
> the new icon is everywhere but not in the taskbar icon. 

This is a Windows cache issue.

**Comment by user1126s** [comment]
> Keep dreaming on being a developer 😃

nuh uh i use nobara linux and arch linux daily, contributed to bloxstrap wiki to make it run on linux (2 weeks later roblox removed support for it.) and contributed to jakoolit fedora hyprland dotfiles to make it work with dnf5 for the fedora release 41 and nobara 41. And i make games with unity, godot and currently making a gravity falls type realistic game on roblox studio. yea i may not be a true developer but atleast it's enough for a 13 year old.

**Comment by user1126s** [comment]
yes i know fedora 41 is in beta but i contributed for easy MOR (migration on release)

**Comment by user1126s** [comment]
> Keep dreaming on being a developer 😃

Heyy! fellow garuda linux user! or i hope so as that's your pfp. What's your discord man?

**Comment by user1126s** [comment]
> > > Keep dreaming on being a developer 😃
> > 
> > 
> > nuh uh i use nobara linux and arch linux daily, contributed to bloxstrap wiki to make it run on linux (2 weeks later roblox removed support for it.) and contributed to jakoolit fedora hyprland dotfiles to make it work with dnf5 for the fedora release 41 and nobara 41. And i make games with unity, godot and currently making a gravity falls type realistic game on roblox studio. yea i may not be a true developer but atleast it's enough for a 13 year old.
> 
> alr, when did i ask for a short story about dreaming

Okay, i think  you will lose more in an online battle as more as you try to prove yourself. but this isn't a battle. this a polite discussion. also if you really want i am making my own project called winux. It's like a linux subsystem for linux. I am making it from scratch without any stolen code except libraries (ofcourse)

**Comment by user1126s** [comment]
@xM4rk1 dude that cat is so adorable sooo cute i wanna pet it :3

**Comment by NabHeyka22** [comment]
> > Keep dreaming on being a developer 😃
> 
> nuh uh i use nobara linux and arch linux daily, contributed to bloxstrap wiki to make it run on linux


If you contributed to the wiki, why won't you send us the page you contributed to?

**Comment by user1126s** [comment]
> > > Keep dreaming on being a developer 😃
> > 
> > 
> > nuh uh i use nobara linux and arch linux daily, contributed to bloxstrap wiki to make it run on linux
> 
> If you contributed to the wiki, why won't you send us the page you contributed to?

okay! the github issue is #1285 also this wiki page was removed 2-3 weeks after adission as roblox discontinued support for it but i hope this is enough.  to be fair i wrote the instructions and @pizzaboxer  put it together in a readable form

**Comment by user1126s** [comment]
im gonna go sudo pacman -Syu

**Comment by internetzx** [comment]
templeos is better than linux

**Comment by NabHeyka22** [comment]
I guess you were right.

**Comment by NabHeyka22** [comment]
But you contributed to a wiki page that then got deleted due to Roblox not supporting Linux, which doesn't make you a developer, nor in the 2.8.0 beta. What you did is basically give a suggestion for a wiki page, pizzaboxer added it, but then Roblox changed some stuff so pizzaboxer removed it.
I'm not saying you're not a developer because the wiki page got deleted, i'm saying you're not a developer because you only gave a suggestion for a wiki page.

**Comment by internetzx** [comment]
wait is nab cooking today

**Comment by NabHeyka22** [comment]
No because i'm a dumbass. I never cook.

**Comment by user1126s** [comment]
> templeos is better than linux

best os in existence. no one can be like the creator of temple os

> But you contributed to a wiki page that then got deleted due to Roblox not supporting Linux, which doesn't make you a developer, nor in the 2.8.0 beta. What you did is basically give a suggestion for a wiki page, pizzaboxer added it, but then Roblox changed some stuff so pizzaboxer removed it. I'm not saying you're not a developer because the wiki page got deleted, i'm saying you're not a developer because you only gave a suggestion for a wiki page.

i am not a developer, just a dumbass making games with unity, godot and unreal as a hobby. also you do need to be quite techy to give instructions because man that wiki took 3 days to test and debug

**Comment by user1126s** [comment]
and i just called the 2.8.0 beta as developer beta because it is a cool term :P

**Comment by NabHeyka22** [comment]
> so i'm in the 2.8.0 developer beta. i know you guys won't provide support for this but i am a developer.

I summon Pandemonium on you.

**Comment by user1126s** [comment]
> > so i'm in the 2.8.0 developer beta. i know you guys won't provide support for this but i am a developer.
> 
> I summon Pandemonium on you.

we dont talk about that. i wrote that at 1 am

**Comment by user1126s** [comment]
also i did contribute to https://github.com/JaKooLit/Fedora-Hyprland via https://github.com/JaKooLit/Fedora-Hyprland/pull/26.
man why cant i code solutions that last. this one was also fixed so it was never added but might be needed again as fedora 41 uses that technology again

**Comment by user1126s** [comment]
Nab you are so cool and epic :3 you aint a dumbass, you a smart fella, not a fart smella

**Comment by user1126s** [comment]
okay then. also wanna be friends please :D @NabHeyka22

**Comment by NabHeyka22** [comment]
No thanks.

**Comment by user1126s** [comment]
:(

**Comment by user1126s** [comment]
![CatTiktokGIF](https://github.com/user-attachments/assets/438310bd-4eaa-46fc-bca9-d6a51cecabdc)

**Comment by user1126s** [comment]
(；′⌒`)

**Comment by internetzx** [comment]
ha

**Comment by user1126s** [comment]
> ha

hwappy enwing
