### ISSUE TITLE
[BUG] Bloxstrap 2022 UI

### ISSUE THREAD

**Issue by Babastian1348** [bloxstraplabs/bloxstrap#3087]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I started Roblox with the 2022 UI and tried to see it it became transparent, the options were locked and I could only close Roblox with the task manager

**Comment by Wanwood1** [comment]
Can you provide a picture?

**Comment by NabHeyka22** [comment]
Don't use V2 menu. V2 menu is broken. Instead, use the 2023 (V4) menu.

**Comment by pizzaboxer** [comment]
Stay on the default menu version for now. This is known and the next version should fix this,
