### ISSUE TITLE
2.8.X (Or 2.9.0) "The Setup Update"

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [bloxstraplabs/bloxstrap#3088]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In my personal opinion, the Bloxstrap setup process is sort of confusing; showing all the options that the normal-use UI shows isn't quite a good idea for user-setup during installation. I suggest doing what other software do, individual option screens.

It could go like this:
1. Press the setup file (obviously)
2. A screen pops up with some basic information about Bloxstrap and standard options (e.g. start menu and desktop pin)
3. Unique options that Bloxstrap provides (e.g. Analytics opt-in, Activity Watcher, etc.)
4. Now Engine Settings, I would like to see this #3020, but you can put the preset options and also a file upload option to import CS list.

Also I've tested the 2.8.0 builds and I don't know if this is just a "I downloaded a beta" problem, but my Engine Settings weren't getting applied so this is sort of a bug report as well.

**Comment by NabHeyka22** [comment]
How is it confusing?

**Comment by ShadowCodeX-debug** [comment]
Tbh I wasn't going for "confusing" this is mainly a streamline suggestion.

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer The Actions tab only provides a version of Bloxstrap that doesn't open a normal setup. So you'd have to install a current build and execute said file to get the the experiemental build. (So no setup ui)

**Comment by ShadowCodeX-debug** [comment]
Also, after I realized that I could get my stuff to work, I downgraded back to the current build.

**Comment by pizzaboxer** [comment]
> The Actions tab only provides a version of Bloxstrap that doesn't open a normal setup. So you'd have to install a current build and execute said file to get the the experiemental build. (So no setup ui)

What? What do you mean there's "no setup ui"?

![image](https://github.com/user-attachments/assets/dd0a4deb-c4f3-4f8e-85a9-a73d55e2d79f)

> Also, after I realized that I could get my stuff to work, I downgraded back to the current build.

Mentioning a problem and then not giving me more information about the problem isn't very helpful. Are you able to still replicate it?

**Comment by user1126s** [comment]
> > The Actions tab only provides a version of Bloxstrap that doesn't open a normal setup. So you'd have to install a current build and execute said file to get the the experiemental build. (So no setup ui)
> 
> What? What do you mean there's "no setup ui"?
> 
> ![image](https://private-user-images.githubusercontent.com/41478239/374484971-dd0a4deb-c4f3-4f8e-85a9-a73d55e2d79f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTg0MjcsIm5iZiI6MTcyODM5ODEyNywicGF0aCI6Ii80MTQ3ODIzOS8zNzQ0ODQ5NzEtZGQwYTRkZWItYzRmMy00ZjhlLTg1YTktYTczZDU1ZTJkNzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODQ0YjI2YjNjZDEzZWI3ZmNkYWVlZWUxYWM0NWFjZWYyZjVlNmRkYzE0OGJiMTg0MmVjNmFlZDMzMTI0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9cLMOZq-J1B9HBv38qUpZ3LM5CAJuDCVYT3wSX_wChI)
> 
> > Also, after I realized that I could get my stuff to work, I downgraded back to the current build.
> 
> Mentioning a problem and then not giving me more information about the problem isn't very helpful. Are you able to still replicate it?

There is no new setup ui if you upgrade from a stable 2.7.0 (which also might in some case give an error but Despite the error still upgrades). And yea, my bloxstrap settings also sometimes alter themselves.

**Comment by ShadowCodeX-debug** [comment]
> What? What do you mean there's "no setup ui"?

Sorry, I completely forgot to test if the RC had setup functionality; When I were testing out 2.7.0 RC it just wouldn't load up a setup if I had no Bloxstrap installed already.

> Mentioning a problem and then not giving me more information about the problem isn't very helpful. Are you able to still replicate it?

Look, I didn't think to send anything at the time and I'm using 2.8.0 again and now it's working just fine.

Also, I've tested out the new setup process and yeah, it's fine. Altough I would've liked if it didn't have the tabs on the left and the window size could've been smaller. (Assuming you made the window size Fixed.)

**Comment by ShadowCodeX-debug** [comment]
More about the bug, my best guess is a version migration bug. I don’t even know if those can happen with Bloxstrap, but that’s all I got.

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer

**Comment by BlueOutside** [comment]
![image](https://github.com/user-attachments/assets/b0bf31f7-9093-436f-af60-bf83702ead9b)
Sooo basically u want a boring installer like most installers
