### ISSUE TITLE
Someone Know how to resolve this erro in bloxstrap?

### ISSUE THREAD

**Issue by Darwingum** [bloxstraplabs/bloxstrap#3089]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot_1](https://github.com/user-attachments/assets/3e937982-4e9d-4915-b2bc-2b3148ad2ef6)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Addressed in Wiki
