### ISSUE TITLE
[BUG] HELP ME PLSSS

### ISSUE THREAD

**Issue by davi2662626** [bloxstraplabs/bloxstrap#3090]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I can't run bloxtrap anymore 

### Bloxstrap Log

![20241005_101106](https://github.com/user-attachments/assets/60eeb938-2a9d-44af-a3ac-80b8d6779767)

**Comment by ShadowCodeX-debug** [comment]
Image doesn't load, sorry.

**Comment by pizzaboxer** [comment]
Upload the image again
