### ISSUE TITLE
[BUG]  The escape menu doesn't work on the v1 and I can't leave

### ISSUE THREAD

**Issue by Averagerobloxenjoyer709** [bloxstraplabs/bloxstrap#3092]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

https://github.com/user-attachments/assets/9a7f27c3-9ed9-4481-9b66-a6699c0848fe

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Add this FFlag:
{
  "FFlagFixReportButtonCutOff": "False"
}
If it's not working, use the 2023 (V4) menu.
