### ISSUE TITLE
this is fake and probably a virus

### ISSUE THREAD

**Issue by randomstuff69** [bloxstraplabs/bloxstrap#3093]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

fake version dont download this its fake

### Bloxstrap Log

N/Asdff

**Comment by internetzx** [comment]
???

**Comment by randomstuff69** [comment]
> ???
![image_2024-10-08_161401228](https://github.com/user-attachments/assets/bba9d579-4376-4bad-b02a-d97d14cc95df)
message from real owner

**Comment by internetzx** [comment]
oh, the github changed

**Comment by randomstuff69** [comment]
then the owner needs to clarify that

**Comment by Naveandice** [comment]
@randomstuff69 https://github.com/bloxstraplabs/bloxstrap/wiki/6th-October-2024-%E2%80%90-Upcoming-changes-to-Bloxstrap#migration-from-pizzaboxerbloxstrap-to-bloxstraplabsbloxstrap

**Comment by MichaelEpicA** [comment]
bruh

**Comment by Frisk9571** [comment]
this could have easily been solved w/o creating an issue by just going to https://github.com/pizzaboxer/bloxstrap and seeing it redirects to here lol

**Comment by randomstuff69** [comment]
i wasnt aware that the github changed at the time and when i clicked on bloxstrap.org on google i didnt think it was the real website (its not) but it redirrects to the official github and i thought it wasnt the real github for bloxstrap because i didnt know it changed to this one because it wasnt the pizza boxer one 
![image](https://github.com/user-attachments/assets/588e3c79-e3d0-4334-a54b-c6a6d428f772)

**Comment by user1126s** [comment]
> i wasnt aware that the github changed at the time and when i clicked on bloxstrap.org on google i didnt think it was the real website (its not) but it redirrects to the official github and i thought it wasnt the real github for bloxstrap because i didnt know it changed to this one because it wasnt the pizza boxer one ![image](https://private-user-images.githubusercontent.com/132950785/374771095-588e3c79-e3d0-4334-a54b-c6a6d428f772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjY1NzUsIm5iZiI6MTcyODQ2NjI3NSwicGF0aCI6Ii8xMzI5NTA3ODUvMzc0NzcxMDk1LTU4OGUzYzc5LWUzZDAtNDMzNC1hNTRiLWM2YTZkNDI4Zjc3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTMxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWYzOTFkNjBlM2M5YTAxNWQyNDc4NzgwMzE1MjA3ZmJhODY2MTI1ZWNhYTY4NTllMjg3MjJhMzc3NTU4NTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yH2YN-BbTWXSMTh14UULg6oL1Pf3xzjJ558BKR3goe8)

Yea the reason these fake websites actually go to this bloxstrap git is to gain people's trust, but at any given moment they can change it to a virus

**Comment by pizzaboxer** [comment]
> then the owner needs to clarify that

please clarify your eyesight prescription

![image](https://github.com/user-attachments/assets/57e492ab-ec19-4f14-ac3d-7d86f0247584)

![image](https://github.com/user-attachments/assets/8e05e88a-a20b-4fb4-8eea-6e308acef610)

**Comment by ShadowCodeX-debug** [comment]
Roasted by the owner lol

**Comment by user1126s** [comment]
lol
