### ISSUE TITLE
fix error

### ISSUE THREAD

**Issue by hyu2112** [bloxstraplabs/bloxstrap#3097]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

không chạy được và bị dính lỗi ngoài lề bloxtrap

### Bloxstrap Log

N/A
[Bloxstrap_20241009T034655Z.log](https://github.com/user-attachments/files/17301759/Bloxstrap_20241009T034655Z.log)

**Comment by Sezei** [comment]
Roblox was down at the time.

Not a Bloxstrap issue.

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
