### ISSUE TITLE
Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zout-of-memory-fixes-control because it returned HTTP 503 (Service Unavailable)

### ISSUE THREAD

**Issue by tuanglam** [bloxstraplabs/bloxstrap#3098]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

cant enter to roblox

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Launch again.
