### ISSUE TITLE
Exception Bloxstrap error

### ISSUE THREAD

**Issue by Analogueee** [bloxstraplabs/bloxstrap#3099]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

It says this when I want to play roblox 
![Screenshot 2024-10-09 122054](https://github.com/user-attachments/assets/9890f569-1617-481c-9239-84e4ad04cc2d)

### Bloxstrap Log

[Bloxstrap_20241009T054809Z.log](https://github.com/user-attachments/files/17302796/Bloxstrap_20241009T054809Z.log)

**Comment by macintosh1999** [comment]
im having the same error

**Comment by saiyancool** [comment]
me too

**Comment by PhantomSloyer** [comment]
any updates?

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
