### ISSUE TITLE
"System.AggregateException" Error

### ISSUE THREAD

**Issue by NickOswald** [bloxstraplabs/bloxstrap#3100]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was trying to log on to a game as usual but then I've shown this error

![image_2024-10-09_142830597](https://github.com/user-attachments/assets/3a8cd703-26a8-481c-b98f-fc27613f471b)

I took a look at the logs and apparently it had to do with my fastflags or something, I'm still new to this.
This never happened before even after I put my desired fastflags months ago until now. I have searched in the Wiki to see if there's any relevant issues, the closest thing I found is the page about [TaskCanceledException](https://github.com/bloxstraplabs/bloxstrap/wiki/"TaskCanceledException"-when-Bloxstrap-launches) error but I have checked my internet connection and disabled any antivirus I had.

### Bloxstrap Log

[Bloxstrap_20241009T072131Z.log](https://github.com/user-attachments/files/17303964/Bloxstrap_20241009T072131Z.log)

**Comment by SomewhereReddish** [comment]
I have this exact issue, it just fine yesterday evening

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
