### ISSUE TITLE
Deserialised application settings is null!

### ISSUE THREAD

**Issue by DesuX-kun** [bloxstraplabs/bloxstrap#3101]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i dont know what happend, yesterday was working fine but today it give me error.
i also tried to check on wiki and google how to fix it. but i found no solution.
System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

### Bloxstrap Log

N/A
[Bloxstrap_20241009T082425Z.log](https://github.com/user-attachments/files/17304927/Bloxstrap_20241009T082425Z.log)

**Comment by Electrocer** [comment]
I recently have the same exact error from Bloxstrap when roblox servers was down today.
[Bloxstrap_20241009T104818Z.log](https://github.com/user-attachments/files/17306806/Bloxstrap_20241009T104818Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
