### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by Willton19** [bloxstraplabs/bloxstrap#3103]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

cant open roblox

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
