### ISSUE TITLE
An expection occurred while running Bloxstrap

### ISSUE THREAD

**Issue by AzulNyehe** [bloxstraplabs/bloxstrap#3104]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

### Bloxstrap Log

N/A
[Bloxstrap_20241009T110829Z.log](https://github.com/user-attachments/files/17306972/Bloxstrap_20241009T110829Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
