### ISSUE TITLE
roblox doesnt open 

### ISSUE THREAD

**Issue by ccccccccccer** [bloxstraplabs/bloxstrap#3106]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

bloxstrap exception error
![image](https://github.com/user-attachments/assets/d0cc3e87-b155-4d60-bd5a-111f82953596)

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
