### ISSUE TITLE
Bloxstrap Issue

### ISSUE THREAD

**Issue by 4c4q** [bloxstraplabs/bloxstrap#3108]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I have just opened my device, tried to open bloxstrap and it showed me an error along with the following code: System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!
I have looked throughout the "Bloxstrap exception" section although I did not find anything that could've helped me.

### Bloxstrap Log

[Bloxstrap_20241009T123652Z.log](https://github.com/user-attachments/files/17308307/Bloxstrap_20241009T123652Z.log)

https://github.com/user-attachments/files/17308307/Bloxstrap_20241009T123652Z.log (downloading log file)

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox

**Comment by kazz708** [comment]
having the same issue but the link isnt working
