### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DeepwokenAddict** [bloxstraplabs/bloxstrap#3113]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I shouldn't be making this but I keep getting the same "Deserialised" Exception issue. I've been trying to do something in my settings that might change it. In the wiki it has told me that it's apparently a problem with Roblox, but I can open Roblox itself just fine without an issue so I am very sure it cannot be a problem on Roblox's end. I've also waited for quite a while now and it's still the same problem. I have no clue how to fix it.

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

**Comment by NabHeyka22** [comment]
Roblox issue. Please wait until they fix it.
