### ISSUE TITLE
QoL Suggestion

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [bloxstraplabs/bloxstrap#3115]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Instead of having only the switches clickable, why not make the entire option clickable? It would make clicking options a lot faster. Those switches could simply be an indicator of when it’s toggled. 

For dropdowns and other selection types, they can stay the same, or — another idea — when you click the option, the dropdown could appear right next to the mouse, anywhere. Additionally, the new shortcut switches (in 2.8.0) could be replaced with buttons.

**Comment by pizzaboxer** [comment]
That's just not how WinUI works.
