### ISSUE TITLE
bloxtrap just wont start

### ISSUE THREAD

**Issue by CsBalazs0703** [bloxstraplabs/bloxstrap#3116]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

its says that: System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

### Bloxstrap Log

[Bloxstrap_20241009T155843Z.log](https://github.com/user-attachments/files/17311492/Bloxstrap_20241009T155843Z.log)

**Comment by Naveandice** [comment]
See #3112.
