### ISSUE TITLE
[BUG] Bloxstrap features won't work

### ISSUE THREAD

**Issue by Erwixity** [bloxstraplabs/bloxstrap#3117]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Very weird thing is happening to me, and I have no idea how to solve it. So whenever I play roblox (even when using bloxstrap's launcher for the app) none of the features apply to it. For example discord shows the roblox logo and not bloxstrap's, or the escape menu is the new version even though i set it to the older version. I saved everything so stupidity does not seem like the issue here. I tried redownloading Bloxstrap but that didn't do it. This issue started when I downloaded shaders, and for them to not get detected it would say on discord that I am playing a different game, but after deleting the shaders it would still say I'm playing a different game, but then a few weeks later it started saying that I play Roblox, which is when the issues started occuring.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Addressed on the Wiki. https://github.com/bloxstraplabs/bloxstrap/wiki/Bloxstrap-doesn't-launch-with-Roblox
