### ISSUE TITLE
[BUG] Random frames jumping when using "alt-enter" fullscreen

### ISSUE THREAD

**Issue by BigBowlORice** [bloxstraplabs/bloxstrap#3118]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When using the "alt-enter" full screen around after every 20 seconds your frames jump causing any movement you made during the jump not happen. This could be a problem with Direct3D as it tends to appear slowly after you've joined a game when using Direct3D11 compared to the frame jumps appearing quicker when using Direct3D10.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Nothing I can do about this. Minor issues are to be expected with exclusive fullscreen.
