### ISSUE TITLE
[BUG] help plz

### ISSUE THREAD

**Issue by AGHA291129** [bloxstraplabs/bloxstrap#3126]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot_1](https://github.com/user-attachments/assets/a32d6e5d-c459-4977-9c9f-2b12e872dcec)
whenever i open my bloxstrap this thing always shows up

**Comment by Wanwood1** [comment]
Try reinstalling

**Comment by AGHA291129** [comment]
hey, tysm its working now
