### ISSUE TITLE
[BUG] Bloxstrap not working at all

### ISSUE THREAD

**Issue by 0202Main** [bloxstraplabs/bloxstrap#3129]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxstrap won't work at all. I even launch games through it but it ends up not working. I have the appearance icon set to the bloxstrap logo and the graphics slider to the 20 option and they don't work, that's how I found out.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
The 21 graphic slider no longer works, due to Roblox removing the FFlag making it work.

**Comment by Wanwood1** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it
https://github.com/bloxstraplabs/bloxstrap/wiki/Bloxstrap-doesn't-launch-with-Roblox
Could you take a look at these and see if it is related to your issue

**Comment by wa1ker38552** [comment]
Have the same issue, no settings are being applied from framerates to texture disabling

**Comment by pizzaboxer** [comment]
> I have the appearance icon set to the bloxstrap logo and the graphics slider

It only takes effect in the bootstrapper.

> and the graphics slider to the 20 option and they don't work

https://github.com/bloxstraplabs/bloxstrap/wiki/'Use-advanced-graphics-quality-selector'-option-not-working
