### ISSUE TITLE
[BUG] Highlights don't show at all

### ISSUE THREAD

**Issue by Z-Yank** [bloxstraplabs/bloxstrap#3132]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I've been having this issue for quite a long time, Roblox in-game highlights do not show for me whatsoever, I've tried to change mulitple bloxstrap settings to try and fix it but it still won't show highlights, I've tried uninstalling and reinstalling bloxstrap and that didn't work either, I've tried running roblox without bloxstrap and it showed me in-game highlights

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Can you please provide a screenshot?
This may be a Roblox issue and not a Bloxstrap issue, since sometimes Roblox doesn't load highlights

**Comment by Z-Yank** [comment]
> Can you please provide a screenshot? This may be a Roblox issue and not a Bloxstrap issue, since sometimes Roblox doesn't load highlights

As I've mentioned before, I've ran roblox normally without bloxstrap and highlights worked perfectly fine, but when I ran the bloxstrap bootstrapper, every highlight broke and did not show (as if the highlight was never there in the first place/as if there's no highlight instance).

Example : I was playing this game called "JoJo's Bizarre Adventure DIAMOND" and 

it has an ability that makes it so u can basically ESP with highlights, by turning your fogend and fogstart to 0 and adding highlights to player characters (basically shows everyone on the map using highlight instances), but when I ran roblox with bloxstrap it only did the fogstart, fogend = 0 and didn't show any highlights

video (with bloxstrap): https://github.com/user-attachments/assets/a829551c-a94a-40c5-a996-1ff5ac91559c
video (without bloxstrap): https://github.com/user-attachments/assets/4301b017-387b-4e0c-9a5c-3babbcdbe51c

**Comment by NabHeyka22** [comment]
Do you have any fastflags? If so, send them here.

**Comment by Z-Yank** [comment]
> Do you have any fastflags? If so, send them here.

Not any that I would know of, The menu says that I have no fastflags

![image](https://github.com/user-attachments/assets/c311ca3b-a12b-4331-81dd-1fc4b3f80e80)

**Comment by NabHeyka22** [comment]
Click show preset flags then screenshot again.

**Comment by Z-Yank** [comment]
> Click show preset flags then screenshot again.

![image](https://github.com/user-attachments/assets/28317b34-9f21-4055-836e-6abf7971672a)

**Comment by NabHeyka22** [comment]
Weird.

**Comment by Z-Yank** [comment]
> Weird.

I've disabled FLogNetwork and it seems the issue's resolved, now when I run roblox with bloxstrap it actually shows the highlights and I can still use bloxstrap's features

**Comment by Z-Yank** [comment]
So I guess I can mark this as resolved I guess

**Comment by joo4nn** [comment]
> So I guess I can mark this as resolved I guess

how did you disabled FlogNetwork? i tried to do it but every time i close bloxtrap and i open it still here, it seems it reset

**Comment by kidlightvevo** [comment]
Did anyone figure out how to disable FLog?

**Comment by mrclbsrr** [comment]
edit it from 7 to 0? unless yours dosen't let you do that, its kinda obvious
