### ISSUE TITLE
[BUG] 60 fps only so every bloxstrap user i find is only running at 60 fps is this able to be fixed?

### ISSUE THREAD

**Issue by thehelperofthego** [bloxstraplabs/bloxstrap#3135]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so i was contacting other bloxstrap users and every bloxstrap user is running at 60 fps is this able to be changed and fix

**Comment by NabHeyka22** [comment]
Are you from the discord server.

**Comment by thehelperofthego** [comment]
no im not

**Comment by NabHeyka22** [comment]
Good.
Anyways, are you playing on a laptop?

**Comment by thehelperofthego** [comment]
yes am

**Comment by NabHeyka22** [comment]
You need to change your power settings then.
Laptops, gaming included, cap games at 60 FPS to not make the battery die.

**Comment by thehelperofthego** [comment]
OH thank you so much everyone i contacted had a laptop so thats my fault

**Comment by NabHeyka22** [comment]
You're welcome.

**Comment by thehelperofthego** [comment]
im running at 120 fps thanks

**Comment by pizzaboxer** [comment]
dude

https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter
