### ISSUE TITLE
Bloxstrap bug

### ISSUE THREAD

**Issue by Gitub004890** [bloxstraplabs/bloxstrap#3138]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I downloaded bloxstrap. I installed it when it opened. But when I searched "Bloxstrap Menu" to open and configure the menu, mods and fastflags, it wasn't there. I checked all my files to see but it was not there. Even I checked where I installed it. The file or app to launch Roblox was there but the menu. It could open Roblox but I could not see the menu anywhere please help I want to configure menu and settings. Thanks and I could not see in the wikipedia

### Bloxstrap Log

N/A

**Comment by Zacgamingpro1234** [comment]
I think is called bloxstrap settings now. If that doesnt work do this:
Go to C:\Users\[Your Username]\AppData\Local\Bloxstrap,
Double click bloxstrap.exe,
You should see an option to select the settings,
Now go to shortcuts in the bloxstrap settings and select the shortcut.
Hope I fixed you issue!

**Comment by pizzaboxer** [comment]
You may need to manually create a shortcut. You can do that by going on the Desktop, selecting New -> Shortcut, and entering this as the item location:

`%localappdata%\Bloxstrap\Bloxstrap.exe -menu`

This issue will be better addressed in the next version of Bloxstrap
