### ISSUE TITLE
[BUG] Unfathomably slow loading times

### ISSUE THREAD

**Issue by qalue** [bloxstraplabs/bloxstrap#3140]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When trying to play any game, Bloxstrap takes ~2 minutes of "Connecting" before it finally works and places you into a game, unsure if this happens for anyone else but it is incredibly annoying having to sit there whilst it takes such a long time to load.

Already reinstalled both ROBLOX & Bloxstrap, nothing changed.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Have you tried running the normal Roblox and seeing if the issue persists?

**Comment by qalue** [comment]
> Have you tried running the normal Roblox and seeing if the issue persists?

yeah - roblox fine by itself

**Comment by pizzaboxer** [comment]
> When trying to play any game, Bloxstrap takes ~2 minutes of "Connecting" before it finally works and places you into a game, 

Can you send your latest log file from `%localappdata%\Bloxstrap\Logs` please?

**Comment by qalue** [comment]
[Bloxstrap_20241015T175310Z.log](https://github.com/user-attachments/files/17382627/Bloxstrap_20241015T175310Z.log)

**Comment by pizzaboxer** [comment]
I see the issue. This appears to be an internet connection problem. I could work on optimising this, but it'd still take quite a while to get through the bootstrapper launch process.

**Comment by qalue** [comment]
> I see the issue. This appears to be an internet connection problem. I could work on optimising this, but it'd still take quite a while to get through the bootstrapper launch process. How is it with v2.8.0?

Works fine for me at the moment but if it changes I'll let you know

Did you change anything in this version that might've fixed it?

**Comment by pizzaboxer** [comment]
> Did you change anything in this version that might've fixed it?

I'm not entirely sure, though I'll keep this open for a bit just in case

**Comment by pizzaboxer** [comment]
Assuming issue is resolved
