### ISSUE TITLE
[BUG] Roblox UI doesn't change

### ISSUE THREAD

**Issue by kotencja3** [bloxstraplabs/bloxstrap#3145]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/08bdd18a-ea25-4c30-b5bc-31673770e7f6)

### Bloxstrap Log

N/A

**Comment by VeryCoolGuy-TSC** [comment]
this just happened to me. Roblox didnt even update

**Comment by VeryCoolGuy-TSC** [comment]
just for clarification: 
![image](https://github.com/user-attachments/assets/6c30938a-a1b7-4c80-8362-03f870ac4ec8)

**Comment by kotencja3** [comment]
> just for clarification: ![image](https://private-user-images.githubusercontent.com/180703763/376788650-6c30938a-a1b7-4c80-8362-03f870ac4ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjQxNDIsIm5iZiI6MTcyOTAyMzg0MiwicGF0aCI6Ii8xODA3MDM3NjMvMzc2Nzg4NjUwLTZjMzA5MzhhLWExYjctNGM4MC04MzYyLTAzZjg3MGFjNGVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQyMDI0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWU0ODBmNzAyNzgyMGY4OGVhMDI3YzE2ZDQ4OWRkYjAxZTExZWRlZDVkZGRiNGM5NTg0YjczMDdmMTJjMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dwfq_fiNhUSMt8TfkxhneXJmwkKxJ4UeWHu4D-t7fgc)

Yes i double checked its also on that for me

**Comment by Josh74000** [comment]
it appears that roblox have removed FFlagEnableInGameMenuChromeABTest3 in the latest update

**Comment by VeryCoolGuy-TSC** [comment]
gosh dangit

**Comment by kotencja3** [comment]
> so no more V1 menu??

No roblox just does it all the time because theyre a bunch of [insert word]

**Comment by Strana** [comment]
I've found a fix for this by digging into flags and setting the following to false, I don't know which specific flag disables the new UI, but these are definitely relevant:
```
FFlagChromeBetaFeature: False
FFlagEnableInGameMenuChromeABTest4: False
FFlagPlayerListChromePushdown: False
```

**Comment by gayloo** [comment]
> I've found a fix for this by digging into flags and setting the following to false, I don't know which specific flag disables the new UI, but these are definitely relevant:
> 
> ```
> FFlagChromeBetaFeature: False
> FFlagEnableInGameMenuChromeABTest4: False
> FFlagPlayerListChromePushdown: False
> ```

This did work for me, the only problem being this...

![RobloxScreenShot20241015_190416684](https://github.com/user-attachments/assets/093f3602-7077-4246-a68f-285104a220a1)

**Comment by Orliminecraft** [comment]
> I've found a fix for this by digging into flags and setting the following to false, I don't know which specific flag disables the new UI, but these are definitely relevant:
> 
> ```
> FFlagChromeBetaFeature: False
> FFlagEnableInGameMenuChromeABTest4: False
> FFlagPlayerListChromePushdown: False
> ```

It's FFlagEnableInGameMenuChromeABTest4: False

**Comment by Frankenstyle46** [comment]
> I've found a fix for this by digging into flags and setting the following to false, I don't know which specific flag disables the new UI, but these are definitely relevant:
> 
> ```
> FFlagChromeBetaFeature: False
> FFlagEnableInGameMenuChromeABTest4: False
> FFlagPlayerListChromePushdown: False
> ```

that doesnt work for me for some reason

**Comment by pizzaboxer** [comment]
Still happening?

**Comment by Shad0w416** [comment]
I made a bug report about this too, where all of the menu/UI versions didn't work, and it was marked as resolved, so its probably fixed now.

**Comment by kotencja3** [comment]
Yes it works fine now

**Comment by kotencja3** [comment]
Yes it works fine now!
