### ISSUE TITLE
[BUG] dont have the option to change escape menu and it wont change

### ISSUE THREAD

**Issue by turbosoggybread** [bloxstraplabs/bloxstrap#3146]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot 2024-10-15 155316](https://github.com/user-attachments/assets/3b837238-6b33-4fec-ac94-84a7133c733b)

### Bloxstrap Log

N/A

**Comment by VeryCoolGuy-TSC** [comment]
![image](https://github.com/user-attachments/assets/bee6dd15-aeff-4973-a57e-1f320190800d)
its here, also yes, the menu is bugged rn. (https://github.com/bloxstraplabs/bloxstrap/issues/3145)
