### ISSUE TITLE
[BUG] i get stuck in the bloxstrap configure whenever i open roblox

### ISSUE THREAD

**Issue by mauropro24** [bloxstraplabs/bloxstrap#3147]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

whenever i want to play roblox bloxstrap updating roblox and configure gets me stuck in here forever, i reinstallated bloxstrap and did many things like re install roblox or clean cache. but nothing works, please help i want my minecraft font again 😭

### Bloxstrap Log

N/A

**Comment by mauropro24** [comment]
title self explain, i already cleaned cache, reinstalled roblox and bloxstrap with every other version.

**Comment by bluepilledgreat** [comment]
pizzaboxer went to sleep as we were about to release a build that fixes this. please kill pizzaboxer once he wakes up.
the problem? you're in zbeta. the solution? download 2.8.0 or launch bloxstrap with the following arguments: `Bloxstrap.exe roblox-player:1+channel:live`.
remember to kill pizzaboxer once he wakes up.

**Comment by ItsVetskuGaming** [comment]
You wouldn't happen to have a link to the release candidate, would you? I got the same problem and I am quite unfamiliar with Github so I don't know where to find it.

**Comment by bluepilledgreat** [comment]
> You wouldn't happen to have a link to the release candidate, would you? I got the same problem and I am quite unfamiliar with Github so I don't know where to find it.

https://github.com/bloxstraplabs/bloxstrap/actions/runs/11354677148
this build should be close to release.

**Comment by ItsVetskuGaming** [comment]
Works like a charm now! Thanks!

**Comment by mauropro24** [comment]
@bluepilledgreat Hi, how i can install bloxstrap 2.8.0? it will help a lot.
