### ISSUE TITLE
[BUG] Upgrading Roblox, then Configuring forever.

### ISSUE THREAD

**Issue by Res0ula** [bloxstraplabs/bloxstrap#3149]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxstrap was working perfectly fine last night and now it decides to "Upgrade Roblox" then Configure forever. I've tried reinstalling both Bloxstrap and Roblox, tried flushing out my cache dns, tried even restarting my pc and it still won't work. The only time Bloxstrap seems to be working is whenever I first install it, which takes me to the Roblox Menu. Closing out of that menu leads to "Upgrading Roblox" problem again.
![image_2024-10-15_191343007](https://github.com/user-attachments/assets/ae6e448a-2058-4d9e-a243-0eacfec9b549)
![image_2024-10-15_191351825](https://github.com/user-attachments/assets/6492e6a8-a160-4ba1-9733-28b0acbd5acc)

### Bloxstrap Log

N/A

**Comment by Progamer912-commits** [comment]
same for me.

**Comment by Terminal-Coding** [comment]
Same issue

**Comment by Rondomeguy** [comment]
It's also happening to 2 of my main accounts, when I switched with a different account, then it works???

**Comment by Terminal-Coding** [comment]
yeh, swithcing accounts works, switching browsers didnt work tho

**Comment by Terminal-Coding** [comment]
changing version also doesnt work
