### ISSUE TITLE
[BUG] Bloxstrap stuck on configuring.

### ISSUE THREAD

**Issue by Progamer912-commits** [bloxstraplabs/bloxstrap#3151]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Every time I try to play ROBLOX, Bootstrap has been stuck on "configuring

### Bloxstrap Log

N/A

**Comment by tbrbx** [comment]
me too
