### ISSUE TITLE
[BUG] Menus not working after new update

### ISSUE THREAD

**Issue by Shad0w416** [bloxstraplabs/bloxstrap#3153]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Whenever I change my menu version, its stuck to the newest version with the big shitty healthbar, and the new chat system and everything.
(Ignore the shaders.)
![image](https://github.com/user-attachments/assets/81eb33f5-4981-4485-b637-3c7f2074735e)
![Euro Truck Simulator 2 Screenshot 2024 10 15 - 21 13 10 84](https://github.com/user-attachments/assets/f61a90e9-1f3b-43d5-b785-d8dfdf734557)
![Euro Truck Simulator 2 Screenshot 2024 10 15 - 21 13 13 37](https://github.com/user-attachments/assets/b5266c6b-b401-414a-979c-b97802d5cbe1)

### Bloxstrap Log

N/A

**Comment by enfunfun** [comment]
same problem here
