### ISSUE TITLE
[BUG]  configuring forever

### ISSUE THREAD

**Issue by xkatgamingx** [bloxstraplabs/bloxstrap#3154]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

! Roblox needed to update so it went through the updating process. Now it needs to be configured but its configuring forever. I tried reinstalling bloxstrap but its still not working. Please help when you can, thank you.
![image (2)](https://github.com/user-attachments/assets/28c7ee1c-79d7-4759-9c59-b7e241f93c68)

### Bloxstrap Log

N/A

**Comment by Trackerlist** [comment]
Same issue here. #3147

**Comment by Terminal-Coding** [comment]
read the tasks correctly 💀 post already made on this

**Comment by xkatgamingx** [comment]
> read the tasks correctly 💀 post already made on this

im not familar with the website brosi 🤡

**Comment by Terminal-Coding** [comment]
lmaooo, u still ticked off the boxes yet didn't read what each of them are

**Comment by Terminal-Coding** [comment]
ur problem has been addressed, legit the top 3 most recent and I guess you told the truth when you said u weren't honest, reread the checkboxes
