### ISSUE TITLE
[BUG] Ingame "Invite Friends" join button exits to desktop with setting enabled

### ISSUE THREAD

**Issue by firedstew** [bloxstraplabs/bloxstrap#3155]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When a friend invites you while you're ingame, a popup will appear in the top right. 
If the **"Don't exit to desktop app"** setting is enabled when you click join, Roblox will close instead of joining the new game. 
 
![image](https://github.com/user-attachments/assets/a1c154b4-5588-4f64-b615-8d10f31affed)
![image](https://github.com/user-attachments/assets/e30b8ed5-431c-413e-a142-3ca2fe551aab)

This issue doesn't seem to occur when the setting is disabled.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Thanks for reporting, wasn't aware about this.

Unfortunately, I don't think I can workaround this issue. We'll just have to warn people about this when they enable it.
