### ISSUE TITLE
Escape menu version

### ISSUE THREAD

**Issue by nxrLover** [bloxstraplabs/bloxstrap#3156]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

No matter what i do my escape menu version will always reset to default which is ugly

### Bloxstrap Log

N/A

**Comment by TTKBradley** [comment]
I am having this exact same problem and trying to fix it because I hate it and don't like the original.
