### ISSUE TITLE
Bloxstrap classic theme error/bug

### ISSUE THREAD

**Issue by PIIXLLL** [bloxstraplabs/bloxstrap#3160]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Recently I've downloaded bloxstrap to customize some of the things on Roblox I wanted which took places a few hours ago. The problem is when I had the Classic Roblox's theme enabled somehow when I opened the Roblox's game setting something has happened, I could not see any others catagory availiable EXCEPT leave, reset and resume game.

Which the 3 options stated, their GUI seems to be not working except for the resume button, I'm unable to left the experience and close Roblox. Unless I restarted my computer which took a long progresses to-do. I searched some while to see if someone has the same issue as I do but couldn't find any (maybe). Any helps?

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
This should be fixed now, is this issue still happening?

**Comment by PIIXLLL** [comment]
Nope, it remains the same

![Uploading image.png…]()

**Comment by pizzaboxer** [comment]
You might be enrolled in a channel which has removed the ability to use newer menu versions. I'll wait a bit to see how this plays out though.
