### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by oversai2** [bloxstraplabs/bloxstrap#3161]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/f921c46b-a215-4b8c-af55-26d1c825ee8e)
Where i can allow multi accounts? Where button?

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap?tab=readme-ov-file#frequently-asked-questions
