### ISSUE TITLE
[BUG] The requested operation requires elevation.

### ISSUE THREAD

**Issue by RedSensed** [bloxstraplabs/bloxstrap#3163]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

this happens each time i open bloxstrap version 2.8.0
![image](https://github.com/user-attachments/assets/cc864b3a-15b6-4e45-bfa0-1be6d3ab8c87)

**Comment by RedSensed** [comment]
my antivirus is off and it still is telling me that

**Comment by pizzaboxer** [comment]
It's not a Bloxstrap issue, something is interfering and preventing Bloxstrap from launching Roblox.

**Comment by RedSensed** [comment]
i had to run it as administrator for it to work again
