### ISSUE TITLE
[BUG] the bloxstrap thinks that the roblox crashes, but roblox is functioning normally.

### ISSUE THREAD

**Issue by bulieme** [bloxstraplabs/bloxstrap#3164]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

as the title above, the roblox is still running but bloxstrap thinks that roblox isnt running.

i've tried:
 - resetted my fastflag's

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Issue confirmed, moved to #3176

**Comment by ronaldo52107** [comment]
This could happen for windows 11 users only with a mid/low-end pc.

**Comment by bulieme** [comment]
im using windows 10 with a low-end pc and had this same problem
