### ISSUE TITLE
[BUG] Bloxshade not working / installing with new Bloxstrap update

### ISSUE THREAD

**Issue by daflame899** [bloxstraplabs/bloxstrap#3165]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![bloxshade_no](https://github.com/user-attachments/assets/17e5f57c-6ed4-479b-b97a-1f3584bbd184)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Report this to Bloxshade, not us.
