### ISSUE TITLE
[BUG] missing features

### ISSUE THREAD

**Issue by parti458777** [bloxstraplabs/bloxstrap#3166]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

where are the avanced graphics and better fullscreen features at?

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
github.com/pizzaboxer/bloxstrap/wiki/release-notes-for-Bloxstrap-v2.8.0
