### ISSUE TITLE
[BUG] I cant click any buttons on bloxstrap 2.8 wdym "new and improved"??

### ISSUE THREAD

**Issue by bloxstrapenjoyer** [bloxstraplabs/bloxstrap#3167]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

installed 2.8 freshly and opened it..had to restart my computer and now bloxstrap doesnt let me click any buttons on roblox home menu

### Bloxstrap Log

bobm fix neow.

**Comment by pizzaboxer** [comment]
Show a video of the issue please

**Comment by bloxstrapenjoyer** [comment]
> Show a video of the issue please
my bad it was just roblox
