### ISSUE TITLE
[BUG] FPS Problems with new version

### ISSUE THREAD

**Issue by ToxicTDX** [bloxstraplabs/bloxstrap#3170]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

My fps has dropped 30 - 50 fps since the new Bloxstrap update. No clue why, went through the fflags, everything, just have future lighting and texture quality at 3 enabled. I know that this is not a Laptop problem, i got it two months ago. 

Specs: Core i7 14650HX
GPU: RTX 4060 

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Are you sure this correlates with the version of Bloxstrap you're using? I doubt it does. If you're sure about it, check by reinstalling 2.7.0 (with auto updates disabled)

**Comment by ToxicTDX** [comment]
> Are you sure this correlates with the version of Bloxstrap you're using? I doubt it does. If you're sure about it, check by reinstalling 2.7.0 (with auto updates disabled)

Yeah, its solved now, turns out my laptop randomly enabled igpu for everything. Thanks though!
