### ISSUE TITLE
[BUG] Game's website link redirect

### ISSUE THREAD

**Issue by grfbdh** [bloxstraplabs/bloxstrap#3173]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I want to join a game through a website, Bloxstrap instead opens an app.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Can you please clarify? What does it open? Show a screenshot

**Comment by grfbdh** [comment]
![RobloxPlayerBeta_GqgGcbrjql](https://github.com/user-attachments/assets/74b57477-76b6-4dec-918e-feecb629f880)
I click on a play button on a website.
Bloxstrap menu shows up.
I click on "Play Roblox" button.
It opens a Roblox app's home page instead of an experience I want to play.

**Comment by pizzaboxer** [comment]
Show the latest log file from `%localappdata%\Bloxstrap\Logs` please

**Comment by grfbdh** [comment]
[Bloxstrap_20241016T134945Z.log](https://github.com/user-attachments/files/17397096/Bloxstrap_20241016T134945Z.log)
This one is an attempt of fixing the other bug when RobloxPlayerBeta.exe disappeared.
[Bloxstrap_20241016T135001Z.log](https://github.com/user-attachments/files/17397131/Bloxstrap_20241016T135001Z.log)
This one is when I tried to join for a second time

**Comment by grfbdh** [comment]
[0.646.0.6460700_20241016T134958Z_Player_D397A_last.log](https://github.com/user-attachments/files/17397230/0.646.0.6460700_20241016T134958Z_Player_D397A_last.log)
[0.646.0.6460700_20241016T134906Z_Player_35354_last.log](https://github.com/user-attachments/files/17397231/0.646.0.6460700_20241016T134906Z_Player_35354_last.log)
Here are the ones from Roblox if needed

**Comment by grfbdh** [comment]
![regedit_75sj1ZRtrF](https://github.com/user-attachments/assets/43132b6f-ad67-48a1-8138-ab583d927daa)

**Comment by grfbdh** [comment]
gtg to college, will be inactive for ~10h today

**Comment by pizzaboxer** [comment]
I might know what's going on, I'll send you a test build in a moment

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 - reopen if not
