### ISSUE TITLE
[BUG] The expansion of the number of quality divisions does not work. The problem has been going on for more than a month.

### ISSUE THREAD

**Issue by blackcat515** [bloxstraplabs/bloxstrap#3175]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The expansion of the number of quality divisions does not work. The problem has been going on for more than a month.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Are you talking about the 21 graphic option?
If so, roblox removed the FFlag that made it work, meaning you can no longer use it.

**Comment by blackcat515** [comment]
Oh, ok(
Sorry.

**Comment by blackcat515** [comment]
Then should I remove this option?

**Comment by NabHeyka22** [comment]
Yes.

**Comment by blackcat515** [comment]
Ok. thk for help )
