### ISSUE TITLE
[REQ] Start Menu option for the 2 "Function" shortcuts

### ISSUE THREAD

**Issue by Mohammad99X** [bloxstraplabs/bloxstrap#3177]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Like the _General_ shortcut, give the 2 _Function_ shortcuts the option to create them on the Start Menu and not just on the Desktop.

Also, so there won't be a bunch of Bloxstrap shortcuts scattered in the Start Menu folder, place them all in a folder simply named _Bloxstrap_.
![explorer_wEyyePF69h](https://github.com/user-attachments/assets/836d5a97-ec6c-4b05-b249-a83759b80ffb)

While yeah we can do this pretty easily manually, I still thought it would be better to have it as an option in the settings so it's more user-friendly.

**Comment by pizzaboxer** [comment]
I only provide the option to place them on the desktop because I intend for people to manually add them to the Start menu if they wish. Same can be said for pinning to the taskbar, etc.
