### ISSUE TITLE
[BUG] new bloxtrap menu when you open it

### ISSUE THREAD

**Issue by kaba4koff** [bloxstraplabs/bloxstrap#3178]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

with the new update, it is no longer convenient for me to open bloxtrap and besides, bloxshade is no longer installed on bloxtrap

### Bloxstrap Log

![Снимок экрана 2024-10-16 193033](https://github.com/user-attachments/assets/94aee640-f665-40f5-91f5-96b8c6e1abe6)
![Снимок экрана 2024-10-16 193033](https://github.com/user-attachments/assets/bf86dfda-42ab-41ae-93b3-7f88793e50bf)

**Comment by NabHeyka22** [comment]
For Bloxshade you need to use the 2.7.0 version.
