### ISSUE TITLE
[BUG] Inconsistency within the Bloxstrap "Mods" page

### ISSUE THREAD

**Issue by Encythe** [bloxstraplabs/bloxstrap#3181]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Initially, on my 1440p screen, the "Open Mods Folder" does not scale to fit the vertical space given when its adjacent button is scaled vertically because the text doesn't fit.
![image](https://github.com/user-attachments/assets/4bbe32a2-ec23-4f3b-9c0e-3d9df741a526)
![chrome_aSb1kmLaQd](https://github.com/user-attachments/assets/3691fc8b-2cee-47e9-9712-19bfc1953a89)
### Bloxstrap Log

nil, null, None, N/A, etc.

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
