### ISSUE TITLE
[BUG] Installer not working (v2.8.0)

### ISSUE THREAD

**Issue by Rivvie** [bloxstraplabs/bloxstrap#3182]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I installed bloxstrap v2.8.0 and running the installer alarms Microsoft Defender Smartscreen. I turned my antivirus off but even then it got blocked, what's happening and how do I fix it?
NOTE - I have tried to see if this problem also encounters with bloxstrap v2.7.0 and it doesn't. It's specifically for v2.8.0.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
> what's happening

2.8.0 is new and antiviruses haven't seen it before and therefore suspect it, This usually clears up after a few days.

> and how do I fix it?

https://github.com/bloxstraplabs/bloxstrap?tab=readme-ov-file#installing

![image](https://github.com/user-attachments/assets/a21f52eb-e769-4f6a-8128-f71e0bf03d1f)

**Comment by Rivvie** [comment]
thanks!
