### ISSUE TITLE
[BUG] i launch the new version of the unlocker and pc crashed

### ISSUE THREAD

**Issue by cyc-boop** [bloxstraplabs/bloxstrap#3187]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

[BUG]As soon as I  launch the unlocker (New version), my pc crash

### Bloxstrap Log

N/A I was about to open my roblox when my computer crashed. I was using the latest version unlocker and I don't know what happened. I tried to reinstall it and it didn't work. It still crashed (btw i use google to play roblox)

**Comment by pizzaboxer** [comment]
What the hell is unlocker?

**Comment by internetzx** [comment]
tf is "unlocker"
