### ISSUE TITLE
[BUG] I cannot use Rich Presence properly

### ISSUE THREAD

**Issue by TotallyNot-Alpha** [bloxstraplabs/bloxstrap#3188]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

So, I checked the wiki, checked for other bugs reported and even checked for youtube videos and none could solve my issue. I already uninstalled and installed roblox, uninstalled and installed bloxstrap and uninstalled and installed discord and I still cannot seem to be able to use Rich Presence

Here are some evidences:
![Captura de pantalla 2024-10-16 212531](https://github.com/user-attachments/assets/5bad8c44-59c1-474d-bc27-560638ee0b13)
![Captura de pantalla 2024-10-16 212605](https://github.com/user-attachments/assets/c4f4a0a4-0b47-4931-ba2c-a1eabba465a5)
![Captura de pantalla 2024-10-16 212628](https://github.com/user-attachments/assets/994803c3-6a4e-4b3a-b9f5-faf2d7824961)
![Captura de pantalla 2024-10-16 212645](https://github.com/user-attachments/assets/8d7adcd2-8fd3-43f0-bed6-e5ed416f3c8a)

here is the latest log file: 

[Bloxstrap_20241016T202954Z.log](https://github.com/user-attachments/files/17402371/Bloxstrap_20241016T202954Z.log)

Let me know if there is anything else to help you guys figure what's the issue cause I cant seem to find it :/

 P.S.: it used to be workin back during 2.5.1 but these recent updates didnt let me use it so idk if it is a discord update, a roblox update or a bloxstrap update that broke it

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Bloxstrap seems to be working fine here. This is an issue on Discord's side in some way. Do you use any Discord client mods?

**Comment by TotallyNot-Alpha** [comment]
Yea, I'm using vencord

**Comment by pizzaboxer** [comment]
What plugins do you have enabled.

**Comment by TotallyNot-Alpha** [comment]
![image](https://github.com/user-attachments/assets/815adce4-6175-4a54-9c48-df45a3008fca)
![image](https://github.com/user-attachments/assets/ffb6f1aa-7b58-4507-b7b5-4455e2c02e0e)

**Comment by pizzaboxer** [comment]
Can you check to see if the stock Discord client works?

**Comment by TotallyNot-Alpha** [comment]
No. I wen back to the stock discord client and it still has the same issue
![image](https://github.com/user-attachments/assets/be31ff3b-c964-42aa-9f80-585d25863b0b)
activity is on
![image](https://github.com/user-attachments/assets/0db13985-90ba-4ff6-ad63-88f05b0409cd)
game being detected is working too
![image](https://github.com/user-attachments/assets/9f0b6930-0a7a-46c7-9f1f-4d6f77c3af18)
and I got a friend of mine who is using the same version but it's working for him so yea :/
![image](https://github.com/user-attachments/assets/31e47b1a-4119-404f-a431-fe9fe130f4ca)
i even asked him about it 
![image](https://github.com/user-attachments/assets/a6d37312-d8c6-4ca2-b887-3bb1a72992c7)

**Comment by pizzaboxer** [comment]
Do you have multiple Discord clients open? Bloxstrap is recognizing your username as `Totally_notalpha`, but in one of the screenshots you sent it appears to be `alpha_washere`

**Comment by TotallyNot-Alpha** [comment]
Yes, `Totally_notalpha` is another account that I have. Should I just log off of it to prevent issues with rich presence?

P.S.: I just quit the other discord client and it actually worked
![image](https://github.com/user-attachments/assets/555caf8d-7bf0-4573-ac51-c5e7f9f1eb8d)

Thank you for all of your help :)
