### ISSUE TITLE
[REQ] OpenGL in rendering mode menu

### ISSUE THREAD

**Issue by ZombifiedV2** [bloxstraplabs/bloxstrap#3190]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

you can already do this via fflags just why would you remove it

**Comment by bluepilledgreat** [comment]
OpenGL is unstable and not recommended. Windows distributions only ever uses D3D10 or D3D11.

**Comment by ZombifiedV2** [comment]
but the thing is you had it there before but you removed it, there is no point in removing something just because the majority dosent use it
