### ISSUE TITLE
[BUG] An exception ocurred while running bloxtrap

### ISSUE THREAD

**Issue by Angeelvxg** [bloxstraplabs/bloxstrap#3191]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I cant open bloxtrap
![Screenshot_1](https://github.com/user-attachments/assets/48b05050-1955-40a0-bada-91eb8b23df85)

### Bloxstrap Log

N/A
[Bloxstrap_20241016T212823Z.log](https://github.com/user-attachments/files/17402976/Bloxstrap_20241016T212823Z.log)

**Comment by bluepilledgreat** [comment]
Update to the latest version of Bloxstrap.
