### ISSUE TITLE
I got an exception issue

### ISSUE THREAD

**Issue by Arch-Maestro** [bloxstraplabs/bloxstrap#3194]
System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by KOMKO190** [comment]
Yeah me as well

**Comment by yarbio** [comment]
SAMEEE
