### ISSUE TITLE
[BUG] Bloxstrap Exception

### ISSUE THREAD

**Issue by yarbio** [bloxstraplabs/bloxstrap#3195]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

[Bloxstrap_20241016T213801Z.log](https://github.com/user-attachments/files/17403030/Bloxstrap_20241016T213801Z.log)

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by pizzaboxer** [comment]
> "I am using the latest version of Bloxstrap"
> "2024-10-16T21:38:01Z [App::OnStartup] Starting Bloxstrap v2.5.3"

thanks buddy

**Comment by yarbio** [comment]
sorry didnt notice i have auto update onn

**Comment by yarbio** [comment]
> Update to 2.8.0.

sorry i didnt know there was anew update , i have auto update on too.. :-(
