### ISSUE TITLE
[BUG] an exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Lucid1172** [bloxstraplabs/bloxstrap#3196]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

my bloxstrap is not opening 

### Bloxstrap Log

[Bloxstrap_20230825T132913Z.log](https://github.com/user-attachments/files/17403055/Bloxstrap_20230825T132913Z.log)

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap. Go upgrade it.

**Comment by bluepilledgreat** [comment]
> You're not using the latest version of Bloxstrap. Go upgrade it.

the log file is over a year old. took him a whole year to send it to us.
