### ISSUE TITLE
[BUG] Got an exception error while running bloxstrap.

### ISSUE THREAD

**Issue by Arch-Maestro** [bloxstraplabs/bloxstrap#3198]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot (1684)](https://github.com/user-attachments/assets/c76ee2da-d590-4f62-a693-1c88f8e75ef0)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by Arch-Maestro** [comment]
ight bet
