### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by koolkidisfunny** [bloxstraplabs/bloxstrap#3205]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

Yes i have a inner exception i dont know if its the same thing but i would think so because they both have exception

**Comment by MaxwellTheGoober** [comment]
same bug

**Comment by levigenesis** [comment]
same bug

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by Aka9000** [comment]
Same bug here

**Comment by TopSpamma** [comment]
same here. Only 35 minutes ago?

**Comment by avery817817** [comment]
same here

**Comment by avery817817** [comment]
same here, you have to go and download the new update from the github page. I don't know why the automatic update says the error.

**Comment by many-boiled-potatoes** [comment]
Is there any way to stay on the current version?

**Comment by lmaoNebula** [comment]
Is there any way to stay on the current version? I am using an older version that supports multi-roblox and it worked just fine prior to this.

**Comment by wilcyG** [comment]
how to update it?
reinstall or i can update?

**Comment by BunnyProPlayz** [comment]
> how to update it? reinstall or i can update?

bloxstraplabs.com

**Comment by wilcyG** [comment]
ty, but i need delete my main old blox trap?
or it wil installs again?

**Comment by TopSpamma** [comment]
Just download the latest version or reinstall

**Comment by Flaviu223** [comment]
yes ik if u  get newer version it works but i wanna use 2.5.4 idk why it doesnt work now

**Comment by many-boiled-potatoes** [comment]
> yes ik if u get newer version it works but i wanna use 2.5.4 idk why it doesnt work now

Sorry, but I am pretty sure that a Roblox update caused all of this, and i doubt the devs will fix it. I think its best to just switch to something else until they bring back multi-instance launching.

**Comment by Eth030** [comment]
> > yes ik if u get newer version it works but i wanna use 2.5.4 idk why it doesnt work now
> 
> Sorry, but I am pretty sure that a Roblox update caused all of this, and i doubt the devs will fix it. I think its best to just switch to something else until they bring back multi-instance launching.

what is something else for multi?

**Comment by many-boiled-potatoes** [comment]
> > > yes ik if u get newer version it works but i wanna use 2.5.4 idk why it doesnt work now
> > 
> > 
> > Sorry, but I am pretty sure that a Roblox update caused all of this, and i doubt the devs will fix it. I think its best to just switch to something else until they bring back multi-instance launching.
> 
> what is something else for multi?

Roblox Account Manager is good
