### ISSUE TITLE
[REQ] It is about the graphic option of 21-1 graphics

### ISSUE THREAD

**Issue by roman123-jpg** [bloxstraplabs/bloxstrap#3208]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Why didn't they add the option to put 21 to 1 graphics, that had helped me a lot in bloxtrap to have a good experience in Roblox, fix it, I want it now, Thank you very much.

**Comment by MaxwellTheGoober** [comment]
For some reason, roblox has broken it, I don't think it's possible to change, but the developers can prove me wrong.

**Comment by MaxwellTheGoober** [comment]
Oh yeah, same thing about the ESC menu with the new gui change.
