### ISSUE TITLE
[BUG] cant find bloxstrap even i have it

### ISSUE THREAD

**Issue by saintflow44** [bloxstraplabs/bloxstrap#3209]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![{87931A01-D255-48CC-A48E-A5C33CCEE102}](https://github.com/user-attachments/assets/312c506d-a3a9-440b-9558-7af763cba7cd)
![{9A7F724A-8D7E-4864-B65F-0CBC7F07F07E}](https://github.com/user-attachments/assets/b379a3f2-736a-4691-a751-6a708e304fd3)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by saintflow44** [comment]
pls fix fast

**Comment by saintflow44** [comment]
Thank You
