### ISSUE TITLE
[BUG] Bloxstrap v2.8.0 not uploaded to Winget

### ISSUE THREAD

**Issue by ProjectHSI** [bloxstraplabs/bloxstrap#3212]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap (I don't think this matters for this issue honestly).
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxstrap v2.8.0 is not available on Winget. The action failed due to it referring to pizzaboxer/winget-pkgs, not bloxstraplabs. Probably.

### Bloxstrap Log

https://github.com/bloxstraplabs/bloxstrap/actions/runs/11363283606

**Comment by pizzaboxer** [comment]
Oh, I didn't notice that. My bad.
