### ISSUE TITLE
[BUG] Rpblox Wont Open

### ISSUE THREAD

**Issue by MellFlovked** [bloxstraplabs/bloxstrap#3216]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

N/A
[Bloxstrap_20241016T235559Z.log](https://github.com/user-attachments/files/17404224/Bloxstrap_20241016T235559Z.log)

**Comment by pizzaboxer** [comment]
You are not using the latest version of Bloxstrap.
