### ISSUE TITLE
the key redist zip is not present in the dictionary?

### ISSUE THREAD

**Issue by vink-racoon** [bloxstraplabs/bloxstrap#3219]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

uhh so i was trying to play roblox but then this error appeared,i just cant explain it j-just read the log

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by 1Terio** [comment]
same thing happened to me

**Comment by Rebirthed-100** [comment]
this is spreading

**Comment by pizzaboxer** [comment]
upgrade bloxstrap
