### ISSUE TITLE
[BUG] my fastflags doesnt work 

### ISSUE THREAD

**Issue by voteally** [bloxstraplabs/bloxstrap#3221]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

(i had them deactivacted before the update and i cant activacte them again in this new update) pls fix this

### Bloxstrap Log

N/A

**Comment by cmerk2021** [comment]
This too happened to me, deleting and reinstalling Bloxstrap worked for me. Hope this helps!

**Comment by pizzaboxer** [comment]
Known bug

You can do what cmerk2021 said, or you can go to `%localappdata%\Bloxstrap`, open `Settings.json` in a text editor, and change the value of `"UseFastFlagManager"` from `false` to `true`

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
