### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by flokkung** [bloxstraplabs/bloxstrap#3222]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i can't join every game in the roblox 
![image](https://github.com/user-attachments/assets/79dacd59-e90e-47d6-9d58-66b575a390ef)

### Bloxstrap Log

pls help me pls😭😭

**Comment by Encythe** [comment]
please upgrade to the latest version of bloxstrap, 2.8.0
