### ISSUE TITLE
[BUG] my fflags not woking.lagyier then old version.never loads my game

### ISSUE THREAD

**Issue by dripblox** [bloxstraplabs/bloxstrap#3225]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

my fflags not woking.lagyier then old version.never loads my game

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Can you give more details please?

**Comment by dripblox** [comment]
old version average fps when i start the game  100 new versoin 70fps
also how do i stop the reminder to read that thing when i downloaded the new versoin(it always pops-up)

**Comment by pizzaboxer** [comment]
> old version average fps when i start the game 100 new versoin 70fps

...Is that it? That's not a very clear indicator as to whether your flags are working or not.

>  also how do i stop the reminder to read that thing when i downloaded the new versoin(it always pops-up)

That's a bug, sorry about that.

**Comment by dripblox** [comment]
thats it
