### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 0xzit** [bloxstraplabs/bloxstrap#3226]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Couldn't install bloxshade for bloxstrap, before it was perfectly fine, but now it just kept saying "failed to open file". Is there any way to fix this issue? My bloxstrap is on version 2.8.0. I'm not so sure what was the version I use before, I think it's 2.7.0.
![Screenshot 2024-10-17 103116](https://github.com/user-attachments/assets/98891b2f-f650-4d53-b5e3-5a44a08698f0)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
No, this is for Bloxshade to fix.
