### ISSUE TITLE
[BUG] Bloxstap Exception Error

### ISSUE THREAD

**Issue by Cobr1** [bloxstraplabs/bloxstrap#3227]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i changed some roblox ui settings (escape menu) on the bloxstrap menu, and when i opened the "Launch Roblox" app, it gave me an exception error

### Bloxstrap Log

[error.txt](https://github.com/user-attachments/files/17405378/error.txt)
![image](https://github.com/user-attachments/assets/3993cefd-a693-4e95-906c-c4edaedfbd73)

**Comment by pizzaboxer** [comment]
Likely an antivirus issue, check to make sure any antiviruses you have aren't causing problems, or try reinstalling

**Comment by Cobr1** [comment]
> Likely an antivirus issue, check to make sure any antiviruses you have aren't causing problems, or try reinstalling

i reinstalled bloxstrap and its still not letting me launch roblox. i opened the windows antivirus history and there was nothing. i have a feeling it could be my internet because its been down for 2 days now, and ive been using my phone's hotspot. also, i forgot to say that i also updated to the newest version, THEN changed some ui settings.
![image](https://github.com/user-attachments/assets/14fede0e-c096-450c-9ea4-8e3cbe395a00)

**Comment by Cobr1** [comment]
> > Likely an antivirus issue, check to make sure any antiviruses you have aren't causing problems, or try reinstalling
> 
> i reinstalled bloxstrap and its still not letting me launch roblox. i opened the windows antivirus history and there was nothing. i have a feeling it could be my internet because its been down for 2 days now, and ive been using my phone's hotspot. also, i forgot to say that i also updated to the newest version, THEN changed some ui settings. ![image](https://private-user-images.githubusercontent.com/185315210/377662341-14fede0e-c096-450c-9ea4-8e3cbe395a00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDkzOTMsIm5iZiI6MTcyOTIwOTA5MywicGF0aCI6Ii8xODUzMTUyMTAvMzc3NjYyMzQxLTE0ZmVkZTBlLWMwOTYtNDUwYy05ZWE0LThlM2NiZTM5NWEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMzUxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWI3MzU4OGViOTZhNjg1MzI1NTA1ZTc3YmI5MTBhYzIxMzRlZmJiYzFkZGFjM2ExMWViZDAxOWYzMDJlOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jWZYOrHTbuVC7eY_AbHhoBFYhDNl5vNwGl9uUE1KASw)

adding to this, everytime i try to launch roblox it always tries to install (Connecting -> Upgrading -> Configuring -> Opening), then gives me the error
