### ISSUE TITLE
[BUG] infinite loop

### ISSUE THREAD

**Issue by kyrosh-ANF** [bloxstraplabs/bloxstrap#3228]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

hello?
uhmm
my bloxtrap dont work, he just keep in a loop of configuration and i dont know why
maybe my wifi? i used the last version but when i saw what bloxtrap dont open, i installed a posterior version only for see if he worked (srry for my English i am bad lerning new lenguajes)

https://github.com/user-attachments/assets/3aa15bc6-eea1-40a3-bedd-4706fae9da22

### Bloxstrap Log

N/A

**Comment by GottaLoveAng** [comment]
same here. i went to github to see if it was just me.

**Comment by GottaLoveAng** [comment]
updating to the latest version 2.8.0 fixed it

**Comment by kyrosh-ANF** [comment]
oh really?

**Comment by kyrosh-ANF** [comment]
yep
