### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by FrosteyeDev** [bloxstraplabs/bloxstrap#3229]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

![image](https://github.com/user-attachments/assets/362b04e1-100a-4886-bcd7-41388588dde7)

**Comment by lifesad** [comment]
how to fix this

**Comment by BunnyProPlayz** [comment]
update bloxstrap
