### ISSUE TITLE
[BUG] Private chats having hex codes and fonts inside the text

### ISSUE THREAD

**Issue by LVIENG** [bloxstraplabs/bloxstrap#3230]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Whenever someone private chats, it displays this weird <fontcolor=#HEXCODE> [username] </font> thing, ever since I got the new bloxstrap.
![bloxstrap error](https://github.com/user-attachments/assets/cfad7c07-40c4-48c5-ad40-c4800847d1dc)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by LVIENG** [comment]
> This seems more like the game's problem. Are you sure this doesn't happen with the regular Roblox bootstrapper?

happens in every single game ive tested.

**Comment by bluepilledgreat** [comment]
> > This seems more like the game's problem. Are you sure this doesn't happen with the regular Roblox bootstrapper?
> 
> happens in every single game ive tested.

Send your fast flags here

**Comment by LVIENG** [comment]
> > > This seems more like the game's problem. Are you sure this doesn't happen with the regular Roblox bootstrapper?
> > happens in every single game ive tested.
> Send your fast flags here
no fast flags except the presets

**Comment by bluepilledgreat** [comment]
> no fast flags except the presets

Are you sure this does not happen with the regular Roblox bootstrapper?

**Comment by LVIENG** [comment]
> > no fast flags except the presets
> 
> Are you sure this does not happen with the regular Roblox bootstrapper?

yeah, my friends seem to have no issue

**Comment by LVIENG** [comment]
huh, it seems to have fixed after i restarted my pc

**Comment by LVIENG** [comment]
apparently not, ill send the configs here: 
[ClientAppSettings.json](https://github.com/user-attachments/files/17442768/ClientAppSettings.json)
[Settings.json](https://github.com/user-attachments/files/17442770/Settings.json)
[State.json](https://github.com/user-attachments/files/17442771/State.json)

**Comment by LVIENG** [comment]
i think this is an issue on roblox's part, i have uninstalled bloxstrap and it still persists.
