### ISSUE TITLE
bloxstrap its bugging or an error

### ISSUE THREAD

**Issue by xbunnyx2** [bloxstraplabs/bloxstrap#3231]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot 2024-10-17 070340](https://github.com/user-attachments/assets/0aa80ffa-cd1f-40ff-8342-beb02b6bc6b3)

### Bloxstrap Log

![Screenshot 2024-10-17 070340](https://github.com/user-attachments/assets/00f69286-8ecc-491b-a550-a8b8e27f2b83)

**Comment by BunnyProPlayz** [comment]
Update bloxstrap
