### ISSUE TITLE
[REQ] Where do I find Game History?

### ISSUE THREAD

**Issue by terminalhead** [bloxstraplabs/bloxstrap#3232]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Self expanatory. It seems helpful, I just cant find it.

**Comment by pizzaboxer** [comment]
Right-click on Bloxstrap's notification area icon while Roblox is running.

**Comment by d-Dice** [comment]
<img width="248" height="229" alt="Image" src="https://github.com/user-attachments/assets/6b2e7f73-149e-42e0-a70b-804a802d2877" />
where is it?
