### ISSUE TITLE
[BUG] me no run bloxstrap

### ISSUE THREAD

**Issue by kola56342** [bloxstraplabs/bloxstrap#3235]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

pls fix

### Bloxstrap Log

plssssssssssss fix

**Comment by BunnyProPlayz** [comment]
can you.. tell us your issue??
