### ISSUE TITLE
[BUG] can't run bloxstrap

### ISSUE THREAD

**Issue by ldkrhsdhf** [bloxstraplabs/bloxstrap#3240]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

can't run bloxstrap

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Can you provide more information please?

**Comment by GodTierUser** [comment]
it keeps saying configuring roblox but doesn't continue, btw it's on 2.7.0
I updated and it works now!!
