### ISSUE TITLE
[BUG] laggy bloxstrap

### ISSUE THREAD

**Issue by idkwhyim** [bloxstraplabs/bloxstrap#3241]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxstrap update makes my Roblox slow 

Uploading 2024-10-17 15-59-24.mp4…

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Upload the video again please

Have you tested this with the original launcher?

**Comment by idkwhyim** [comment]
> Upload the video again please
> https://gofile.io/d/nyKtl1 here 
> Have you tested this with the original launcher?
>ah the roblox is laggy idk why
