### ISSUE TITLE
[BUG] I cant onpen robloxc

### ISSUE THREAD

**Issue by Jeroldalt** [bloxstraplabs/bloxstrap#3243]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i dont know why i cant open roblox

### Bloxstrap Log

N/A
[Bloxstrap_20241017T090215Z.log](https://github.com/user-attachments/files/17410205/Bloxstrap_20241017T090215Z.log)

**Comment by pizzaboxer** [comment]
"I have thoroughly looked through the available Wiki articles" yeah sure you have buddy
