### ISSUE TITLE
[BUG]  2,80v version.

### ISSUE THREAD

**Issue by reaperbw** [bloxstraplabs/bloxstrap#3244]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Well, when i installed it, i cant find it, i searched for "play roblox", nothing popped up, also on other ones its like this too, i cannot play roblox for now.

**Comment by reaperbw** [comment]
yes, i am using the latest one.

**Comment by user1126s** [comment]
> yes, i am using the latest one.

Try Searching For Bloxstrap. Then click it. then you get the two options. if you want the play roblox back you can go to shortcuts in settings and clicking the launch roblox shortcut. Hope i helped!

**Comment by pizzaboxer** [comment]
![image](https://github.com/user-attachments/assets/a690904e-6ba8-4406-a716-b7631c4b2947)

**Comment by reaperbw** [comment]
thanks now i can sweat my balls off in roblox bedwars again

**Comment by reaperbw** [comment]
god bless
