### ISSUE TITLE
[REQ] re-add that one feature where you double-click the bloxstrap icon and it comes up the settings

### ISSUE THREAD

**Issue by randomgithubaccount19837** [bloxstraplabs/bloxstrap#3246]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

the title says for itself

there used to be a feature where you could double-click the bloxstrap icon and it came up the settings

**Comment by pizzaboxer** [comment]
Open Settings and go to the Shortcuts tab
