### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mpro0625** [bloxstraplabs/bloxstrap#3247]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

проблема со скачиванием 

### Bloxstrap Log

N/A

https://github.com/user-attachments/assets/8bbbf127-4c05-4465-92e0-e56d3274cef1

**Comment by hdaZew523** [comment]
same problem means there is a error with bloxstrap update

**Comment by hdaZew523** [comment]
[Bloxstrap_20241017T112957Z.log](https://github.com/user-attachments/files/17411559/Bloxstrap_20241017T112957Z.log)
that is the log that i god

**Comment by mpro0625** [comment]
не понимаю что делать с этой проблемой честно )

**Comment by mpro0625** [comment]
новая версия 2.7 вообще бесконечная загрузка

**Comment by mpro0625** [comment]
настраиваем и уже как час грузит

**Comment by hdaZew523** [comment]
хз

**Comment by hdaZew523** [comment]
у меня всё ещё не обновилось

**Comment by mpro0625** [comment]
++

**Comment by Naveandice** [comment]
Обновитесь до 2.8.0. Предыдущие версии работать не будут.

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by hdaZew523** [comment]
bro i cant update

**Comment by NabHeyka22** [comment]
Cause you're a Wave user.

**Comment by hdaZew523** [comment]
nah
