### ISSUE TITLE
[BUG] it says an "exception occurred"

### ISSUE THREAD

**Issue by krasimir-rgb** [bloxstraplabs/bloxstrap#3249]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

an exception occurred

### Bloxstrap Log

[Bloxstrap_20241017T121803Z.log](https://github.com/user-attachments/files/17412382/Bloxstrap_20241017T121803Z.log)

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
