### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by abdoramy382** [bloxstraplabs/bloxstrap#3250]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i can't open roblox from bloxstrap
![image](https://github.com/user-attachments/assets/04b41a37-092f-4a18-a466-f8e5686c0b10)

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
