### ISSUE TITLE
[BUG] The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by tema32rus2000** [bloxstraplabs/bloxstrap#3251]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Just joined game and an error occured.
Also roblox was updating
![image](https://github.com/user-attachments/assets/46c0fcb4-d9f8-45d7-a48e-62ccc1214c5a)

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]

System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
[Bloxstrap_20241017T124107Z.log](https://github.com/user-attachments/files/17412583/Bloxstrap_20241017T124107Z.log)

**Comment by Goofyhooda** [comment]
I can get it to work it say the same thing
