### ISSUE TITLE
[BUG] The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by LifeCheats** [bloxstraplabs/bloxstrap#3252]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/b9a25b9f-44fa-4850-bc38-0dfd6998a52f)

### Bloxstrap Log

N/A

**Comment by Storm-930** [comment]
This has a very simple fix
Update without question

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
