### ISSUE TITLE
[BUG] we need to apply a patch to Bloxstrap to keep you on the current Roblox version.

### ISSUE THREAD

**Issue by Topgrin404** [bloxstraplabs/bloxstrap#3253]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

we need to apply a patch to Bloxstrap to keep you on the current Roblox version.
What do I need to do to avoid this error?
I'm trying to use Wave executor but I'm getting this error

### Bloxstrap Log

N/A

**Comment by playervalley** [comment]
>I'm trying to use Wave executor but I'm getting this error

There's your problem. Uninstall it to fix it.

**Comment by bluepilledgreat** [comment]
bruh
