### ISSUE TITLE
[BUG] an exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by Zsaesi** [bloxstraplabs/bloxstrap#3256]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

it says System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.) [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary. and i cant launch roblox

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.) [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by bluepilledgreat** [comment]
if you bothered to read the bug report template, it clearly states to not report these issues. update to 2.8.0.
