### ISSUE TITLE
[BUG] an exception occured while running bloxstrap

### ISSUE THREAD

**Issue by thefemboylover** [bloxstraplabs/bloxstrap#3257]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Zrzut ekranu 2024-10-17 154210](https://github.com/user-attachments/assets/a274dea8-8c5c-4a91-9edd-f100833ed972)

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by thefemboylover** [comment]
> Update to 2.8.0.

how
