### ISSUE TITLE
[REQ] Can you please add a "Perferred TopBar version" for Bloxtrap?

### ISSUE THREAD

**Issue by TeleTimofeya** [bloxstraplabs/bloxstrap#3261]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

"Perferred TopBar version" in Engine Settings Bloxtrap

Styles:
2015 v1
![1729176999803](https://github.com/user-attachments/assets/3e742c77-e28f-4318-afaf-6fed9c16da33)
2020 v2
![1729177023552](https://github.com/user-attachments/assets/3b11304a-ddc1-4484-b829-171ebbed2369)
2023 v4
![Screenshot_20241017_175608_Roblox](https://github.com/user-attachments/assets/fa9eab30-7992-43d5-b931-3dc1bde8cd69)

**Comment by NabHeyka22** [comment]
The fuck is a perclle.

**Comment by pizzaboxer** [comment]
add a what

**Comment by TeleTimofeya** [comment]
> add a what

"Perferred TopBar version" in Engine Settings Bloxtrap

**Comment by NabHeyka22** [comment]
Just use the preferred escape menu.
And no, this isn't possible to even make.
