### ISSUE TITLE
[BUG] ''Bloxstrap is unable to download roblox'' 

### ISSUE THREAD

**Issue by Connora11y** [bloxstraplabs/bloxstrap#3262]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/b9ef7cbb-48d2-46e1-ba11-d2ff9ee4bfa6) Is there any solution to fix this bug? I randomly logged on and saw this.

### Bloxstrap Log

Expected hash: 8643830e6ff0e796bdb432b68a2ac726
Got hash: acf1affe252d462f3c33192d82e66911

**Comment by NabHeyka22** [comment]
Have you clicked the link.
If so, have you read it **entirely** including the last bit

**Comment by Connora11y** [comment]
What link?

**Comment by Connora11y** [comment]
I'll try it.
