### ISSUE TITLE
[REQ] Make it to where the test mode warning cannot pop up by turning on a setting within the bloxstrap settings

### ISSUE THREAD

**Issue by kalenhop9** [bloxstraplabs/bloxstrap#3267]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Basically, this wouldn't let the test mode popup appear on the screen and would enable immediately with a setting like disable test mode warning popup.

**Comment by pizzaboxer** [comment]
Is this really necessary?

**Comment by kalenhop9** [comment]
In my really honest opinion, it would be nice not to have a popup every single time to test if your settings worked. Some people might need the popup to read what it says however a setting to disable something you don't wanna see every single time would be nice.

**Comment by pizzaboxer** [comment]
How often are you having to enable it?

**Comment by kalenhop9** [comment]
Usually when I install a new mod or a new fflag this would mostly likely sometimes be either a day or maybe even during the day when i see a cool mod to use. I don't commonly add fflags unless needed however but with mods i sometimes add one during the day or during the day. Having to not get the pop up after installing or updating the mod (and installing the mod after updating) would again be very nice. So sometimes I will use test mode but not always.

**Comment by pizzaboxer** [comment]
I still don't see how this is necessary, as the time it takes to dismiss the prompt is incredibly nominal. The popup serves double-duty as a confirmation dialog to prevent people from accidentally enabling it, not just to inform you as to what it does.
