### ISSUE TITLE
Bloxstrap an exception occured

### ISSUE THREAD

**Issue by WasCarter** [bloxstraplabs/bloxstrap#3268]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/fa176b99-0f27-46fa-be4d-79b74703a2b4)

### Bloxstrap Log

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by NabHeyka22** [comment]
Update.
