### ISSUE TITLE
[BUG] Bloxshade

### ISSUE THREAD

**Issue by GGSILENT** [bloxstraplabs/bloxstrap#3271]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

what should I do if bloxshade does not work when starting the blockstrap, I cannot find the folder with blockstrap when updating it?

### Bloxstrap Log

N/A

**Comment by GGSILENT** [comment]
I was wrong, I can find the folder, but the blockshade can't

**Comment by NabHeyka22** [comment]
Update.

**Comment by pizzaboxer** [comment]
Wait for them to fix it (if they do)
