### ISSUE TITLE
[BUG] Alt + enter aka true full screen not working anymore in 2.8.0

### ISSUE THREAD

**Issue by strait7291** [bloxstraplabs/bloxstrap#3272]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

if i pressed alt + enter in previous versions it would blackout for few seconds and then go true fullscreen but now its not working anymore in 2.8.0 and its giving me normal full screen :(

https://github.com/user-attachments/assets/a41ec5c1-66f1-4417-a952-3025dde7e8da

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Just because it's not blacking out doesn't mean it's not in true fullscreen. Are you seeing the Bloxstrap launch dialog show before Roblox opens?

**Comment by redspider407** [comment]
I also experienced this issue, idk how to fix, I tried the compatibility thing and it still doesn't work.

**Comment by strait7291** [comment]
I don't know what you mean by "Bloxstrap launch dialog show"

**Comment by strait7291** [comment]
> Just because it's not blacking out doesn't mean it's not in true fullscreen. Are you seeing the Bloxstrap launch dialog show before Roblox opens?

Idk what you mean by "Bloxstrap launch dialog show" but for a fact I know that its not in true full screen because in roblox settings Fullscreen should be off not on and if its on that means you're not in true full screen but if it is off that means you are in true full screen

**Comment by pizzaboxer** [comment]
> Idk what you mean by "Bloxstrap launch dialog show"

Do you see this?

![image](https://github.com/user-attachments/assets/557cfe3e-69c6-4d29-b44e-cc3797d12768)

Also, @smellier @strait7291, upload your configuration please:

https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by strait7291** [comment]
yes

**Comment by strait7291** [comment]
[ClientAppSettings.json](https://github.com/user-attachments/files/17438700/ClientAppSettings.json)
[Settings.json](https://github.com/user-attachments/files/17438701/Settings.json)
[State.json](https://github.com/user-attachments/files/17438702/State.json)

**Comment by glimm321** [comment]
is there a fix yet

**Comment by strait7291** [comment]
i think i found it and it works for me

**Comment by strait7291** [comment]
just use the flag FFlagHandleAltEnterFullscreenManually and set it to false

**Comment by pizzaboxer** [comment]
Yes, I was about to tell you to do that. I'll make a Wiki page for this.

**Comment by glimm321** [comment]
> FFlagHandleAltEnterFullscreenManually

appreciate it it works

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
