### ISSUE TITLE
[BUG] Requested operation requires elevation

### ISSUE THREAD

**Issue by smellier** [bloxstraplabs/bloxstrap#3274]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

After updating to 2.8, disabling windows fullscreen optimisations & selecting the "run as adminstrator" box in the compatibility settings I have been getting the following exception. This is after multiple clean installs of Bloxstrap, the standalone Roblox launcher works fine.

### Bloxstrap Log

System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\c\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'C:\Users\c\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.

**Comment by pizzaboxer** [comment]
> & selecting the "run as adminstrator" box in the compatibility settings

why did you do that

**Comment by NabHeyka22** [comment]
What does running administrator do so bad by the way?

**Comment by Storm-930** [comment]
Isn't there a warning when it is ran as administrator for it to _not_ be ran as administrator?
I thought it had one...

**Comment by pizzaboxer** [comment]
We don't have one, no. I didn't think about this being a problem.

**Comment by smellier** [comment]
> We don't have one, no. I didn't think about this being a problem.

I have gotten better performance in other games by doing the same thing, so I didn't expect it to be an issue. Now bloxstrap refuses to work completely. I have double checked the compatibility tab in all roblox & bloxstrap related executables and none of the options are enabled,

**Comment by pizzaboxer** [comment]
> I have double checked the compatibility tab in all roblox & bloxstrap related executables and none of the options are enabled,

Are you sure? Let me see a screenshot of Roblox's compatibility settings please.

**Comment by pizzaboxer** [comment]
That should be fine, you're still getting the error with that?

**Comment by smellier** [comment]
> That should be fine, you're still getting the error with that?

Yes, not sure if it's relevant but Bloxstrap thinks Roblox isn't installed.
![{345F0E54-1E6C-4620-9927-7F30C82200E4}](https://github.com/user-attachments/assets/178ce536-3864-44f9-ab24-0e6c78a5f8fc)
This is what I am prompted with when I try to go into the compatibility menu via Bloxstrap. 
The only solution I can think of at this point would be factory resetting my PC, as I've installed and uninstalled Bloxstrap & Roblox on multiple occasions and found no solution

**Comment by pizzaboxer** [comment]
Oh, you were editing the compatibility settings of the RobloxPlayerBeta executable in the %localappdata%\Roblox folder.

Since you reinstalled, yes, it's going to do that. Did you launch Roblox at least once?

**Comment by smellier** [comment]
> Oh, you were editing the compatibility settings of the RobloxPlayerBeta executable in the %localappdata%\Roblox folder.
> 
> Since you reinstalled, yes, it's going to do that. Did you try launching Roblox at least once?

Yes I launched Roblox standalone, then launched a fresh Bloxstrap client and the error still persists.

**Comment by pizzaboxer** [comment]
Oh right, I see.

Open the registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`, delete the entry for RobloxPlayerBeta.exe in Bloxstrap's installation folder.

**Comment by smellier** [comment]
> Oh right, I see.
> 
> Open the registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`, delete the entry for RobloxPlayerBeta.exe in Bloxstrap's installation folder.

Thank you, this worked. Just to note, the exclusive fullscreen seems to differ from 2.7. It doesn't work the same when tabbing out / windows notifications are displayed on top of my game. For example, the server location feature never used to show on the previous update when I was using fullscreen, however now it does.

**Comment by Caio06** [comment]
Eu  tbm estou com o mesmo problema e ainda nao consegui resolver, alguem poderia dar uma ajuda?

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
