### ISSUE TITLE
[BUG] My bloxstrap commited suicide

### ISSUE THREAD

**Issue by stevefromminecraft123456** [bloxstraplabs/bloxstrap#3275]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so it just disappeared 

### Bloxstrap Log

no logs, ITS JUST **GONE**

**Comment by Wanwood1** [comment]
Reinstall then

**Comment by pizzaboxer** [comment]
It didn't do that by itself, you must've knowingly uninstalled it or deleted its installation folder. Reinstall it.
