### ISSUE TITLE
Error for bloxstrap ( i tested it without bloxstrap and works )

### ISSUE THREAD

**Issue by rosebull12** [bloxstraplabs/bloxstrap#3278]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/2b41b431-654a-4e90-9117-f1cdc3b2ba84)

Please help me I have been having this issue redownloading bloxstrap over and over again ( made all my settings back to normal ) and nothing has helped. 

### Bloxstrap Log

N/A

**Comment by rosebull12** [comment]
I think I know what I did wrong I'll check back when I'm on my pc

**Comment by rosebull12** [comment]
I put this random setting in compatibility I think its the issue

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22The-requested-operation-requires-elevation%22-error-when-launching-Roblox
