### ISSUE TITLE
[REQ] roblox textures folder

### ISSUE THREAD

**Issue by i0nut2o** [bloxstraplabs/bloxstrap#3279]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

so, in version 2.7.0 there was the "Version" folder visible in which you could go to textures and change the textures to anything u want. we players from the game called "Trident Survival" used those textures to put custom faces for a advantage but now in version 2.8.0 the "versions" folder is nowhere to be seen. the same can be said for the "textures" folder that was containing the Roblox textures. basically all i am asking is for a way to get into that texture folder back so we could use our custom faces again.

**Comment by i0nut2o** [comment]
@pizzaboxer and where is the "texture" folder containing the roblox textures in mods folder? theres a "texture" folder in "content" which only contains "cursors" and nothing else.

**Comment by pizzaboxer** [comment]
![image](https://github.com/user-attachments/assets/29c5567f-4694-4acb-b1e1-388b19a88bde)

Can you please learn to read the information and resources given to you?
