### ISSUE TITLE
[BUG] Fast Flags not working/disabled maybe

### ISSUE THREAD

**Issue by zoinkedasf** [bloxstraplabs/bloxstrap#3281]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Ever since Bloxstrap updated, my fast flag have been disabled of some sort where I have everything pasted in by JSON in the fast flag editor but they don't actually apply in game I can't see a toggle for fast flags in the settings anywhere so how do I resolve this.

### Bloxstrap Log

N/A

**Comment by zoinkedasf** [comment]
Here's what i use:
{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFIntTaskSchedulerTargetFps": "5588562",
  "FStringPartTexturePackTablePre2022": "{\u0022foil\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873266399\u0022,\u0022rbxassetid://9438410239\u0022],\u0022color\u0022:[238,238,238,255]},\u0022asphalt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9930003180\u0022,\u0022rbxassetid://9438410548\u0022],\u0022color\u0022:[227,227,228,234]},\u0022basalt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920482224\u0022,\u0022rbxassetid://9438413638\u0022],\u0022color\u0022:[160,160,158,238]},\u0022brick\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920482992\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[229,214,205,227]},\u0022cobblestone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9919719550\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,219,219,243]},\u0022concrete\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920484334\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[225,225,224,255]},\u0022crackedlava\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920485426\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[76,79,81,156]},\u0022diamondplate\u0022:{\u0022ids\u0022:[\u0022rbxassetid://10237721036\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[210,210,210,255]},\u0022fabric\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920517963\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[221,221,221,255]},\u0022glacier\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920518995\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[225,229,229,243]},\u0022glass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873284556\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[254,254,254,7]},\u0022granite\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920550720\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[210,206,200,255]},\u0022grass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920552044\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[196,196,189,241]},\u0022ground\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920554695\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[165,165,160,240]},\u0022ice\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920556429\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[235,239,241,248]},\u0022leafygrass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920558145\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[182,178,175,234]},\u0022limestone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920561624\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[250,248,243,250]},\u0022marble\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873292869\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[181,183,193,249]},\u0022metal\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920574966\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[226,226,226,255]},\u0022mud\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920578676\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[193,192,193,252]},\u0022pavement\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920580094\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,218,219,236]},\u0022pebble\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920581197\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[204,203,201,234]},\u0022plastic\u0022:{\u0022ids\u0022:[\u0022\u0022,\u0022rbxassetid://9475422736\u0022],\u0022color\u0022:[255,255,255,255]},\u0022rock\u0022:{\u0022ids\u0022:[\u0022rbxassetid://10129366149\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[211,211,210,248]},\u0022corrodedmetal\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920589512\u0022,\u0022rbxassetid://9439557520\u0022],\u0022color\u0022:[206,177,163,180]},\u0022salt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920590478\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[249,249,249,255]},\u0022sand\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920591862\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,216,210,240]},\u0022sandstone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920596353\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[241,234,230,246]},\u0022slate\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920600052\u0022,\u0022rbxassetid://9439613006\u0022],\u0022color\u0022:[235,234,235,254]},\u0022snow\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920620451\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[239,240,240,255]},\u0022wood\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920625499\u0022,\u0022rbxassetid://9439649548\u0022],\u0022color\u0022:[217,209,208,255]},\u0022woodplanks\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920626896\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[207,208,206,254]}}",
  "FFlagDebugSkyGray": "True",
  "FFlagDebugDisplayFPS": "True",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFFlagDebugPauseVoxelizer": "True",
  "FFlagNewLightAttenuation": "True",
  "FIntRenderShadowIntensity": "0",
  "FFlagDisablePostFx": "True",
  "FIntRenderShadowmapBias": "0",
  "FFlagLuaAppSystemBar": "False",
  "FIntFontSizePadding": "3",
  "FFlagAdServiceEnabled": "False",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagMSRefactor5": "False",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FFlagDebugDisableTelemetryV2Stat": "True"
}

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Or, well, see this: https://github.com/bloxstraplabs/bloxstrap/wiki/Manual-configuration-of-Fast-Flag-management
