### ISSUE TITLE
[BUG] error 443

### ISSUE THREAD

**Issue by Blux5712** [bloxstraplabs/bloxstrap#3284]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when ever i try to load up my bloxstrap it works and i get into roblox but not with the textures and other things whenever i load roblox it says error 443. And i have to hit close then it takes me to roblox but in the error 443 it says i need install or update roblox in order to countine to play with bloxstrap. Ive already tried both of these u have any other ideas?
![Screenshot 2024-10-17 151615](https://github.com/user-attachments/assets/7c811091-22ea-4624-aa7a-beda2ce35ded)

there is what it says.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Are you using a VPN, and can you check that any antivirus you have isn't interfering with Bloxstrap?

**Comment by Blux5712** [comment]
i am using an anti virus i think if i change it, it will work thank you

**Comment by Blux5712** [comment]
why did u close

**Comment by pizzaboxer** [comment]
Try adding Bloxstrap's installation folder as an exception
