### ISSUE TITLE
[BUG] roblox settings dont work with bloxstrap

### ISSUE THREAD

**Issue by olizero2** [bloxstraplabs/bloxstrap#3285]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

[
![Zrzut ekranu 2024-10-17 223519](https://github.com/user-attachments/assets/71e089bc-7150-4536-8d5c-89efa3afe64e)
](url)

yes i can see the settings, but im unable to click them 

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Stick to the V4 menu for now, we're figuring this one out.

**Comment by VeryCoolGuy-TSC** [comment]
https://github.com/bloxstraplabs/bloxstrap/issues/2911#issuecomment-2363473923 try this.

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
