### ISSUE TITLE
[BUG] bloxshade refuses to work after update (idk whats going on)

### ISSUE THREAD

**Issue by exefrr** [bloxstraplabs/bloxstrap#3287]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxshades (the shader program i use) doesnt work after recent bloxstrap update. it says "bloxstrap is true. failed to open file"

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
bruh we are not bloxshade
