### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sirbaconyt** [bloxstraplabs/bloxstrap#3288]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

there is no option to disable all fast flags anymore like there was before, screenshot attached
![image](https://github.com/user-attachments/assets/9506db48-8fc9-411f-99d3-c2302142c4b2)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
![image](https://github.com/user-attachments/assets/ffd03085-822d-4f96-b9b1-e2e6ff94b763)
Pretty sure this disables all fast flags

**Comment by sirbaconyt** [comment]
> ![image](https://github.com/user-attachments/assets/ffd03085-822d-4f96-b9b1-e2e6ff94b763)
> 
> Pretty sure this disables all fast flags

i thought that just deleted all fast flags, im trying to temporarily disable them

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Manual-configuration-of-Fast-Flag-management
