### ISSUE TITLE
[BUG] Infinite Config

### ISSUE THREAD

**Issue by sjdhfiuyhknamsldwadkij** [bloxstraplabs/bloxstrap#3289]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When i attempt to Reinstall Bloxstrap it gets an Infinite Configuration Screen which happened at the latest Update of rblx

### Bloxstrap Log

N/A

**Comment by redspider407** [comment]
download 2.8.0

**Comment by bluepilledgreat** [comment]
^
