### ISSUE TITLE
[REQ] FFLAG Management

### ISSUE THREAD

**Issue by Chaos-Smiler56lol** [bloxstraplabs/bloxstrap#3290]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Please Add A FFlag on/off switch In Engine Settings.

This Will Allow The User To Turn On All Of They'ree FastFlagt With **A Click Of A Button**

Some User's Likke Me **Need** This Feature.
Thanks

(Sorry For Bad English)

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Manual-configuration-of-Fast-Flag-management
