### ISSUE TITLE
[BUG] Exclusive fullscreen not working

### ISSUE THREAD

**Issue by whyads33** [bloxstraplabs/bloxstrap#3291]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I enter roblox and press alt + enter nothing happens, and for some of my mods to work it has to be in full screen

### Bloxstrap Log

N/A

**Comment by whyads33** [comment]
Also this bug has only started happening today, I have had no issues previously.

**Comment by SilentStormLE** [comment]
me aswell, since i lag frequently for some reason when im not in exclusive, this is imperative for me, please tell me theres a fix for this and its not roblox disabling the fflag or smth

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by whyads33** [comment]
[Settings.json](https://github.com/user-attachments/files/17436266/Settings.json)
[State.json](https://github.com/user-attachments/files/17436280/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/17436281/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
Seems to be all good, can you confirm that you're seeing the Bloxstrap launch dialog show when you launch Roblox?

**Comment by whyads33** [comment]
yes, i can see the bloxstrap launch dialogue

**Comment by pizzaboxer** [comment]
Can you get Roblox's latest log file from `%localappdata%\Roblox\logs`, and send it to me privately via email (at pizzaboxer@proton.me)? Let me know here once you have

**Comment by whyads33** [comment]
how do i find this information?

**Comment by whyads33** [comment]
sent

**Comment by strait7291** [comment]
found a solution

**Comment by strait7291** [comment]
first you need disable fullscreen optimizations on roblox and you make bloxstrap run as administrator second you add this FFlagHandleAltEnterFullscreenManually and set it to false boom fixed

**Comment by pizzaboxer** [comment]
You alraedy had that flag in your configuration though, but at least it's all good.
