### ISSUE TITLE
[BUG] DO BLOXTRAP

### ISSUE THREAD

**Issue by dandark2** [bloxstraplabs/bloxstrap#3295]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

EU NAO TO CONSEGUINDO ABAIXAR

### Bloxstrap Log

N/A

**Comment by dandark2** [comment]
MUITA VDD DANDARK 2

**Comment by toofastforboo** [comment]
apareceu alguma mensagem de erro? você poderia anexar as logs aqui?

**Comment by VeryCoolGuy-TSC** [comment]
what..?

**Comment by MrT-tak** [comment]
huh?

**Comment by pizzaboxer** [comment]
Closing as fruitless

**Comment by MrT-tak** [comment]
> Closing as fruitless

Fruitless?
