### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dandark2** [bloxstraplabs/bloxstrap#3296]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

TA DIZENDO QUE TEM DOIS ARQUIVO 

### Bloxstrap Log

N/A

**Comment by nunk7** [comment]
Abre executar (ou segura tecla windows e pressiona r), coloca "%localappdata%/Bloxstrap/Logs" dentro, pressiona tecla enter e manda o arquivo mais recente de dentro da pasta
