### ISSUE TITLE
[BUG] My issue is a fastflag that is affecting my game by make every mesh that is like a tree or shrubbery it becomes squished or small and i am trying to find the certain fastflags

### ISSUE THREAD

**Issue by Sonder210** [bloxstraplabs/bloxstrap#3297]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

So the trees and the shrubbery is all broken and i need to find the root of the issue i dont know if its a fast flag or a bug 

### Bloxstrap Log

![image](https://github.com/user-attachments/assets/df8029f7-e43b-443a-a69b-5e1edd8378e3)

**Comment by Sonder210** [comment]
The picture right there is supposed to be a palm tree in the game southwest Florida

**Comment by cowboy-1337** [comment]
Can you attach your flag list?

**Comment by pizzaboxer** [comment]
This is an issue with your flag configuration. We clearly and specifically tell you to not blindly paste in flags if you're not fully aware of what they do.

**Comment by Sonder210** [comment]
Yeah its understandabe it doesnt make the game unplayable i have a lot of flast flags because  i cant run some roblox games with this pc

**Comment by RetroSmash321** [comment]
> The picture right there is supposed to be a palm tree in the game southwest Florida

Yo dude, took me 8 hours but i found the issue:
It's "DFIntCSGLevelOfDetailSwitchingDistance" you prolly have it on 0...

The number is the STUDS distance you need to be within for the mesh to load properly, i set mine to 200 so it still unloads and looks all shruggery when i'm afar, u can see it higher if u want.
