### ISSUE TITLE
[BUG] System.AggregateException

### ISSUE THREAD

**Issue by CatYIU** [bloxstraplabs/bloxstrap#3298]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

N/A
[Bloxstrap_20241018T032428Z.log](https://github.com/user-attachments/files/17427569/Bloxstrap_20241018T032428Z.log)

**Comment by cowboy-1337** [comment]
"I did not answer truthfully to all the above checkboxes." We could already tell

One single look at the Discord:
![image](https://github.com/user-attachments/assets/7096c0aa-971e-42e9-877c-220652bd5808)

A measly glance at the Wiki:
![image](https://github.com/user-attachments/assets/d7655117-4def-4fc9-b94e-bdc72759c576)
![image](https://github.com/user-attachments/assets/f4fda949-11bf-412a-8184-32cb971d7e3c)

**Comment by cowboy-1337** [comment]
Log shows you're on Bloxstrap 2.5.2, which is why this is happening for you.

Update to 2.8.0 to fix - https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.0
