### ISSUE TITLE
Using any other rendering api that isnt a directx one results in horrible screen tear and slightly choppy gameplay

### ISSUE THREAD

**Issue by Bluetonik123** [bloxstraplabs/bloxstrap#3300]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

ive been using vulkan for a while now with genuinely no problems at all until recently where it just started causing screen tear for some reason?? 
heres a timeline of events to help solve this if you can, at first i was using vulkan just fine but my fps didnt want to be uncapped, which was probably exclusive fullscreen actually working, until one day i join a game and suddenly my fps is uncapped and the screen tear starts, i tried to cap my fps again but that didnt work, i reinstalled bloxstrap and roblox a bunch of times and that didnt work, i forced v sync and forced a 60 fps cap using nvidia control pannel, that didnt work too, i ran regular roblox and that was fine until i changed rendering api to vulkan and the screen tear started again
that only really leaves two theories, either exclusive fullscreen isnt working or changing the rendering api is messing something up, keep in mind this is exclusively a roblox problem and im using a decent 60hz laptop
if you can suggest anything that would be apreciated, thank you

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
disable vulkan then. what are we meant to do about it?

**Comment by Bluetonik123** [comment]
> disable vulkan then. what are we meant to do about it?
im clearly looking for a way to actually fix it instead of disable it
