### ISSUE TITLE
[BUG] Unable to use with BloxShade shaders with new update.

### ISSUE THREAD

**Issue by qweeneyy** [bloxstraplabs/bloxstrap#3301]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

In the previous version of BloxStrap, I was able to use my BloxShade shaders with my BloxStrap fonts, but as of recently, with the new BloxShade launcher, everytime I open through the BloxShade application, my shaders are unable to work.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
This is for Bloxshade to fix, not us.
