### ISSUE TITLE
[REQ] language korean

### ISSUE THREAD

**Issue by PENPLEKR** [bloxstraplabs/bloxstrap#3302]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would like to recreate the language that Korean disappeared in 2.8.0.

**Comment by bluepilledgreat** [comment]
> I would like to recreate the language that Korean disappeared in 2.8.0.

The Korean language has been removed from 2.8.0 due to a lack of Korean translators. We will re-implement it once all strings are translated again.
If you'd like to contribute, please read https://github.com/bloxstraplabs/bloxstrap/wiki/Contributing-translations
