### ISSUE TITLE
[BUG] Black Screen

### ISSUE THREAD

**Issue by fright628** [bloxstraplabs/bloxstrap#3304]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i go into a game on roblox my screen turns black when i open other apps it stays black and i have to close roblox and it dosent happen with regular downloaded roblox

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Can you send your fast flags?

**Comment by fright628** [comment]
I wasnt using any fflags

**Comment by fright628** [comment]
Im not home right now

**Comment by bluepilledgreat** [comment]
Closed due to inactivity.
