### ISSUE TITLE
[BUG] net 6,0

### ISSUE THREAD

**Issue by Rmcobaka** [bloxstraplabs/bloxstrap#3305]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Well, I was running Bloxstraps, and then it showed version 6.0. I thought it was a glitch, so I tried restarting Bloxstraps, but it still showed the 6.0 install. When I clicked 'Yes,' no website appeared on the screen. I also tried going to the web and installing it again, but it still didn't fix the issue.
![Screenshot 2024-10-18 182114](https://github.com/user-attachments/assets/4fcb66e8-7d67-47c6-a3ec-d9762df141cb)

### Bloxstrap Log

N/A

**Comment by Rmcobaka** [comment]
and also i cant uninstall it too

**Comment by Rmcobaka** [comment]
oh nvm i juust install the new version and it work ;O

**Comment by 5xdf** [comment]
Please read the checkboxes before checking them please. The last one you checked invalidates pretty much this entire issue

**Comment by only1mistakE** [comment]
grrrr just install all the .NET versions
