### ISSUE TITLE
[REQ] Please add another thing about regions.

### ISSUE THREAD

**Issue by gruhfr** [bloxstraplabs/bloxstrap#3307]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

**I have a request for two features about the regions when joining.**

The first feature, is to have the _option to automatically let the user leave the game and go back to Home_ (I'm not sure if that's what it's called, sorry.) _or instantly close the app itself for the people who use the Roblox website when they join a server with a specific region_.
For example, I join a Tokyo, JP region when I set it to automatically make me leave, I will _either be sent back to Home or the app closes itself immediately._

The second feature, is to _let the user have an option to automatically serverhop into a server with a specific region for public servers_, for private servers that are empty, the app should let them _have an option to rejoin_, for private servers that are not empty however, would let the user _have an option to either get sent to Home (or close the app) or stay in the private server_.

I hope nothing is too confusing and thank you for reading.

**Comment by pizzaboxer** [comment]
We're not able to make you leave the game. We can't interact with the app like that.
