### ISSUE TITLE
[BUG] Что делать, помогите!

### ISSUE THREAD

**Issue by MegaAndreys** [bloxstraplabs/bloxstrap#3309]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Что делать если настройка Роблокса от блокстрапа вечная?

**Comment by Naveandice** [comment]
Обновитесь до версии 2.8.0.

**Comment by bluepilledgreat** [comment]
^

**Comment by MegaAndreys** [comment]
> Обновитесь до версии 2.8.0.

А если она и есть
