### ISSUE TITLE
[BUG] asdf

### ISSUE THREAD

**Issue by bluepilledgreat** [bloxstraplabs/bloxstrap#3310]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

asdf

### Bloxstrap Log

```text
asdf``
```

**Comment by pizzaboxer** [comment]
what is bro doing

**Comment by NabHeyka22** [comment]
This is a very difficult bug.

**Comment by user1126s** [comment]
No FOSS dev can fix this, ask the ms guys. the might be able to help
