### ISSUE TITLE
[BUG]  Bloxstrap randomly deleted and installer doesnt work.

### ISSUE THREAD

**Issue by stevefromminecraft123456** [bloxstraplabs/bloxstrap#3312]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I've tried reinstalling roblox, Nothing, Tried to use bloxstrap installer, Error? I already deleted the folder and it still doesnt work, It just recreates the folder and puts nothing in. Please help.

**Comment by pizzaboxer** [comment]
...What's the error?

**Comment by stevefromminecraft123456** [comment]
remove bloxstrap manually, I DID???

**Comment by pizzaboxer** [comment]
What? You're not making any sense. You said you got an error. What's the error?

**Comment by stevefromminecraft123456** [comment]
its fixed now, i guess it takes time
