### ISSUE TITLE
[BUG] missing roblox menu thing

### ISSUE THREAD

**Issue by myusername450** [bloxstraplabs/bloxstrap#3318]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so basically when you launch bloxstrap with v1 2015 menu, the entire menu disappears for some reason, and if you try using escape key it doesnt show the pause menu
![image](https://github.com/user-attachments/assets/48e6b1a5-b823-43a4-a7f8-d2b0abbcf948)
as you can see the menu is missing for some reason, and i believe its the chrome ui update which caused it

im not like the github god or something but i am also using a theme mod so i dont know if its causing that as well

### Bloxstrap Log

```text
N/A
```

**Comment by myusername450** [comment]
for some reason switching to 2023 (v4 not chrome) fixes this
![image](https://github.com/user-attachments/assets/27c98b6f-d813-40f5-a600-0a2a68236a8d)
![image](https://github.com/user-attachments/assets/de654799-4514-48b6-806b-385e0374a72f)

**Comment by NabHeyka22** [comment]
Then just use that.

**Comment by kotencja3** [comment]
Got the same issue

**Comment by NabHeyka22** [comment]
> Got the same issue

Use the 2023 (V4) menu now. I think Roblox removed it.

**Comment by myusername450** [comment]
if someone has a fastflag thing to fix it then it would be appreciated

**Comment by NabHeyka22** [comment]
> if someone has a fastflag thing to fix it then it would be appreciated

There probably isn't, as we can't make FFlags. Use the 2023 (V4) menu.

**Comment by DionBlox1** [comment]
> if someone has a fastflag thing to fix it then it would be appreciated

Sky (@0100152000022000) on discord has one and its:
`{
"FFlagSettingsHubIndependentBackgroundVisibility": "False"
}`

**Comment by VeryCoolGuy-TSC** [comment]
im not having this issue.

**Comment by pexotiic** [comment]
> im not having this issue.

same.

**Comment by MistressDoom** [comment]
> issue

thank you for the intel

**Comment by Blue-Star-Technology** [comment]
i'm having this issue, i was wondering if roblox broke the old ui or something because in 2.7.0 the 2015 v1 escape menu was broken i hope @pizzaboxer fixes this if he can

**Comment by Mohammed66551** [comment]
> i'm having this issue, i was wondering if roblox broke the old ui or something because in 2.7.0 the 2015 v1 escape menu was broken i hope @pizzaboxer fixes this if he can

They posted a fix on discord like @DionBlox1 Said add the fast flags
```
{
  "FFlagFixReportButtonCutOff": "False",
"FFlagSettingsHubIndependentBackgroundVisibility": "False"
}
```
and it will be fixed

**Comment by Blue-Star-Technology** [comment]
ty

**Comment by myusername450** [comment]
> > i'm having this issue, i was wondering if roblox broke the old ui or something because in 2.7.0 the 2015 v1 escape menu was broken i hope @pizzaboxer fixes this if he can
> 
> They posted a fix on discord like @DionBlox1 Said add the fast flags
> 
> ```
> {
>   "FFlagFixReportButtonCutOff": "False",
> "FFlagSettingsHubIndependentBackgroundVisibility": "False"
> }
> ```
> 
> and it will be fixed

ty srry for the late responce
