### ISSUE TITLE
2023(V4) Menu option 

### ISSUE THREAD

**Issue by saintstanding** [bloxstraplabs/bloxstrap#3320]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When ever I try to use the 2023(V4) Menu it NEVER saves and resets back to default. I can use literally every other menu including the 2023(V4 + New Gui), I just cannot use the 2023(V4) menu. Wouldn't care but I need my Roblox version specifically on 2023(V4) for this game I am playing I cannot use any newer or older version, When I test it goes back to default, if I go to any other tab it'll go to default, It doesn't  set it to 2023(V4) after I press save. please help!!

### Bloxstrap Log

```text
N/A
```

**Comment by coolgrandy** [comment]
it says unable to install bloxstrap menu and when i set font to bloxstrap it just resets the font after i close the bloxstrap

**Comment by NabHeyka22** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [ ]  I did not answer truthfully to all the above checkboxes.
> 
> ### What problem did you encounter?
> When ever I try to use the 2023(V4) Menu it NEVER saves and resets back to default. I can use literally every other menu including the 2023(V4 + New Gui), I just cannot use the 2023(V4) menu. Wouldn't care but I need my Roblox version specifically on 2023(V4) for this game I am playing I cannot use any newer or older version, When I test it goes back to default, if I go to any other tab it'll go to default, It doesn't set it to 2023(V4) after I press save. please help!!
> 
> ### Bloxstrap Log
> ```
> N/A
> ```

This is because Roblox rolled out Chrome UI for all users.
To disable this, please add this FFlag:
{
  "FFlagEnableInGameMenuChromeABTest3": "False"
}

**Comment by NabHeyka22** [comment]
Also what version are you using?

**Comment by saintstanding** [comment]
> Also what version are you using?

Newest 2.8.0 gonna try this soon

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
