### ISSUE TITLE
[BUG]every time i go on a roblox game bloxstrap unconfigures me the sound thing in roblox and i have to configure every time manually.

### ISSUE THREAD

**Issue by mauropro24** [bloxstraplabs/bloxstrap#3325]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

title self explain.

### Bloxstrap Log

```text
N/A
```

**Comment by cowboy-1337** [comment]
Title is a bit confusing. Are you talking about your modifications folder being overwritten?

**Comment by pizzaboxer** [comment]
What do you mean by "the sound thing"? How are you configuring it?

**Comment by mauropro24** [comment]
@pizzaboxer im sorry for the false report, it just fixed by itself a day after i just reported it xd
