### ISSUE TITLE
[BUG] On install of bloxstrap it gets stuck on configering roblox

### ISSUE THREAD

**Issue by Samuelff1239** [bloxstraplabs/bloxstrap#3326]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

[BUG] On install of bloxstrap it gets stuck on configering roblox. note i have installed it before and am now reinstaling it

**Comment by WindowsAutomatic11** [comment]
Same. i cant downgrade anymore

**Comment by bluepilledgreat** [comment]
> Same. i cant downgrade anymore

use the latest version

**Comment by WindowsAutomatic11** [comment]
> > Same. i cant downgrade anymore
> 
> use the latest version

no. There's no muti and no channels

**Comment by gamerloch10** [comment]
> > > Same. i cant downgrade anymore
> > 
> > 
> > use the latest version
> 
> no. There's no muti and no channels

Older versions broke, you have to use the newer ones now.
