### ISSUE TITLE
[BUG] shiftlock is broken

### ISSUE THREAD

**Issue by rvmainz** [bloxstraplabs/bloxstrap#3327]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

after the newest bloxstrap update my shiftlock completely broke It moves my cursor even after i press shift

### Bloxstrap Log

```text
N/A
```

**Comment by rvmainz** [comment]
shift lock is enabled but every time I press shift I'm still able to move
my cursor around and the shift lock logo shows

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by ThatSortaPerson** [comment]
i'm also experiencing this issue! shift lock enables as normal, but it doesn't actually lock the mouse. i have attached a configuration (to be consistent with above) and also a video about how shiftlock is "broken", and also a video of the bug happening.

**Configuration**
[Settings.json](https://github.com/user-attachments/files/17535507/Settings.json)
[State.json](https://github.com/user-attachments/files/17535508/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/17535509/ClientAppSettings.json)

**Example video**
https://github.com/user-attachments/assets/5a8a425e-5c0e-4d62-8349-1ef8e83ba933

**Comment by pizzaboxer** [comment]
Does it happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ThatSortaPerson** [comment]
Oh, after checking, it happens with Roblox in general too. It probably isn't a Bloxstrap problem.
