### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by issuereporterguy** [bloxstraplabs/bloxstrap#3329]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was typing, which could be a part of it, but when I was typing in a game, **my monitor temporarily blackscreened for no reason**, and during that time, **roblox crashed without the normal roblox crash message**. When roblox disappeared during the black screen, other apps stayed open, so its likely on roblox or bloxstraps end. I sadly can't tell the difference between it being roblox or bloxstrap, as theres no evidence that would show what caused it.

### Bloxstrap Log

```text
N/A
```

**Comment by cowboy-1337** [comment]
Has this happened multiple times, or only a one-time occurrence? Seems like a GPU issue, but I could be wrong.

**Comment by pizzaboxer** [comment]
> but when I was typing in a game, my monitor temporarily blackscreened for no reason, and during that time, roblox crashed without the normal roblox crash message

That kind of sounds like just you ran out of memory. Does this happen consistently or did this just happen one time?

**Comment by issuereporterguy** [comment]
one time

**Comment by pizzaboxer** [comment]
Closing as not a Bloxstrap issue
