### ISSUE TITLE
[solved]

### ISSUE THREAD

**Issue by TheExoticBone** [bloxstraplabs/bloxstrap#3330]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?
# SOLVED!!!
![image](https://github.com/user-attachments/assets/b6a1de19-36d7-4a4f-8370-b4489c194a67)
I shouldn't have downloaded 2.8, it worked fine right before I updated.. I have already tried tinkering with my FFs and settings, nothing worked.

### Bloxstrap Log

```text
N/A
```

**Comment by cowboy-1337** [comment]
What is your Font size set to? (in Engine settings, scroll down a bit)

![image](https://github.com/user-attachments/assets/b38139f9-3836-4b94-8ee8-697f3e5cd89b)
