### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KIPPFARIz** [bloxstraplabs/bloxstrap#3333]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

fixx it

### Bloxstrap Log

```text
N/ASystem.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
```

**Comment by KIPPFARIz** [comment]
pliss fix this bug

**Comment by NabHeyka22** [comment]
WE won't fix this.
Infact, YOU'LL fix this.
Just update to 2.8.0

**Comment by strait7291** [comment]
omg so helpfull11111!!!!!11!

**Comment by Pineappleisgood11** [comment]
close this NOW!

**Comment by NabHeyka22** [comment]
> omg so helpfull11111!!!!!11!

It is.

**Comment by bluepilledgreat** [comment]
Update to 2.8.0
