### ISSUE TITLE
[REQ] Bloxstrap for Roblox Website

### ISSUE THREAD

**Issue by coconutech47** [bloxstraplabs/bloxstrap#3335]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

What if you created a web extension for Roblox that brings like custom fonts, have the ability to change the Roblox logo and like have an old Roblox look because you can do that with extensions like tampermonkey, stylish and stylus.

**Comment by NabHeyka22** [comment]
Would be a good idea, but can pizzaboxer do this?

**Comment by Blue-Star-Technology** [comment]
I think so.

**Comment by MistressDoom** [comment]
i don't really see the point in this. why can't you just use stylus or tampermonkey? it'd be extremely out of character for bloxstrap to have a web extension

**Comment by Blue-Star-Technology** [comment]
Well more then just Old Roblox look

**Comment by MistressDoom** [comment]
> Well more then just Old Roblox look

if you view the marketplace there are far more options

**Comment by Blue-Star-Technology** [comment]
(i'm not a bot it may look like it because i'm responding quickly it's just my email telling me you commented)

**Comment by Blue-Star-Technology** [comment]
> > Well more then just Old Roblox look
> 
> if you view the marketplace there are far more options

Ok I'll have a look and see and if I have any other ideas that other extensions don't have I'll comment here if I do

**Comment by bluepilledgreat** [comment]
Use stylus
