### ISSUE TITLE
[BUG] I cant open roblox anymore

### ISSUE THREAD

**Issue by radbadmadbunny** [bloxstraplabs/bloxstrap#3337]
### Acknowledgement of preliminary instructions

- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Ok so I use bloxstrap 2.6 usually to use vulkan because it still hasnt been ported, but it started not loading roblox. I switched over to the latest version and used FFlag editor to add it back in, and still nothing works. I cant run roblox anymore without vulkan because it lags too badly. I really don't know what to do. When I reinstall the old version of bloxstrap, it is stuck saying configuring, and the same happens when I ran roblox with it on. Roblox always crashes when I load it now or doesnt load. If I manage to get in i get consistent lag spikes. This really sucks.

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Vulkan's buggy.

**Comment by Wanwood1** [comment]
Stop using vulkan
Problem solved
![Screenshot_5387](https://github.com/user-attachments/assets/a7ef68fe-6805-4466-904d-1b86509a68e9)
Maybe read before you check these boxes too?

**Comment by radbadmadbunny** [comment]
Ok its fixed but bro I cant not use vulkan, btw that checkbox aint true now i use latest version

**Comment by pizzaboxer** [comment]
> I switched over to the latest version and used FFlag editor to add it back in, and still nothing works. 

Can you clarify what's not working? Is it Roblox that's not working? Is it Vulkan that's not working?

**Comment by radbadmadbunny** [comment]
> > I switched over to the latest version and used FFlag editor to add it back in, and still nothing works.
> 
> Can you clarify what's not working? Is it Roblox that's not working? Is it Vulkan that's not working?

Ok so its fixed now and I don't know why, however what would happen is when I loaded my game it would crash a few seconds into loading. If I managed to get in there were strong lag spikes (unrelated i believe). However, since its fixed i'll close the issue. I have no idea why it crashed or why it fixed.
