### ISSUE TITLE
[REQ] Multi Instances

### ISSUE THREAD

**Issue by ihatelifebecauseofthisonething** [bloxstraplabs/bloxstrap#3338]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add back the multi instances. I really liked that feature. It was useful most of the time.

**Comment by NabHeyka22** [comment]
Pizzaboxer won't add multi instance, as people use it to farm in games.

**Comment by pizzaboxer** [comment]
Duplicate of #3276
