### ISSUE TITLE
[BUG] what the hell is this 

### ISSUE THREAD

**Issue by viljoOlen** [bloxstraplabs/bloxstrap#3339]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I get that roblox crashed but no it did not it then starts but it send me to the "crash bloxtrap" thing when it did not crash it starts roblox on right game and why it says always bloxtrap crashes WHEN IT DID NOT AND SENDS ME TO THE CRASH WEBSITE

**Comment by Wanwood1** [comment]
![Screenshot_5385](https://github.com/user-attachments/assets/3bb363dd-7a85-41ea-8e67-3faff31022d3)
You are obviously not deserving of help

**Comment by pizzaboxer** [comment]
Problem addressed in Wiki
