### ISSUE TITLE
[BUG]при запуске bloxtrap пишет что произошла проблема при его запуске

### ISSUE THREAD

**Issue by DuxsuGD** [bloxstraplabs/bloxstrap#3341]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/b149755b-3527-4b31-9b9d-a06b1512e199)

### Bloxstrap Log

```text
N/A
```

**Comment by internetzx** [comment]
update bloxstrap

**Comment by NabHeyka22** [comment]
Update.
