### ISSUE TITLE
[REQ] Seperate shortcut for opening roblox (like pre 2.8.0)

### ISSUE THREAD

**Issue by thefunny1111** [bloxstraplabs/bloxstrap#3342]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add back a seperate shortcut for opening roblox with bloxstrap like pre 2.8.0 because it adds convenience for people who just want to leave it on their taskbar and for those who are prone to accidentally changing a setting

**Comment by Wanwood1** [comment]
Go to shortcuts

**Comment by thefunny1111** [comment]
my bad i did not see that
