### ISSUE TITLE
[BUG] I kept getting an error whilst installing Bloxstrap. Please fix it.

### ISSUE THREAD

**Issue by Drew290** [bloxstraplabs/bloxstrap#3343]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I kept getting an error message while installing Bloxstrap.

### Bloxstrap Log

```text
Bloxstrap-v2.5.4
```

**Comment by NabHeyka22** [comment]
Maybe send the log file.

**Comment by Wanwood1** [comment]
Update

**Comment by Drew290** [comment]
> Maybe send the log file.

How do I do that?

**Comment by Storm-930** [comment]
when an error pops up, a "locate log file" button appears, which opens the file manager with the logs folder
or alternatively go to C:\Users\[You]\AppData\Local\Bloxstrap\Logs

**Comment by Storm-930** [comment]
make sure you sort by Date Modified with the arrow pointing downwards like [this](https://github.com/user-attachments/assets/6397dd6f-b2ab-4cb5-9956-1a79a1c44608)

**Comment by Drew290** [comment]
> C:\Users[You]\AppData\Local\Bloxstrap\Logs

Then?

**Comment by Drew290** [comment]
> make sure you sort by Date Modified with the arrow pointing downwards like [this](https://github.com/user-attachments/assets/6397dd6f-b2ab-4cb5-9956-1a79a1c44608)

What's next?

**Comment by Storm-930** [comment]
you drag it here to send it

**Comment by Storm-930** [comment]
the latest one, at the top if you did everything right

**Comment by pizzaboxer** [comment]
This report is already null and void since you're using 2.5.4 and not the latest version

**Comment by Drew290** [comment]
> This report is already null and void since you're using 2.5.4 and not the latest version

I guess that's why.
