### ISSUE TITLE
[BUG] Bloxstrap fails to start on latest version.

### ISSUE THREAD

**Issue by 1Bottle2Jars** [bloxstraplabs/bloxstrap#3345]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Everything was working fine today till i logged off my pc for a few hours. I came back, wanted to hop into a game and it just fails to launch. Tried reïnstalling, disabled all my startup apps in task manager and rebooted my pc, looked at the wiki for anything, went trough reddit but yet nothing has helped me. 

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Maybe show a screenshot?

**Comment by 1Bottle2Jars** [comment]
Screenshot of what exactly?

**Comment by NabHeyka22** [comment]
Of the error.

**Comment by 1Bottle2Jars** [comment]
This is what i gets, the site i get sent to is this one:https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
![image](https://github.com/user-attachments/assets/9a6e98b9-1c06-4c1d-91f0-212caee6ee36)

**Comment by NabHeyka22** [comment]
It's taking too long to launch.

**Comment by 1Bottle2Jars** [comment]
and what an cause this? The wiki wasn't helpfull so im pretty desperate

**Comment by 1Bottle2Jars** [comment]
[Bloxstrap_20241019T181047Z.log](https://github.com/user-attachments/files/17446896/Bloxstrap_20241019T181047Z.log)

**Comment by pizzaboxer** [comment]
Does Roblox launch if you use the original launcher?

**Comment by pizzaboxer** [comment]
Please open a new issue when you can confirm that this happens only with Bloxstrap
