### ISSUE TITLE
[BUG] Constant hours passing by as it loads "Configuring Roblox"

### ISSUE THREAD

**Issue by LIQAT3d** [bloxstraplabs/bloxstrap#3347]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

 I left it open all night after it updated for me. I woke up this morning to STILL see it configuring. I closed it and tried again and it has yet to open at all. all its shows is the "configuring Roblox" loading screen. 
![image](https://github.com/user-attachments/assets/c9549c51-ce45-4d60-bf52-a76792a282ad)
![Screenshot (517)](https://github.com/user-attachments/assets/0c76030c-3192-47a9-989d-f5628854d1a5)

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Update.

**Comment by LIQAT3d** [comment]
I have updated

**Comment by NabHeyka22** [comment]
https://bloxstraplabs.com/

**Comment by LIQAT3d** [comment]
hm no, I went to the website, and it showed the latest was 2.7.0. thank you I'll try that

**Comment by NabHeyka22** [comment]
> hm no, I went to the website, and it showed the latest was 2.7.0. thank you I'll try that

You probably didn't go to one of the 2 official websites.

**Comment by Wanwood1** [comment]
> hm no, I went to the website, and it showed the latest was 2.7.0. thank you I'll try that

Question, what website did you go to?

**Comment by LIQAT3d** [comment]
github, just searched bloxstrap and it showed. but I think I got it now

**Comment by pizzaboxer** [comment]
such a shame that you didn't show a screenshot of the page scrolled up because if you did then it would've showed this notice which would've made this report a lot funner

![image](https://github.com/user-attachments/assets/bae4caca-414c-48fb-848a-21860cdd6398)
