### ISSUE TITLE
[BUG] menu bug.?

### ISSUE THREAD

**Issue by sdwafsher** [bloxstraplabs/bloxstrap#3348]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

this only happens while using the V1 (2015) esc menu , but the playerlist is gone , leaving doesn't work , resetting doesn't 
![image](https://github.com/user-attachments/assets/fadad52e-bba8-483d-9869-0bae7d9cdefe)
this is what happens when leave/reset is pressed
pressing alt f4 and trying to leave with the x gives the same screen below
![image](https://github.com/user-attachments/assets/ff2a259e-6828-4a10-8c2e-702db1e4fab0)
i can live without the V1 menu , just reporting it

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Add these fflags
{
  "FFlagFixReportButtonCutOff": "False",
  "FFlagSettingsHubIndependentBackgroundVisibility": "False"
}

**Comment by sdwafsher** [comment]
thanks nab

**Comment by NabHeyka22** [comment]
Yw.
