### ISSUE TITLE
[BUG] My "choose where to install" isint working :(

### ISSUE THREAD

**Issue by Hector6934** [bloxstraplabs/bloxstrap#3349]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when i click reset than install it said i cant use the location. pls i need help

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
What location is it unable to install to? Censor your username if needed

**Comment by Hector6934** [comment]
idk how to censor it

**Comment by Hector6934** [comment]
lemme send a screenshot
![image](https://github.com/user-attachments/assets/a26619e5-8ff4-4cbc-bc80-bcb042da3d5b)

**Comment by Hector6934** [comment]
![image](https://github.com/user-attachments/assets/0615b412-c588-4781-b040-3495a658a7aa)

**Comment by bluepilledgreat** [comment]
bruh

**Comment by pizzaboxer** [comment]
what in the fuck

**Comment by Hector6934** [comment]
idk what to do

**Comment by pizzaboxer** [comment]
You should be able to install it at C:\Bloxstrap\ for the time being, though I recommend that you reinstall it to be at the default path after the next update comes out.

**Comment by Hector6934** [comment]
??? i kinda dont understand
