### ISSUE TITLE
[BUG] unable to connect to github

### ISSUE THREAD

**Issue by EnzoCamilo** [bloxstraplabs/bloxstrap#3352]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i was attempting to change my emojis when i received an error message saying:

> bloxstrap is unable to connect to github
> the emoji mod can not be applied at this time
> please try again later
> more information:
`System.IO.IOException: The file 'C:\Users\User\AppData\Local\Bloxstrap\Modifications\content\fonts\TwemojiMozilla.ttf' already exists.`

### Bloxstrap Log

```text
N/A
```

**Comment by MrT-tak** [comment]
Quick question, @EnzoCamilo Have you removed the file `C:\Users\User\AppData\Local\Bloxstrap\Modifications\content\fonts\TwemojiMozilla.ttf` and disabled then re enabled custom mod?

**Comment by EnzoCamilo** [comment]
i haven't thought of that actually lemme try that

**Comment by EnzoCamilo** [comment]
that seems to have solved the issue, thank you

**Comment by pizzaboxer** [comment]
Weird, since we should be handling that. Thanks for reporting this bug though.

**Comment by MrT-tak** [comment]
To the people looking into it:
I assume something went wrong and Bloxstrap isnt acknowledging the existence of the font, attempts to add, errors out for file existing, unable to overwrite.

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
