### ISSUE TITLE
The fucking lag

### ISSUE THREAD

**Issue by ithkuilfan** [bloxstraplabs/bloxstrap#3354]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was playing roblox normally and bloxstrap was lagging on my roblox so I put the best fast flags but they keep the fucking lag and I restarted my computer 534875478583459837543 times and the fucking lag is still on bloxstrap. (why I have lag and on top of that I play in very low quality and the game lags so much that I can't even hear the audio because of the new bloxstrap?)

### Bloxstrap Log

```text
N/A
```

**Comment by user1126s** [comment]
and then his computer jumped for the beef, and fell...

**Comment by pizzaboxer** [comment]
i hate to break the news to you but the version of bloxstrap you're using has no bearing on roblox's performance, that's just not how it works

So, does this happen if you use the original launcher, or is it only with Bloxstrap?

**Comment by MHMHMHM121H** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [x]  I did not answer truthfully to all the above checkboxes.
> 
> ### What problem did you encounter?
> I was playing roblox normally and bloxstrap was lagging on my roblox so I put the best fast flags but they keep the fucking lag and I restarted my computer 534875478583459837543 times and the fucking lag is still on bloxstrap. (why I have lag and on top of that I play in very low quality and the game lags so much that I can't even hear the audio because of the new bloxstrap?)
> 
> ### Bloxstrap Log
> ```
> N/A
> ```

i know how to fix this, open control panel uninstall roblox reinstall fixed.

**Comment by ithkuilfan** [comment]
only with bloxstrap when i delete all the fast flags the lag is so Powerful that he freezes my computer

**Comment by pizzaboxer** [comment]
If that's really the case, then that's not our fault. We can't possibly cause that. We don't do anything more than the Roblox bootstrapper does by default. There's likely some discrepancy between how your system treats Roblox and how it treats Bloxstrap (like an antivirus), and we can't fix that.
