### ISSUE TITLE
[BUG] its still configuring roblox 

### ISSUE THREAD

**Issue by hiilikecheese** [bloxstraplabs/bloxstrap#3355]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

its not opening roblox bruv

**Comment by gamerloch10** [comment]
You need to be on 2.8.0 for bloxstrap to work now, older versions broke in a roblox update.

**Comment by FluffyXDOnGH** [comment]
Same issue here still Configuring...

**Comment by FluffyXDOnGH** [comment]
> You need to be on 2.8.0 for bloxstrap to work now, older versions broke in a roblox update.

Where can we get that?

**Comment by FluffyXDOnGH** [comment]
> You need to be on 2.8.0 for bloxstrap to work now, older versions broke in a roblox update.

Just downloaded it and worked!

**Comment by only1mistakE** [comment]
#635
