### ISSUE TITLE
[BUG] Bloxstrap exception

### ISSUE THREAD

**Issue by joosch22** [bloxstraplabs/bloxstrap#3361]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/a2e08d22-4db0-4948-af51-b4a8d6da08bb)
It's locate log fil 

System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
 it's the error message

### Bloxstrap Log

```text
![image](https://github.com/user-attachments/assets/a2e08d22-4db0-4948-af51-b4a8d6da08bb)
```

**Comment by NabHeyka22** [comment]
Update.

**Comment by l0sinn** [comment]
> Update.

What do you mean update? Update what, and how?

**Comment by l0sinn** [comment]
How

**Comment by NabHeyka22** [comment]
https://bloxstraplabs.com/

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
