### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by WooLuu** [bloxstraplabs/bloxstrap#3364]
Alt + Enter (Full Screen) is an incredible feature, but I can't seem to get back that FPS boost with the official windows configuration. I'm not sure how to return it to that state.
My last option is to return to bloxstrap 2.7
can anyone assist ?

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Assuming problem is resolved in 2.8.1. Open a new issue if not.
