### ISSUE TITLE
[BUG] I'm trying to open wave but it's not opening and it's saying failed to get bloxstrap versinon info win-version is unable to access file

### ISSUE THREAD

**Issue by cdjdhr** [bloxstraplabs/bloxstrap#3365]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I'm trying to open wave but it's not opening and it's saying failed to get bloxstrap versinon info win-version is unable to access file
![image](https://github.com/user-attachments/assets/28d7b032-8f29-497e-b360-ad414c6bcb34)

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Fuck you.

**Comment by bluepilledgreat** [comment]
lebron james
