### ISSUE TITLE
thanks but you can help me?

### ISSUE THREAD

**Issue by cdjdhr** [bloxstraplabs/bloxstrap#3366]
![image](https://user-images.githubusercontent.com/185703809/378203350-a52613bd-78f7-4ec7-8950-fd8fa0455309.png)

**Comment by cdjdhr** [comment]
![image](https://github.com/user-attachments/assets/8e6a295b-7437-45c5-9463-2ceb5d20a7d0)

**Comment by cdjdhr** [comment]
![image](https://github.com/user-attachments/assets/d92b04ec-e572-402e-84a8-49ce7e37126d)

**Comment by internetzx** [comment]
You dirty wave users should get good at games.

**Comment by bluepilledgreat** [comment]
lebron james
