### ISSUE TITLE
[BUG] Roblox crash: Does not contain application settings table

### ISSUE THREAD

**Issue by nnvecy** [bloxstraplabs/bloxstrap#3367]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I log into Roblox, it gives me an error:
Failed to download or apply critical settings, please check your internet connection. Error info: Does not contain application settings table.
_(Recently, everything worked, but I changed some FFlags and now it gives me this error)_

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Can you send your original (untranslated) error message?

**Comment by nnvecy** [comment]
> Можете ли вы отправить свое оригинальное (непереведенное) сообщение об ошибке?
Roblox

       Failed to download or apply critical settings, please check your internet connection. Error info: Does not contain application 
       settings table mera

**Comment by vrchatp** [comment]
Started getting the same error today

**Comment by OnlyLuis** [comment]
Me too

**Comment by DeRzKaya1337** [comment]
started getting this error around 5 hours ago, still getting it even after trying several fix methods

**Comment by rubgiru** [comment]
After the error, I tried to find ways to solve it, I found a "one-time" one. After each reinstallation, you can log in 1 time, if you exit roblox, reinstall again.

**Comment by KitiKat69** [comment]
Has anyone found a way to permanently bring Bloxstrap back to play roblox?

**Comment by rubgiru** [comment]
if you found it, you haven't written yet

**Comment by pizzaboxer** [comment]
Not a Bloxstrap issue

**Comment by pizzaboxer** [comment]
> but I changed some FFlags and now it gives me this error

Could you perhaps state what you added/changed?

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
