### ISSUE TITLE
[BUG] help pls

### ISSUE THREAD

**Issue by SigmaBoy658** [bloxstraplabs/bloxstrap#3368]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

я хотел зайти поиграть,но вылетела ошибка
[Bloxstrap_20241020T161906Z.log](https://github.com/user-attachments/files/17451194/Bloxstrap_20241020T161906Z.log)

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
Don't use Wave you loser.

**Comment by SigmaBoy658** [comment]
что такое wave

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
