### ISSUE TITLE
[BUG] BLOQUER SUR CONFIGURATION DE ROBLOX

### ISSUE THREAD

**Issue by MDLD-LASS** [bloxstraplabs/bloxstrap#3371]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

J'installe bloxstrap quand j'installe sa mets installé etc et ensuite sa mets configuration de roblox j'attends et sa affiche rien d'autre que sa 
![image](https://github.com/user-attachments/assets/acfa9df3-d1e1-4253-a80a-d3a7d945c622)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.

**Comment by MDLD-LASS** [comment]
TY !!
