### ISSUE TITLE
[BUG] Full Screen causes colors to be inverted while using DirectX3D11.

### ISSUE THREAD

**Issue by BloxyReimu** [bloxstraplabs/bloxstrap#3372]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Basically, if I use DirectX3D11 when using exclusive fullscreen, it caused my screen colors to be inverted for some reason. I don't what is causing this, and with Vulkan it doesn't do this, but there's a different issue there, I can't close out of True Fullscreen so I can't really use it. at all. My hardware is AMD A6-7310 for my CPU, and my graphics is Radeon R4. Does it have to do with my hardware?

### Bloxstrap Log

```text
N/A
```

**Comment by only1mistakE** [comment]
what the fuck is directx3d 11
are you rendering with Direct3D 11 or DirectX 11

**Comment by BloxyReimu** [comment]
That's the full name. DirectX3D 11 is the full name for it, but it's called Direct3d 11 in bloxstrap

**Comment by only1mistakE** [comment]
> That's the full name. DirectX3D 11 is the full name for it, but it's called Direct3d 11 in bloxstrap

hey buddy DirectX 11 and Direct3D 11 is different okay
people say DX11 and D3D11 theres nothing as DX3D11

**Comment by only1mistakE** [comment]
> > That's the full name. DirectX3D 11 is the full name for it, but it's called Direct3d 11 in bloxstrap
> 
> hey buddy DirectX 11 and Direct3D 11 is different okay
> people say DX11 and D3D11 theres nothing as DX3D11
> 
> now yes i know that Direct3D is a part of DirectX used to render 3D stuff but nobody says DirectX3D
> you can call it D3DX[version] tho

oh btw just download DX11/12 libs, they come with D3D libs too.
try that and lmk

**Comment by pizzaboxer** [comment]
> Does it have to do with my hardware?

Likely, yes. Well, more with software. I don't really see how this could happen if it wasn't a GPU config problem. Check your graphics settings in the Radeon Software.
