### ISSUE TITLE
How do I install RoShade?

### ISSUE THREAD

**Issue by Luuunar** [bloxstraplabs/bloxstrap#3373]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

When I installed Roshade It didn't work I tried the shortcuts and everything is there a way to fix it?

### Bloxstrap Log

```text
N/A
```

**Comment by stevefromminecraft123456** [comment]
roshade isnt supported because of the 64 bit and byfron update, sorry

**Comment by Luuunar** [comment]
Oh Damn. So do I have to uninstall bloxstrap inorder to use it?

**Comment by stevefromminecraft123456** [comment]
no its just unsupported

**Comment by stevefromminecraft123456** [comment]
use bloxshade, if you dont have a nvidia gpu, sorry
