### ISSUE TITLE
When i try to join a game it says roblox failed to launch

### ISSUE THREAD

**Issue by FallenMxru** [bloxstraplabs/bloxstrap#3381]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

When i try to join a game it says roblox failed to launch and takes me to the help website and i dont know why

### Bloxstrap Log

```text
N/A
```

**Comment by Vad1mCSO2** [comment]
![image](https://github.com/user-attachments/assets/09eca669-2047-411a-9acc-75872a7780db)
Runs fine, but is encounted as bug.

**Comment by Spoonus** [comment]
re: i have also been encountering this, yet roblox launches just fine
dunno why it's happening

**Comment by lukaku112** [comment]
I have the same issue, anyone have a solution for this?

**Comment by unfunny1** [comment]
That's a bug which is gonna be fixed in the new bloxstrap update

**Comment by pizzaboxer** [comment]
Addressed in Wiki
