### ISSUE TITLE
[BUG] bloxstrap not opening roblox

### ISSUE THREAD

**Issue by rgeghwt** [bloxstraplabs/bloxstrap#3386]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8

### What problem did you encounter?

so i have been opening my roblox and then bloxstrap says OPENING ROBLOX APPLYING MODIFICATIONS AND THEN JUST CLOSES WONT LAUNCH ROBLOX OR ANYTHING AND YES I HAVE RESTARTED MY PC AND GOT THE NEWEST UPDATE I HAVE TRIED TO UNINSTALL IT AND THEN REINSTALLING BUT STILL THE PROBLEM SHOWS UP. FIX THIS >:(

### Bloxstrap Log

```text
CONFIGUIRING ROBLOX
```

**Comment by rgeghwt** [comment]
FIX IT RN

**Comment by NabHeyka22** [comment]
Calm down.
So it downloads, then just closes?
And you've also stated that Roblox, when tried opening, doesn't open?

**Comment by rgeghwt** [comment]
oh thank god some1 replied ok ill calm down
anw yes it says opening roblox then configuring roblox then just
doesnt open roblox

**Comment by NabHeyka22** [comment]
But, does the Launch Roblox work?

**Comment by rgeghwt** [comment]
no

**Comment by rgeghwt** [comment]
it dont launch roblox

**Comment by NabHeyka22** [comment]
Did you setup any FastFlags?
If so, try to delete them.

**Comment by rgeghwt** [comment]
ok lemme see

**Comment by rgeghwt** [comment]
TYSM IT LOADED TURNS OUT I JUST NEEDED TO SWITCH FFLAGS

**Comment by rgeghwt** [comment]
can u delete my review or just say change fflags

**Comment by NabHeyka22** [comment]
No.

**Comment by rgeghwt** [comment]
alr ty
ill contact u if smths wrong agn

**Comment by NabHeyka22** [comment]
You're welcome.

**Comment by pizzaboxer** [comment]
> TYSM IT LOADED TURNS OUT I JUST NEEDED TO SWITCH FFLAGS

**Comment by rgeghwt** [comment]
close
