### ISSUE TITLE
[BUG] Bloxstrap not working after reset

### ISSUE THREAD

**Issue by Fabi007-down** [bloxstraplabs/bloxstrap#3387]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

i am using a custom iso (Xos11) and it was working before but today when i tried installing it roblox keeps crashing on the start

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
That may be the issue.
Some custom ISOs may have stuff deleted that cause Roblox to break.
If you care about bloat, use [Windows 11 IoS Enterprise](https://massgrave.dev/windows_ltsc_links). It's official and stable and i'm using it right now.

**Comment by Fabi007-down** [comment]
> That may be the issue.
no, the problem is its the same iso i had before and it was working fine, but now it wont work anymore for sum reason

**Comment by Fabi007-down** [comment]
its the same iso and it worked b4

**Comment by NabHeyka22** [comment]
Maybe it updated.
An ISO doesn't always work the same.

**Comment by Fabi007-down** [comment]
> Maybe it updated. An ISO doesn't always work the same.

no, its the same iso from the same usb stick, cant have changed by magic

**Comment by Fabi007-down** [comment]
it was timezone issue lol, if ur roblox is not working guys try changing the day 1 next so today is 21st just set it to the 22st
