### ISSUE TITLE
[BUG] ESC menu

### ISSUE THREAD

**Issue by totallyrandom001** [bloxstraplabs/bloxstrap#3389]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

the ESC menu ingame doesnt appear AT ALL, i tried clicking ESC but it doesnt show up.
here is an image below of the top left of my screen
![image_2024-10-21_210435702](https://github.com/user-attachments/assets/b4fa638b-8125-438d-bbf8-a97939b18cce)

extra details:
fast flags
FFlagEnableInGameMenuChromeABTest2 = false
FFlagEnableMenuModernizationABTest = false
FFlagEnableMenuModernizationABTest2 = false
FFlagEnableReportAbuseMenuRoactABTest2 = false
ESC menu: V1 (2015)

### Bloxstrap Log

```text
N/A
```

**Comment by forzanapoli90** [comment]
bro the chat and menu dont show up
![e](https://github.com/user-attachments/assets/2bf4397b-375d-4b4a-9737-3aa397312530)

**Comment by forzanapoli90** [comment]
how to fix??

**Comment by internetzx** [comment]
dopnt use the v1 menu

**Comment by forzanapoli90** [comment]
why?
im a bit nostalgic

**Comment by forzanapoli90** [comment]
so is there something i can do

**Comment by Orliminecraft** [comment]
> so is there something i can do


> "FFlagFixReportButtonCutOff": "False", "FFlagSettingsHubIndependentBackgroundVisibility": "False"
> 
> add these fflags and lmk how it goes

**Comment by domain666** [comment]
those fflags fixed the issue thanks

**Comment by pizzaboxer** [comment]
Addressed in Wiki

**Comment by totallyrandom001** [comment]
tysm red you saved my day

**Comment by forzanapoli90** [comment]
where do i put the code??

**Comment by forzanapoli90** [comment]
say it to me pleasee

**Comment by forzanapoli90** [comment]
qwertyuiolpòèàù
