### ISSUE TITLE
[BUG] Bloxstrap does not open roblox from private server links

### ISSUE THREAD

**Issue by thefunny1111** [bloxstraplabs/bloxstrap#3390]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

Bloxstrap does not open roblox private servers from links, it instead just opens bloxstrap, launching roblox from bloxstrap does not put you in the private server

### Bloxstrap Log

```text
N/A
```

**Comment by butheresthekicker** [comment]
this is a new feature that appeared out of nowhere that messes up only firefox users including myself
it'll forever stay a mystery as to how do you mess up something that worked perfectly fine before, without the ability to revert back to an older version of the app

**Comment by pizzaboxer** [comment]
> it'll forever stay a mystery as to how do you mess up something that worked perfectly fine before

when you develop software you'll learn someday

> Bloxstrap does not open roblox private servers from links, it instead just opens bloxstrap, launching roblox from bloxstrap does not put you in the private server

It's only private server links that do this? What about clicking on the green play button?

**Comment by totallyrandom001** [comment]
this is probably because private server links launch the Roblox executable directly. bloxstrap devs may have been trying to make a way for people to launch Roblox without launching bloxstrap with it, which would answer why this happened.

**Comment by butheresthekicker** [comment]
> > it'll forever stay a mystery as to how do you mess up something that worked perfectly fine before
> 
> when you develop software you'll learn someday
> 
> > that messes up only firefox users including myself
> 
> from what i've seen, that might actually be a problem with firefox and not me! but, i can remedy it on my end.
> 
> > Bloxstrap does not open roblox private servers from links, it instead just opens bloxstrap, launching roblox from bloxstrap does not put you in the private server
> 
> It's only private server links that do this? What about clicking on the green play button?

yeah, i apologize for appearing entitled and being harsh with how i word my sentences.
though, i found it frustrating that i wasn't able to revert to v2.7.0 either, because it'd just infinitely configure roblox. is this intentional? or it's roblox being roblox?

**Comment by red-nt** [comment]
roblox added a new file called redist.zip which caused the old versions of bloxstrap to break. to fix this just get the latest version

**Comment by pizzaboxer** [comment]
@red-nt Accidentally marked your comment as off-topic, sorry about that.

@butheresthekicker Yes, that's Roblox.

**Comment by red-nt** [comment]
it's ight

**Comment by MrT-tak** [comment]
> > it'll forever stay a mystery as to how do you mess up something that worked perfectly fine before
> 
> when you develop software you'll learn someday
Agreed.

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
