### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by imasigmalphawolf** [bloxstraplabs/bloxstrap#3392]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.80

### What problem did you encounter?

This has been happening since the v2.70 update of bloxstrap  but when im playing a certain game bloxstrap just freezes and i cant close it or do anything and the only way to make it close is to sign out and sign back in

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Does this happen when you use the original Roblox launcher?

**Comment by imasigmalphawolf** [comment]
yes it does but it closes it for me tho

**Comment by pizzaboxer** [comment]
> but it closes it for me tho

Not a discrepancy on our end. Invalid issue.
