### ISSUE TITLE
[worlds most important problem that will cause the end of world]

### ISSUE THREAD

**Issue by user1126s** [bloxstraplabs/bloxstrap#3393]
Would you be safe and jump for the git cli or would you do a one block vertical jump for github desktop beta app. Here, in github civilization no one jumps for the github desktop beta, It's better to be safe and use the git cli rather than risk your entire Repository by failing the jump.

**Comment by user1126s** [comment]
yeah I couldn't phrase this so:
# [X] would you do a one block vertical jump for the raw beef or a  [X] one block jump for the raw chicken.

**Comment by GoingCrazyDude** [comment]
not funny
![sukuna](https://tenor.com/view/sukuna-jujutsu-kaisen-sukuna-looking-down-gif-7333648534605432939)

**Comment by internetzx** [comment]
not funny at all

**Comment by user1126s** [comment]
> not funny at all

dude i was like 99% asleep writing this and when i woke up i freaked out and found out you  cannot delete github issues. I am very sorry :(

**Comment by user1126s** [comment]
i feel so bad i should just abandon all my ongoing projects and delete this account. Goodbye LSW
