### ISSUE TITLE
[BUG] ROBLOX Faild To Launch [Windows ROBLOX]

### ISSUE THREAD

**Issue by WVEZ** [bloxstraplabs/bloxstrap#3394]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

So the new bloxstrap 2.8.0 it update automatic and it's says 
[roblox faild to luanch] 
I play roblox for windows cuz my webside roblox not even start when i click Play

![Screenshot 2024-10-22 145138](https://github.com/user-attachments/assets/4a2f1bd2-072a-47ef-9fef-23f4098c50b0)

### Bloxstrap Log

```text
N/A
```

**Comment by Ivthered-123ivopp** [comment]
Can you send the log?
And why did you check:  I did not answer truthfully to all the above checkboxes?

**Comment by WVEZ** [comment]
> Can you send the log? And why did you check: I did not answer truthfully to all the above checkboxes?

by mistake

**Comment by Ivthered-123ivopp** [comment]
Can you send the log?

**Comment by pizzaboxer** [comment]
Did you read the information that opened?

**Comment by pizzaboxer** [comment]
Does using the original Roblox launcher work?

**Comment by Ira-svg** [comment]
> Does using the original Roblox launcher work?

no it doesnt'

**Comment by lukaku112** [comment]
i had the same problem for like a week and i sitll hjave it anyine has a solution?

**Comment by pizzaboxer** [comment]
Assuming person has not read the information given; open a new issue if/when you have
