### ISSUE TITLE
[BUG] Building from source: Builds with dll's

### ISSUE THREAD

**Issue by Ivthered-123ivopp** [bloxstraplabs/bloxstrap#3395]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

When i build bloxstrap from the source, It creates a folder with dll's and the exe. My problem is i want the standalone exe whitout the dll's

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Building-Bloxstrap-from-source
