### ISSUE TITLE
[BUG] V3 Menu

### ISSUE THREAD

**Issue by saintstanding** [bloxstraplabs/bloxstrap#3396]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

Please watch this clip cannot use V3 Menu.
https://saintstanding.tixte.co/Blox_Strap.mp4
(edit : yes i did just press play without changing tabs sets it back in roblox when its loaded)
### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Duplicate of #3336
