### ISSUE TITLE
[BUG] WHERE IS THE ROBLOX MENU?

### ISSUE THREAD

**Issue by SCOPA-A** [bloxstraplabs/bloxstrap#3401]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.0

### What problem did you encounter?

roblox menu is gone, I can't customize settings while playing, pls help

**Comment by NabHeyka22** [comment]
provide screenshot

**Comment by SCOPA-A** [comment]
> provide screenshot
![Uploading Screenshot 2024-10-23 002609.png…]()

**Comment by SCOPA-A** [comment]
> provide screenshot

![Screenshot 2024-10-23 002609](https://github.com/user-attachments/assets/86f4ba4f-d8cc-485f-bb6a-9ea1e7c9b453)

**Comment by NabHeyka22** [comment]
add these fflags:
{
  "FFlagFixReportButtonCutOff": "False",
"FFlagSettingsHubIndependentBackgroundVisibility": "False"
}
if it doesn't work, switch to V4 with new UI
we don't care if you like it or not

**Comment by SCOPA-A** [comment]
> add these fflags: { "FFlagFixReportButtonCutOff": "False", "FFlagSettingsHubIndependentBackgroundVisibility": "False" } if it doesn't work, switch to V4 with new UI we don't care if you like it or not

tks, it worked

**Comment by NabHeyka22** [comment]
yw
