### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BOBBYdaw1234** [bloxstraplabs/bloxstrap#3402]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.80

### What problem did you encounter?

![{B62A5CBA-4A51-4A26-A338-4F20CCAB17C6}](https://github.com/user-attachments/assets/b57fc34b-35bf-4251-bd2b-00f1329697ba)

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
![Screenshot_5440](https://github.com/user-attachments/assets/15505ae9-c5cb-4beb-8115-bff6c2d16e7f)
