### ISSUE TITLE
[BUG] roblox opens but doesn't show anything

### ISSUE THREAD

**Issue by alriceeeee** [bloxstraplabs/bloxstrap#3403]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

while using bloxstrap, roblox sits in the background according to taskmgr, yet it doesn't actually open. 
![{3449BF4C-FEBB-4290-91D3-FB2D5FD45839}](https://github.com/user-attachments/assets/72899df9-86ff-4dbe-955f-426ed6a7f0a5)
loading roblox normally works just fine, i've tried reinstalling/resetting config settings. i've even restarted my pc

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by alriceeeee** [comment]
> https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

already read it, nothing there helped.

**Comment by alriceeeee** [comment]
@pizzaboxer nevermind apparently closing steam just solved my issue? not sure how that makes sense but yeah..
