### ISSUE TITLE
[BUG] Bloxstrap Crash

### ISSUE THREAD

**Issue by MrKaioasma** [bloxstraplabs/bloxstrap#3406]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

In bloxstrap when I click the "Install" button, the window stays all the time on "Configuring Roblox" and does nothing.
![bloxstrap](https://github.com/user-attachments/assets/3c533044-b3e9-4eb0-a134-309944d23ebf)

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
update

**Comment by bluepilledgreat** [comment]
bluestrap
