### ISSUE TITLE
[REQ] how to fix?

### ISSUE THREAD

**Issue by thahstudioGM** [bloxstraplabs/bloxstrap#3409]
System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

**Comment by gamerloch10** [comment]
Update to 2.8.0

**Comment by thahstudioGM** [comment]
ok
