### ISSUE TITLE
[BUG] PC sees a certain account as a severe virus threat

### ISSUE THREAD

**Issue by AltThePro** [bloxstraplabs/bloxstrap#3410]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

After i tried changing my roblox password itt logged me out as normal then when i tried logging back in the password wasnt working and so i changed it again after a couple tries becuase it said something about "something went wrong" and after a few tries i reseted my password and got into the account. After that i tried playing a game and when i click launch roblox it stays on configuring roblox and a screen pops up saying "bloxstrap exception, an exception occurred while running bloxstrap System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\detex\AppData\Local\Bloxstrap\Downloads\2335576c8450d75663735f7016e5d712'. Check the bloxstrap wiki first to see if this problem has already been addressed with a fix. If not, then please report this excpetion through a GitHub issue along a copy of the log file that was created." While this is happening my pc shows me an alert saying a severe threat has been caught or something and it doesnt open roblox.

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
Where did you download bloxstrap from

**Comment by NoobLikesThis** [comment]
bro downloaded a fake virus pop-up because a pc doesnt show an alert for servere threats like that, fake websites: https://bloxstrap.org/ https://bloxstrap.dev/ https://bloxstrap.pro/ https://bloxstrap.com/ https://www.softpedia.com/get/Gaming-Related/Bloxstrap.shtml
real websites: https://github.com/bloxstraplabs/bloxstrap/ https://bloxstraplabs.com/
do not be fooled.

**Comment by user1126s** [comment]
> bro downloaded a fake virus pop-up because a pc doesnt show an alert for servere threats like that, fake websites: https://bloxstrap.org/ https://bloxstrap.dev/ https://bloxstrap.pro/ https://bloxstrap.com/ https://www.softpedia.com/get/Gaming-Related/Bloxstrap.shtml real websites: https://github.com/bloxstraplabs/bloxstrap/ https://bloxstraplabs.com/ do not be fooled.

i love ublock 
![image](https://github.com/user-attachments/assets/6bcb2bbd-7b6e-4184-8557-1547cdef8008)
sad chrome is removing it

**Comment by NoobLikesThis** [comment]
> > bro downloaded a fake virus pop-up because a pc doesnt show an alert for servere threats like that, fake websites: https://bloxstrap.org/ https://bloxstrap.dev/ https://bloxstrap.pro/ https://bloxstrap.com/ https://www.softpedia.com/get/Gaming-Related/Bloxstrap.shtml real websites: https://github.com/bloxstraplabs/bloxstrap/ https://bloxstraplabs.com/ do not be fooled.
> 
> i love ublock ![image](https://private-user-images.githubusercontent.com/114283670/379827609-6bcb2bbd-7b6e-4184-8557-1547cdef8008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTU5NzcsIm5iZiI6MTcyOTc5NTY3NywicGF0aCI6Ii8xMTQyODM2NzAvMzc5ODI3NjA5LTZiY2IyYmJkLTdiNmUtNDE4NC04NTU3LTE1NDdjZGVmODAwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxODQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDhiZTI3NmJiMTEzNTI1ZmYzODczMzI2OTFhMzZkNWMwMjgxMjJiOGI2ZDJlNzViN2JjZDliYTAyY2U2ZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LGcs0DyjMVKQKQzbNZN4-ILujp2AO3HSzegxS-CpMLg) sad chrome is removing it

i use firefox so it doesnt get removed for me

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by pizzaboxer** [comment]
Addressed in Wiki
