### ISSUE TITLE
why does my bloxstrap keep showing configuring roblox but won't open roblox?

### ISSUE THREAD

**Issue by thahstudioGM** [bloxstraplabs/bloxstrap#3412]

**Comment by gamerloch10** [comment]
Update to 2.8.0 or newer as older versions broke awhile back

**Comment by thahstudioGM** [comment]
how about 2.5?

**Comment by gamerloch10** [comment]
It wont work you have to update to use bloxstrap now

**Comment by thahstudioGM** [comment]
okay

**Comment by thahstudioGM** [comment]
how about bloxstrap v2.7.0?

**Comment by gamerloch10** [comment]
You have to use 2.8.0, why do you need to be on a version under that anyway.

**Comment by Wanwood1** [comment]
Update to latest version which is 2.8.0, older versions will not work so stop asking

**Comment by NoobLikesThis** [comment]
> You have to use 2.8.0, why do you need to be on a version under that anyway.

had more features like vulkan, but you can do that with fflags anyway, i dont dont get the point.
