### ISSUE TITLE
No UI issue.

### ISSUE THREAD

**Issue by reaperbw** [bloxstraplabs/bloxstrap#3413]
well, this happens in every game i join.
![image](https://user-images.githubusercontent.com/185354628/379286219-13ca9003-fa7e-4657-9778-51487bea8033.png)
May u help me?

**Comment by reaperbw** [comment]
Oof, it doesnt work, basically i got the chat ui, but there is no other ui on the screen, (Roblox UI) please help me fix this.
#725 #3059 #3138 #1856

**Comment by user1126s** [comment]
@bluepilledgreat i think you should apply the clarification needed tag or is this an issue?

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by reaperbw** [comment]
thanks i alr fixed it
