### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by Dream1SUS** [bloxstraplabs/bloxstrap#3414]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

 Cant connect Roblox and Bloxstrap

**Comment by gamerloch10** [comment]
Update to 2.8.0 as older versions broke awhile back
