### ISSUE TITLE
[REQ] ai generator

### ISSUE THREAD

**Issue by gothprayer** [bloxstraplabs/bloxstrap#3419]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

make it happen

**Comment by NabHeyka22** [comment]
ai generator for what

**Comment by gothprayer** [comment]
what do you think you insectual aprecot

**Comment by bluepilledgreat** [comment]
Done. Will be out in v7.15.0.

**Comment by NabHeyka22** [comment]
> what do you think you insectual aprecot

i don't know you fucking idiot
you just put "ai generator" without specifying what the ai generator needs to be used for

**Comment by gothprayer** [comment]
are you stupid or just dense like really what is your purpose commenting on the fucking post if all you do is bitch like a retard who just got his dick cut off

**Comment by NabHeyka22** [comment]
yes i am stupid
now you can answer my fucking question

what do you need an ai generator for

**Comment by gamerloch10** [comment]
we can't read your mind lmao

**Comment by gothprayer** [comment]
ai generator for generating mutated artists such as but not limited to: Meek Mill, Justin Beiber, Taylor Swift, Kanye West, Liam Payne, Lil Mabu, Drake, P Diddy, etc.

you are all just stupid as fuck tbh i wish none of you existed you are waste of sperm and oxygen truthfully please find an effortless way to dispose of your shitty life like the retarded fucks you are

**Comment by gamerloch10** [comment]
are you in the wrong github

**Comment by bluepilledgreat** [comment]
> ai generator for generating mutated artists such as but not limited to: Meek Mill, Justin Beiber, Taylor Swift, Kanye West, Liam Payne, Lil Mabu, Drake, P Diddy, etc.
> 
> you are all just stupid as fuck tbh i wish none of you existed you are waste of sperm and oxygen truthfully please find an effortless way to dispose of your shitty life like the retarded fucks you are

Oh that's what you meant. This feature is scheduled for v9.60.2.

**Comment by NabHeyka22** [comment]
> ai generator for generating mutated artists such as but not limited to: Meek Mill, Justin Beiber, Taylor Swift, Kanye West, Liam Payne, Lil Mabu, Drake, P Diddy, etc.
> 
> you are all just stupid as fuck tbh i wish none of you existed you are waste of sperm and oxygen truthfully please find an effortless way to dispose of your shitty life like the retarded fucks you are

you say that we're stupid and retarted when you're literally fucking asking for a AI generator of mutated artists on a fucking roblox bootstrapper
like can you even read or use your brain or are you this stupid to not read

**Comment by gothprayer** [comment]
@gamerloch10 would i be making a feature request if i was in the wrong github? no right? so dont ask such ridiculous questions that serve literally no purpose other than fucking around and bullshitting

**Comment by gamerloch10** [comment]
no

**Comment by Wanwood1** [comment]
> @gamerloch10 would i be making a feature request if i was in the wrong github? no right? so dont ask such ridiculous questions that serve literally no purpose other than fucking around and bullshitting

can you guys block him so he doesnt make anymore useless requests

**Comment by gamerloch10** [comment]
> > @gamerloch10 would i be making a feature request if i was in the wrong github? no right? so dont ask such ridiculous questions that serve literally no purpose other than fucking around and bullshitting
> 
> can you guys block him so he doesnt make anymore useless requests? this is a very obvious ragebait and troll post lol, try harder chud, your not aryan

yeah I was guessing it was rage bait

**Comment by gamerloch10** [comment]
funny thing is I thought this was a legit post and they we're gonna ask if we could ai generate fflags lmao

**Comment by pizzaboxer** [comment]
when multako speaks yall gotta learn to stay quiet

**Comment by user1126s** [comment]
> > ai generator for generating mutated artists such as but not limited to: Meek Mill, Justin Beiber, Taylor Swift, Kanye West, Liam Payne, Lil Mabu, Drake, P Diddy, etc.
> > you are all just stupid as fuck tbh i wish none of you existed you are waste of sperm and oxygen truthfully please find an effortless way to dispose of your shitty life like the retarded fucks you are
> 
> Oh that's what you meant. This feature is scheduled for v9.60.2.

a bit of a mistake there, this is scheduled for release v42.0.69.
 The estimated date is sometime in november of the year 2420.

**Comment by user1126s** [comment]
> when multako speaks thats when yall gotta learn to stay quiet

- sun tzu - the art of war
