### ISSUE TITLE
[BUG] No menu buttons

### ISSUE THREAD

**Issue by normalgithubuser01** [bloxstraplabs/bloxstrap#3420]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

It seems like the new roblox UI made it impossible to go back to menu if using V1 only.
![Screenshot 2024-10-23 232837](https://github.com/user-attachments/assets/07e7130e-5d10-45e5-b0ba-77af5cb56282)
![Screenshot 2024-10-23 2328372](https://github.com/user-attachments/assets/7ca2e39a-f2b6-4d35-8d13-4a30327affd1)

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment]
{
  "FFlagFixReportButtonCutOff": "False",
"FFlagSettingsHubIndependentBackgroundVisibility": "False"
}

**Comment by NabHeyka22** [comment]
> { "FFlagFixReportButtonCutOff": "False", "FFlagSettingsHubIndependentBackgroundVisibility": "False" }

add these fflags

**Comment by normalgithubuser01** [comment]
thanks man :) appreciated it
