### ISSUE TITLE
[BUG] Bloxstrap will not launch

### ISSUE THREAD

**Issue by PitayaPapaya** [bloxstraplabs/bloxstrap#3421]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

Every time i launch bloxstrap i get this error, I have deleted this twice and redownloaded it both times still getting the message, I even downloaded an upgraded version and it still gives me the same error log.

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
```

**Comment by bluepilledgreat** [comment]
update
