### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZombifiedV2** [bloxstraplabs/bloxstrap#3424]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

everytime i launch roblox it installs a new update even though there hasnt been a new update

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Could you show a screen recording of the issue please?

**Comment by ZombifiedV2** [comment]
i reinstalled a couple of times and its working,crashes sometimes

**Comment by ZombifiedV2** [comment]
mark as resolved
