### ISSUE TITLE
[BUG] bloxstrap fflags potato graphics

### ISSUE THREAD

**Issue by BeltFrawx** [bloxstraplabs/bloxstrap#3430]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

new version

### What problem did you encounter?

Is there a fflags that can make my laptop faster or just make my graphics potato like smooth plastic, old lighting, old rendering mode and reduce effects?

### Bloxstrap Log

```text
fflags
```

**Comment by BunnyProPlayz** [comment]
Engine settings

**Comment by Oyasumii14** [comment]
Use Direct3D10 because its the most old usable API you can use on Bloxstrap, but there's vulkan and opengl which you can use via FFlags editor but it may be unstable 


Fyi use DX10 rather than Vulkan because their graphics is almost the same as DX11 but optimizd in some scnearios, also use your texture. Also disable textures, post processing effects and terrain textures and voxel on preferred lightning technology and texture quality to lowest in exchange of worst graphics and blurry ones for higher performance

**Comment by BeltFrawx** [comment]
> Engine settings

where

**Comment by BeltFrawx** [comment]
> Use Direct3D10 because its the most old usable API you can use on Bloxstrap, but there's vulkan and opengl which you can use via FFlags editor but it may be unstable
> 
> Fyi use DX10 rather than Vulkan because their graphics is almost the same as DX11 but optimizd in some scnearios, also use your texture. Also disable textures, post processing effects and terrain textures and voxel on preferred lightning technology and texture quality to lowest in exchange of worst graphics and blurry ones for higher performance

Ive done this in the old versions of roblox cause my laptop is to old and it cant even run 30fps without applying this settings, do you have a new fflags so I can reduce some effects and make the texture smooth plastic for my fps boost?

**Comment by BeltFrawx** [comment]
> > > Engine settings
> > 
> > 
> > where
> 
> What version are you on? The latest version should have an "Engine Settings" on the menu sidebar. If it's not present, please update.
> 
> Also don't open issues asking for fast flags. GitHub issues are meant for bug reports and support.

I can see it now. I tried to apply it but the textures and shadows are still there. My apologies for opening issue cause I'm new here and Im tryna solve this problem
