### ISSUE TITLE
[BUG] "DFIntDebugFRMQualityLevelOverride bugged or doesn't work anymore ?

### ISSUE THREAD

**Issue by amairisu** [bloxstraplabs/bloxstrap#3432]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.80

### What problem did you encounter?

Usually with fastflag "DFIntDebugFRMQualityLevelOverride": "1", i got low textures but with high render distance, but now the render distance are really close and sometimes blinked with full render to short render distance, Idk what's happening.

### Bloxstrap Log

```text
N/A
```

**Comment by amairisu** [comment]
![Uploading ragh.png…]()

**Comment by ElRaider** [comment]
I have the same issue

![ESE](https://github.com/user-attachments/assets/18bfbcdd-5bd5-4ab6-9a06-6d0c0bb5b49d)

**Comment by Seravilean** [comment]
Try reinstalling roblox, It fixed it for me

**Comment by finleey** [comment]
reinstalling roblox fixes it for my first session and then the problem returns on next launch

**Comment by bluepilledgreat** [comment]
roblox bug
