### ISSUE TITLE
[BUG] AC conflicting with basically everything on 26100.2033

### ISSUE THREAD

**Issue by only1mistakE** [bloxstraplabs/bloxstrap#3440]
-  [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.

### Bloxstrap Version

r2.8.0 stable / 2.7.0, 2.6.1 also has issues.

### What problem did you encounter?

Looking for a way to find out what process is hooking onto RobloxPlayerBeta.exe.
MSI Afterburner has been patched and is not conflicting with RobloxPlayerBeta.exe anymore in any way. Another process is.

Refer to #3120 for the situation.

**Comment by only1mistakE** [comment]
>  [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
>  [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
>  [x]  I am using the latest version of Bloxstrap.
> 
> ### Bloxstrap Version
> r2.8.0 / 2.7.0, 2.6.1 also has issues the same way.
> 
> ### What problem did you encounter?
> Looking for a way to find out what process is hooking onto RobloxPlayerBeta.exe. MSI Afterburner has been patched and is not conflicting with RobloxPlayerBeta.exe anymore in any way. Another process is.
> 
> Refer to #3120 for the situation.

**Comment by bluepilledgreat** [comment]
what are we meant to do about this?

**Comment by only1mistakE** [comment]
> what are we meant to do about this?

not 100% sure but it only happens with bloxstrap now... so that's an issue

**Comment by bluepilledgreat** [comment]
> > what are we meant to do about this?
> 
> not 100% sure but it only happens with bloxstrap now... so that's an issue

oh does this not occur with the regular roblox bootstrapper?

**Comment by only1mistakE** [comment]
> > > what are we meant to do about this?
> > 
> > 
> > not 100% sure but it only happens with bloxstrap now... so that's an issue
> 
> oh does this not occur with the regular roblox bootstrapper?

yeah
i did some testing both in safe mode n normal stuff i actually dont really know why this even happens
hyperion on this side is just going AHUIFHAIUCGHIAUGEUIAGIU or something's really going on

**Comment by only1mistakE** [comment]
> > > > what are we meant to do about this?
> > > 
> > > 
> > > not 100% sure but it only happens with bloxstrap now... so that's an issue
> > 
> > 
> > oh does this not occur with the regular roblox bootstrapper?
> 
> yeah i did some testing both in safe mode n normal stuff i actually dont really know why this even happens hyperion on this side is just going AHUIFHAIUCGHIAUGEUIAGIU or something's really going on

forgot to say i did do what roblox themselves told me to do back in #3120, worked temporarily until the last few days

**Comment by only1mistakE** [comment]
> > > > > what are we meant to do about this?
> > > > 
> > > > 
> > > > not 100% sure but it only happens with bloxstrap now... so that's an issue
> > > 
> > > 
> > > oh does this not occur with the regular roblox bootstrapper?
> > 
> > 
> > yeah i did some testing both in safe mode n normal stuff i actually dont really know why this even happens hyperion on this side is just going AHUIFHAIUCGHIAUGEUIAGIU or something's really going on
> 
> forgot to say i did do what roblox themselves told me to do back in #3120, worked temporarily until the last few days

NO THIS CANNOT BE NO WAY THIS IS JUST MCAFEE THIS WHOLE TIME HOLD UP

**Comment by user1126s** [comment]
> > > > > > what are we meant to do about this?
> > > > > 
> > > > > 
> > > > > not 100% sure but it only happens with bloxstrap now... so that's an issue
> > > > 
> > > > 
> > > > oh does this not occur with the regular roblox bootstrapper?
> > > 
> > > 
> > > yeah i did some testing both in safe mode n normal stuff i actually dont really know why this even happens hyperion on this side is just going AHUIFHAIUCGHIAUGEUIAGIU or something's really going on
> > 
> > 
> > forgot to say i did do what roblox themselves told me to do back in #3120, worked temporarily until the last few days
> 
> NO THIS CANNOT BE NO WAY THIS IS JUST MCAFEE THIS WHOLE TIME HOLD UP

Should have never trusted them. Windows security/defender is enough

**Comment by pizzaboxer** [comment]
lol

**Comment by only1mistakE** [comment]
> lol

big lol
