### ISSUE TITLE
[BUG] My graphic slider isn't working in on rendering the world fully/better any fixes?

### ISSUE THREAD

**Issue by Crazy83014** [bloxstraplabs/bloxstrap#3441]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2,8,0

### What problem did you encounter?

graphic slider not working as intended

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
This is a Roblox bug. There is nothing we can do about it.
