### ISSUE TITLE
[BUG] how do i fix pixelated images, not changing graphics to 3??

### ISSUE THREAD

**Issue by ihaterobloxbugs** [bloxstraplabs/bloxstrap#3450]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

i just can't look at these pixelated images

### Bloxstrap Log

```text
N/A
```

**Comment by ihaterobloxbugs** [comment]
[
![Снимок экрана 2024-10-24 204836](https://github.com/user-attachments/assets/839dc53c-6782-43be-9ab4-81886f525d13)
](url)

**Comment by ihaterobloxbugs** [comment]
and also there's non-loading textures

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 205012](https://github.com/user-attachments/assets/9a2918f6-9cda-4a31-ae9f-32ea46a5167f)

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 205216](https://github.com/user-attachments/assets/4bad61f2-f3f0-4239-9741-3d62125ff473)
WOW

**Comment by RyanLua** [comment]
How much memory does your device have? It looks like either an issue with your FFlags or with Roblox itself, not Bloxstrap. The pixelated textures are a sign of low memory.

**Comment by ihaterobloxbugs** [comment]
8192

**Comment by ihaterobloxbugs** [comment]
i just setted to standart, deleted all fflags and setted graphics to 2, msaa to 4x and remove shadows of players

**Comment by ihaterobloxbugs** [comment]
also if i switch my roblox graphics it won't work
it's all same

**Comment by RyanLua** [comment]
Do you have [reduced motion](https://devforum.roblox.com/t/introducing-accessibility-settings/2723187) enabled in the settings menu? The settings menu uses [CanvasGroup](https://create.roblox.com/docs/reference/engine/classes/CanvasGroup) when using reduced motion which causes a blurry image on lower settings or with limited memory.

> 8192

Assuming that's in MBs, that is ~8GB which should be enough but larger games can eat that up quickly. Do the pixelated images happen in all experiences? Try seeing if it happens if you are on an empty baseplate.

**Comment by ihaterobloxbugs** [comment]
no in total i have 8192 memory available

**Comment by ihaterobloxbugs** [comment]
lemme try to disable it

**Comment by RyanLua** [comment]
> 8192 memory

Can you provide a screenshot? I need a unit to work with. Likely you are referring to MBs.

**Comment by ihaterobloxbugs** [comment]
how do i check?
or how do i see where to screenshot

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 211835](https://github.com/user-attachments/assets/01e3f823-0b29-41f7-8566-4a5e04c83b3a)
i have 16 gb

**Comment by ihaterobloxbugs** [comment]
oh wait

**Comment by ihaterobloxbugs** [comment]
yup i have 16 gb, 8 gb  available.

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 212232](https://github.com/user-attachments/assets/647b7f18-ca44-4099-8ad4-e3ef18dafc92)

**Comment by RyanLua** [comment]
> yup i have 16 gb, 8 gb available.

That's more than enough than in most scenarios. You shouldn't be getting any texture issues related to memory.

* Have you tried disabling reduced motion yet and seeing any differences?
* Does this issue happen when you launch Roblox without Bloxstrap?

**Comment by ihaterobloxbugs** [comment]
it someone how just got fixed, but it had reduced motion disabled, and this issue kinda was happening when i started roblox with bloxstrap

**Comment by ihaterobloxbugs** [comment]
what if i change my graphics, but it stays the same, how do i fix it?

**Comment by ihaterobloxbugs** [comment]
why even i have fps 60-70 on roblox, when i have strong pc, and game is not really good at graphics

**Comment by ihaterobloxbugs** [comment]
can i make more performance???

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 212903](https://github.com/user-attachments/assets/e454f3a4-6ae3-45df-b905-44e963aaf5c4)

![Снимок экрана 2024-10-24 212910](https://github.com/user-attachments/assets/58506bb6-2dc7-4da0-9208-564660862d5d)
![Снимок экрана 2024-10-24 212915](https://github.com/user-attachments/assets/b8264d7b-e7dc-4039-b57f-a8eb5cf3f1c1)

**Comment by RyanLua** [comment]
> can i make more performance???

There are some FFlags that can be used to improve performance. Read "[A guide to FastFlags
](https://github.com/bloxstraplabs/bloxstrap/wiki/A-guide-to-FastFlags)" on a bit about FFlags and how to use them. You can find collections of performance FFlags online as well.

**Comment by ihaterobloxbugs** [comment]
Graphics: auto , rendering: auto, msaa: 4x, turn off shadows of players: on

**Comment by ihaterobloxbugs** [comment]
yo
![Uploading Снимок экрана 2024-10-24 213423.png…]()

i copied fflag and it tells me

**Comment by ihaterobloxbugs** [comment]
![Снимок экрана 2024-10-24 213423](https://github.com/user-attachments/assets/8763890b-9407-4258-b1ae-f14429a5f7ad)
![Снимок экрана 2024-10-24 213426](https://github.com/user-attachments/assets/85615386-323a-4528-93bb-9c23f163f856)

**Comment by pizzaboxer** [comment]
Set your texture quality to Level 3 (Highest)
