### ISSUE TITLE
[BUG] my esc menu disappeared

### ISSUE THREAD

**Issue by amongus40bozo** [bloxstraplabs/bloxstrap#3451]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

where is it
![no menu](https://github.com/user-attachments/assets/506f731c-26a5-4575-bee2-9ca55724a758)

### Bloxstrap Log

```text
N/A
```

**Comment by amongus40bozo** [comment]
ok i switched from 2015 to default and it fixed

**Comment by pizzaboxer** [comment]
Issue was also addressed on the Wiki but yes, we recommend you keep it set to default for now.
