### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by doutorbiscoit** [bloxstraplabs/bloxstrap#3458]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v1000

### What problem did you encounter?

nao ta entrando nos jogos do roblox

### Bloxstrap Log

```text
N/A nada
```

**Comment by regginator** [comment]
Incredible :fire:

**Comment by pizzaboxer** [comment]
Closing as invalid
