### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FamAlt** [bloxstraplabs/bloxstrap#3459]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

after opening roblox through bloxstrap, i cannot access the menu where i can change the client settings nor hide chat box

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Addressed in Wiki
