### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tw1stedXx** [bloxstraplabs/bloxstrap#3462]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

I changed my settings to display the old Hud in Roblox. After I clicked install it started to do the installation but then it gets stuck on “configuring Roblox” 

https://github.com/user-attachments/assets/85e240b7-f9c8-4455-be0c-9bc4c84993a6

### Bloxstrap Log

```text
N/A
```

**Comment by gamerloch10** [comment]
Update to 2.8.0

**Comment by moyaimoment** [comment]
Why are you recording with your phone when you have Medal?
but yeah update to 2.8.0

**Comment by user1126s** [comment]
bros 1 year behind. god the reason most of these problems are coming is because they get it from a website or a youtuber who gives the external link to old version

**Comment by Tw1stedXx** [comment]
> bros 1 year behind. god the reason most of these problems are coming is because they get it from a website or a youtuber who gives the external link to old version

I just got this pc. It’s my very first. Be kind.

**Comment by user1126s** [comment]
> > bros 1 year behind. god the reason most of these problems are coming is because they get it from a website or a youtuber who gives the external link to old version
> 
> I just got this pc. It’s my very first. Be kind.

i wasn't directing it towards you, instead to other people. Also, i very apolozise for my behaviour, i should have been more kind. thanks
