### ISSUE TITLE
[BUG] 2015 (V1) escape menu version hides all topbar buttons and disables the escape menu

### ISSUE THREAD

**Issue by TheDoctor1977** [bloxstraplabs/bloxstrap#3463]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

i cannot access the escape menu with any shortcuts
this consistently reoccurs on all games, disregarding the type of chatbox or any custom GUI elements
this image taken in https://www.roblox.com/games/15687212155/Airplane-Factory-Simulator
![image](https://github.com/user-attachments/assets/227558ea-4dec-4355-b427-f3386bf69428) 
this image taken in https://www.roblox.com/games/3226555017/SCP-Site-Roleplay
![image](https://github.com/user-attachments/assets/e4f5ecf5-6254-4c2b-a1b2-00d74ae75957)

### Bloxstrap Log

```text
N/A
```

**Comment by Averagerobloxenjoyer709** [comment]
I have the same issue

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/V1-escape-menu-doesn't-work-properly
