### ISSUE TITLE
[BUG] There is no menu button on the screen

### ISSUE THREAD

**Issue by Averagerobloxenjoyer709** [bloxstraplabs/bloxstrap#3465]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8

### What problem did you encounter?

https://github.com/user-attachments/assets/f591f324-7235-47f1-b4ef-65776f59a820

### Bloxstrap Log

```text
N/A
```

**Comment by wavypurples** [comment]
Same problem, anyone know how to fix it?

**Comment by Piro-arts** [comment]
same problem 3rd time re-installing

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/V1-escape-menu-doesn't-work-properly

I recommend you don't use the option for the time being
