### ISSUE TITLE
[REQ] Give an option for going to the wiki when roblox crashes or doesnt open.

### ISSUE THREAD

**Issue by TechnicallyMC** [bloxstraplabs/bloxstrap#3466]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

add an extra button thats close without going to the wiki, im sick of it.

**Comment by TechnicallyMC** [comment]
also is there a reason im getting this error, but then roblox is still opening?

**Comment by MrT-tak** [comment]
> also is there a reason im getting this error, but then roblox is still opening?

#3176 ?

**Comment by TwangyMoney** [comment]
> also is there a reason im getting this error, but then roblox is still opening?

It's cause bloxstrap is checking for the roblox process making a log file, they thought making the delay for the check to be 5 seconds would be a good idea.
If the bloxstrap team is seeing this, it would make the community more happy if you also take into contact the laggier users or hire laggy testers so the program can be tested on a laggy device as well.

**Comment by MrT-tak** [comment]
Agreed

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
