### ISSUE TITLE
[BUG] issue resolved 

### ISSUE THREAD

**Issue by alzurz** [bloxstraplabs/bloxstrap#3468]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/c17c9ea6-d46d-4386-8328-faf6d1d0196d)

![image_2024-10-25_214402724](https://github.com/user-attachments/assets/f2a9ad17-8b3a-4af2-8d6f-5c421d8c5caf)

So, after I deleted one of the older versions of Bloxstrap without disabling this setting (maybe 2.7.0?) it won't let me disable it. I don't know how to fix it 

### Bloxstrap Log

```text
N/A
```

**Comment by user1126s** [comment]
try going to the mods folder by typing  %AppData% in the explorer bar and then clicking enter then in that tap click appdata then Local then Bloxstrap then modifications then ExtraContent then places and deleting the mobile.rbxl file

**Comment by alzurz** [comment]
> try going to the mods folder by typing %AppData% in the explorer bar and then clicking enter then in that tap click appdata then Local then Bloxstrap then modifications then ExtraContent then places and deleting the mobile.rbxl file

theres no mobile.rbxl file? am i doing something wrong

**Comment by alzurz** [comment]
> > try going to the mods folder by typing %AppData% in the explorer bar and then clicking enter then in that tap click appdata then Local then Bloxstrap then modifications then ExtraContent then places and deleting the mobile.rbxl file
> 
> theres no mobile.rbxl file? am i doing something wrong

nvm
