### ISSUE TITLE
[BUG] using 0 fps for roblox fps unlocker doesnt work

### ISSUE THREAD

**Issue by NoobLikesThis** [bloxstraplabs/bloxstrap#3469]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

When you use 0 for roblox's fps unlocker, it doesnt work, although I know a solution, some people wont.
I use windows 11.
fflag for roblox's fps unlocker:
{
    "FFlagGameBasicSettingsFramerateCap5": "True",
    "DFIntTaskSchedulerTargetFps": "0"
}
additional fflags:
{
    "FFlagTaskSchedulerLimitTargetFpsTo2402": "False",
}

**Comment by Wanwood1** [comment]
lol

**Comment by NoobLikesThis** [comment]
> why are you trying to set an fps cap of 0

yes
