### ISSUE TITLE
[BUG] always updating roblox on startup despite already updated

### ISSUE THREAD

**Issue by JerryLinLOL** [bloxstraplabs/bloxstrap#3473]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/b5a1154b-5138-4873-ab95-06e0ddcbe27b)
Everytime no matter when its already updated or not today, it always updates on startup.
auto update is off and it still does this.

### Bloxstrap Log

```text
N/A
```

**Comment by panoslagos** [comment]
same here, really need a fix

**Comment by pizzaboxer** [comment]
>  auto update is off and it still does this.

That's for auto updating Bloxstrap. Not Roblox.

Can you open go to Bloxstrap's logs folder at `%localappdata%\Bloxstrap\Logs`, create a zip archive of all the log files, upload it somewhere, and send a link to it here?

**Comment by JerryLinLOL** [comment]
https://www.mediafire.com/file/hnqmva38fnxorvm/Logs.zip/file

**Comment by JerryLinLOL** [comment]
ok now today it doesnt for some reason- this is really weird

**Comment by pizzaboxer** [comment]
You didn't have a single successful launch on the day you reported this issue. Are you aware of that?
