### ISSUE TITLE
can't launch roblox

### ISSUE THREAD

**Issue by GustMatos** [bloxstraplabs/bloxstrap#3474]
[Bloxstrap_20241025T192936Z.log](https://github.com/user-attachments/files/17526787/Bloxstrap_20241025T192936Z.log)

whenever i try launching roblox from bloxstrap it says that the file 34b53a6e6c2540f8699e50ac9f2cfed6 from the bloxstrap downloads folder might be a virus or malware, when i go check the folder that file doesn't exist

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Malware-detected-when-trying-to-upgrade-Roblox
