### ISSUE TITLE
[BUG] Internet connection error

### ISSUE THREAD

**Issue by Brasileirojveb** [bloxstraplabs/bloxstrap#3476]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Everytime i try to join a game for the First time after i turn on the Pc ir after some time It gives me the internet connection error, but when i try again It Works, but i have to do this every time. Also my ping sometimes keeps spiking, this only happens on bloxstrap, already reinstalled and Its the same thing, It only started happening after 2.8.0, already did everything to try to fix It so the only thing It could be is bloxstrap

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Brasileirojveb** [comment]
[Settings.json](https://github.com/user-attachments/files/17528266/Settings.json)
[State.json](https://github.com/user-attachments/files/17528267/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/17528269/ClientAppSettings.json)

**Comment by Brasileirojveb** [comment]
> Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

Is it a problem with my settings?

**Comment by pizzaboxer** [comment]
All seems fine. Could be an antivirus issue? See if whitelisting it affects anything.

**Comment by Brasileirojveb** [comment]
> All seems fine. Could be an antivirus issue? See if whitelisting it affects anything.

I already whitelisted both roblox and bloxstrap on the firewall and it still happends, i even installed windows again yesterday (it was for something else) but its still happening sometimes.

**Comment by pizzaboxer** [comment]
Massive stab in the dark here, can you try disabling the "Allow Bloxstrap to manage Fast Flags" option, and also disable the activity tracker?

**Comment by Brasileirojveb** [comment]
> Massive stab in the dark here, can you try disabling the "Allow Bloxstrap to manage Fast Flags" option, and also disable the activity tracker?

Ok i will try It when i get home

**Comment by Brasileirojveb** [comment]
> Massive stab in the dark here, can you try disabling the "Allow Bloxstrap to manage Fast Flags" option, and also disable the activity tracker?

Yo it actually worked

**Comment by Brasileirojveb** [comment]
I tested it and its not the activity tracker its the fast flags

**Comment by pizzaboxer** [comment]
Try setting your framerate limit to zero

**Comment by Brasileirojveb** [comment]
> Try setting your framerate limit to zero

Didnt work
