### ISSUE TITLE
[BUG] Infinite configuration time during BloxStrap installation

### ISSUE THREAD

**Issue by pedroBVrandow** [bloxstraplabs/bloxstrap#3484]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

I am experiencing an issue with the **Bloxstrap** application, where the installation gets **stuck** on an **infinite loading** screen. Right after starting the installer, the **process does not progress** and remains in a **loading loop**, without showing any **error messages or signs of advancement**. This makes it **impossible** to complete the installation and use it, as it remains **stuck** in this **loading state**.

![Captura de tela 2024-10-26 072554](https://github.com/user-attachments/assets/4a44c288-596e-474e-93fd-23e5dbe5a4e5)
**_(Image Translated with Google Translate)_**

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
