### ISSUE TITLE
[BUG] It just stays on the "configuring roblox" screen

### ISSUE THREAD

**Issue by Zurilo7812** [bloxstraplabs/bloxstrap#3487]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

Every time I try to run bloxtrap it just keeps loading on the screen that says "configuring roblox" and it doesn't run, I don't know if it's a bug or if my PC isn't compatible but I can't run bloxtrap
![imagem_2024-10-26_132404341](https://github.com/user-attachments/assets/28e797d5-b6a8-44ac-9312-84bad9f3e455)
and normal roblox opens normally

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
Update.
https://bloxstraplabs.com
