### ISSUE TITLE
[BUG] the chat and the menu eliminated!

### ISSUE THREAD

**Issue by forzanapoli90** [bloxstraplabs/bloxstrap#3488]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

ok so when i join a game the v2015 menu dont show up 
![e](https://github.com/user-attachments/assets/f2f11af4-b70d-4285-8759-257de6a18c29)
is there a fix or is it going to come back again??
i love that menu :(

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/V1-escape-menu-doesn't-work-properly

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
