### ISSUE TITLE
[BUG] Blurry Textures despite setting the quality to the highest

### ISSUE THREAD

**Issue by syouj1** [bloxstraplabs/bloxstrap#3493]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

I've noticed that I sometimes receive blurry textures in games even though I have already set the texture quality to the highest possible in Bloxstrap. I don't often see it happen all the textures, it mostly just happens on things like the emote wheel in the screenshot where it displays your character but I did notice it happen to other player's clothing. Sometimes the blurry textures appear for a second and go back to normal and sometimes it just stays that way.
![Screenshot (1109)](https://github.com/user-attachments/assets/869a7018-925c-4132-b9da-1230995786a1)
![Screenshot (1110)](https://github.com/user-attachments/assets/fbdf191f-b2de-4ff1-bd39-bbe32a245f52)

![Screenshot (1108)](https://github.com/user-attachments/assets/7dca3d05-adab-4d55-be9c-c00a67465da4)
![Screenshot (1107)](https://github.com/user-attachments/assets/fe147d52-4496-4a7e-b7cb-efded331555b)

### Bloxstrap Log

```text
N/A
```

**Comment by Spoonus** [comment]
i know this is 3 days old but
this is an issue with roblox, if you're running out of ram roblox begins messing with the textures and making them blurry and pixelated

**Comment by pizzaboxer** [comment]
If it's happening even when you're set to the highest texture quality for sure, then this is out of our scope. Does this happen with the original bootstrapper? Are other engine settings applying?

**Comment by syouj1** [comment]
I have pretty much tried every method available. I have tried to play with and without Bloxstrap and the issue still shows up. I also tried using "DFFlagDisableDPIScale" "DFFlagTextureQualityOverrideEnabled" "DFIntTextureQualityOverride" in the fast flags editor but still the same results. I haven't had any problems with any settings but I will still always get the blurry textures

**Comment by pizzaboxer** [comment]
> I have tried to play with and without Bloxstrap and the issue still shows up

Yeah, not our issue then.
