### ISSUE TITLE
[BUG] I can't launch roblox its crashes

### ISSUE THREAD

**Issue by Unknown-source-error** [bloxstraplabs/bloxstrap#3495]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

When im launching roblox it crashes

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Read https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch then come back if you're still facing problems

**Comment by nope312** [comment]
doesnt crash with roblox launcher but crashes with bloxstrap launcher
