### ISSUE TITLE
Please add an option to disable the auto redirecting to the "Roblox crashes or Doesn't launch" link.

### ISSUE THREAD

**Issue by NarCodingLUA** [bloxstraplabs/bloxstrap#3498]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

[Roblox crashes or does not launch](https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

Because I am using a modified Windows, it always gives me the error and sometimes doesn't open Roblox or just opens it while the error is still running. Add an option to disable the auto redirecting to the [github](https://github.com/bloxstraplabs/bloxstrap/wiki/Roblox-crashes-or-does-not-launch), it affects my low-end PC. Before the Bloxstrap's update was forced my Roblox was working PERFECTLY fine and no issues or errors whatsoever.

### Bloxstrap Log

```text
N/A
```

**Comment by PhoenixCCZ** [comment]
Same issue, I hope they respond 😔

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
