### ISSUE TITLE
No dropdown GUI

### ISSUE THREAD

**Issue by bobmanwoah** [bloxstraplabs/bloxstrap#3499]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

There is absolutely no dropdown menu for any roblox games, please fix it

### Bloxstrap Log

```text
N/A
```

**Comment by moosetwin0** [comment]
Also having this issue.

**Comment by moosetwin0** [comment]
I was able to work around this issue by switching `Engine Settings - Preferred escape menu version` from `Default` to `2023 (V4)`, though this should still be fixed.

**Comment by Buggyboi01** [comment]
After having a quick look myself, using `2020 (V2)`, `2023 (V4)`, and `2023 (V4 + New UI)` all work. Having it set to `Default` or `2015 (V1)` doesn't come up with any roblox UI.

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
