### ISSUE TITLE
[BUG] my game automatically puts the lighting on voxel but I have it on future

### ISSUE THREAD

**Issue by jcloser3** [bloxstraplabs/bloxstrap#3508]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

it just puts the lighting on voxel :(

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
This happens because your computer is considered incapable of handling Future lighting by the Roblox engine. The only fix is to get a better computer. lol.
