### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mace12409** [bloxstraplabs/bloxstrap#3509]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.9

### What problem did you encounter?

![Screenshot 2024-10-27 213432](https://github.com/user-attachments/assets/c326a11f-71c1-4e14-a206-f53de8233073)
So basicly it is js crashing on me.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Duplicate issue, this is fixed in the upcoming Bloxstrap release.
