### ISSUE TITLE
[BUG] my vc goes on but it doesnt detect my mic at all.

### ISSUE THREAD

**Issue by killalltwinks** [bloxstraplabs/bloxstrap#3511]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

When I turn on my vc it completely shows that it is on but it does not detect my voice at all, I tried switching the input and output devices but nothing works and i redownloaded latest version to see but it still wasnt detecting it but when i speak it works on discord.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Does this happen with the stock Roblox bootstrapper?

**Comment by Spoonus** [comment]
gonna chime in here
this isn't a bug with bloxstrap, this is just a general roblox bug, i had it a year ago  when i didn't use bloxstrap.
just give roblox time to fix it,

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
