### ISSUE TITLE
[BUG] V1 Menu Not Transparent After Applying Suggested Flag Fix

### ISSUE THREAD

**Issue by ProjectBuddle** [bloxstraplabs/bloxstrap#3514]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

After applying the fix suggested in github to the V1 menu not working, it being:

{
    "FFlagFixReportButtonCutOff": "False",
    "FFlagSettingsHubIndependentBackgroundVisibility": "False"
}

The V1 menu does appear and function, however a majority of the background is completely black where it should be transparent.
![image](https://github.com/user-attachments/assets/936049db-64f3-449f-ba8d-4bd3cf5734ba)

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
![image](https://github.com/user-attachments/assets/c4f536c0-a138-4ea3-9887-2d20cd699db5)
Completely decreasing this option will fix your issue.
