### ISSUE TITLE
[BUG] Cant download bloxstap

### ISSUE THREAD

**Issue by sprogg28** [bloxstraplabs/bloxstrap#3519]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

N/A

### What problem did you encounter?

Cant download the bloxstrap Im having problems getting bloxstrap it says i need to "install .NET desktop Runtime to run this application" If someone can help me i would really love the help

### Bloxstrap Log

```text
N/A
```

**Comment by sprogg28** [comment]
![Screenshot 2024-10-28 155443](https://github.com/user-attachments/assets/abded062-6d6f-4e1e-9c5b-55785bab76e4)

**Comment by internetzx** [comment]
install it dumahh

**Comment by Wanwood1** [comment]
Install it you autistic monkey
