### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by luxz0731** [bloxstraplabs/bloxstrap#3524]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Bloxstrap Exception 29_10_2024 14_48_19](https://github.com/user-attachments/assets/6900443e-ac27-40cc-98a2-fa4534888e3d)

### Bloxstrap Log

```text
pls im really want use bloxtrap
```

**Comment by luxz0731** [comment]
plsss

**Comment by theletron** [comment]
Update.
bloxstraplabs.com

**Comment by Wanwood1** [comment]
Update your bloxstrap to the latest version
