### ISSUE TITLE
[BUG] the menu isnt working and please fix it :\

### ISSUE THREAD

**Issue by cringley2044w** [bloxstraplabs/bloxstrap#3527]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

the menu isnt working
please fix it i rlly need the old menu

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
This isnt a bloxstrap issue, were not roblox devs and we cant fix it, using the flags below should fix it.
{
  "FFlagFixReportButtonCutOff": "False",
  "FFlagSettingsHubIndependentBackgroundVisibility": "False"
}

**Comment by cringley2044w** [comment]
ty
