### ISSUE TITLE
[BUG] the alt +enter version of full screen is not working?

### ISSUE THREAD

**Issue by lizard-3** [bloxstraplabs/bloxstrap#3529]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

whenever i do alt+enter it goes in fullscreen, but after using bloxstrap for a while i realized if you press the windows key during BS fullscreen it wont work and you need to get out of it first. So what im getting at is that now whenever i enter BS fullscreen i don get the fps boost when i press the windows key the windows menu pops up and generally speaking it just feels like normal fullscreen.

im not 100% sure this is a bug or even an error it could be my fault because i recently reinstalled bloxstrap, but i felt like this would be worth pointing out

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1
