### ISSUE TITLE
[BUG] "Failed to authenticate" message

### ISSUE THREAD

**Issue by 1Bottle2Jars** [bloxstraplabs/bloxstrap#3530]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/3f880928-6ddd-4b90-a7c2-e4ba183fa46b)
Wanted to play roblox today and this just popped up.

### Bloxstrap Log

```text
N/A
```

**Comment by oteue** [comment]
same problem ha

**Comment by 1Bottle2Jars** [comment]
amazing, did you find a fix yet? Tried uninstalling and reïnstalling, forced reïnstallation and task manager didn't help me much either.

**Comment by PikachuWolverine** [comment]
Roblox is down just wait for it to come back up

**Comment by 1Bottle2Jars** [comment]
That explains a lot, thanks!
