### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cryo-Byte** [bloxstraplabs/bloxstrap#3543]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Happened Randomly after Joining a game (Worked fine minutes before)

System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

[Bloxstrap_20240920T221830Z.log](https://github.com/user-attachments/files/17563554/Bloxstrap_20240920T221830Z.log)
(I do Apologize if I'm wasting your time)

**Comment by Mikethemonkey08** [comment]
roblox-player:1+launchmode:app+channel:production // paste this into ur brower it fixes bloxstrap
