### ISSUE TITLE
[BUG] "content-platform-dictionaries.zip" appears whenever Bloxstrap is started

### ISSUE THREAD

**Issue by MendanSmiles** [bloxstraplabs/bloxstrap#3544]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Whenever I try and open Roblox, an error message appears saying "content-platform-dictionaries.zip" appears and I can't open Roblox.

**Comment by Mikethemonkey08** [comment]
it everywhere dawg im getting it to.

**Comment by Mikethemonkey08** [comment]
![BloxstrapDown](https://github.com/user-attachments/assets/b18d743a-2519-4153-a1c3-c8eb5a3ff5c6)

**Comment by DerpyDerp80** [comment]
same, encountered it just now

**Comment by Mikethemonkey08** [comment]
roblox-player:1+launchmode:app+channel:production // paste this into ur brower it fixes bloxstrap

> same, encountered it just now

**Comment by MendanSmiles** [comment]
@Mikethemonkey08 Thanks!

**Comment by Mikethemonkey08** [comment]
@MendanSmiles NP!

**Comment by EEEEEE22234** [comment]
Im trying to reinstall it and it wont work
