### ISSUE TITLE
[BUG] Classic Bloxstrap Logo toggle does not exist despite being mentioned in release notes

### ISSUE THREAD

**Issue by RickGotTaken** [bloxstraplabs/bloxstrap#3545]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

As shown in the image attached below, the setting does not exist in the location specified, nor anywhere else.
![image](https://github.com/user-attachments/assets/3512b747-34ac-4534-ac7c-3d553edf00f6)

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
its in the appearance tab

**Comment by RickGotTaken** [comment]
> its in the appearance tab

It is not in the Appearance tab.
![image](https://github.com/user-attachments/assets/be59e780-52c9-48f7-b869-af55a07096b4)

It is also not in the dropdown menu in the Appearance tab.
![image](https://github.com/user-attachments/assets/64bc2f06-787d-4d06-91ec-0541305f0a7d)

**Comment by RickGotTaken** [comment]
> It is not in the Appearance tab. ![image](https://private-user-images.githubusercontent.com/96528846/381329801-be59e780-52c9-48f7-b869-af55a07096b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNDI5MjksIm5iZiI6MTczMDI0MjYyOSwicGF0aCI6Ii85NjUyODg0Ni8zODEzMjk4MDEtYmU1OWU3ODAtNTJjOS00OGY3LWI4NjktYWY1NWEwNzA5NmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDIyNTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZWQ5ZDk1OGU4NjBkYzVhNWJlMWNhZDc2YzQ1OTk2MTdjOTAzZTY4YzIwYzQ0MWNlNjIzN2UwOWU2Nzk5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7G5Q9-J0_oj1FLM41sCqS7SQgAO1LKdbPrklU5mnPYQ)

It actually is, however this does not change the icon in the top left, only the icon that appears for a short amount of time when starting/updating Roblox/Bloxstrap. Changing that setting to have the old icon was already possible through the "Custom" option, I would not have suggested #3162 if it was that simple. My suggestion was for the icon in the top left to be modifiable.

**Comment by pizzaboxer** [comment]
> My suggestion was for the icon in the top left to be modifiable.

it's not - this is all that we could do
