### ISSUE TITLE
Preferred escape menu is gone

### ISSUE THREAD

**Issue by Boobaart** [bloxstraplabs/bloxstrap#3547]
The "preferred escape menu" options in Engine Settings is seemingly gone and now I can't use the old chat UI which bothers me because I dislike the new one. 
Old:
![RobloxScreenShot20241028_202126090](https://github.com/user-attachments/assets/b877dded-f17c-4ecf-a102-a56b2ba21b49)
New: (bad)
![image](https://github.com/user-attachments/assets/c5b3720b-da0f-4d72-9bbe-72f3585e870b)

**Comment by ReinoScreech** [comment]
The setting was removed (possibly temporarily) due to it going unstable from Roblox updates and changes. You can learn more about this through the [update logs](https://github.com/bloxstraplabs/bloxstrap/wiki/Release-notes-for-Bloxstrap-v2.8.1#removals).

**Comment by Boobaart** [comment]
Thank you so much! I didn't  see the update logs so I thought it was a bug
