### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by w9ac** [bloxstraplabs/bloxstrap#3549]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

![Screenshot 2024-10-30 031015](https://github.com/user-attachments/assets/24949bf1-499d-4cb4-bc49-e3a665fa1a4b)

### Bloxstrap Log

```text
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by moosetwin0** [comment]
Try updating to v1.8.1, there's another `key not present` issue that was fixed, this might be related.
