### ISSUE TITLE
[BUG] Outdated wiki page

### ISSUE THREAD

**Issue by moosetwin0** [bloxstraplabs/bloxstrap#3550]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

N/A

### What problem did you encounter?

[This page](https://github.com/bloxstraplabs/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap) assumes the Play Roblox feature, which was removed in v2.8.0.

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Thanks, didn't realize that.
