### ISSUE TITLE
[BUG] Top right circle menu instead of square menu escape menu

### ISSUE THREAD

**Issue by Sunivana** [bloxstraplabs/bloxstrap#3552]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

How can i change the top right circle menu into the old square menu? 

![Screenshot 2024-10-29 210150](https://github.com/user-attachments/assets/df4df577-782a-4cdc-960f-25ea85a6ddd7)

**Comment by Spoonus** [comment]
the escape menu option was removed in 2.8.1
you'll just have to wait until they find a way to put it back without it being an unstable mess

**Comment by Sunivana** [comment]
wasnt there a fflag that overwrote it? I know i had one but it got removed

**Comment by Sunivana** [comment]
it was something that contained chrometest4 or something like that

**Comment by its-mrarsikk** [comment]
I am very infuriated by this change. I understand that the feature is very unstable, but it's basically the reason I'm using Bloxstrap at all. It'd be best for everyone if you kept the setting, but put some warning on it, so that we could keep using it, even if at our own risk. For now, I'll stick with 2.8.0.

**Comment by pizzaboxer** [comment]
> It'd be best for everyone if you kept the setting, but put some warning on it, so that we could keep using it, even if at our own risk.

We value stability over confusion and inconsistency. Warnings will hardly affect anything.
