### ISSUE TITLE
[REQ] re add the pick which esc menu  do u want 2 use

### ISSUE THREAD

**Issue by flamingolxix** [bloxstraplabs/bloxstrap#3553]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

re add the esc menu optin like 2015 2020 2023 why did u  remove them why

**Comment by ReinoScreech** [comment]
The preset was removed (possibly temporarily) due to the fastflags becoming unstable from Roblox updates / changes.

**Comment by pizzaboxer** [comment]
i wrote a whole paragraph in the 2.8.1 release notes explaining why
