### ISSUE TITLE
banned on the discord for "cheating"

### ISSUE THREAD

**Issue by lookinlikepaper** [bloxstraplabs/bloxstrap#3554]
i sent my list of fflags that i got off a discord server that said i would get less ping, i dont want to get banned on roblox for a fflag I did not know was not allowed. i need help finding what fflag it was so i can remove it

[Telemetry-FFlags.txt](https://github.com/user-attachments/files/17565374/Telemetry-FFlags.txt)

**Comment by pizzaboxer** [comment]
> i sent my list of fflags that i got off a discord server that said i would get less ping

We tell you to not import big lists that other people create. I recommend you remove all of them.
