### ISSUE TITLE
[BUG] Framerate limit just won't work at all above 240 FPS. 

### ISSUE THREAD

**Issue by Eware-0** [bloxstraplabs/bloxstrap#3557]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

[BUG] Framerate limit just won't work at all above 240 FPS. The cap in the game still exists

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Addressed in the Wiki
