### ISSUE TITLE
[BUG] There is no button to change the interface in roblox, please fix it

### ISSUE THREAD

**Issue by plshelpbloxstrap** [bloxstraplabs/bloxstrap#3558]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

There is no button to change the interface in roblox, please fix it

### Bloxstrap Log

```text
N/A
```

**Comment by paperboi31** [comment]
they removed it for now because it was unstable to support, at a later date maybe it will be added again.

**Comment by HarryBlueJay** [comment]
it is REMOVED but the v4 menu (minus chrome) still works, soo
just add this:
{
    "FFlagEnableMenuControlsABTest":false,
    "FFlagEnableV3MenuABTest3":false,
    "FFlagEnableInGameMenuChromeABTest3":false,
    "FFlagEnableInGameMenuChromeABTest4":false,
    "FFlagEnableInGameMenuControls":true,
    "FFlagEnableInGameMenuModernization":true,
    "FFlagEnableInGameMenuChrome":false
}

**Comment by ThatGreenBlur** [comment]
"The engine setting preset for the Roblox escape menu version has been removed. It's become increasingly unstable overtime as Roblox continues to make breaking changes to how it works. It may be readded at a later date when we can support it properly."
