### ISSUE TITLE
[old bloxstrap] 

### ISSUE THREAD

**Issue by MaskBlue23** [bloxstraplabs/bloxstrap#3560]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would like to suggest bringing back the old Bloxstrap because Roblox is lagging for me. I’ve tried various solutions, including many tutorials on YouTube, but nothing has helped. My current operating system is Windows 10, while the old one was Windows 11, which worked well. After switching to Windows 10 and trying to play Roblox with FPS Boost, I noticed no improvements. I recommend either making a better version of Bloxstrap or reverting to the original.

**Comment by ThatGreenBlur** [comment]
this is a roblox issue and not a bloxstrap issue!! roblox only became laggy after the fps unlock update.

**Comment by bluepilledgreat** [comment]
old bloxstrap wont help with your fps lol get a better computer
