### ISSUE TITLE
[BUG] in bloxtrab there isn't anymore the menu option in fast flags!!

### ISSUE THREAD

**Issue by forzanapoli90** [bloxstraplabs/bloxstrap#3562]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

AAAAA WTH WHY WOLUD THEY DO THIS :(
![AAAAAAAAAA](https://github.com/user-attachments/assets/6c2aaec3-8231-48f1-b240-f6661c6d9428)

### Bloxstrap Log

```text
N/A
```

**Comment by FloppaDelicious** [comment]
they removed it cause it was unstable, possibly in the future it will be brung back when its gonna be stable
