### ISSUE TITLE
[REQ] Logitech G HUB detection

### ISSUE THREAD

**Issue by Kamireq** [bloxstraplabs/bloxstrap#3565]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Make it so Logitech G HUB(App for Logitech peripherals) can detect bloxstrap. right now it doesn't detect roblox if I use bloxstrap at all so If I want to change my binds I have to change my G HUB profile manually.

**Comment by pizzaboxer** [comment]
Not our responsiblity. Add it as an application manually (be sure you add RobloxPlayerBeta.exe as it's in Bloxstrap's installation folder).
