### ISSUE TITLE
[RESOLVED] [BUG] System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\Quixaq\AppData\Local\Bloxstrap\Downloads\f806bdcfd32ec64de061292e1d02f151'

### ISSUE THREAD

**Issue by quixaq** [bloxstraplabs/bloxstrap#3566]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

roblox was upgrading and it throwed the error and microsoft defender said this
![image](https://github.com/user-attachments/assets/ba129111-cc7c-4c5f-b197-2be17924a7d0)

### Bloxstrap Log

```text
N/A
```

**Comment by Roblox-Thot** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Malware-detected-when-trying-to-upgrade-Roblox

**Comment by quixaq** [comment]
alright ty
