### ISSUE TITLE
[BUG] Upgrading Roblox Everytime you Change Account

### ISSUE THREAD

**Issue by Brasileirojveb** [bloxstraplabs/bloxstrap#3574]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

So, i just downloaded 2.8.1 and i was playing some games on my main, but i decided to switch to my alt to play another game that i had more stuff there, but then when i joined it, roblox said it was updating, i didnt mind but after i got back to my main it did the same thing, i tried without changing accounts and it worked normally, but when i got back into my alt it updated again. This actually happened to be some time back then when there was a multiple roblox-instance option i dont remember the name, but its removed now and it got fixed, but now it came back but without that option beeing on.

### Bloxstrap Log

```text
N/A
```

**Comment by nakoyasha** [comment]
This kinda sounds like the two accounts are on separate build channels? Check by logging into each account and then going to [this endpoint](https://clientsettings.roblox.com/v2/user-channel)

**Comment by pizzaboxer** [comment]
Not a Bloxstrap bug. That's just how Roblox behaves.
