### ISSUE TITLE
help please?

### ISSUE THREAD

**Issue by imreallybadlol** [bloxstraplabs/bloxstrap#3578]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

bloxstrap is not downloading

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by pizzaboxer** [comment]
You're not using 2.8.1. Go upgrade.
