### ISSUE TITLE
[REQ] The Good GUI

### ISSUE THREAD

**Issue by RedactedO5-13** [bloxstraplabs/bloxstrap#3582]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would greatly appreciate it if we had the option to get our glorious 2023 GUI back, i currently cannot play roblox in fear of vomiting due to the chrome GUI

If we cannot get it, can we at least get the ability to get old versions of Bloxstrap or the FastFlags necessary to get that GUI back (I do not know much about fast flags, or coding in general)

**Comment by ReinoScreech** [comment]
Since stability is a top priority, it'll be unlikely for the preset to return.
There are a few fastflags you can disable through engine settings, but don't be surprised when they stop working from Roblox updates.
```{
"FFlagEnableInGameMenuControls": "False",
 "FFlagDisableNewIGMinDUA": "True",
"FFlagEnableInGameMenuChromeABTest4": "False",
}
```

**Comment by pizzaboxer** [comment]
I don't see how this at all addresses my concern with the option's removal
