### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'E:\Bloxstrap\Roblox\Player\content\textures\ui\traildot.png' is denied.

### ISSUE THREAD

**Issue by widraGITHUB** [bloxstraplabs/bloxstrap#3588]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

i was opening bloxstrap to play as i often do then it showed me an exception 
![image](https://github.com/user-attachments/assets/4718bc37-ebc1-45d3-a66a-ce127046526a)

### Bloxstrap Log

```text
[Bloxstrap_20241031T105557Z.log](https://github.com/user-attachments/files/17586712/Bloxstrap_20241031T105557Z.log)
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
