### ISSUE TITLE
[BUG] Appearance>Bootstrapper>Style seems to do nothing

### ISSUE THREAD

**Issue by 360gamerxbox** [bloxstraplabs/bloxstrap#3595]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

when i change the aforementioned setting it does not seem to affect anything, neither bootstrap or roblox, even if i set it to a non vista/legacy setting
![Capture d'écran 2024-10-31 154038](https://github.com/user-attachments/assets/10e44650-f759-4d50-965d-2b85398536fb)
![Capture d'écran 2024-10-31 154106](https://github.com/user-attachments/assets/c4f7791c-d83f-41bb-a688-02e8d6f014f1)
i have added the screenshots though i dont think they add much ressources.

### Bloxstrap Log

```text
N/A
```

**Comment by goldenskull1023** [comment]
How did you fix this?
