### ISSUE TITLE
[BUG] System.AggregateException

### ISSUE THREAD

**Issue by https-dre** [bloxstraplabs/bloxstrap#3600]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

Durante a instalação do Blox Trap ocorreu um erro

![image](https://github.com/user-attachments/assets/153379da-ee13-4dec-a532-c8d05b01406d)

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
Você está usando uma versão desatualizada do Bloxstrap. A atualização para a versão 2.8.1 corrigirá seu problema. Você pode atualizar a partir daqui: https://github.com/bloxstraplabs/bloxstrap/releases/latest

**Comment by bluepilledgreat** [comment]
update to 2.8.1
