### ISSUE TITLE
[REQ] Bring back multi instance lauching

### ISSUE THREAD

**Issue by sirihasbands** [bloxstraplabs/bloxstrap#3604]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

read the title, it would help so much ty!

**Comment by Wanwood1** [comment]
No

**Comment by Wanwood1** [comment]
No, reasons are stated here
https://github.com/bloxstraplabs/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
Thank you for using Bloxstrap and have a good day

**Comment by bluepilledgreat** [comment]
no
