### ISSUE TITLE
its not letting me install lbloxstrap

### ISSUE THREAD

**Issue by zorolostatmcdonalds** [bloxstraplabs/bloxstrap#3608]
![image](https://github.com/user-attachments/assets/80159a08-210a-4827-8565-003dcd7c51c1)

**Comment by gamerloch10** [comment]
Update to 2.8.1

**Comment by L3G4CY16** [comment]
how do you get the update(2.8.1) im clueless

**Comment by L3G4CY16** [comment]
> Update to 2.8.1

i have the same issue how do i get 2.8.1 though?

**Comment by gamerloch10** [comment]
> > Update to 2.8.1
> 
> i have the same issue how do i get 2.8.1 though?

Just download the new file from here, or https://bloxstraplabs.com/
