### ISSUE TITLE
[BUG] no ui option to choose

### ISSUE THREAD

**Issue by Tierthegoat** [bloxstraplabs/bloxstrap#3609]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i checked everywhere for the option in the settings and couldn't find it. earlier versions it was there but now its gone. please help

**Comment by gayloo** [comment]
Roblox removed/disabled all of the fastflags related to the old UI's.

**Comment by Tierthegoat** [comment]
oh okay thank you
