### ISSUE TITLE
This is roblox issue, but i guess this can help me out ( won't let me launch roblox ) 

### ISSUE THREAD

**Issue by SenZore** [bloxstraplabs/bloxstrap#3610]
trying to fix with yt tutorial, but all of them did not even working at all

things what i did : 
reinstall roblox 
reinstall roblox with revo uninstaller ( Full uninstall ) 
localappdata remove 
temp removed
compability Tested
Run As Administrator
Reinstalling bloxstrap just made same issue as the real one
fully remove roblox from appdata/localappdata with revo

-- Things what i said above this text is tested with bloxstrap and roblox official launcher, hope yall can help me out 😁✌ 

![image](https://github.com/user-attachments/assets/7230ed61-a613-496f-9896-5cd5e6b7c286)
![image](https://github.com/user-attachments/assets/8bd309db-0e30-4430-b8a8-6e8c3a661370)

**Comment by random4565** [comment]
Did you learn a fix yet or anyway how to fix?

**Comment by pizzaboxer** [comment]
Only advice I can give you is to read the Wiki page.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

Please, don't open an issue here for Roblox-specific issues.
