### ISSUE TITLE
[BUG] Roblox crash at every time i start

### ISSUE THREAD

**Issue by MikraGD** [bloxstraplabs/bloxstrap#3611]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary. 

![image](https://github.com/user-attachments/assets/7a341937-f802-4491-b491-f542760bcd36)
Guys please help me

**Comment by nabheyka880** [comment]
update to 2.8.1
