### ISSUE TITLE
[BUG] Error 280

### ISSUE THREAD

**Issue by FeL1x0n** [bloxstraplabs/bloxstrap#3612]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/b617bfd9-bb4e-4781-b1fa-fad2972248f4)
I have never seen a error in Bloxstrap, how to fix it?

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
Enable "Fresh reinstall roblox on next launch" in the Bloxstrap menu, should maybe fix it

**Comment by bluepilledgreat** [comment]
dont intentionally downgrade your roblox
