### ISSUE TITLE
[Old Bloxstrap]

### ISSUE THREAD

**Issue by Kenzeiko** [bloxstraplabs/bloxstrap#3615]
Is there any way to get the old bloxstrap to work for shaders compatibility ? (Since 2.8.0 renames roblox all the time)

**Comment by PikachuWolverine** [comment]
You cannot use the old bloxstrap anymore.

**Comment by Kenzeiko** [comment]
> You cannot use the old bloxstrap anymore.

Oh well, I guess i will try to modify the source code myself then.

**Comment by Wanwood1** [comment]
Good luck

**Comment by Wanwood1** [comment]
> > You cannot use the old bloxstrap anymore.
> 
> Oh well, I guess i will try to modify the source code myself then.

Good luck, you will have to make it somehow compatible with Roblox's newer versions if you wanna make the old versions compatible
