### ISSUE TITLE
Bloxstrap bug

### ISSUE THREAD

**Issue by Mark869123** [bloxstraplabs/bloxstrap#3616]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1.exe

### What problem did you encounter?

When i launch a game in roblox i activated the allow Activity joining inBloxstrap but when i launch discord i didn't saw any button of join game or View game page. May somebody help me? Because from my friend that also the program used there are the both buttons.
![F918EF72-EE9F-4191-BB1D-0513682CBB3A](https://github.com/user-attachments/assets/2cacf47b-a8f7-4bcf-862a-bb3269e1dd63)
and my friend has this 

 There is the join button missing because he leaved the game.

### Bloxstrap Log

```text
N/A
```

**Comment by Mark869123** [comment]
Here is that from my friend 
![z7gse78v](https://github.com/user-attachments/assets/3a0cffb9-91ca-4df6-941b-2145961d9434)

**Comment by nexpid** [comment]
You can't see buttons on your own Discord activity

**Comment by Mark869123** [comment]
Oh

**Comment by Mark869123** [comment]
Thank you!
