### ISSUE TITLE
Banned on the discord for "Adding executables"

### ISSUE THREAD

**Issue by kiazenny123** [bloxstraplabs/bloxstrap#3617]
Sorry I dont know how else to open up an issue....

### What problem did you encounter?

I got banned on the discord for "adding executables". Some dude said to remove the executables since it was against the rules so I immediately did and than went to go look through the rules and like 2 minutes later I was banned. I was trying to search the rules (as in actually search with the bar in top right not as in scouring) for the word exe but nothing was coming up. And than I decided to manually read and saw that it said at one of the last few rules (I think it was #17 No posting executables). But since I was told to remove it and I removed the executable immediately when asked, I don't understand why I was banned. It was a Multi-Instance exe i was just trying to help. And I removed it immediately w/o arguing or questioning at all. I genuinely didn't know I didn't do this maliciously or anything like that.

**Comment by lilbeefaroni** [comment]
posting multi instances exes is not allowed

**Comment by PikachuWolverine** [comment]
Hi, I’m the one that banned you.
1. You posted executables, big no no
2. It was not taken down when I banned you. Even despite the warnings.

**Comment by bluepilledgreat** [comment]
dont post your discord appeals here lol
