### ISSUE TITLE
[BUG] Roblox failed to launch 

### ISSUE THREAD

**Issue by random4565** [bloxstraplabs/bloxstrap#3624]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1 

### What problem did you encounter?

Whenever i try to load roblox it gives me a error saying roblox failed to launch i have tried to switch to the Original roblox launcher  but when i try to launch roblox with the original launcher it spins then it vanishes and does not load.

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
> but when i try to launch roblox with the original launcher it spins then it vanishes and does not load.

Not Bloxstrap issue
