### ISSUE TITLE
[REQ] New Loading Screen with Spongebob on It

### ISSUE THREAD

**Issue by SolarIDK** [bloxstraplabs/bloxstrap#3626]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

He's not there and he should be there because I'm Spongebob's number 1 fan
![hi im spongebob](https://github.com/user-attachments/assets/65653541-ecbc-476f-9406-5c1d33e55677)

**Comment by nabheyka880** [comment]
pizzaboxer will never add that loading screen
![{5BEE4A65-94E6-40C8-9E42-D638379472C3}](https://github.com/user-attachments/assets/3e1c4491-793d-4599-9f51-393f6c89d095)
