### ISSUE TITLE
[BUG] when i trie to download bloxstrap it gives me this error : "System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary."

### ISSUE THREAD

**Issue by ezzplayita** [bloxstraplabs/bloxstrap#3627]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### Bloxstrap Log

```text
N/A
```

**Comment by GodlySlayer2024** [comment]
Please help me fixing this thing bro i used to play roblox smoothly with bloxstrap now i can't use it because of this issue.

**Comment by GodlySlayer2024** [comment]
Anybody knows how to fix this thing? plsss

**Comment by nexpid** [comment]
Update bloxstrap
