### ISSUE TITLE
[BUG] WTF IS THIS?

### ISSUE THREAD

**Issue by Maksiu077** [bloxstraplabs/bloxstrap#3629]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![4341](https://github.com/user-attachments/assets/2ffb38a2-570e-4ee8-86d3-c28dddedb573)
Why?

### Bloxstrap Log

```text
I dont get any
```

**Comment by red-nt** [comment]
false positive
