### ISSUE TITLE
[BUG] what?

### ISSUE THREAD

**Issue by quepro2** [bloxstraplabs/bloxstrap#3630]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

me sale que el roblox no se pudo ejecutar, que hago?
![toma](https://github.com/user-attachments/assets/c9ca7e45-d140-4447-bf06-fcb9ad960399)

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Translations haven't updated, sorry. See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
