### ISSUE TITLE
[BUG] ping issue

### ISSUE THREAD

**Issue by saintflow44** [bloxstraplabs/bloxstrap#3635]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i need help with my ping whenever i join a server that is my region i keep getting 200 ping for no reason could you give me a fast flag that could help me fix my ping 
![{A3E51E79-BDB9-44B5-BD25-577D920213C2}](https://github.com/user-attachments/assets/87c50298-a54d-42c0-b3fc-93ae9c09df00)

### Bloxstrap Log

```text
N/A
```

**Comment by saintflow44** [comment]
pls help

**Comment by ReinoScreech** [comment]
Ping is dependent on the region the **server** is in. Communication delays are usually the cause to high ping.
You can also enable activity tracking and query server information to see what region is causing this.
