### ISSUE TITLE
Bloxstrap doesnt open.

### ISSUE THREAD

**Issue by Huggywuggyplavi** [bloxstraplabs/bloxstrap#3636]
### Acknowledgement of preliminary instructions

- [] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [] I am using the latest version of Bloxstrap.
- [] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

Latest Version

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/8b590911-f299-4d3d-a3ea-800e55242819)
Keep getting this. tried with original launcher still doesnt work. tried all article help, doesnt work.

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
> tried with original launcher still doesnt work

Not Bloxstrap issue.
