### ISSUE TITLE
[BUG] Bloxstrap keeps reinstalling roblox everytime it opens

### ISSUE THREAD

**Issue by srecko211313** [bloxstraplabs/bloxstrap#3637]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I cant disable the feature, This happened as soon as I updated Bloxstrap  

![cant disable](https://github.com/user-attachments/assets/a29961c2-0c6f-4e10-b3af-1c559eeb5ade)

### Bloxstrap Log

```text
N/A
```

**Comment by nexpid** [comment]
This is on purpose

**Comment by ILikeDownloading** [comment]
Care to explain why its on purpose? @nexpid

**Comment by ILikeDownloading** [comment]
oh and because of this does it log you out of your account everytime you reopen roblox?

**Comment by nexpid** [comment]
> Care to explain why its on purpose? @nexpid 

Since a new version of Bloxstrap was just downloaded, Roblox is reinstalled as a precaution. I don't see why this matters that much?

**Comment by nexpid** [comment]
> oh and because of this does it log you out of your account everytime you reopen roblox?

No
