### ISSUE TITLE
[BUG] Cannot disable "Force Roblox reinstallation"

### ISSUE THREAD

**Issue by styalos** [bloxstraplabs/bloxstrap#3638]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

All of a sudden i can no longer disbale "Force Roblox reinstallation" and it make no sense
![Captura de tela 2024-11-02 135554](https://github.com/user-attachments/assets/b2dd545d-6f1c-471b-bfba-3a7143fd91b4)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
thats because roblox isnt even installed yet. if that's not the case, please tell me.

**Comment by DJarrk** [comment]
i fucking have roblox installed this is bullshit
