### ISSUE TITLE
[BUG] Blurred textures

### ISSUE THREAD

**Issue by Blox123gg** [bloxstraplabs/bloxstrap#3639]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Hello, I have a very annoying problem. My textures get blurry when I enter a game, something that didn't happen before. I've already set the quality (in the bloxstrap menu) to maximum, automatic, medium, low, I've already tried creating a new FastFlag (as I had seen in the developer's comment), lowering the graphics quality to one (in roblox) and it didn't work.
![RobloxScreenShot20241102_184249587](https://github.com/user-attachments/assets/4d3bb821-fc8e-45b4-8c76-9f8048360859)
![RobloxScreenShot20241102_184259229](https://github.com/user-attachments/assets/66bda70d-8672-4f44-a96f-1223cdbac992)

### Bloxstrap Log

```text
N/A
```

**Comment by ReinoScreech** [comment]
This occurs when your device's memory can't produce textures at a higher quality, so Roblox makes it lower to increase performance.

**Comment by Blox123gg** [comment]
Is there any way to resolve this? This didn't happen before. I used Bloxstrap to solve this and it did the trick, but now it stopped working.

**Comment by pizzaboxer** [comment]
I hate to say it, but I've got no idea. You might be straight out of luck with this given for you it seems like it's a Roblox-specific issue. I'm personally not aware of what else can be used to configure texture quality other than the option we provide in the settings.

**Comment by Blox123gg** [comment]
How sad, but thanks for helping me. I don't understand how bloxstrap solved my textures problem for a few weeks and then stopped, but anyway, thanks for trying to help.
