### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WindowsDefen517** [bloxstraplabs/bloxstrap#3641]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Hello, i am running Windows 7 x64 Ultimate, and i am unable to install bloxstrap, when i try to open it it's gave me this error 
![image](https://github.com/user-attachments/assets/94ace565-fc54-4de9-adc8-ac2bdb574999)

### Bloxstrap Log

```text
N/A
```

**Comment by red-nt** [comment]
install Visual C++ Redistributable for Visual Studio 2015 (both x64 and x86 bit) from microsoft's website.

**Comment by pizzaboxer** [comment]
Ensure Windows is up to date using https://legacyupdate.net and ensure you have the .NET 6 runtime installed. https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true
