### ISSUE TITLE
[BUG] Discord Rich Presence

### ISSUE THREAD

**Issue by JustCloudyLeft** [bloxstraplabs/bloxstrap#3643]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

Whenever I join a Roblox game, my Bloxstrap/Discord rich presence isn't working. I've read through the "Discord Rich Presence does not work" and I have completed all of the steps listed. It said to open an issue, so I'm hoping this will be read.

### Bloxstrap Log

```text
N/A
```

**Comment by vhyuze** [comment]
im having the same issue and idk how to fix it

**Comment by bluepilledgreat** [comment]
you arent even on the latest version
