### ISSUE TITLE
 [REQ] Hey PizzaBoxxer! Can you add a region finder option?

### ISSUE THREAD

**Issue by nigghas** [bloxstraplabs/bloxstrap#3644]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

 I live in Germany, but Roblox keeps putting me in American servers, which is a bit frustrating since I play competitive games. Having low ping is crucial, and the high ping makes it difficult to play effectively. Adding a region finder option would be appreciated by everyone!  My Discord if you want to contact me: **c9dxl**

**Comment by bluepilledgreat** [comment]
no
