### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\PC\Desktop\Bloxstraps\Bloxstrap\Roblox\Player\content\sounds\ouch.ogg' is denied.

### ISSUE THREAD

**Issue by younes1623** [bloxstraplabs/bloxstrap#3645]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

they wont let me play

### Bloxstrap Log

```text
N/A
```

**Comment by nigghas** [comment]
first clear your temp and %temp% then goto appdata and clear bloxstrap then open bloxstrap and set it up
