### ISSUE TITLE
[BUG] it keeps crashing on my tiny 11 windows mid game pls fix this

### ISSUE THREAD

**Issue by JanncrisSG** [bloxstraplabs/bloxstrap#3649]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

while im playing mid game it keeps crashing whatever game im playing in roblox it still crashes on my windwows tiny 11

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
maybe that's issue
do you have any fastflags?
if so, send them

**Comment by JanncrisSG** [comment]
> maybe that's issue do you have any fastflags? if so, send them

i do not have any fast flag

**Comment by MrT-tak** [comment]
Since tiny 11 strips some services, maybe some kInd of direct X or some files not existing which Roblox is calling?

**Comment by pizzaboxer** [comment]
Create a new issue when you can confirm that you've read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch and that this happens only with Bloxstrap
