### ISSUE TITLE
[BUG] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\newby\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\families'.

### ISSUE THREAD

**Issue by iamtjjj** [bloxstraplabs/bloxstrap#3650]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

blox trap is not letting me play roblox on it

### Bloxstrap Log

```text
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\newby\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\families'.
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
