### ISSUE TITLE
[REQ] UI update requires wiki revision

### ISSUE THREAD

**Issue by Atomaly06** [bloxstraplabs/bloxstrap#3656]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In-game UI updated again and I can't find a fix. Can this be added to the wiki???

**Comment by PikachuWolverine** [comment]
(This message is copy pasted from my pinned message in the official discord server https://discord.gg/nKjV3mGq6R)
# Q: Where is the menu selector? How do I get rid of Chrome menu?
**A: I highly recommend staying on the chrome menu. Its the only one properly supported by roblox and the others will most likely be removed completely very soon.**
-# If you REALLY want the old menus and just CANT live without it (I still advise just getting used to chrome its better anyways) then you can refer to this thread https://discord.com/channels/1099468797410283540/1301330066231267389/1301330066231267389; Any of these flags can stop working at any time, dont complain if they dont work

**Comment by pizzaboxer** [comment]
> In-game UI updated again and I can't find a fix. Can this be added to the wiki???

We're not officially supporting menu UI changes currently. That's why we removed the option for it.
