### ISSUE TITLE
[BUG] content-platform-dictionaries.zip

### ISSUE THREAD

**Issue by peterteo123** [bloxstraplabs/bloxstrap#3664]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/46f5be8c-341e-46cb-990b-167a03e0cf1c)
![Screenshot 2024-11-05 002213](https://github.com/user-attachments/assets/b9abe1b9-ee83-4fa2-bb3b-98654fa2170e)

**Comment by PikachuWolverine** [comment]
Read before posting
Update your bloxstrap to the newest version
Answer truthfully to the text boxes next time

**Comment by peterteo123** [comment]
> Read before posting Update your bloxstrap to the newest version Answer truthfully to the text boxes next time

hey can you help me
 i don't know how to update

**Comment by nabheyka880** [comment]
> hey can you help me i don't know how to update

how can you say that you don't know how to update when you've literally downloaded bloxstrap
anyways, you can either use the github or https://bloxstraplabs.com/

**Comment by peterteo123** [comment]
thks
