### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\Admin\AppData\Local\Bloxstrap\Roblox\Player\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by minhquan611** [bloxstraplabs/bloxstrap#3666]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i had an exception occur when running bloxstrap.

### Bloxstrap Log

```text
System.UnauthorizedAccessException: Access to the path 'C:\Users\Admin\AppData\Local\Bloxstrap\Roblox\Player\ucrtbase.dll' is denied.
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
