### ISSUE TITLE
[BUG] Bloxstrap menu

### ISSUE THREAD

**Issue by oladqq** [bloxstraplabs/bloxstrap#3674]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

V2.8.1

### What problem did you encounter?

i installed today bloxstrap and i found out i dont have bloxstrap menu and i looked in wiki i didn't see anythink to get the bloxstrap menu and i installed it from gitbit.

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Bloxstrap Menu is now Bloxstrap Settings
