### ISSUE TITLE
[BUG] Failed to get Bloxstrap Version info

### ISSUE THREAD

**Issue by Elite989** [bloxstraplabs/bloxstrap#3676]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v8.1

### What problem did you encounter?

![Screenshot 2024-11-05 200748](https://github.com/user-attachments/assets/b4e7a6f0-a76b-4db8-b71d-1c60433a495a)

Please help i tried so many ways to get the error to dissapear. I deleted wave, roblox, and bloxstrap, reseted my pc, tried different versions and it still wont work

### Bloxstrap Log

```text
N/A
```

**Comment by BunnyProPlayz** [comment]
💀💀💀💀☠️☠️😐😂😂🤣🤣🤣🤣😂😅😅😐😐😐😖☹️😕

**Comment by BunnyProPlayz** [comment]
🤡🤡🤡🤡🤡

**Comment by gamerloch10** [comment]
lmao

**Comment by mathewgavilanes-afk** [comment]
https://github.com/user-attachments/assets/05597aa6-d23b-4983-aaa9-5424c18f24b6

**Comment by mathewgavilanes-afk** [comment]
Mathew
