### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by rakharifai** [bloxstraplabs/bloxstrap#3679]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Screenshot 2024-11-06 192803](https://github.com/user-attachments/assets/6638a847-f697-4768-be3f-ca83a5fd7803)

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by rakharifai** [comment]
pls help me

**Comment by PikachuWolverine** [comment]
Update.

**Comment by ROBlNET13** [comment]
how do ppl actually fall for that last checkbox

**Comment by user1126s** [comment]
> how do ppl actually fall for that last checkbox

is it even possible, like these guys must have failed the are you a human capcha lol
