### ISSUE TITLE
[BUG] Game won't load when I use Bloxtrap + mouse cursor disappears

### ISSUE THREAD

**Issue by Mishantaaa** [bloxstraplabs/bloxstrap#3680]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I've encountered this literally recently **(as of today)**. Now when I start the game, my roblox doesn't launch fully - that is, the basic details of the game load, but it remains as if incomplete **(including gray player models, a half gray unloaded map, UI)**, and a cursor that disappears from view as soon as I go into a valid roblox window. _And yes, I don't use any flags or mods of any kind_

When I run roblox exclusively **(without using bloxtrap)**, the gameplay starts normally, without any twists and turns. So still, what do I do?

### Bloxstrap Log

```text
N/A
```

**Comment by Mishantaaa** [comment]
When i launch my roblox with bloxtrap:
![image](https://github.com/user-attachments/assets/fcdc5484-a843-40f2-8f44-4e257b9b3cdf)

**Comment by Mega9915** [comment]
bro this thing happend me to. i tried to reinstall app 3 times and restart my pc but anything is not working. oh and i am playing TDX to i just got relic but i cant test it also i dont wanna miss night 4 pls someone help us

**Comment by pizzaboxer** [comment]
If you enable the "Force Roblox reinstallation" option in Bloxstrap Settings, does it change anything?

**Comment by pizzaboxer** [comment]
#3691
