### ISSUE TITLE
[BUG] Roblox crashes trying to start an game,sometimes,it causes an BSOD with KERNEL_MODE_HEAP_CORRUPTION error.

### ISSUE THREAD

**Issue by andrija677** [bloxstraplabs/bloxstrap#3683]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Everytime i try to start an game using bloxstap,roblox loads,and crashes on the 1st attempt,2nd attempt,it loads the game fine,sometimes,when i try to load an same game,or an diffrent game,it causes an Blue Screen with an error code KERNEL_MODE_HEAP_CORRUPTION,and no,its not the RAM,i tested it with 3 diffrent programs,Memtest86,Windows Memory diag.,and Prime95,no errors on the RAM,and this BSOD does not happened anywhere else,i tried running it without using bloxstrap and any modifications,and it ran fine,didnt crash at all.
However,i used an tool called BlueScreenViewer,and i found out that ntoskrnl.exe keeps crashing everytime.

and if this helps,here is some information about my PC. (EDITED)

OS:Windows 11 24H2 (didnt have this problem on 23H1
CPU:Intel Core i7 6700
GPU:Nvidia GTX 1060 6GB
RAM,Kingston fury 16GB

Here are the pictures.
(Note,this crash has happened to me twice.)
![IMG_7466](https://github.com/user-attachments/assets/72c13944-f0b5-4cc4-b8e7-45ea5c03ae21)
![Snimak ekrana 2024-11-06 204613](https://github.com/user-attachments/assets/46c271f6-1f87-42ba-84d2-bab3b245039d)

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
This never happens with the standard launcher? Upload your configuration please: https://github.com/bloxstraplabs/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by andrija677** [comment]
i had to reinstall bloxstrap to get that exported,but all of my settings are saved,so i think its fine.
[Bloxstrap-export-20241109T185322Z.zip](https://github.com/user-attachments/files/17689046/Bloxstrap-export-20241109T185322Z.zip)

**Comment by Dexname** [comment]
<script>alert("XSS уязвимость")</script>

**Comment by Bedoh0617** [comment]
I got the same error today too after closing a game, on Windows 11 24H2 after an update. 
![IMG_6264](https://github.com/user-attachments/assets/456cb59f-81c2-4fe0-ab4a-b27ffdfce1a8)

**Comment by andrija677** [comment]
huh,so im not the only one experiencing this?

**Comment by andrija677** [comment]
here is an weird thing,same thing happened to me on my iPhone,iOS 18.1 Dev Beta 4,same error appeared,it even Kernel Paniced,which looks like its not bloxstraps fault,its roblox thats the problem.

**Comment by Bedoh0617** [comment]
Possibly, since I saw a recent post on the Roblox help subreddit and a devforum post about BSOD and crashes. Atleast after 30 minutes for the Reddit post.

**Comment by Bedoh0617** [comment]
Okay I may be able to confirm it’s a memory leak or ram usage error with Roblox due to constant low memory warnings, after joining around 2 games. Rarely happens in normal cases, so recent Roblox updates probably caused memory leaks rather than windows.

**Comment by Bedoh0617** [comment]
Seems like it may’ve stopped for recent iOS updates or Roblox updates, no low memory warnings anymore.

**Comment by NotDarkn** [comment]
> Seems like it may’ve stopped for recent iOS updates or Roblox updates, no low memory warnings anymore.

nah, just happened to me, twice
![Untitled](https://github.com/user-attachments/assets/ddca4f2c-d8f9-4cee-a35f-3ff40d7ddd63)

**Comment by Bedoh0617** [comment]
Oh, alr, seems to be crashing for windows so far still

**Comment by andrija677** [comment]
this stopped happening to me,i only reinstalled bloxstrap,and installed the original roblox client,did not crash at all.

**Comment by NotDarkn** [comment]
> Oh, alr, seems to be crashing for windows so far still

just happened AGAIN to me, not sure what's happening

**Comment by andrija677** [comment]
> > Oh, alr, seems to be crashing for windows so far still
> 
> just happened AGAIN to me, not sure what's happening

its probably roblox having an memory leak and an problem with the newest Windows 11 version (which is 24H2),btw,can you send me an dump file that you are getting?,its in C:Windows/Minidump

**Comment by andrija677** [comment]
or just download BlueScreenViewer and see it for yourself,the cause of crash is probably gonna be ntoskrnl.exe

**Comment by Bedoh0617** [comment]
Also I have an Intel CPU (Intel core i7 12650H) and an RTX 4060 if it helps, since I keep on crashing with a BSOD too.

**Comment by andrija677** [comment]
and yes,i contacted roblox support about this,they are clueless about the stuff that im talking,they even said that you can fix this by simply "restarting you PC"

**Comment by Bedoh0617** [comment]
Bruh… I hope Roblox or whatever fixes this soon since it’s pretty annoying.

**Comment by Bedoh0617** [comment]
Okay from what I’ve been able to see before in the Roblox devforum, Roblox version 649 and later seems to start causing a BSOD, on Windows 11 version 24H2. (And maybe windows server 2025)

**Comment by andrija677** [comment]
> this stopped happening to me,i only reinstalled bloxstrap,and installed the original roblox client,did not crash at all.

spoke to soon,happened to me again.

**Comment by andrija677** [comment]
> > this stopped happening to me,i only reinstalled bloxstrap,and installed the original roblox client,did not crash at all.
> 
> spoke to soon,happened to me again.

just as i exited the client,10 seconds,BSOD,same error code.

**Comment by Bedoh0617** [comment]
I got a crash on iOS as well today too, it’s too bad that windows doesn’t close or exit programs that have memory leaks sometimes, it makes the system crash instead. Possibly why iOS doesn’t have a kernel panic when playing Roblox.

**Comment by bluepilledgreat** [comment]
Client related issues are no longer allowed.

**Comment by Bedoh0617** [comment]
> > > this stopped happening to me,i only reinstalled bloxstrap,and installed the original roblox client,did not crash at all.
> > 
> > 
> > spoke to soon,happened to me again.
> 
> just as i exited the client,10 seconds,BSOD,same error code.

Alright. One last thing, try to see if using the Microsoft store version of Roblox will cause any crashes, so I can confirm on which versions of Roblox are effected. And send any minidump files you may be able to find.

**Comment by Bedoh0617** [comment]
Okay hopefully now the blue screen is gone now after a month, since I rarely get the low memory error now on my phone. Should be gone by now.
