### ISSUE TITLE
[BUG] Roblox show a big black line without cursor

### ISSUE THREAD

**Issue by Czechia777** [bloxstraplabs/bloxstrap#3689]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

i turned on my computer, launched roblox and i see this.
![image](https://github.com/user-attachments/assets/b4949f4a-1914-416a-9fa8-2ec9c005687a)
i dont really know if this is a bloxtrap bug or roblox bug i just need to be fixed. i dont use any fonts. i use only custom cursors, death sound, old walking sound, etc.

### Bloxstrap Log

```text
N/A
```

**Comment by REYtlp** [comment]
тоже самое,только без линии

**Comment by ZER0News** [comment]
Mine is also like this
![Captura de tela 2024-11-07 065625](https://github.com/user-attachments/assets/1cdf5713-1aa2-4019-80f4-f7949efa9a19)

**Comment by TropicalLaos** [comment]
Same thing, just without black line

**Comment by mangaming** [comment]
same thing for me

**Comment by samatic237** [comment]
same. I think this is bug in update, when i tried to launch game from browser textures and fonts cant load

**Comment by Wanwood1** [comment]
Make sure the drive location your bloxstrap is installed in has no special characters, and is from A to Z in the latin alphabet, if this doesnt work im not sure what else could be the fix.

**Comment by ReinoScreech** [comment]
Which fastflags are currently enabled for you?

**Comment by Czechia777** [comment]
> Which fastflags are currently enabled for you?

i dont have enabled any fastslags.

**Comment by Czechia777** [comment]
> Make sure the drive location your bloxstrap is installed in has no special characters, and is from A to Z in the latin alphabet, if this doesnt work im not sure what else could be the fix.

dosent work either.

**Comment by Czechia777** [comment]
> Same thing, just without black line

i forgot to mention that if you have fullscreen, the black line will show up.

**Comment by Czechia777** [comment]
Roblox got updated, and it got fixed.
