### ISSUE TITLE
[BUG Не работает

### ISSUE THREAD

**Issue by REYtlp** [bloxstraplabs/bloxstrap#3691]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Включаю блокстрап,открывается окно друзей и больше нечего,курсора тоже нету

### Bloxstrap Log

```text
N/A
```

**Comment by kilia011014** [comment]
у меня также хз как пофиксить

**Comment by pizzaboxer** [comment]
Confirmed Roblox issue. https://devforum.roblox.com/t/latest-roblox-update-made-it-impossible-for-my-client-to-load-assets-images-styles-mouse-icon/3250561
