### ISSUE TITLE
[BUG] ПРОБЛЕМА КОТОРУЮ НАДО НЕМЕДЛЕННО РЕШИТЬ

### ISSUE THREAD

**Issue by VIRALO234** [bloxstraplabs/bloxstrap#3695]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

версия 2.8.1

### What problem did you encounter?

просто ничего не показывает на экране роблокса кроме значков друзей, все серое и ничего не видно, ничего не прогружается. И даже не показывает курсор. БЫСТРО РЕШИЛИ ПРОБЛЕМУ.
![Roblox 07 11 2024 14_19_34](https://github.com/user-attachments/assets/45feb56d-012e-4b09-8422-d30a0496117b)
![Roblox 07 11 2024 14_19_28](https://github.com/user-attachments/assets/32d290f8-f0c0-4aee-8325-b774738847b2)

### Bloxstrap Log

```text
N/A
```

**Comment by Vylesh** [comment]
@VIRALO234 Попробуйте удалить Bloxtrapi и загрузить его снова, я думаю, что обновление вызвало повреждение файлов в приложении, у меня была такая же ошибка, но переустановка исправила ее.

(Перевод пишу я, прошу прощения, если в тексте что-то не так. Я еще не выучил русский язык)

**Comment by Mishantaaa** [comment]
> @VIRALO234 Попробуйте удалить Bloxtrapi и загрузить его снова, я думаю, что обновление вызвало повреждение файлов в приложении, у меня была такая же ошибка, но переустановка исправила ее.
> 
> (Перевод пишу я, прошу прощения, если в тексте что-то не так. Я еще не выучил русский язык)

Я столкнулся с такой же проблемой. Где я могу найти Bloxtrapi? К тому же, я несколько раз удалял и снова устанавливал Bloxtrap, но всё равно ошибка оставалась прежней

**Comment by kilia011014** [comment]
у меня также

**Comment by Vylesh** [comment]
@Mishantaaa https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1 <---- Вы можете скачать по этой ссылке 

Удалите приложение из панели управления, а затем заново установите его из приложения по ссылке.

**Comment by Mishantaaa** [comment]
> @Mishantaaa https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1 <---- Вы можете скачать по этой ссылке
> 
> Удалите приложение из панели управления, а затем заново установите его из приложения по ссылке.

Да, я именно так и сделал, а сейчас установил вновь Bloxtrap по вашей ссылке, но проблема всё та же. Я заметил, что без использования bloxtrap у меня остается эта ошибка, даже при переустановке самого Roblox. Что мне делать?
![image](https://github.com/user-attachments/assets/be5df935-6629-4d01-8013-d64f9be52f46)

**Comment by Vylesh** [comment]
> > @Mishantaaa https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1 <---- Вы можете скачать по этой ссылке
> > Удалите приложение из панели управления, а затем заново установите его из приложения по ссылке.
> 
> Да, я именно так и сделал, а сейчас установил вновь Bloxtrap по вашей ссылке, но проблема всё та же. Я заметил, что без использования bloxtrap у меня остается эта ошибка, даже при переустановке самого Roblox. Что мне делать? ![image](https://private-user-images.githubusercontent.com/187535693/383992643-be5df935-6629-4d01-8013-d64f9be52f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODg4ODksIm5iZiI6MTczMDk4ODU4OSwicGF0aCI6Ii8xODc1MzU2OTMvMzgzOTkyNjQzLWJlNWRmOTM1LTY2MjktNGQwMS04MDEzLWQ2NGY5YmU1MmY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNDA5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTU2ZTBiNmE4YjE5NTBlZjk2ZTJiYjFlZTRjYzg3NmFmNGI2NzYwNmE0NGY3ZTgyZTE1MmJkMDY5ODk5ZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kWCywValavw9HCMCEZREAnP1D2Eexi-NEYd1qFnQM7g)
Если да, то могу честно сказать, что понятия не имею. Должно быть, что-то повредило программное обеспечение..... Это было исправлено, когда я переустановил его. Переустановите, но на этот раз попробуйте очистить местоположение файла перед установкой, я выбрал место установки Plain General вместо моего собственного предыдущего местоположения файла при переустановке. Если вы устанавливаете там, где вы ранее установили, очистите каталог и переустановите.

**Comment by Mishantaaa** [comment]
> > > @Mishantaaa https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1 <---- Вы можете скачать по этой ссылке
> > > Удалите приложение из панели управления, а затем заново установите его из приложения по ссылке.
> > 
> > 
> > Да, я именно так и сделал, а сейчас установил вновь Bloxtrap по вашей ссылке, но проблема всё та же. Я заметил, что без использования bloxtrap у меня остается эта ошибка, даже при переустановке самого Roblox. Что мне делать? ![image](https://private-user-images.githubusercontent.com/187535693/383992643-be5df935-6629-4d01-8013-d64f9be52f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODg4ODksIm5iZiI6MTczMDk4ODU4OSwicGF0aCI6Ii8xODc1MzU2OTMvMzgzOTkyNjQzLWJlNWRmOTM1LTY2MjktNGQwMS04MDEzLWQ2NGY5YmU1MmY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNDA5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTU2ZTBiNmE4YjE5NTBlZjk2ZTJiYjFlZTRjYzg3NmFmNGI2NzYwNmE0NGY3ZTgyZTE1MmJkMDY5ODk5ZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kWCywValavw9HCMCEZREAnP1D2Eexi-NEYd1qFnQM7g)
> > Если да, то могу честно сказать, что понятия не имею. Должно быть, что-то повредило программное обеспечение..... Это было исправлено, когда я переустановил его. Переустановите, но на этот раз попробуйте очистить местоположение файла перед установкой, я выбрал место установки Plain General вместо моего собственного предыдущего местоположения файла при переустановке. Если вы устанавливаете там, где вы ранее установили, очистите каталог и переустановите.

Как я могу изменить путь установки Roblox? Или же это нужно делать с самим Bloxtrap?

**Comment by Mishantaaa** [comment]
> > > @Mishantaaa https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1 <---- Вы можете скачать по этой ссылке
> > > Удалите приложение из панели управления, а затем заново установите его из приложения по ссылке.
> > 
> > 
> > Да, я именно так и сделал, а сейчас установил вновь Bloxtrap по вашей ссылке, но проблема всё та же. Я заметил, что без использования bloxtrap у меня остается эта ошибка, даже при переустановке самого Roblox. Что мне делать? ![image](https://private-user-images.githubusercontent.com/187535693/383992643-be5df935-6629-4d01-8013-d64f9be52f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODg4ODksIm5iZiI6MTczMDk4ODU4OSwicGF0aCI6Ii8xODc1MzU2OTMvMzgzOTkyNjQzLWJlNWRmOTM1LTY2MjktNGQwMS04MDEzLWQ2NGY5YmU1MmY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNDA5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTU2ZTBiNmE4YjE5NTBlZjk2ZTJiYjFlZTRjYzg3NmFmNGI2NzYwNmE0NGY3ZTgyZTE1MmJkMDY5ODk5ZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kWCywValavw9HCMCEZREAnP1D2Eexi-NEYd1qFnQM7g)
> > Если да, то могу честно сказать, что понятия не имею. Должно быть, что-то повредило программное обеспечение..... Это было исправлено, когда я переустановил его. Переустановите, но на этот раз попробуйте очистить местоположение файла перед установкой, я выбрал место установки Plain General вместо моего собственного предыдущего местоположения файла при переустановке. Если вы устанавливаете там, где вы ранее установили, очистите каталог и переустановите.

Я изменил путь установки Bloxtrap на Program Files и после этого всё работало стабильно, до первого запуска игры. Подскажите мне, какой наилучший путь мне стоит указать при установке?

**Comment by killaheelz** [comment]
Проблема в том, что при установке Bloxtrap'а, корневая папка ставится на юзера, а у многих он содержит буквы русского алфавита, переустановите Bloxtrap путём, где не будет фигурировать русский язык.

**Comment by pizzaboxer** [comment]
Duplicate of #3691
