### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ProJeetYt** [bloxstraplabs/bloxstrap#3696]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

My bloxstrap doesn't not launch roblox and close itself automatically.

https://github.com/user-attachments/assets/51b1817e-29b1-40fd-be40-62c051fa1845

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
> It might be because of my flags, but I optimises it for my setup.

Remove your flags then, flags arent designed to improve your fps

**Comment by ProJeetYt** [comment]
> > It might be because of my flags, but I optimises it for my setup.
> 
> Remove your flags then, flags arent designed to improve your fps

But I'm using bloxstrap for flags only, and I've optimised them to my setup. How can they go wrong

**Comment by ProJeetYt** [comment]
I'm just gonna use normal roblox launcher now I guess.
