### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ofri1233** [bloxstraplabs/bloxstrap#3698]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![Roblox VR Screenshot 2024 11 07 - 15 37 15 55](https://github.com/user-attachments/assets/21e286c5-67ca-4044-9d50-a52b2ddc1c17)

### Bloxstrap Log

```text
N/A
```

**Comment by ofri1233** [comment]
what can i do ?????????????

**Comment by Wanwood1** [comment]
You can possibly solve this issue by making sure the drive your bloxstrap is installed in has no special characters, and is from A to Z in latin alphabet.

**Comment by ofri1233** [comment]
how can i do that

**Comment by pizzaboxer** [comment]
Duplicate of #3691
