### ISSUE TITLE
[BUG] Bloxstrap error with last roblox update (Help please)

### ISSUE THREAD

**Issue by PoPcAkOtA** [bloxstraplabs/bloxstrap#3701]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### What problem did you encounter?

I've have ben goten a bloxstrap issue i reinstaled bloxstrap 5 times and thats didn't help me 
![image](https://github.com/user-attachments/assets/7caf418a-22a2-4056-8b34-2264ae4c5010)

### Bloxstrap Log

```text
N/A
```

**Comment by PoPcAkOtA** [comment]
help me pls

**Comment by bigbubule** [comment]
ive also got this issue and i dunno how to fix it so i cant help you

**Comment by IcarusFAith** [comment]
SOMEONE NEEDS TO HELP US

**Comment by Wanwood1** [comment]
You can possibly solve this issue by making sure the drive your bloxstrap is installed in has no special characters, and is from A to Z in latin alphabet.

**Comment by pizzaboxer** [comment]
Duplicate of #3691
