### ISSUE TITLE
[BUG] fix that

### ISSUE THREAD

**Issue by FIXY0URBUGS** [bloxstraplabs/bloxstrap#3704]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

**_when i load in the game i see this:_**
![изображение_2024-11-07_221421826](https://github.com/user-attachments/assets/c3cbeb2f-ccb5-48c2-bc35-2bae00e9d86f)
also the games are is visible in charts section.
![image](https://github.com/user-attachments/assets/a8b25529-188b-40c3-8c4f-cfba34c2bcf1)
_the cursor is invisible, it's very annoying._**I'd really appreciate it if you could help.**
**_I've tried reinstalling Bloxstrap, Roblox in attempts to fix the problem._**

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
What is your windows user
