### ISSUE TITLE
[BUG] update bloxstrap pls

### ISSUE THREAD

**Issue by snepogar** [bloxstraplabs/bloxstrap#3705]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

main page not loading and no cursor after roblox update

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
What is your windows user?

**Comment by mnoiall** [comment]
> What is your windows user?

admin

**Comment by Wanwood1** [comment]
> > What is your windows user?
> 
> admin

This is a roblox issue

**Comment by pizzaboxer** [comment]
Duplicate of #3691
