### ISSUE TITLE
[BUG]  ПРОПАЛ КУРСОР! ПОЖАЛУЙСТА ОБНОВИТЕ БЛОКС ТРАП ПОД ОБНОВЛЕНИЕ РОБЛОКСА!! ТАКЖЕ ЗАГРУЖАЮТСЯ ТОЛЬКО ДРУЗЬЯ

### ISSUE THREAD

**Issue by deddybearw** [bloxstraplabs/bloxstrap#3710]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

версия 2.8.1

### What problem did you encounter?

я захожу в роблокс, и у меня пропадает курсор в зоне окна роблокса, также загружаются только друзья.
![RobloxScreenShot20241107_230142979](https://github.com/user-attachments/assets/b59ff1b3-8090-4169-b0af-ab7a57085285)

**Comment by Wanwood1** [comment]
What is your windows user named

**Comment by hypno-maker** [comment]
> What is your windows user named

у меня максим

**Comment by hypno-maker** [comment]
> ПОЖАЛУЙСТА ПОМОГИТЕ РЕШИТЬ ЭТУ ПРОБЛЕМУ Я УЖЕ ЦЕЛЫЙ ДЕНЬ ПЫТАЮСЬ НЕ ЧЕ НЕ ПОМОГАЕТ ДЛЯ БЛОКСТРАПА

1 проблема: это windows имя. убедись что там нету специальных символов
2. можешь установить или зайти в обычный роблокс и если тоже такое же то нажми на правую кнопкой мыши на значок роблокс и нажми на расположение файла а потом ищи RobloxPlayerInstaller

**Comment by pizzaboxer** [comment]
Duplicate of #3691
