### ISSUE TITLE
RESOLVENDO PROBLEMA DO ROBLOX COM A TELA INCIAL BUGADA,TANTO O ROBLOX NORMAL TANTO O BLOXSTRAP

### ISSUE THREAD

**Issue by Kakadx** [bloxstraplabs/bloxstrap#3713]
### NOTE
DONT INSTALL INTO THE INTEL DIRECTORY. PLEASE WAIT FOR ROBLOX TO FIX THE PROBLEM OR INSTALL BLOXSTRAP SOMEWHERE ELSE.

### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

to solve the problem on the home screen and the bloxstrap cursor bug, change where the file will be installed (it is installed by default in appdata, local, there on disk c:) change it to another place I changed it to an Intel folder, a random folder just to test, and it worked, I tried putting it in the program file, but it didn't work very well) I'm here more to help anyone who has the same problem I had, and I got it from another guy who replied to a comment , and vylesh is his name, but I'm putting it here for other people to know too, it will probably work, it worked for me, but if it doesn't work for you, I'm really sorry.
![2024-11-08 (1)](https://github.com/user-attachments/assets/9e20e2b9-1abe-419a-8e85-eb9662291e8a)

### Bloxstrap Log

```text
N/A
```

**Comment by snipers14** [comment]
So? I didn't have an Intel folder, I created a fake one and put it there

![Captura de tela 2024-11-08 041207](https://github.com/user-attachments/assets/cea73740-a7cd-41e1-b507-62fad332d2ec)

**Comment by snipers14** [comment]
I came back to say it worked, thanks bro

Voltei para dizer que funcionou valeu mano

**Comment by structiveAlpha** [comment]
hello. What's up with the intel folder? Does it only work on intel pcs? Or does a fake just workwith any name?

**Comment by structiveAlpha** [comment]
YOO this actually worked! Thanks dude

**Comment by Mishantaaa** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [x]  I did not answer truthfully to all the above checkboxes.
> 
> ### Bloxstrap Version
> v2.8.1
> 
> ### What problem did you encounter?
> to solve the problem on the home screen and the bloxstrap cursor bug, change where the file will be installed (it is installed by default in appdata, local, there on disk c:) change it to another place I changed it to an Intel folder, a random folder just to test, and it worked, I tried putting it in the program file, but it didn't work very well) I'm here more to help anyone who has the same problem I had, and I got it from another guy who replied to a comment , and vylesh is his name, but I'm putting it here for other people to know too, it will probably work, it worked for me, but if it doesn't work for you, I'm really sorry. ![2024-11-08 (1)](https://private-user-images.githubusercontent.com/187722800/384229933-9e20e2b9-1abe-419a-8e85-eb9662291e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODEyNzUsIm5iZiI6MTczMTA4MDk3NSwicGF0aCI6Ii8xODc3MjI4MDAvMzg0MjI5OTMzLTllMjBlMmI5LTFhYmUtNDE5YS04ZTg1LWViOTY2MjI5MWU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNTQ5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmM3ZTY4MmVlMWIxN2YxNDRiZTRjOGIzYzNkNGY1MGRjODgzMGE3MTAwOGRhZDE2NjFkMThkM2RjNjYyNjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6g1ONop7dZQf3BjVq1mZL074aFzkB7CBUTb4u1d_lYE)
> 
> ### Bloxstrap Log
> ```
> N/A
> ```

Thank you so much, stranger! And yes, guys, if you have an AMD video card, then just specify the Bloxtrap installation path exactly there ;)

**Comment by Kakadx** [comment]
> hello. What's up with the intel folder? Does it only work on intel pcs? Or does a fake just work with any name?

This folder must be because my Windows is Intel, but it probably works with any other folder, or you can put it in any folder other than the Program Files folder because I tried and It didn't work, but if you want to test it out, see.

**Comment by bluepilledgreat** [comment]
This may break your computer depending on whatever is installed in the C:\Intel\ folder.

**Comment by bluepilledgreat** [comment]
Could you please check if this works for any other install directory. Installing into the Intel directory is incredibly fucking stupid.

**Comment by Kakadx** [comment]
> Você poderia verificar se isso funciona para qualquer outro diretório de instalação? Instalar no diretório Intel é incrivelmente estúpido.

Create a folder and put it there
