### ISSUE TITLE
[BUG] Error when reinstalling bloxstrap

### ISSUE THREAD

**Issue by vipnip** [bloxstraplabs/bloxstrap#3715]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

Error when reinstalling roblox. 
Can you please find a solution for this? And also the roblox menu is kinda broken.. ![Screenshot_6](https://github.com/user-attachments/assets/fa529b2c-1fad-44c4-89e4-da5f7b13a4ac)Thanks!

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by Wanwood1** [comment]
Update roblox
Dont have any special characters in your drive name or windows user, they must be from the latin alphabet
