### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by demo3357** [bloxstraplabs/bloxstrap#3716]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

i not play bloxstrap vertion new do you hlep me?

**Comment by Wanwood1** [comment]
Update to 2.8.1
