### ISSUE TITLE
Change chat icons

### ISSUE THREAD

**Issue by vilzio89** [bloxstraplabs/bloxstrap#3719]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

The connect button looks like the icon game chat should be and I want the connect button to have 2 people in the icon
Game chat: 2 lines
Connect: 2 people

**Comment by Shavixinio** [comment]
what

**Comment by vilzio89** [comment]
Make a mod

**Comment by Shavixinio** [comment]
Bloxstrap doesn't modify the Roblox assets, and neither can any Roblox mod. The most you can do, is change in-game textures with a certain FastFlag. Bloxstrap uses FastFlags provided by Roblox themselves to use, and all it does is add these FastFlags to your iirc `ClientUserSettings.json` file.
