### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SpaghettiSaint** [bloxstraplabs/bloxstrap#3721]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

This issue is a reupload

This could be an issue relating to GoodbyeDPI but i'm not certain.
The Roblox original launcher works, i even tried using a different vpn to get through the first loading screen and then switch to GoodbyeDPI (I use this on the normal roblox launcher because some stuff wont load if i dont) but that didn't work.
Any help on this would be appreciated. (If this is any relevant, i haven't made any changes to the launcher.)

![Ekran görüntüsü 2024-11-07 223343](https://github.com/user-attachments/assets/31829b89-7820-4596-ab7c-06d21cd4778b)

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
this made me thought i have dementia when i was clicking through the issues
