### ISSUE TITLE
[BUG] font wont reset back to default even when font is removed

### ISSUE THREAD

**Issue by funniguy420** [bloxstraplabs/bloxstrap#3722]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

The font wont change back to default, even when its removed

### Bloxstrap Log

```text
N/A
```

**Comment by funniguy420** [comment]
its kinda annoying, as its stuck on the font that ultrakill uses

**Comment by funniguy420** [comment]
sorry i was being stupid all i needed to do was restarting my pc

**Comment by bluepilledgreat** [comment]
^^^
