### ISSUE TITLE
[BUG] after running bloxstrap for the first time, future lighting just gave up

### ISSUE THREAD

**Issue by zinoboy56fhgc** [bloxstraplabs/bloxstrap#3723]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Running bloxstrap for the first time and i choose the lighting to be future: after i join, it didn't work, rather changing it to shadowmap/voxel.

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
Your lighting should be on automatic

**Comment by pizzaboxer** [comment]
How are you checking this?

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
