### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Urgamerboi2-0** [bloxstraplabs/bloxstrap#3724]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

the newest version of bloxstrap

### What problem did you encounter?

my themes button dissapeared from my bloxstrap config and im used to using the V1 menu but the button to choose themes is gone now and i also have this gold theme for bloxstrap but after i made it i remembered that i cant use it

### Bloxstrap Log

```text
[24k_gradient_gold_theme_update_7.zip](https://github.com/user-attachments/files/17684443/24k_gradient_gold_theme_update_7.zip)

```

**Comment by Wanwood1** [comment]
V1 Menu was removed by Roblox + Button to choose menus has been removed because roblox constantly messes with menus

**Comment by pizzaboxer** [comment]
What is the "themes button"?

**Comment by Shavixinio** [comment]
From what I understood, OP meant, that you could change the [in-experience menu](https://roblox.fandom.com/wiki/In-experience_menu) in the Bloxstrap setup between menu v1 and some other ones, but now the toggle for it in the Bloxstrap setup is gone.

However, if you still want to change the menu, you can do so by pasting these fastflags in the FastFlag editor:

V2 (Not supported anymore, could have issues)
```json
{ "FIntNewInGameMenuPercentRollout3": "100",
"FFlagEnableInGameMenuControls": "False",
"FFlagDisableNewIGMinDUA": "True",
"FFlagEnableInGameMenuChromeABTest4": "False" }
```

V4 Menu
```json
{ "FFlagEnableInGameMenuControls": "False",
"FFlagDisableNewIGMinDUA": "True",
"FFlagEnableInGameMenuChromeABTest4": "False" }
```

V4 Menu + Chrome Ui
```json
{ "FFlagEnableInGameMenuChromeABTest4": "True",
"FFlagEnableInGameMenuChrome": "True" }
```

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.

**Comment by Urgamerboi2-0** [comment]
what about V1?

**Comment by gamerloch10** [comment]
v1 was completely removed

**Comment by Urgamerboi2-0** [comment]
😔🔫
