### ISSUE TITLE
[BUG] ???

### ISSUE THREAD

**Issue by supernov4h** [bloxstraplabs/bloxstrap#3727]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

latest

### What problem did you encounter?

![Screenshot_14](https://github.com/user-attachments/assets/5d707dbd-f226-461a-b281-1fa64dc2a4fb)
blurry icons (outside game and inside game)

### Bloxstrap Log

```text
N/A
```

**Comment by supernov4h** [comment]
![Uploading Screenshot_15.png…]()

**Comment by pizzaboxer** [comment]
Open the Bloxstrap Settings menu, go to the Engine Settings tab, set the texture quality option to the highest.
