### ISSUE TITLE
[BUG] NOW FIXED

### ISSUE THREAD

**Issue by Zaneriea** [bloxstraplabs/bloxstrap#3728]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I found now how fix to the problem. Download Bloxstrap for other folder (intel and others).
![image](https://github.com/user-attachments/assets/c3784f93-dc5e-450d-ace5-f486a640a3b9)

### Bloxstrap Log

```text
nothink
```

**Comment by Wanwood1** [comment]
do not do this
