### ISSUE TITLE
[REQ] Discord Rich Presence and OneSkyVed's Trolleybus Place

### ISSUE THREAD

**Issue by tobias-the-czech** [bloxstraplabs/bloxstrap#3729]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

the game OneSkyVed's Trolleybus Place should have more activity shown, like what route you're driving on, what type of Trolleybus are you driving, the most cool thing would be speed and if your trolleys are derailed or not.

**Comment by Wanwood1** [comment]
There is no reason to add all of this this for just one game

**Comment by Naveandice** [comment]
Ask the game developer for that.

https://github.com/bloxstraplabs/bloxstrap/wiki/Integrating-Bloxstrap-functionality-into-your-game
