### ISSUE TITLE
[BUG] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by 5h1b** [bloxstraplabs/bloxstrap#3733]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

**I know it says not to report it here, but I was ignored on the bloxstraplabs/builder repository.**
**I also know it says not to report this error and update Bloxstrap, but as updating did not fix this i'm going to send this issue.**
Every time I launch Roblox (website & app), I get this error while it's starting. I can't seem to play Roblox sadly.
![Screenshot 2024-11-09 145812](https://github.com/user-attachments/assets/373b2b50-c984-4c1c-b6ba-0bf680abd823)

### Bloxstrap Log

```text
[Bloxstrap-QA_20241109T195849Z.log](https://github.com/user-attachments/files/17689219/Bloxstrap-QA_20241109T195849Z.log)
```

**Comment by nabheyka880** [comment]
wtf is Bloxstrap-QA

**Comment by 5h1b** [comment]
https://github.com/bloxstraplabs/builder

**Comment by nabheyka880** [comment]
well have you tried using the REAL bloxstrap?
https://bloxstraplabs.com/

**Comment by 5h1b** [comment]
it's made by bloxstraplabs, the official group for Bloxstrap

**Comment by nabheyka880** [comment]
ok but have you tried uninstalling that and using the normal bloxstrap
what do you even need Bloxstrap-QA for

**Comment by 5h1b** [comment]
for testing certain stuff, and also no i haven't tried that as i need Bloxstrap-QA

**Comment by nabheyka880** [comment]
> and also no i haven't tried that

well try using the normal bloxstrap then

**Comment by 5h1b** [comment]
> as i need Bloxstrap-QA

i need it to test certain stuff

**Comment by nabheyka880** [comment]
> i need it to test certain stuff

and i honestly do not care
now please, try using the normal bloxstrap

**Comment by 5h1b** [comment]
??? so am i not suppose to use one of the official bloxstrap builds?, only use the normal one?

**Comment by nabheyka880** [comment]
i mean if the normal bloxstrap works

**Comment by red-nt** [comment]
are you a translator cause that is only meant for them to preview translations, not general use

**Comment by 5h1b** [comment]
no i am not a tramslator, i use the QA build to see certain stuff that may help me

**Comment by red-nt** [comment]
what certain stuff??

**Comment by 5h1b** [comment]
i was thinking about making my own fork of bloxstrap, and i was hoping for the QA build to help me

**Comment by red-nt** [comment]
a literal fork button on this repo exists

**Comment by red-nt** [comment]
and qa build won't help you

**Comment by 5h1b** [comment]
> and qa build won't help you

why is that?

**Comment by red-nt** [comment]
> > and qa build won't help you
> 
> why is that?

I just said that this build is only meant to preview fucking translations, not creating your own fork

**Comment by red-nt** [comment]
it also says this

![IMG_20241110_022957.jpg](https://github.com/user-attachments/assets/80bef60f-16b3-4ff8-8637-f0bedaf25ca0)

**Comment by 5h1b** [comment]
the build tool is made for translators, that why it need a Crowdin key, not the QA build that is made from it, which can also be use to freely test certain stuff

**Comment by red-nt** [comment]
no genius QA build is literally that build where you preview translations

**Comment by 5h1b** [comment]
just because the builder is made for translators, does not make the QA build specifically made to preview translations, it's a QA build, i just happen to use the translator's builder to build it

**Comment by red-nt** [comment]
The QA build is literally that one you use to preview translations. there's no separate QA build that's used for forking. how about you try reading English better gosh

**Comment by 5h1b** [comment]
i don't think pizzaboxer will be too happy to see us argue, i don't care about the whole what a QA build is for, i just want this bug to be fixed, the QA build still counts as a part of bloxstrap, as the QA build is build from the bloxstraplabs/bloxstrap repository.

**Comment by nabheyka880** [comment]
use the normal bloxstrap

**Comment by nabheyka880** [comment]
and see if it works

**Comment by Roki100** [comment]
i am on latest "prod" bloxstrap:
```
2024-11-09T22:37:18Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-11-09T22:37:18Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 11:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
```
and the same issue pops up
idk why everyone gets mad at qa build if it should make no difference at all, hell, it should have higher chance of having that issue already patched
rule of thumb: if you have no clue about something, dont argue about it 🤦‍♂️

**Comment by bluepilledgreat** [comment]
> no i am not a translator, i use the QA build to see certain stuff that may help me

qa builds have nothing special. update to 2.8.1.

**Comment by bluepilledgreat** [comment]
> i am on latest "prod" bloxstrap:

no you aren't. 2.8.1 is the latest production build

**Comment by Roki100** [comment]
> > i am on latest "prod" bloxstrap:
> 
> no you aren't. 2.8.1 is the latest production build

well then your auto updater doesnt do its only job

**Comment by pizzaboxer** [comment]
> does not make the QA build specifically made to preview translations

yes it does actually - that's why it's completely isolated from standard bloxstrap installations and therefore does not follow auto updates

> it should have higher chance of having that issue already patched due to building from source

the build is from an old state of the main branch from when 2.8.1 was still in development

> and the same issue pops up

![image](https://github.com/user-attachments/assets/fdc459c8-2c06-4160-b14b-a3540d51f1f7)

> well then your auto updater doesnt do its only job

depends - if it can't query the github api then it won't update, no way around that. can't say for sure in your case.

**Comment by 5h1b** [comment]
> > does not make the QA build specifically made to preview translations
> 
> yes it does actually - that's why it has the obnoxious red border to make it obvious that it shouldn't be used in place of standard releases, is why it's completely isolated from standard bloxstrap installations, and therefore does not follow auto updates
> 
> we literally have a guide for building bloxstrap, it's right here: https://github.com/bloxstraplabs/bloxstrap/wiki/Building-Bloxstrap-from-source
> 
> > it should have higher chance of having that issue already patched due to building from source
> 
> the build is from an old state of the main branch from when 2.8.1 was still in development (no idea how or why they only reported it now)
> 
> > and the same issue pops up
> 
> ![image](https://private-user-images.githubusercontent.com/41478239/384651851-fdc459c8-2c06-4160-b14b-a3540d51f1f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDMyNDEsIm5iZiI6MTczMTIwMjk0MSwicGF0aCI6Ii80MTQ3ODIzOS8zODQ2NTE4NTEtZmRjNDU5YzgtMmMwNi00MTYwLWIxNGItYTM1NDBkNTFmMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDAxNDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzRkMmIyNjBjZjQzNDc2Nzk3NjhlMjljMmM3MDAyYzFiNWQzOTIzYmRkNjVjZWQwNjY1NjEyMzE3ZWEyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dCAcGYnbKygCAxSllWw6M1zMCzIMJIMfzmkNizRS58)
> 
> > well then your auto updater doesnt do its only job
> 
> depends - if it can't query the github api then it won't update, no way around that. can't say for sure in your case. making childish remarks like this is incredibly embarrassing on your part given you've been writing code for basically as long as i have lol

Sorry, I thought the QA builds had some sort of code that may have help me, I will do further research next time, sorry for wasting your time.

**Comment by 5h1b** [comment]
> The QA build is literally that one you use to preview translations. there's no separate QA build that's used for forking. how about you try reading English better gosh

Sorry to you too, you were right, I will try next time not to make this mistake again.
