### ISSUE TITLE
[BUG] Process Monitor must be unloaded before continuing.

### ISSUE THREAD

**Issue by cheeseburgrmc** [bloxstraplabs/bloxstrap#3738]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/21d3f076-f026-44bc-8f47-0543e2f58071)
There is no instance of "process monitor" on my computer.

### Bloxstrap Log

```text
N/A
```

**Comment by BunnyProPlayz** [comment]
Are you sure you don't have procmon? Did you ever download the system internals suite (which includes process monitor)?

**Comment by bluepilledgreat** [comment]
restart your computer. you have the procmon driver loaded.
