### ISSUE TITLE
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by rottenflesh1223** [bloxstraplabs/bloxstrap#3739]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

i got a bug when i tried to install 2.5.4

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by internetzx** [comment]
Why are you trying to install 2.5.4?

**Comment by Wanwood1** [comment]
Older versions are incompatible and broken due to roblox updates, download the latest version. (v2.8.1)

**Comment by wrtrteyteey23ee** [comment]
Bruh i just need the fucking fast flag for the old menu thing

**Comment by bluepilledgreat** [comment]
> Bwuh i just need da fuckim fast fwag fow da owd menu dim 👉👈
