### ISSUE TITLE
when i go into fullscreen it goes to max brightness. why????

### ISSUE THREAD

**Issue by pizzamuncher-cmyk** [bloxstraplabs/bloxstrap#3740]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

[BUG] when i go into fullscreen it goes to max brightness. Why? i uninstalled bloxstrap and launched Roblox and it was fine. So it must be a

**Comment by bluepilledgreat** [comment]
Client related issues are no longer allowed.
