### ISSUE TITLE
[BUG] Discord says playing Euro Truck Simulator 2

### ISSUE THREAD

**Issue by SOMERANDOMDUDEEEEEEE** [bloxstraplabs/bloxstrap#3742]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Whenever I play Roblox, Discord says I am playing Euro Truck Simulator 2.

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
![Screenshot 2024-11-10 193540](https://github.com/user-attachments/assets/98a80c47-f3bf-4285-b202-ddb2d642e0b1)

**Comment by BunnyProPlayz** [comment]
Bloxshade?

**Comment by BunnyProPlayz** [comment]
This isnt a bloxstrap issue, this isnt even an issue at all. This is what bloxshade does to add shaders to roblox, however I do believe bloxstrap activity status can override this

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
how do I override it

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
I have rich presence turned on

**Comment by internetzx** [comment]
the funny thing is, you dont

**Comment by internetzx** [comment]
you cant override Euro Trucks, only changing the name

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
how do i change the name then

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
which setting is it

**Comment by SOMERANDOMDUDEEEEEEE** [comment]
> Bloxshade?

yea
