### ISSUE TITLE
[BUG] my left click is was not working in games

### ISSUE THREAD

**Issue by IM-HI** [bloxstraplabs/bloxstrap#3743]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.8.1

### What problem did you encounter?

MY LEFT CLICK ISNT WORKING WHEN IM PLAYING I THOUGHT IT MIGHT BE MY PC BUT WHEN I LEFT CLICK OUTSIDE OF BLOXSTRAP IT WORKS

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
