### ISSUE TITLE
[BUG] I can't download bloxstrap on Wave

### ISSUE THREAD

**Issue by Sashafun** [bloxstraplabs/bloxstrap#3744]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v 2.8.1

### What problem did you encounter?

"Unknown hard error" i got this when i tried to install bloxstrap from Wave. I don't know the problem

https://github.com/user-attachments/assets/cc5fa7c3-0693-4eae-a2ee-13650c222ad0

https://github.com/user-attachments/assets/9f265238-72e0-4fdb-8c28-b6319131033d

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by bluepilledgreat** [comment]
YOU HAVE BEEN CURSED WITH THE LEBRON JAMES CURSE. YOU MUST REPOST THIS UNDER 100 GITHUB REPOSITORIES OR ELSE LEBRON JAMES WILL MURDER YOU.

**Comment by nabheyka880** [comment]
skill issue
