### ISSUE TITLE
[BUG] Lights not rendering

### ISSUE THREAD

**Issue by ThisAintComputin** [bloxstraplabs/bloxstrap#3745]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Lights do not render in-game.

### Bloxstrap Log

```text
N/A
```

**Comment by ThisAintComputin** [comment]
I have the same issue

**Comment by bluepilledgreat** [comment]
remove all your flags
