### ISSUE TITLE
[BUG] Roblox Crash?

### ISSUE THREAD

**Issue by Brasileirojveb** [bloxstraplabs/bloxstrap#3746]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

Sometimes when im playing roblox a random lag spike happends and when that happends after i leave the game it says my game crashed, but it didnt i just close the game normaly, and it only happends when that lag spike happends some time while im playing.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
