### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by heheboyga** [bloxstraplabs/bloxstrap#3747]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

**Comment by theletron** [comment]
### Your version of Bloxstrap is out of date
Please update to the latest version. You can install the latest version from here:
https://github.com/bloxstraplabs/bloxstrap/releases/latest

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
