### ISSUE TITLE
[BUG] Constantly getting signed out of Roblox

### ISSUE THREAD

**Issue by Comeonnoob** [bloxstraplabs/bloxstrap#3749]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

When I try to join (especially a private game owned by me) at times, it consistently gives me error code 403 while not having a VPN or an moderation action on my account. 

When I launch Roblox directly from Bloxstrap without the website, I am signed out and ALL in game settings reset themselves. Signing in allows me to play, but re-launching again will sign me out of my account and reset all in-game settings.

Only encountering problem with Bloxstrap, Roblox's own launcher has no issues with this..
Bloxstrap was installed in a non-system drive, "E:\Roblox Game Client"

![изображение](https://github.com/user-attachments/assets/d52a0d4f-fc43-43bf-8405-a37e5c8bf142)
![изображение](https://github.com/user-attachments/assets/d083c90b-6ae7-40cd-99ea-489397c59b7d)

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
what in the fuck is that error message

**Comment by Comeonnoob** [comment]
> what in the fuck is that error message

Supposed to be this:
![be8ce920ca9091dc9c33f276d59e3915a23d42dd](https://github.com/user-attachments/assets/9c27aa6a-de22-4f93-9f0a-f4b74374b52f)

**Comment by Wanwood1** [comment]
maybe dont download bloxtrap into E drive

**Comment by moyaimoment** [comment]
why do you have it on your E drive? Roblox takes not even a GB?

**Comment by Comeonnoob** [comment]
> maybe dont download bloxtrap into E drive

Why not?!?

**Comment by bluepilledgreat** [comment]
403 means that it failed to authenticate. This could be from a variety of issues.

**Comment by Comeonnoob** [comment]
> 403 means that it failed to authenticate. This could be from a variety of issues.

Will I know the "variety of issues" anytime

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
