### ISSUE TITLE
[BUG] Mouse cursor leaves window even in fullscreen (similar to UWP version of the bug)

### ISSUE THREAD

**Issue by Matthewkyos** [bloxstraplabs/bloxstrap#3750]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

It's self explanatory the mouse cursor leaves the window of the application, even in Fullscreen like the Microsoft store version bug. 
Nothing in the bloxstrap settings seems to fix this either.

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
Does this happen in bloxstrap only or also on the default roblox launcher?

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
