### ISSUE TITLE
[BUG] No automatic re-entry after more than 20 minutes

### ISSUE THREAD

**Issue by fgr178707** [bloxstraplabs/bloxstrap#3752]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ]  I did not answer truthfully to all the above checkboxes.
### Bloxstrap Version

2.8.1

### What problem did you encounter?

No automatic re-entry after more than 20 minutes
Iusedtobeabletore-enterautomatically.
Is this feature removed or does it need to be installed separately?
![image](https://github.com/user-attachments/assets/c7e05536-0ad8-4027-b3cb-dba494cf5d5a)

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
bloxstrap has no such feature?
![Screenshot_5557](https://github.com/user-attachments/assets/88cf8381-03fb-411b-95c2-84b4f3ea77b9)
lol

**Comment by fgr178707** [comment]
> bloxstrap has no such feature?

I remember it used to work.

**Comment by fgr178707** [comment]
It seems to be getting better again.
