### ISSUE TITLE
Roblox failed to launch. Last version

### ISSUE THREAD

**Issue by stommking** [bloxstraplabs/bloxstrap#3756]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v 2.8.1

### What problem did you encounter?

Im trying to open my roblox but i cant, appears a message and say "Roblox failed to launch. Please read the following information which will open in your browser when you close the dialog"... But when i close the dialog the page dont open, so what can i do?... I was playing in the morning but now i cant, can you help me please. 
![image](https://github.com/user-attachments/assets/a37f6fc7-5d72-4a54-a1db-4d08e86f2d96)

I want to add is the last version, also i have the visual c++ redistributables, and NVIDIA controlers are updated... so i dont know... please help me.

### Bloxstrap Log

```text
N/A
```

**Comment by riizzly** [comment]
my roblox is failed to launch bro

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
