### ISSUE TITLE
[REQ] toggle custom presets

### ISSUE THREAD

**Issue by hugo9655** [bloxstraplabs/bloxstrap#3760]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

You can import/save custom fflag presets and toggle them on or off. You can also open that preset in an editor to quickly change it. (not sure if this has been requested already, I couldn't find any gh issues)

**Comment by bluepilledgreat** [comment]
> thanks for the explanation? @bluepilledgreat

sorry, this is a duplicate suggestion.
