### ISSUE TITLE
[REQ] Switch back to version- folders.

### ISSUE THREAD

**Issue by bluepilledgreat** [bloxstraplabs/bloxstrap#3761]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

The new file structure is causing many problems. See "UnauthorizedAccessException" posts.

**Comment by Kenrick88** [comment]
Bmvh

**Comment by Kenrick88** [comment]
Hacks

**Comment by bluepilledgreat** [comment]
> Hacks

Thank you Kenrick88

**Comment by user1126s** [comment]
bloxshade crying in the corner:

**Comment by MrT-tak** [comment]
#3908 Might do this... Lets see...

**Comment by MrT-tak** [comment]
#3908 fixes this.
Someone close pls
