### ISSUE TITLE
[BUG]  Anti Aliasing Making not rendering properly?

### ISSUE THREAD

**Issue by SQQ2019** [bloxstraplabs/bloxstrap#3762]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

**Weird things start appearing on my screen similar on when you reach the floating point of roblox**

example
![image](https://github.com/user-attachments/assets/a32983b6-3219-4203-95b5-9d0ef112bf16)
**It's not has bad it's barely noticeable but once you see it it's impossible to unsee it. It only applies to objects, this only happens when im moving in any way**

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
