### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by toeslova** [bloxstraplabs/bloxstrap#3763]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/e3567a5a-a59e-4f10-9655-60e412a8394d)

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
update

**Comment by bluepilledgreat** [comment]
> I did not answer truthfully to all the above checkboxes.
