### ISSUE TITLE
[BUG] không vào được bloxstrap nó hiện --------------------------- Bloxstrap-v2.8.1.exe --------------------------- You must install or update .NET to run this application.  Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)  Would you like to download it now?  Learn about framework resolution: https://aka.ms/dotnet/app-launch-failed 

### ISSUE THREAD

**Issue by ahhhdsad** [bloxstraplabs/bloxstrap#3766]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/3c7ddaf6-830f-4612-8f74-01adbfc40a18)
 

### Bloxstrap Log

```text
N/A
```

**Comment by ahhhdsad** [comment]
cần trợ giúp cái này 
![image](https://github.com/user-attachments/assets/66280c40-67d2-4cd2-94ab-dd8d0829ad75)

**Comment by sewshee** [comment]
bro cannot follow instructions

**Comment by lolasaman** [comment]
follow the damn instructions!!!

**Comment by bluepilledgreat** [comment]
bruh
