### ISSUE TITLE
[BUG] weird bug

### ISSUE THREAD

**Issue by lolasaman** [bloxstraplabs/bloxstrap#3767]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

ok so when i open bloxstrap it says what it failed to launch roblox when after that error, roblox just opens in place and right now i dont have a screenshot because its not happening that common

**Comment by MrT-tak** [comment]
#3176?
hmmmm

**Comment by Wanwood1** [comment]
answer truthfully to all the above checkboxes

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
