### ISSUE TITLE
[BUG] i cant install it

### ISSUE THREAD

**Issue by david1564** [bloxstraplabs/bloxstrap#3769]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.3

### What problem did you encounter?

![Snímek obrazovky 2024-11-15 213526](https://github.com/user-attachments/assets/c13de49e-b177-42e1-97ca-22b2238476c7)

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
update

**Comment by Amaniel2020** [comment]
help
