### ISSUE TITLE
[BUG] System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.

### ISSUE THREAD

**Issue by dar84us** [bloxstraplabs/bloxstrap#3771]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1]

### What problem did you encounter?

 not instaling

### Bloxstrap Log

```text
System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.
```

**Comment by bluepilledgreat** [comment]
Related to #3761
