### ISSUE TITLE
[BUG] Connection Error, Yet Still Loads Mods.

### ISSUE THREAD

**Issue by Spoonus** [bloxstraplabs/bloxstrap#3772]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![wuhhuhbluh](https://github.com/user-attachments/assets/01bc3e0e-01ec-4580-8999-05e1572f76e3)
every time i launch roblox i get this, yet my mods still load and i'd presume that i still get roblox updates.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Relaunch Roblox from the website

**Comment by Spoonus** [comment]
> Relaunch Roblox from the website

been launching roblox from the website normally, yet this always shows up.

**Comment by Spoonus** [comment]
fixed via reinstall.
