### ISSUE TITLE
[BUG] Bloxstrap using microphone when clearly its not voice chat

### ISSUE THREAD

**Issue by babyyucky** [bloxstraplabs/bloxstrap#3774]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![Screenshot 2024-11-16 231203](https://github.com/user-attachments/assets/ca70e395-5547-485c-81b2-730635a56789)
![Screenshot 2024-11-16 231211](https://github.com/user-attachments/assets/cd107a56-0ad5-4d04-a5be-31f452902f83)

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
Where did you download Bloxstrap from?

**Comment by babyyucky** [comment]
from the github

**Comment by bluepilledgreat** [comment]
Bloxstrap does not access your microphone. The operating system might be confusing the Roblox client for Bloxstrap.
