### ISSUE TITLE
[BUG] An error pops up saying that One or more errors occurred, the key 'content-platform-dictionaries.zip' was not present in the dictionary. An error occurred while running bloxstrap, this prevents me from installing it. What should I do?

### ISSUE THREAD

**Issue by JxidenYT** [bloxstraplabs/bloxstrap#3779]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.7 I think

### What problem did you encounter?

When pressing install, it just does this error message.

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/

**Comment by JxidenYT** [comment]
> update https://bloxstraplabs.com/

thanks so much man
