### ISSUE TITLE
[BUG] the bloxstrap is running but it isn't displaying 

### ISSUE THREAD

**Issue by TranBao0707** [bloxstraplabs/bloxstrap#3780]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I open Bloxstrap, and it's displayed on Task Manager but it doesn't display on the screen

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
