### ISSUE TITLE
Bloxstrap FPS Unlocker not working

### ISSUE THREAD

**Issue by mjhates419** [bloxstraplabs/bloxstrap#3782]
[Bloxstrap-export-20241118T200355Z.zip](https://github.com/user-attachments/files/17805709/Bloxstrap-export-20241118T200355Z.zip)
I have been having issues with my fps not being able to uncap for the past 2 weeks now and I've tried everything to uncap it but nothing seems to work. I have uploaded my Bloxstrap configuration along with All my bloxstrap logs. Does anyone know how to fix this? I have been running mad trying to fix it. I'd also like to mention that I use a laptop and maybe that is causing the issue? Thanks

**Comment by bluepilledgreat** [comment]
Client issues are no longer allowed.
