### ISSUE TITLE
[BUG] An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by KennZzzz1** [bloxstraplabs/bloxstrap#3783]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

V2.5.4

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by DanGameZone** [comment]
can you read? because you clearly can't

**Comment by DanGameZone** [comment]
you're not getting helped bud

**Comment by DanGameZone** [comment]
update bloxstrap
and learn to read

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
