### ISSUE TITLE
[BUG] When Im tryna take off the cursor it stays on when i enter roblox

### ISSUE THREAD

**Issue by dvxluft** [bloxstraplabs/bloxstrap#3784]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

So, when I take off the cursor and I join Roblox it doesn't take off the cursor. The cursor stays.

### Bloxstrap Log

```text
N/A
```

**Comment by DanGameZone** [comment]
did u click save?

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
