### ISSUE TITLE
[BUG] my roblox crash wheen i respawn, 

### ISSUE THREAD

**Issue by Viquitus** [bloxstraplabs/bloxstrap#3785]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

latest

### What problem did you encounter?

I play a lot of strongest and jujutsu shenanigans and sometimes in the middle of the game it freezes and comes back later, that already wastes my time and I lose the battle, and when I respawn it takes about 5 seconds to return to normal (srry i used translator)

### Bloxstrap Log

```text
np
```

**Comment by DanGameZone** [comment]
what do you mean "bloxstrap version: lastest" you need to say the version number
