### ISSUE TITLE
[BUG] Suspendedapp when run bloxstrap

### ISSUE THREAD

**Issue by TranBao0707** [bloxstraplabs/bloxstrap#3786]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.2.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/35ee57e6-7bb7-4bbc-b77f-fd44669f4a11)
i open Bloxstrap but it shows suspended

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
ok so first thing you've gotta do is update
https://bloxstraplabs.com/

**Comment by TheConfusedlol** [comment]
and i thought 2.5.3/4 was bad,holy.

**Comment by TranBao0707** [comment]
> và tôi nghĩ 2.5.3/4 tệ lắm, thánh thần ơi. Vâng, hãy cập nhật

  i try to use 2.8.1 and it displayed on task manager but doesn't displaying on the screen

**Comment by TheConfusedlol** [comment]
> > và tôi nghĩ 2.5.3/4 tệ lắm, thánh thần ơi. Vâng, hãy cập nhật
> 
> i try to use 2.8.1 and it displayed on task manager but doesn't displaying on the screen

Ah, i see, have you tried double clicking it in the taskbar/maximizing it in task manager?

**Comment by TranBao0707** [comment]
> > > và tôi nghĩ 2.5.3/4 tệ lắm, thánh thần ơi. Vâng, hãy cập nhật
> > 
> > 
> > i try to use 2.8.1 and it displayed on task manager but doesn't displaying on the screen
> 
> Ah, i see, have you tried double clicking it in the taskbar/maximizing it in task manage



> > > và tôi nghĩ 2.5.3/4 tiền tệ lắm, thánh thần ơi. Vâng, hãy cập nhật
> > 
> > 
> > tôi thử sử dụng 2.8.1 và nó hiển thị trên trình quản lý tác vụ nhưng không hiển thị trên màn hình
> 
> À, tôi hiểu rồi, bạn đã thử nhấp đúp vào nó trên thanh tác vụ/phóng to nó trong trình quản lý tác vụ chưa?

it doesn't work

**Comment by bluepilledgreat** [comment]
Update Bloxstrap. 2.2.0 won't save you.
