### ISSUE TITLE
issue please help

### ISSUE THREAD

**Issue by skibidisigma-hue** [bloxstraplabs/bloxstrap#3788]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

Hi, Bloxstrap i launched roblox through Bloxstrap when i did it launched it but it showed a gray screen i really want to play using Bloxstrap because it help me with my fps i hope you will help me. Thank you
![Bloxstrap](https://github.com/user-attachments/assets/fee93ad5-d17d-4f98-ab7c-dca683dcc3c4)

**Comment by DanGameZone** [comment]
bloxstrap cant improve fps
are u using vulkan?

**Comment by theletron** [comment]
**Fast flags cannot "improve" or "optimise" your FPS, ping or anything else.** To fix this problem, you must remove your flag configuration. You can remove it by:
1. Go to "Engine Settings"
2. Scroll all the way down
3. Turn on "Reset everything to defaults"
4. Save

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
