### ISSUE TITLE
[BUG] Game freezes for like 3 seconds whenever i enter exclusive fullscreen

### ISSUE THREAD

**Issue by Ep1cG** [bloxstraplabs/bloxstrap#3789]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I pressed alt + enter (my exclusive fullscreen keybind) and it completely froze my game for about 3-5 seconds. If you could fix this issue that would be great.

### Bloxstrap Log

```text
N/A
```

**Comment by DanGameZone** [comment]
do u know how to read by any chance?

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
