### ISSUE TITLE
[REQ] Launch specific custom integrations when certain games launch

### ISSUE THREAD

**Issue by CubesterYT** [bloxstraplabs/bloxstrap#3791]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Custom integrations are great and all, but I find it cumbersome at times. Like let's say I like using an auto clicker for certain games, so I make it launch with custom integrations, but the thing is, nobody ONLY, not even myself, would play games that need that one integration. So it gets annoying if that auto clicker opens when I'm trying to play a game that doesn't need it. So I'm proposing adding a way to assign games for a integration to launch with only.

![image](https://github.com/user-attachments/assets/44ae2454-9737-41a8-a927-04809187c67d)
There could be a new box with a plus button where you put the ID(s) of the games you want to assign this integration for only, and there can be a new checkbox that only appears if there are assigned games, that says "Auto close when game is exited" or something like that.

**Comment by bluepilledgreat** [comment]
no

**Comment by CubesterYT** [comment]
What's not a "good use case" as I said above? You know what, I'll elaborate my uses.

I use several different apps for different games, and each for it's own different reason, I obviously can't use the current way integrations work unless I want them ALL to launch for EVERY single game. I use the timer app for certain games where I need to time myself, so I'd launch with those games, some games where I want to auto click on, and some games that I want to use tinytask on for macros. All of these are individual needs that do NOT coincide with each other and should not, why should I be limited to having all apps open every time or none at all?

**Comment by CubesterYT** [comment]
Another addition on the thing I presented on having an app close/open once the associated game closes/opens makes management of such apps a lot easier, and reduces unnecessary taskbar bloat (In the event I just deal with 5 apps opening every time I open Roblox)

**Comment by CubesterYT** [comment]
You know what, I'll just work on it myself.
![tenor 1](https://github.com/user-attachments/assets/81c44025-fb1c-4aca-97cb-ca1926ab2e22)

**Comment by MrT-tak** [comment]
> You know what, I'll just work on it myself. ![tenor 1](https://private-user-images.githubusercontent.com/78769806/395357892-81c44025-fb1c-4aca-97cb-ca1926ab2e22.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MjcyNDEsIm5iZiI6MTczNTQyNjk0MSwicGF0aCI6Ii83ODc2OTgwNi8zOTUzNTc4OTItODFjNDQwMjUtZmIxYy00YWNhLTk3Y2ItY2ExOTI2YWIyZTIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzMDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzM2ODYzNjkwZjUyNzdkZGU3OTEzN2RhZGVlM2RlYWFhODcwNWNhYWMyNGJhZWMxMmI5MGM3NjRiMzIyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wl6No0VW9TFWSmmF0Y6-ma41LoJ8v_bG7EJhX1k-mYU) [ ![tenor 1](https://private-user-images.githubusercontent.com/78769806/395357892-81c44025-fb1c-4aca-97cb-ca1926ab2e22.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MjcyNDEsIm5iZiI6MTczNTQyNjk0MSwicGF0aCI6Ii83ODc2OTgwNi8zOTUzNTc4OTItODFjNDQwMjUtZmIxYy00YWNhLTk3Y2ItY2ExOTI2YWIyZTIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzMDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzM2ODYzNjkwZjUyNzdkZGU3OTEzN2RhZGVlM2RlYWFhODcwNWNhYWMyNGJhZWMxMmI5MGM3NjRiMzIyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wl6No0VW9TFWSmmF0Y6-ma41LoJ8v_bG7EJhX1k-mYU) ](https://private-user-images.githubusercontent.com/78769806/395357892-81c44025-fb1c-4aca-97cb-ca1926ab2e22.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MjcyNDEsIm5iZiI6MTczNTQyNjk0MSwicGF0aCI6Ii83ODc2OTgwNi8zOTUzNTc4OTItODFjNDQwMjUtZmIxYy00YWNhLTk3Y2ItY2ExOTI2YWIyZTIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzMDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzM2ODYzNjkwZjUyNzdkZGU3OTEzN2RhZGVlM2RlYWFhODcwNWNhYWMyNGJhZWMxMmI5MGM3NjRiMzIyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wl6No0VW9TFWSmmF0Y6-ma41LoJ8v_bG7EJhX1k-mYU) [ ](https://private-user-images.githubusercontent.com/78769806/395357892-81c44025-fb1c-4aca-97cb-ca1926ab2e22.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MjcyNDEsIm5iZiI6MTczNTQyNjk0MSwicGF0aCI6Ii83ODc2OTgwNi8zOTUzNTc4OTItODFjNDQwMjUtZmIxYy00YWNhLTk3Y2ItY2ExOTI2YWIyZTIyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDIzMDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzM2ODYzNjkwZjUyNzdkZGU3OTEzN2RhZGVlM2RlYWFhODcwNWNhYWMyNGJhZWMxMmI5MGM3NjRiMzIyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wl6No0VW9TFWSmmF0Y6-ma41LoJ8v_bG7EJhX1k-mYU)

Give this guy a trophy for real! I absolutely agree with @CubesterYT who suggested this!
See #4032
