### ISSUE TITLE
[BUG] Roblox custom font error

### ISSUE THREAD

**Issue by Espinoscuro** [bloxstraplabs/bloxstrap#3792]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

V.2.8.1

### What problem did you encounter?

Bloxstrap breaks roblox when removing a custom font, when opening roblox it just shows the sidebar and friends without any text or games before crashing

Pic: *(lightmode)*
![image](https://github.com/user-attachments/assets/f787b06d-7267-4ee4-8e36-4cedb93db990)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
![image](https://github.com/user-attachments/assets/1c3e9a5a-0343-4817-af92-87ba1ce9cf37)
Enable "Force Roblox reinstallation" and relaunch Bloxstrap.
