### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\TEJOSHNANDA\AppData\Local\Bloxstrap\Roblox\Player\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by TejoshnandaChilakalapudi** [bloxstraplabs/bloxstrap#3794]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.58.0

### What problem did you encounter?

When i am trying to open it says "an exeption occured to bloxtrap" or it open the app but then the app frezes and then crashes what shoud i do? and some times it says configurin and gets stuck on coniguring roblox.*

### Bloxstrap Log

```text
System.UnauthorizedAccessException: Access to the path 'C:\Users\TEJOSHNANDA\AppData\Local\Bloxstrap\Roblox\Player\ucrtbase.dll' is denied.*
```

**Comment by nexpid** [comment]
maybe stop cheating idk just a suggestion

**Comment by bluepilledgreat** [comment]
Related to #3761.
