### ISSUE TITLE
[BUG] im getting 55 fps when i open bloxstrap

### ISSUE THREAD

**Issue by veil77** [bloxstraplabs/bloxstrap#3799]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![Screenshot 2024-11-20 175759](https://github.com/user-attachments/assets/b687fea5-e701-4c37-87af-465ecce64418)

### Bloxstrap Log

```text
N/A
```

**Comment by DanGameZone** [comment]
1: learn to read
2: I don’t see the issue

**Comment by dfshjfsdjhsdfkjlkdsf** [comment]
I can confirm this, I got the 55 FPS bug too. Also, it got worse in not so laggy spots (usually). (pc capable of running more)

**Comment by DanGameZone** [comment]
Well if it’s Roblox’s fault I can’t help ya

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
