### ISSUE TITLE
[BUG] Bad reinstallation of Roblox Player

### ISSUE THREAD

**Issue by Willixau** [bloxstraplabs/bloxstrap#3802]
###  Instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

Version 2.8.1

### What problem did you encounter?

So, I was going through the Bloxstrap options and noticed the option: Force reinstall Roblox. So, I clicked on it and I clicked save. 

Afterwards, I opened Roblox and noticed that the textures/pictures were very blurry. For example: On the Roblox Login Page, the Roblox Wallpaper is completely blurred as are its logo and buttons. The only things that weren't blurry were the Create Account and Login text and the Privacy Policies. 

To make sure this wasn't a bug on Roblox's part, I reinstalled Roblox on the Official website. And strangely, the images were clear without any blurring! So could you fix this? Because I don't like seeing the menu blurry!👍

This is what I see:
![image](https://github.com/user-attachments/assets/23067856-eda5-4d3a-aea2-ed25d0a7dfb3)
![image](https://github.com/user-attachments/assets/e9f24336-8261-46af-853a-e4c6243cb03f)

Thank you for creating Bloxstrap! I really like this app! And I hope you could fix this problem!

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
You have decreased your texture quality, **this is normal and expected.**
Here's how to fix it:
1. Open Bloxstrap Settings
2. Go to the Engine Settings tab
3. Set the Texture Quality option to "Level 3 (Highest)"

**Comment by Willixau** [comment]
Thanks! I will test it!👍
