### ISSUE TITLE
[BUG] I dont have the hud options in my bloxstrap

### ISSUE THREAD

**Issue by chlebofficial** [bloxstraplabs/bloxstrap#3803]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Well, i dont have the hud options in my bloxstrap. Maybe a week ago i did have the new hud (the circle when i want to open menu), and now i dont. i have been searching but i couldn't find any solutions. Can someone help?

### Bloxstrap Log

```text
N/A
```

**Comment by chlebofficial** [comment]
okay so, i just joined into bloxburg and i have the options back. idk what happen

**Comment by bluepilledgreat** [comment]
In-game menu options have been permanently removed from the bootstrapper due to stability issues. You can still force a certain version via fast flags.
