### ISSUE TITLE
[BUG] Problem with rendering

### ISSUE THREAD

**Issue by darkkalcor** [bloxstraplabs/bloxstrap#3808]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

Maintain rendering quality when scaling the display. A video of the bug itself: https://youtu.be/bFTG80sA6Qg?si=ZvciMVlzh34ZBH08 I followed the link you left in the function itself and there is not even an article about this function.

### Bloxstrap Log

```text
N/A
```

**Comment by darkkalcor** [comment]
Hello, I set the texture quality to max like you said, but nothing changed, unfortunately.

**Comment by darkkalcor** [comment]
> У вас снизилось качество текстур, **это нормально и ожидаемо**. Вот как это исправить:
> 
>     1. Откройте настройки Bloxstrap
> 
>     2. Перейдите на вкладку «Настройки движка».
> 
>     3. Установите для параметра «Качество текстур» значение «Уровень 3 (самый высокий)».
> 
> 
> You have decreased your texture quality, **this is normal and expected.** Here's how to fix it:
> 
>     1. Open Bloxstrap Settings
> 
>     2. Go to the Engine Settings tab
> 
>     3. Set the Texture Quality option to "Level 3 (Highest)"

Hello, I set the texture quality to max like you said, but nothing changed, unfortunately. Here's how I did what you said in the video: https://youtu.be/FDUu6Gp6aEs?si=D2CUI6Or3__58bb6

**Comment by theletron** [comment]
Извините, похоже, я неправильно понял. Если хотите, вы можете изменить обратно опцию, которую я вам посоветовал.
Если вы снизите качество графики до уровня 1, расстояние обзора значительно уменьшится, что приведет к тому, что детали не будут отрисовываться после достижения предела расстояния обзора. Это не ошибка.

---

Sorry, looks like I misunderstood. You can change back the option I told you to change if you want.
If you lower your graphics quality to level 1, your view distance will decrease significantly, which will cause parts to unrender after you reach the view distance limit. This is not a bug.

**Comment by darkkalcor** [comment]
> Извините, похоже, я неправильно понял. Если хотите, вы можете изменить обратно опцию, которую я вам посоветовал. Если вы снизите качество графики до уровня 1, расстояние обзора значительно уменьшится, что приведет к тому, что детали не будут отрисовываться после достижения предела расстояния обзора. Это не ошибка.
> 
> Sorry, looks like I misunderstood. You can change back the option I told you to change if you want. If you lower your graphics quality to level 1, your view distance will decrease significantly, which will cause parts to unrender after you reach the view distance limit. This is not a bug.

На видео я ошибся немножко, я говорил про прорисовку, да и ваш пункт называется как сохранение рендеринга, и я думал что оно сохраняет прорисовку, но это не так. Вот на видео как я проверял: https://youtu.be/krcxYUyyedo?si=U9o4O5-NzUG4vRrY

**Comment by theletron** [comment]
Должен вам сказать, что я не знаю русского языка и, как и вы, пользуюсь DeepL.
Из того, что я вижу, вы говорили об этом:
1. Вы хотите снизить качество графики, но при этом не хотите уменьшать расстояние просмотра.
2. Я слышал, что вы говорили о сохранении качества рендеринга. Эта опция сделает качество рендеринга объектов более высоким, только если масштабирование дисплея больше 100 %.
###### (масштабирование дисплея)
![image](https://github.com/user-attachments/assets/fdf90929-2771-47e9-9628-9c333a428cc5)

Пожалуйста, поправьте меня, если я что-то не так сказал.

---

I have to tell you that I don't know Russian, and I use DeepL just like you.
From what I see, you were talking about these:
1. You want to decrease your graphics quality but you also don't want to decrease your view distance.
2. I heard you talking about preserving rendering quality. This option will only make rendered objects have a higher quality if your display scaling is greater than 100%.
###### (display scaling)
![image](https://github.com/user-attachments/assets/fdf90929-2771-47e9-9628-9c333a428cc5)

Please correct me if there is anything wrong with what I said.

**Comment by darkkalcor** [comment]
> Должен вам сказать, что я не знаю русского языка и, как и вы, пользуюсь DeepL. Из того, что я вижу, вы говорили об этом:
> 
>     1. Вы хотите снизить качество графики, но при этом не хотите уменьшать расстояние просмотра.
> 
>     2. Я слышал, что вы говорили о сохранении качества рендеринга. Эта опция сделает качество рендеринга объектов более высоким, только если масштабирование дисплея больше 100 %.
> 
> 
> ###### (масштабирование дисплея)
> 
> ![image](https://private-user-images.githubusercontent.com/159174251/389029283-fdf90929-2771-47e9-9628-9c333a428cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEwNDMsIm5iZiI6MTczMjMwMDc0MywicGF0aCI6Ii8xNTkxNzQyNTEvMzg5MDI5MjgzLWZkZjkwOTI5LTI3NzEtNDdlOS05NjI4LTljMzMzYTQyOGNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTRjMjBjOGViNDhlZjdjYzhkYjU1MDBiZWYyNDkzNTQ2ZjY2YjU1YzZmMzAxOWYwZThlNDEyZjcwYTQ5ZDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.svoKqeLzVHTXZbya2kIRCXgfngsKoFlqgXUV5VIicMU)
> 
> Пожалуйста, поправьте меня, если я что-то не так сказал.
> 
> I have to tell you that I don't know Russian, and I use DeepL just like you. From what I see, you were talking about these:
> 
>     1. You want to decrease your graphics quality but you also don't want to decrease your view distance.
> 
>     2. I heard you talking about preserving rendering quality. This option will only make rendered objects have a higher quality if your display scaling is greater than 100%.
> 
> 
> ###### (display scaling)
> 
> ![image](https://private-user-images.githubusercontent.com/159174251/389029283-fdf90929-2771-47e9-9628-9c333a428cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDEwNDMsIm5iZiI6MTczMjMwMDc0MywicGF0aCI6Ii8xNTkxNzQyNTEvMzg5MDI5MjgzLWZkZjkwOTI5LTI3NzEtNDdlOS05NjI4LTljMzMzYTQyOGNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxODM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTRjMjBjOGViNDhlZjdjYzhkYjU1MDBiZWYyNDkzNTQ2ZjY2YjU1YzZmMzAxOWYwZThlNDEyZjcwYTQ5ZDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.svoKqeLzVHTXZbya2kIRCXgfngsKoFlqgXUV5VIicMU)
> 
> Please correct me if there is anything wrong with what I said.

Thanks for the tip, I almost ruined my eyesight XD Okay, seriously speaking, that didn't help either, no matter how much I changed the settings even in the bloxstrap launcher. Here's a video of how I tried it: https://youtu.be/yPHqx0mSi3k?si=_H7YAZ7qb_NpdhuD

**Comment by theletron** [comment]
Да, при увеличении расстояния становится все более неудобно, особенно если вы используете небольшой экран. Если вы пытаетесь достичь максимального расстояния просмотра при низком качестве графики, используйте эти флаги:

{
"DFIntDebugFRMQualityLevelOverride": 21
}

Используйте эти значения:
6 = Рекомендуется
21 = Максимальное расстояние просмотра

---

Yes, it gets more uncomfortable as you increase it, especially if you are using a smaller screen. If you are trying to achieve maximum viewing distance with low graphics quality, use these flags:

{
"DFIntDebugFRMQualityLevelOverride": 21
}

Use these values:
6 = Recommended
21 = Maximum view distance

**Comment by darkkalcor** [comment]
> Да, при увеличении расстояния становится все более неудобно, особенно если вы используете небольшой экран. Если вы пытаетесь достичь максимального расстояния просмотра при низком качестве графики, используйте эти флаги:
> 
> { "DFIntDebugFRMQualityLevelOverride": 21 }
> 
> Используйте эти значения: 6 = Рекомендуется 21 = Максимальное расстояние просмотра
> 
> Yes, it gets more uncomfortable as you increase it, especially if you are using a smaller screen. If you are trying to achieve maximum viewing distance with low graphics quality, use these flags:
> 
> { "DFIntDebugFRMQualityLevelOverride": 21 }
> 
> Use these values: 6 = Recommended 21 = Maximum view distance

Where do I enter and configure this?

**Comment by theletron** [comment]
1. Откройте настройки Bloxstrap
2. Перейдите в раздел «Настройки движка
3. Прокрутите страницу вниз и нажмите «Быстрый редактор флагов».
(может появиться предупреждение, просто продолжайте)
4. Нажмите «Добавить новый».
5. Нажмите «Импорт JSON».
6. Скопируйте и вставьте флаги, которые я вам дал.
7. Нажмите «ОК» и сохраните

---

1. Open Bloxstrap Settings
2. Go to Engine Settings
3. Scroll all the way down and click "Fast Flag Editor"
(it may give you a warning, just continue)
4. Click "Add New"
5. Click "Import JSON"
6. Copy and paste the flags that i gave you
7. Click "OK" and save

**Comment by darkkalcor** [comment]
> И я также рекомендую вам вернуться к исходному масштабу дисплея, если вам не нравится текущий.
> 
> And I also recommend that you switch back to your original display scaling if you don't like the current one.

Thank you very much, now my rendering does not decrease.

**Comment by darkkalcor** [comment]
> И я также рекомендую вам вернуться к исходному масштабу дисплея, если вам не нравится текущий.
> 
> And I also recommend that you switch back to your original display scaling if you don't like the current one.

Only here I noticed that I, set 1 in the graphics setting roblox, but at that the graphics looks like at maximum.

**Comment by darkkalcor** [comment]
> Да, при увеличении расстояния становится все более неудобно, особенно если вы используете небольшой экран. Если вы пытаетесь достичь максимального расстояния просмотра при низком качестве графики, используйте эти флаги:
> 
> { "DFIntDebugFRMQualityLevelOverride": 21 }
> 
> Используйте эти значения: 6 = Рекомендуется 21 = Максимальное расстояние просмотра
> 
> Yes, it gets more uncomfortable as you increase it, especially if you are using a smaller screen. If you are trying to achieve maximum viewing distance with low graphics quality, use these flags:
> 
> { "DFIntDebugFRMQualityLevelOverride": 21 }
> 
> Use these values: 6 = Recommended 21 = Maximum view distance

It just sets the maximum graphics in your launcher, but at the same time the slider in roblox with the graphics settings does not work now and even if I set one slider, the graphics are still at maximum. How can this be fixed?

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
