### ISSUE TITLE
[BUG] along with a copy of the log

### ISSUE THREAD

**Issue by sixma777** [bloxstraplabs/bloxstrap#3811]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

i can download blox trap

### Bloxstrap Log

```text
N/A
```

**Comment by PikachuWolverine** [comment]
Update bloxstrap to 2.8.1. You are using an outdated version.

**Comment by kiet140140** [comment]
..

**Comment by theletron** [comment]
### Your version of Bloxstrap is out of date
Please update to the latest version. You can install the latest version from here:
https://github.com/bloxstraplabs/bloxstrap/releases/latest

**Comment by DanGameZone** [comment]
learn to read and we dont care if u need multi instance
