### ISSUE TITLE
[BUG] I keep getting sent to Egyptian server when I use bloxstrap, If I use normal Client it sends me to London servers (Most Local)

### ISSUE THREAD

**Issue by Cill-game** [bloxstraplabs/bloxstrap#3813]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

If I join Roblox through the website or the app via Bloxstrap I am usually sent to a server in Egypt or in the US. I am in Ireland and my most local server would be in London! What's happening?
![image_2024-11-22_195532146](https://github.com/user-attachments/assets/08ad3e3e-dc21-487b-8031-9924687c0742)

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment]
Are you sure its egypt? It could be ipinfo just being inaccurate

**Comment by abdullahdevrel** [comment]
I work for IPinfo. Can you check your IP address directly with us? Let me know what we say about your location. If it is inaccurate, please open a support ticket at https://ipinfo.io/support.

This project uses our data, and I am available to address location issues directly. Thanks.

**Comment by imide** [comment]
if you have the logs from this, you can send the server IP 

(example) https://pics.imide.xyz/u/Medal_LqPn2euknz.png

**Comment by deetwit** [comment]
![Screenshot 2024-11-26 175357](https://github.com/user-attachments/assets/cb937405-0127-4719-bd0c-9a62ebcd7905)
getting the same problem any help?

**Comment by bluepilledgreat** [comment]
This is an IP info problem. There is nothing we can do about it.

**Comment by abdullahdevrel** [comment]
Please see what we say about your IP geolocation on our website [IPinfo.io](https://ipinfo.io/). If it is not accurate, please open a ticket with our support team. They will fix it as soon as possible.
