### ISSUE TITLE
[BUG] bruh

### ISSUE THREAD

**Issue by sheesssshh** [bloxstraplabs/bloxstrap#3822]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.5.4

### What problem did you encounter?

![Desktop Screenshot 2024 11 23 - 01 38 36 50](https://github.com/user-attachments/assets/6161c1b8-1350-40f8-9974-ecf5b0a45108)

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com
