### ISSUE TITLE
MULTI GAMES

### ISSUE THREAD

**Issue by dvinelv** [bloxstraplabs/bloxstrap#3823]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

PLEASE ADD BACK THE FEATURE TO HAVE MULTIPLE ROBLOX GAMES OPENED AT ONCE. THATS ALL IM ASKING FOR PLEASE

**Comment by nabheyka880** [comment]
it will never be added back
pizzaboxer stated that the bugs are already fixed, he just doesn't want to release it since people use it for farming

**Comment by robloxianstudio123** [comment]
bruh just use multibloxy
