### ISSUE TITLE
[REQ] can you add legacy lightning to bloxstrap?

### ISSUE THREAD

**Issue by outrotricks** [bloxstraplabs/bloxstrap#3826]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i want roblox to look nostalgic because i remember legacy lightning being in every game and i want it back
i want it to look like this video right here https://www.youtube.com/watch?v=1MMICxQPqMY

**Comment by Wanwood1** [comment]
i dont think theres a flag for legacy lighting
