### ISSUE TITLE
[REQ] Could you add the old roblox launcher in settings?

### ISSUE THREAD

**Issue by Davimineboy7862** [bloxstraplabs/bloxstrap#3828]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I mean, if you see some extensions like: Stylus or Stylish.
You can actually see that there are some themes that we can create on the website...
But I didn't see (I saw one, but idk if it's real) new launchers for old roblox...
![imagem_2024-11-23_134720650](https://github.com/user-attachments/assets/8dbe58e0-49b1-495f-934f-94e9aa203b7a)
(The image above me is a theme style by Ologist)

**Comment by wanwoodanother** [comment]
this would not only make bloxstrap into 1 gigabyte or so if we add the roblox clients from 2007 to 2016, this wouldnt benefit any other user because bloxstrap is literally made to improve the current versions of roblox
if you want to use old roblox clients, go download novetus on itch, multiplayer not recommended on unsecure client versions

**Comment by Davimineboy7862** [comment]
> this would not only make bloxstrap into 1 gigabyte or so if they add the roblox clients from 2007 to 2016, this wouldnt benefit any other user because bloxstrap is literally made to improve the current versions of roblox if you want to use old roblox clients, go download novetus on itch, multiplayer not recommended on unsecure client versions

Sorry then, I can't search that bc my language is different...

**Comment by ClaytonTDM** [comment]
is this what you mean?
![.](https://clickette.org/u/05xXDG.png)

**Comment by bluepilledgreat** [comment]
There's already an option for this.

**Comment by Davimineboy7862** [comment]
> is this what you mean? ![.](https://camo.githubusercontent.com/641d14e948a373a3545802e54be0c192cd00b04324f46b2b494cb201bbfc825e/68747470733a2f2f636c69636b657474652e6f72672f752f3035785844472e706e67)

Nope, I mean, like the esc menu option...

**Comment by Davimineboy7862** [comment]
> > is this what you mean? ![.](https://camo.githubusercontent.com/641d14e948a373a3545802e54be0c192cd00b04324f46b2b494cb201bbfc825e/68747470733a2f2f636c69636b657474652e6f72672f752f3035785844472e706e67)
> 
> Nope, I mean, like the esc menu option...

But, someone of your team (I forgot already) said to me use Novetus, but when I used it, well, only local :(

**Comment by Davimineboy7862** [comment]
> > > is this what you mean? ![.](https://camo.githubusercontent.com/641d14e948a373a3545802e54be0c192cd00b04324f46b2b494cb201bbfc825e/68747470733a2f2f636c69636b657474652e6f72672f752f3035785844472e706e67)
> > 
> > 
> > Nope, I mean, like the esc menu option...
> 
> But, someone of your team (I forgot already) said to me use Novetus, but when I used it, well, only local :(

I don't know if works with radmin vpn...
