### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ALiteralDodo** [bloxstraplabs/bloxstrap#3833]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Roblox settings wont save with bloxtrap on, I've been trying to save my graphics settings higher then they are for the past month and have been completely unable to. This only happens with bloxstrap on.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
