### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by vinesrdacoolest** [bloxstraplabs/bloxstrap#3834]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

![gui evolution](https://github.com/user-attachments/assets/b85ccb52-b3aa-4b7f-ba27-c93c5a1ff8f1)
Hey bloxstrap, can't you please start gui 2006-2010, gui early 2011, gui 2011-mid 2014, gui late 2014, gui early 2015-2019, gui April 2020, gui 2020-2022, and gui 2022-2024, in Mods,

**Comment by vinesrdacoolest** [comment]
and please start roblox app 2016, and roblox app 2020, in Integrations,
![b5fbce723d5434fefbbb32790feb13489c3f4357](https://github.com/user-attachments/assets/c2c5e91a-4688-4bb5-8958-5c53f7924a72)

**Comment by internetzx** [comment]
bad idea

**Comment by vinesrdacoolest** [comment]
I don't know, how to do start gui old 2016, can't you guys help me, please

**Comment by theletron** [comment]
Only V3 and V3 + New UI topbar is possible. Roblox has removed every other topbar.
