### ISSUE TITLE
[REQ] Revert Roblox Client Freeze (aka Tabbing) Glitch Patch

### ISSUE THREAD

**Issue by Snapshot8888** [bloxstraplabs/bloxstrap#3835]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Could you add an option to revert Roblox patching out the Client Freeze (Tabbing) Glitch?

Explanation: Roblox recently patched an extremely powerful glitch called the Client Freeze Glitch (also known as the Tab Glitch or Tabbing), which has devastated many technical aspects of Roblox and heavily impacted the Glitch and Gear Fighting Communities.

The glitch worked on the Windows Platform by Holding M2 (Right-Click) on the white window bar, causing the client to halt completely until M2 was released.
![Screenshot 2024-11-23 174452](https://github.com/user-attachments/assets/947b10c4-3631-486a-81fe-2e5b43da21ba)
This allowed for tons of valuable tech to be performed in Roblox, such as:
* Client Freeze Buffer (Inputting buttons on your keyboard cause your inputs to be stored. Releasing M2 allows you to release all the stored inputs at hyperspeed, which is very powerful in certain games where you can release many abilities simultaneously, usually impossible without Client Freeze Buffering.)
* Lag High-Jump (Against a wall, jump and continue holding the Spacebar, then time your Client-Freeze with the Re-jump. This gives you a vast jump boost, which is extremely powerful in obbys where you can shortcut sections with roofs on them by getting on top of them.)
The Client Freeze Glitch can be used for many other techs; however, I don't want to overrun this discussion with valuable tech skills.

On November 20th, 2024, Roblox somewhat patched the glitch by making the Window Right-Click prompt (that initially caused the glitch) no longer available, preventing you from being able to freeze the game. The Client Freeze Glitch can still be performed via holding M1 (Left-Click) on the Minimize/WindowView/Close Buttons that are part of the window; however, the damage was done to the experienced players. This singlehandedly destroys lots of experienced Roblox users' habits and muscle memory (several years long) due to the original method getting patched, as well as the new process being far riskier and inaccessible (Ex, You can accidentally close the game if you are trying to use the Client Freeze Glitch with minimal durations, and you now always have to go to the top-right instead of it always being accessible on the entirety of the window bar (on windowed fullscreen) and thus making it far more impractical to use frequently). This has the most significant impact on the Gear Fighting community, to which players often rely on this glitch to perform vast amounts of Gear Tech Skill, such as Shortening the total distance traveled on gears with double-click Lunges to avoid being predictable during a fight.

This is a huge deal, thanks to Roblox partially fixing a bug accessible in every game. If this is revertable, please make a Bloxstrap option that allows users to revert this change to regain the ability to use the Client Freeze Glitch consistently and reliably.

**Comment by bluepilledgreat** [comment]
bruh

**Comment by nabheyka880** [comment]
lol
