### ISSUE TITLE
Freezes and closes for no reason when i join a game on a certain time

### ISSUE THREAD

**Issue by sstrikerrr** [bloxstraplabs/bloxstrap#3836]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

everytime i joined a game it freezes at a certain time and just closes itselfs for no reason

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
Do you use Bloxshade?

**Comment by sstrikerrr** [comment]
> Do you use Bloxshade?

Nope
