### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Erişim izinlerince izin verilmeyen bir şekilde bir yuvaya erişilmeye çalışıldı. (setup.rbxcdn.com:80)

### ISSUE THREAD

**Issue by reallysaidold** [bloxstraplabs/bloxstrap#3838]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

no

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
you can't expect to support if you just put as "What problem did you encounter" "no"
like atleast the logs dude

**Comment by theletron** [comment]
Eğer DNS'ini değiştirmediysen [WARP](https://1111-releases.cloudflareclient.com/win/latest) yükle. Bu Roblox ve diğer bütün websitelerdeki blokları kaldırır.

**Comment by bluepilledgreat** [comment]
Roblox is blocked in Turkey.
