### ISSUE TITLE
[BUG] Bloxstrap isnt Installing after restarting or waiting for it to get fixed

### ISSUE THREAD

**Issue by GorillaPC** [bloxstraplabs/bloxstrap#3839]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Bloxstrap isnt installing even restarting and waiting to get fixed. I uninstalled Bloxstrap and tried reinstalling but it still didnt work the same error but with a different hash kept showing up. I even tried using administrator and it still didnt work.. I dont know what else to try! I went through appdata to delete all Bloxstrap files and still the same error with a differnt hash code.

What i see when its installing;
Installing for a few or less than a second then starts to install again after that point (see image) an error message comes up.
![image_2024-11-24_182910396](https://github.com/user-attachments/assets/51d3cbe2-451b-489a-8811-988ee87bf024)

### Bloxstrap Log

```text
Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-8aa36bbf0eb1494a-RobloxApp.zip

Expected hash: 49f61f3a1dd6b51e7919f5bfccbad9f1
Got hash: 04a825d3a9fa83d380eddb095db31cdf
```

**Comment by bluepilledgreat** [comment]
Please read the wiki about this.
