### ISSUE TITLE
playing Roblox and I got banned thing

### ISSUE THREAD

**Issue by mahitoes** [bloxstraplabs/bloxstrap#3840]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I was playing Roblox and I got banned for a stupid reason i got banned for saying yo wsg and calling  a Roblox hacker goofy

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
ok
we're not roblox support

**Comment by DanGameZone** [comment]
ok well go ask roblox moderation
this isnt even a bloxstrap issue
and GET OU-
(this is a joke)

**Comment by bluepilledgreat** [comment]
how the fuck is this our problem???
