### ISSUE TITLE
[REQ] bring back multi instances

### ISSUE THREAD

**Issue by GitHuber1st** [bloxstraplabs/bloxstrap#3842]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

add the multi instanes back sance roblox account managers gone

**Comment by DanGameZone** [comment]
why Do u need that?

**Comment by CubesterYT** [comment]
pizzaboxer, even though he removed it for reasons in connection to bugs, did find a solution to the bugs, but will not be adding it back due to people using it for farms and similar reasons. So it's very likely he will never add it back.

**Comment by bluepilledgreat** [comment]
are you even old enough to use github
