### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by luasanateo** [bloxstraplabs/bloxstrap#3845]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.657654

### What problem did you encounter?

kujyhtgrtyujki,lo.;lk,jheretgyhujiop0-[pu67yt54r3e4r5t6y7u89p-0[p98u67y5t4r3e2w1

### Bloxstrap Log

```text
N/Ahjukil,
```

**Comment by bluepilledgreat** [comment]
TGYHJDOTG ,JTFIEITFYHI5RJOTG5ROTIYH5RJOGIYHJOI5RJOIRTUJOYHI5RGJTJUYHOTIRJUIOY9THUO5REFIOHRTURH9IO5RETUIO5RE6YHRUJYHIO6RTUY9HTJIOYRHUIOY9RTUIOYHRUT9YB5U9ORTRUYBRTUIOYU5V4RU0EBRJUIYORTGODRJUOYDRJUOIYNUBJORTORETOIRUJTYKOIRTYUREOITIY
