### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by deetwit** [bloxstraplabs/bloxstrap#3846]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

V2.8.1

### What problem did you encounter?

I'm having problems with servers and since I live in the UK and my server's are never in London and always in EG or US.
What's the problem with the servers?
![Screenshot 2024-11-26 175357](https://github.com/user-attachments/assets/567978c4-2b7b-4236-a4f5-793ebdc0ba48)

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
it's just ipinfo being inaccurate

**Comment by nabheyka880** [comment]
take back whatever i just said

**Comment by deetwit** [comment]
> take back whatever i just said

wdum?

**Comment by nabheyka880** [comment]
maybe it is ipinfo being inaccurate but i'm not sure

**Comment by deetwit** [comment]
> maybe it is ipinfo being inaccurate but i'm not sure

Ioh alr.
