### ISSUE TITLE
[REQ] Option to only hide the top-bar while playing

### ISSUE THREAD

**Issue by LatviaKiegelis** [bloxstraplabs/bloxstrap#3851]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I know there are GUI hiding keybinds/options but it hides all the CoreGUI, cursor included. I prefer not to have the topbar but still have the cursor, this could be useful for people who want to play legacy Roblox revivals without being bothered by the menu/current topbar. Dunno if it is possible though, or am I doing something wrong when hiding the CoreGUI? Sorry for bad English.

**Comment by PikachuWolverine** [comment]
They can’t control/add things like that, we can’t create fastflags.
