### ISSUE TITLE
[BUG] Critical system files are missing or damaged. Please repair or reset your Windows installation

### ISSUE THREAD

**Issue by AlvaTechnoo** [bloxstraplabs/bloxstrap#3852]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### What problem did you encounter?

when i use bloxstrap or not the error " **Critical system files are missing or damaged. Please repair or reset your Windows installation** " keep showing whenever solution i use ( i cannot take screenshot the pop up just disappear ) 

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
...
Do what the error message says?
