### ISSUE TITLE
[BUG]  Freezing bug

### ISSUE THREAD

**Issue by Jnoon71** [bloxstraplabs/bloxstrap#3853]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I cant join private servers due to  it freezing when i open the menu, and the only way to fix this is by un full screening which i cant do anymore

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
