### ISSUE TITLE
[BUG] Roblox is not opening

### ISSUE THREAD

**Issue by GamerSantaroXDD** [bloxstraplabs/bloxstrap#3854]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

When my Bloxtrap installs Roblox and tries to open it an error appears saying "Roblox failed to launch." 
![imagen_2024-11-27_170748657](https://github.com/user-attachments/assets/9593f2fe-4db9-4350-869c-bad8834633a4)

### Bloxstrap Log

```text
N/A
```

**Comment by miguelcuellar241** [comment]
help me and him

**Comment by ihatewoodenspoons** [comment]
Does it show any other dialog boxes like I've been experiencing? If so, then it may have something to do with Bloxstrap. Also, try running Roblox without Bloxstrap installed, as that made my Roblox installation work. Bloxstrap seems to break the Roblox installation in my case.
![Screenshot 2024-11-24 132143](https://github.com/user-attachments/assets/9319a355-46f8-497c-96d9-f9b41a6a22a9)
![Screenshot 2024-11-21 014755](https://github.com/user-attachments/assets/2da48650-8a36-4c7c-a95e-5be3e572a461)

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
