### ISSUE TITLE
[REQ] (i didnt know what to put this under) is there a new version of 2.5.4?

### ISSUE THREAD

**Issue by mildandsnipah** [bloxstraplabs/bloxstrap#3859]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

see i used 2.5.4 to run shaders alongside with your fast flags thing and i cant seem to use that version anymore, last time i used a later version the robloxplayerbeta.exe wouldnt be renamed to eurotrucks2 (the method to use nvidea filters)

**Comment by bluepilledgreat** [comment]
yes, its called 2.8.1. bloxshade auto renames bloxstrap's roblox executable to eurotrucks.
