### ISSUE TITLE
[BUG] i put in a font for bloxstrap and it says that it is not a valid font file

### ISSUE THREAD

**Issue by lalainsan** [bloxstraplabs/bloxstrap#3860]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

blox strap says this is not a valid font file
[starborn.zip](https://github.com/user-attachments/files/17953144/starborn.zip)

### Bloxstrap Log

```text
N/A
```

**Comment by DanGameZone** [comment]
Why are you not answering the checkboxes truthfully?

**Comment by DanGameZone** [comment]
The more honest you are the more people will feel like they need to help

**Comment by DanGameZone** [comment]
Anyways, you can only set .ttf, .otf and .ctf files as your font, not .zip files

**Comment by ihatewoodenspoons** [comment]
![Screenshot 2024-12-01 163855](https://github.com/user-attachments/assets/74e9c802-ba44-49b5-8d6d-c2b0569434a8)
Extract the .ttf/.otf file inside the .zip file. Doesn't matter which one you use.

**Comment by bluepilledgreat** [comment]
Extract the zip file...

**Comment by lalainsan** [comment]
omg thank u so much
