### ISSUE TITLE
[BUG] Roblox App is Closing if I click minimize button

### ISSUE THREAD

**Issue by Mystikistis** [bloxstraplabs/bloxstrap#3864]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

As usual, I set my bloxstrap as the default to launch the Roblox app with some modifications (like fast flags, for better gaming).  After launching successfully, after I tried minimizing the Roblox App, it closes, when it shouldn't. I tried opening it again then "clicked" the "minimize button", still closes the app. I never encountered this problem before. I don't know what went wrong. Its a simple thing, but sometimes I want to minimize the app for me to do other things while afk on roblox. 

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
