### ISSUE TITLE
[BUG] so uhmm when i was about to download bloxtrap it showed that when the pic was tooken of the roblox home page there was the colour green. and i want to get that but idk how.

### ISSUE THREAD

**Issue by JetkiRobotJetki** [bloxstraplabs/bloxstrap#3865]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

isnt there supposed to be a colour purple somewhere at the home page

**Comment by bluepilledgreat** [comment]
???
