### ISSUE TITLE
[BUG] Preferred escape menu version and Use advanced graphics quality selector missing on the list

### ISSUE THREAD

**Issue by realcandyuwu** [bloxstraplabs/bloxstrap#3867]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

So I went to settings and there is two missing options for me named
"Preferred escape menu version" and "Use advanced graphics quality selector"
because i need to get old escape menu back to not see the small open bars on top
Here is the proof:
![Screenshot 2024-11-30 110422](https://github.com/user-attachments/assets/d7fa6008-c3bc-45aa-9068-af47b515fbf3)
Can anyone help?

**Comment by bluepilledgreat** [comment]
Roblox has removed these options

**Comment by Lsiphambo** [comment]
aww

**Comment by 2020-robloxplayer123** [comment]
this got taken away from bloxstrap in newer versions, because it was reported to not work
