### ISSUE TITLE
[BUG] so the gui hidder no longer works for me all-though im still in the roblox group and discord (idk if the discord is relevant)

### ISSUE THREAD

**Issue by samiiieeen** [bloxstraplabs/bloxstrap#3868]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

The gui hidder aint workin, like, i press the key set (eg: Shift + Ctrl + G or any other and aint workin like it doesnt do it)please lmk how to fix this or atleast give me some tips on it

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.

**Comment by samiiieeen** [comment]
hell nah why
