### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cookie-4** [bloxstraplabs/bloxstrap#3869]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Screenshot 2024-11-30 204326](https://github.com/user-attachments/assets/bd55050a-ae32-44e5-b839-3c6b165fdd30)
![Screenshot 2024-11-30 204342](https://github.com/user-attachments/assets/95053b2e-fab4-400d-8b92-e12ddbd37c19)

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/
**also, when submitting a log you're supposed to upload the FILE, not the SCREENSHOT**
