### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ehhh22** [bloxstraplabs/bloxstrap#3872]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

So when i launch roblox it stays for like a minute and then crashes without any messages or with an error message roblox crashed because of incompatible software harddiskvolume3 windows xdwd.dll but with a normal roblox launcher it works perfectly fine.

### Bloxstrap Log

```text
N/A
```

**Comment by ClaytonTDM** [comment]
> * [x]  I did not answer truthfully to all the above checkboxes.

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
