### ISSUE TITLE
[BUG] XD

### ISSUE THREAD

**Issue by crywhat7** [bloxstraplabs/bloxstrap#3874]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

bloxtrap its goood

### Bloxstrap Log

```text
for install
```

**Comment by crywhat7** [comment]
Error

**Comment by DanGameZone** [comment]
Update, and no we do not give a fuck about you needing multi instance

**Comment by bluepilledgreat** [comment]
update
