### ISSUE TITLE
[BUG] Bloxstrap it doesn't open for me due to a dictionary error

### ISSUE THREAD

**Issue by Dreamerss1** [bloxstraplabs/bloxstrap#3881]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.4

### What problem did you encounter?

When I started the program, it was installing and I ran into this error. Surprisingly I was scared but I calmed down, maybe there is a solution for this.
![Captura de pantalla 2024-12-01 123352](https://github.com/user-attachments/assets/71543efc-ae5f-441a-8bfd-a66a47e868c7)

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/
you're using an outdated version of bloxstrap
we don't care if you want multi instance, as we don't provide support for it anymore

**Comment by ihatewoodenspoons** [comment]
Update.
https://bloxstraplabs.com/
