### ISSUE TITLE
[BUG] on a bloxtrap2.5.3.exe

### ISSUE THREAD

**Issue by jan462569** [bloxstraplabs/bloxstrap#3885]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary. something is wrong with bloxtrap 

### Bloxstrap Log

```text
1733133703712
7B7DAF25-90FC-4D5A-B1E3-E2499319ECCD
```

**Comment by bluepilledgreat** [comment]
please update bloxstrap
