### ISSUE TITLE
[BUG] Bloxstrap is not allowing me to Turn on Force reinstall roblox

### ISSUE THREAD

**Issue by DummyYungM85** [bloxstraplabs/bloxstrap#3887]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

It Is not allowing me to disable Force Roblox reinstallation and I don't know why

### Bloxstrap Log

```text
N/A
```

**Comment by totallyphysicallypossible** [comment]
literally install bloxstrap first

**Comment by bluepilledgreat** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
