### ISSUE TITLE
this is not a bug but a question

### ISSUE THREAD

**Issue by HelloKerem** [bloxstraplabs/bloxstrap#3890]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

why discord issues closed for no reasonest ever
i need find out the true reason

### Bloxstrap Log

```text
ğüğü
```

**Comment by HelloKerem** [comment]
ğüğü
ik

**Comment by Lsiphambo** [comment]
> ğüğü ik

and everybody knows

**Comment by HelloKerem** [comment]
for wat
