### ISSUE TITLE
[BUG] Style dosen't change in Roblox even after disabling dark mode

### ISSUE THREAD

**Issue by balleranimates** [bloxstraplabs/bloxstrap#3891]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

The title says it, when I open Roblox with Bloxstrap, The style dosen't change when I enable light mode in Roblox.
![Screenshot 2024-12-04 202132](https://github.com/user-attachments/assets/81ea535e-d9b7-4476-b843-0c8ec6551a6c)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
These settings only affect Bloxstrap's look.
