### ISSUE TITLE
My fps is capped at 60 but when I hold my left shift it uncaps

### ISSUE THREAD

**Issue by lightyam** [bloxstraplabs/bloxstrap#3893]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

my fps is capped at 60 but whenever i hold the left shift button it uncaps I dont know if this has something to do with bloxstraps but I been stuck on this 

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
