### ISSUE TITLE
[BUG] Cannot find multi instance launching

### ISSUE THREAD

**Issue by Vapid3004** [bloxstraplabs/bloxstrap#3896]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.81

### What problem did you encounter?

![Screenshot 2024-12-04 220616](https://github.com/user-attachments/assets/ee03e368-98e3-4e96-820b-7722e1591fc4)
I tried searching for multi launch setting but couldn't find it?

### Bloxstrap Log

```text
N/A
```

**Comment by qwqtoday** [comment]
they removed the feature
