### ISSUE TITLE
[BUG] Skybox Issue?????

### ISSUE THREAD

**Issue by MourningS1ar** [bloxstraplabs/bloxstrap#3899]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

So for some reason my skybox in roblox is fine but through bloxstrap my skybox is just pure white if its a dark skybox and Idk whats causing it. [
![Screenshot 2024-12-04 233754](https://github.com/user-attachments/assets/fd1420ca-e93f-497e-9cf7-3126854fa759)
![Screenshot 2024-12-04 232902](https://github.com/user-attachments/assets/afe12b5a-0b06-4aa3-a31b-5ff2c29ac735)
](url)

### Bloxstrap Log

```text
N/A
```

**Comment by Storm-930** [comment]
Send your fastflags 
There's a certain flag that causes the sky to be that colour, you might have it on

**Comment by Storm-930** [comment]
If you got your list from somewhere online like YouTube just do all of us the favour of wiping it clean

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.

**Comment by MourningS1ar** [comment]
> If you got your list from somewhere online like YouTube just do all of us the favour of wiping it clean

This is exactly what the problem was thank you

**Comment by DimasGitHubOfficial** [comment]
it have "skygray" on it.
