### ISSUE TITLE
[BUG] Roblox failed to launch prevents any roblox windows from launch until you close it

### ISSUE THREAD

**Issue by kequask** [bloxstraplabs/bloxstrap#3902]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/3675eeb2-98a9-467c-a6cf-6ca30f12dc7d)
it can be just stuck like that, because of some bloxstrap bug that makes roblox to crash on startup. is there a way to disable this warning or to disable the feature to wait for other instances while launching? it is so annoying when autofarming with wave

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
"it is so annoyim when autofawmim with wave 👉👈"
