### ISSUE TITLE
[BUG] System.AggregateException, System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by kraychyk** [bloxstraplabs/bloxstrap#3907]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Снимок экрана 2024-12-05 202829](https://github.com/user-attachments/assets/400b7f9d-8056-415c-98c1-e8825422c0df)
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.

**Comment by kraychyk** [comment]
> Update Bloxstrap.

Could you give a link to the latest version?

**Comment by nabheyka880** [comment]
https://bloxstraplabs.com/
