### ISSUE TITLE
[BUG] Things not found in the "Dictionary"

### ISSUE THREAD

**Issue by Luk3DC** [bloxstraplabs/bloxstrap#3910]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
![Capture](https://github.com/user-attachments/assets/6dd26b5d-e359-43b0-aa6e-637285f4e052)

**Comment by bluepilledgreat** [comment]
Update Bloxstrap. You are not on 2.8.1.
