### ISSUE TITLE
[BUG] Roblox crashes and freezes my screen when i split-screen

### ISSUE THREAD

**Issue by yhogi-dev** [bloxstraplabs/bloxstrap#3911]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Roblox crashes and then freezes my screen for a few seconds after i spilit-screen

**Comment by Storm-930** [comment]
Split screen... Resizing window?

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.
