### ISSUE TITLE
[BUG] I can't freeze jump on roblox

### ISSUE THREAD

**Issue by laprium** [bloxstraplabs/bloxstrap#3912]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Whenever i try to right click or trying to freeze jump in games i cannot do it
and so i'm trying to play a game that requires it.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
bruh
