### ISSUE TITLE
Roblox will no longer supports Windows 7, Windows 8.1 after 2025. Bloxstrap will ended Windows 7 support?

### ISSUE THREAD

**Issue by RobloTechYT** [bloxstraplabs/bloxstrap#3913]
![GeGbx_PXYAAHf7U](https://github.com/user-attachments/assets/7901bd95-5dae-4721-bea9-970c92d04bb3)
Here's tweet: https://x.com/TheBobPony/status/1864943006157033837

**Comment by bluepilledgreat** [comment]
I plan to add a message box warning about the sunsetting of Windows 7 & 8.1 support. Duplicate.
