### ISSUE TITLE
[BUG] i cannot install im in 2.50

### ISSUE THREAD

**Issue by dar84us** [bloxstraplabs/bloxstrap#3914]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.50

### What problem did you encounter?

i cannot install

**Comment by totallyphysicallypossible** [comment]
did you try not using an old version

**Comment by dar84us** [comment]
but i want to bring back 2016 roblox escape menu

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
