### ISSUE TITLE
[BUG] where is FastFlags

### ISSUE THREAD

**Issue by dar84us** [bloxstraplabs/bloxstrap#3916]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### What problem did you encounter?

where is fastflags

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
In the menu
