### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by leanhquoc250** [bloxstraplabs/bloxstrap#3917]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/4de49331-f177-4583-b806-528a41e5f356)

### Bloxstrap Log

```text
pls i cant play Roblox:<
```

**Comment by leanhquoc250** [comment]
pls fix this

**Comment by bluepilledgreat** [comment]
Client related issues are no longer accepted.

**Comment by lilbeefaroni** [comment]
bcz u dont like helping ppl
