### ISSUE TITLE
FFlag I have some fflags wich dont allow me to see outlines 

### ISSUE THREAD

**Issue by JingleBallsOka** [bloxstraplabs/bloxstrap#3923]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i used some fflags wich dont allow me to see outlines 

{
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FIntDebugForceMSAASamples": "1",
  "FFlagDebugDisableTelemetryV2Stat": "True",
  "DFIntCullFactorPixelThresholdShadowMapHighQuality": "2147483647",
  "FIntV1MenuLanguageSelectionFeaturePerMillageRollout": "0",
  "FFlagEnableInGameMenuControls": "True",
  "FFlagHandleAltEnterFullscreenManually": "False",
  "DFIntTextureQualityOverride": "3",
  "FFlagSimEnableDCD16": "true",
  "FIntTerrainArraySliceSize": "0",
  "FFlagUserShowGuiHideToggles": "True",
  "FFlagGlobalWindRendering": "false",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FIntRenderShadowIntensity": "0",
  "DFIntNumAssetsMaxToPreload": "9999999",
  "FFlagOcclusionCullingBetaFeature": "true",
  "DFFlagTeleportClientAssetPreloadingDoingExperiment": "True",
  "DFIntFrameRateMSToReduceTouchEvents": "30",
  "FFlagGameBasicSettingsFramerateCap5": "True",
  "DFIntCanHideGuiGroupId": "32380007",
  "DFIntRuntimeTickrate": "60",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "FFlagDebugGraphicsPreferD3D11FL10": "True",
  "FFlagEnableTFFeedbackModeEntryCheck": "False",
  "FIntSmoothMouseSpringFrequencyTenths": "100",
  "DFIntAnimationLodFacsDistanceMax": "0",
  "FFlagNewCameraControls_MouseDeltaFix": "True",
  "FFlagTouchscreenSupport": "True",
  "FIntRuntimeMaxNumOfDPCs": "64",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "FIntRenderShadowmapBias": "0",
  "DFIntInitialAccelerationLatencyMultTenths": "1",
  "DFIntRuntimeConcurrency": "16",
  "FFlagDisableFeedbackSoothsayerCheck": "False",
  "DFIntTaskSchedulerTargetFps": "999999",
  "FFlagVideoRenderUseHardwareBuffer": "True",
  "DFFlagDisableDPIScale": "True",
  "FFlagAddHapticsToggle": "False",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FLogNetwork": "7",
  "FFlagEnableInGameMenuChrome": "False",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FIntFullscreenTitleBarTriggerDelayMillis": "18000000",
  "FIntRuntimeMaxNumOfSemaphores": "4000000",
  "FFlagUserCameraControlLastInputTypeUpdate": "True",
  "FFlagAlwaysShowVRToggleV3": "False",
  "FIntRuntimeMaxNumOfLatches": "4000000",
  "FFlagChatTranslationSettingEnabled3": "False",
  "FIntDefaultMeshCacheSizeMB": "256",
  "FFlagDisablePostFx": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagUserCameraInputRefactor3": "True",
  "FFlagEnableInGameMenuModernization": "True",
  "FIntEnableCullableScene2HundredthPercent3": "1000",
  "FFlagNewLightAttenuation": "True",
  "FFlagAdServiceEnabled": "False",
  "FFlagEnableInGameMenuChromeABTest4": "False",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "FFlagDebugGraphicsPreferOpenGL": "True",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "FFlagDebugGraphicsPreferD3D11": "True",
  "FIntNewInGameMenuPercentRollout3": "0",
  "DFIntDebugFRMQualityLevelOverride": "1",
  "FFlagNewCameraControls_SpeedAdjustEnum": "False",
  "DFIntDebugPerformanceControlFrameTime": "2",
  "DFFlagDebugPauseVoxelizer": "True",
  "FFlagRenderGpuTextureCompressor": "True",
  "FFlagChatTranslationEnableSystemMessage": "False",
  "FFlagUpdateHealthBar": "False",
  "FIntRuntimeMaxNumOfMutexes": "4000000",
  "FFlagDebugNextGenReplicatorEnabledWriteCFrameColor": "true",
  "FFlagVideoTextureSupportHardwareRender2": "true",
  "DFIntCullFactorPixelThresholdShadowMapLowQuality": "2147483647",
  "DFIntAnimationLodFacsDistanceMin": "0",
  "FIntRobloxGuiBlurIntensity": "0",
  "DFIntAnimationLodFacsVisibilityDenominator": "0",
  "FFlagGraphicsEnableD3D10Compute": "True",
  "FFlagFastGPULightCulling3": "True",
  "FFlagUserUpdateInputConnections": "True",
  "FIntRuntimeMaxNumOfConditions": "4000000",
  "FFlagGlobalWindActivated": "False",
  "FFlagDebugForceFSMCPULightCulling": "True",
  "FFlagDebugRenderCollectGpuCounters": "True",
  "DFIntPerformanceControlFrameTimeMax": "4",
  "FIntRenderGrassHeightScaler": "0",
  "DFFlagUseVisBugChecks": "True",
  "FFlagEnablePerformanceControlStreamingDistance2": "true",
  "FFlagNextGenReplicatorEnabledWrite": "true",
  "FIntRenderGrassDetailStrands": "0",
  "FFlagUserCameraInputDt": "True",
  "FFlagFixTextureCompositorFramebufferManagement2": "True",
  "FIntTerrainOTAMaxTextureSize": "1024",
  "DFFlagTeleportClientAssetPreloadingEnabled9": "True",
  "FIntFRMMaxGrassDistance": "0",
  "FFlagNextGenReplicatorEnabledRead": "true",
  "DFIntMaxFrameBufferSize": "4",
  "FFlagDebugCheckRenderThreading": "True",
  "DFFlagDebugPerfMode": "False",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagReportGpuLimitedToPerfControl": "False",
  "DFFlagTeleportClientAssetPreloadingEnabledIXP2": "True",
  "FFlagDebugGraphicsDisableDirect3D11": "False",
  "DFIntPerformanceControlTextureQualityBestUtility": "-1",
  "FFlagEnableVisBugChecks27": "True",
  "FIntUITextureMaxRenderTextureSize": "1024",
  "DFFlagNextGenRepRollbackOverbudgetPackets": "true",
  "FFlagRenderEnableGlobalInstancingD3D10": "True",
  "FIntEnableVisBugChecksHundredthPercent27": "1000",
  "FIntFRMMinGrassDistance": "0",
  "FFlagRenderDynamicResolutionScale6": "true",
  "DFIntPerformanceControlReportingPeriodInMs": "1500",
  "FIntRuntimeMaxNumOfSchedulers": "4000000",
  "DFIntTeleportClientAssetPreloadingHundredthsPercentage2": "100000",
  "DFFlagTeleportClientAssetPreloadingEnabledIXP": "True",
  "DFIntThrottlingPredictionAccelerationHoldThousandth": "2",
  "FFlagEnableCullableScene2OptimizeStep": "true",
  "FFlagRenderSkipReadingShaderData": "True",
  "FIntRenderLocalLightUpdatesMax": "1",
  "FIntRenderLocalLightFadeInMs": "0",
  "FIntRenderLocalLightUpdatesMin": "1",
  "FIntRomarkStartWithGraphicQualityLevel": "1",
  "DFFlagTeleportClientAssetPreloadingDoingExperiment2": "True",
  "DFIntGraphicsOptimizationModeFRMFrameRateTarget": "60",
  "FFlagDebugSkyGray": "True",
  "DFIntServerPhysicsUpdateRate": "60",
  "FFlagGraphicsGLEnableSuperHQShadersExclusion": "False",
  "DFFlagBatchAssetApiNoFallbackOnFail": "False",
  "FFlagEnableReportAbuseMenuRoactABTest2": "False",
  "FFlagEnableNewHeapSnapshots": "False",
  "DFStringTelegrafHTTPTransportUrl": "null",
  "FFlagEnableNewInviteMenuIXP2": "False",
  "DFStringRobloxAnalyticsURL": "null",
  "FStringInGameMenuChromeForcedUserIds": "1353919681",
  "FFlagEnableQuickGameLaunch": "False",
  "FStringCredit": "Potato Mode | @KiwisASkid on YT",
  "FFlagPreloadTextureItemsOption4": "True",
  "FIntEmotesAnimationsPerPlayerCacheSize": "16778899",
  "DFFlagAudioDeviceTelemetry": "False",
  "DFStringTelemetryV2Url": "null",
  "DFIntRakNetMtuValue3InBytes": "1200",
  "DFStringAltHttpPointsReporterUrl": "null",
  "FFlagEnableInGameMenuV3": "True",
  "FStringPerformanceSendMeasurementAPISubdomain": "opt-out",
  "DFFlagEnableHardwareTelemetry": "False",
  "DFFlagRakNetUseSlidingWindow4": "True",
  "DFIntUserIdPlayerNameCacheSize": "33554432",
  "DFFlagSimReportCPUInfo": "False",
  "DFIntReportOutputDeviceInfoRateHundredthsPercentage": "0",
  "DFIntRakNetNakResendDelayMs": "10",
  "FFlagLuaAppExitModal2": "False",
  "FFlagEnableBetaBadgeLearnMore": "false",
  "FFlagRenderPerformanceTelemetry": "False",
  "FFlagGraphicsGLEnableHQShadersExclusion": "False",
  "FFlagVoiceBetaBadge": "false",
  "FFlagTopBarUseNewBadge": "False",
  "FIntHSRClusterSymmetryDistancePercent": "10000",
  "FFlagControlBetaBadgeWithGuac": "false",
  "FFlagBetaBadgeLearnMoreLinkFormview": "false",
  "DFFlagESGamePerfMonitorEnabled": "False",
  "FFlagEnableMenuModernizationABTest": "False",
  "FFlagCloudsReflectOnWater": "True",
  "FFlagEnableFavoriteButtonForUgc": "True",
  "FFlagEnableAudioOutputDevice": "false",
  "FFlagEnableTerrainFoliageOptimizations": "True",
  "FFlagTweenOptimizations": "True",
  "DFStringLightstepToken": "null",
  "FFlagOptimizeNetworkTransport": "True",
  "FFlagSimIslandizerManager": "false",
  "DFIntRakNetNakResendDelayMsMax": "100",
  "DFIntLightstepHTTPTransportHundredthsPercent2": "0",
  "FIntBootstrapperTelemetryReportingHundredthsPercentage": "0",
  "DFIntRakNetNakResendDelayRttPercent": "50",
  "DFIntGoogleAnalyticsLoadPlayerHundredth": "0",
  "FFlagAnimatePhysics": "False",
  "DFIntUserIdPlayerNameLifetimeSeconds": "86400",
  "DFStringAltTelegrafHTTPTransportUrl": "null",
  "FFlagOptimizeNetwork": "True",
  "DFFlagDisableFastLogTelemetry": "True",
  "DFFlagBrowserTrackerIdTelemetryEnabled": "False",
  "DFFlagEnableLightstepReporting2": "False",
  "FFlagRenderFixFog": "True",
  "DFFlagDebugAnalyticsSendUserId": "False",
  "FFlagOptimizeEmotes": "False",
  "FFlagEnableReportAbuseMenuLayerOnV3": "false",
  "FIntReportDeviceInfoRollout": "0",
  "FStringNote": "CHANGE TO false IF YOU DONT WANNA HAVE GRAY SKYBOX",
  "FIntLmsClientRollout2": "0",
  "FFlagUseUnifiedRenderStepped": "False",
  "DFIntMaxProcessPacketsStepsAccumulated": "0",
  "DFIntRakNetResendRttMultiple": "1",
  "FFlagNewNetworking": "False",
  "FFlagMSRefactor5": "False",
  "FFlagUseParticlesV2": "False",
  "FFlagEnableNewInput": "True",
  "FFlagEnableSoundTelemetry": "False",
  "DFIntMegaReplicatorNetworkQualityProcessorUnit": "10",
  "DFIntRakNetLoopMs": "1",
  "DFStringRobloxAnalyticsSubDomain": "opt-out",
  "FFlagRenderCheckThreading": "True",
  "FStringErrorUploadToBacktraceBaseUrl": "https://opt-out.roblox.com",
  "FFlagUseDeferredContext": "False",
  "DFIntPlayerNetworkUpdateQueueSize": "20",
  "FFlagLuaAppSystemBar": "False",
  "DFIntS2PhysicsSenderRate": "250",
  "DFIntCodecMaxOutgoingFrames": "10000",
  "FFlagCoreGuiTypeSelfViewPresent": "False",
  "DFIntRenderingThrottleDelayInMS": "1",
  "FStringCoreScriptBacktraceErrorUploadToken": "null",
  "DFStringAnalyticsEventStreamUrlEndpoint": "opt-out",
  "DFIntRunningBaseOrientationP": "115",
  "DFIntWaitOnRecvFromLoopEndedMS": "100",
  "FFlagTaskSchedulerLimitTargetFpsTo2402": "False",
  "DFStringLightstepHTTPTransportUrlPath": "null",
  "FFlagUseDynamicSun": "False",
  "DFIntServerTickRate": "60",
  "FFlagEnableLightAttachToPart": "False",
  "FFlagEnableTerrainOptimizations": "True",
  "DFIntNewRunningBaseAltitudeD": "45",
  "FFlagEnableHumanoidLuaSideCaching": "False",
  "FFlagFixGraphicsQuality": "True",
  "DFIntNetworkLatencyTolerance": "1",
  "DFIntCodecMaxIncomingPackets": "100",
  "FFlagPreloadAllFonts": "False",
  "FFlagPreloadMinimalFonts": "True",
  "DFIntRaknetBandwidthInfluxHundredthsPercentageV2": "10000",
  "DFIntLargePacketQueueSizeCutoffMB": "1000",
  "FFlagEnableMenuModernizationABTest2": "False",
  "FIntRakNetDatagramMessageIdArrayLength": "1024",
  "DFIntPlayerNetworkUpdateRate": "60",
  "DFStringLightstepHTTPTransportUrlHost": "null",
  "FFlagGpuGeometryManager7": "True",
  "FFlagAnimationClipMemCacheEnabled": "True",
  "FFlagLuaAppExitModalDoNotShow": "True",
  "FFlagDebugLightGridShowChunks": "False",
  "FFlagFixScalingModelRendering": "False",
  "FFlagInGameMenuV1FullScreenTitleBar": "False",
  "FFlagOptimizeNetworkRouting": "True",
  "DFIntWaitOnUpdateNetworkLoopEndedMS": "100",
  "FFlagUseNewAnimationSystem": "False",
  "DFIntMaxProcessPacketsJobScaling": "10000",
  "DFIntMaxProcessPacketsStepsPerCyclic": "5000",
  "DFFlagBaseNetworkMetrics": "False",
  "FStringGamesUrlPath": "/games/",
  "DFStringHttpPointsReporterUrl": "null",
  "FFlagOptimizeServerTickRate": "True",
  "DFIntRakNetMtuValue1InBytes": "1280",
  "FFlagEnableReportAbuseMenuRoact2": "false",
  "FIntRakNetResendBufferArrayLength": "128",
  "FFlagNullCheckCloudsRendering": "True",
  "FFlagGraphicsSettingsOnlyShowValidModes": "True",
  "DFIntNetworkPrediction": "120",
  "FIntStartupInfluxHundredthsPercentage": "0",
  "FIntCameraMaxZoomDistance": "99999",
  "DFFlagEnableFmodErrorsTelemetry": "False",
  "DFIntRakNetMtuValue2InBytes": "1240",
  "FFlagBatchAssetApi": "True",
  "FFlagFeedbackEntryPointButtonSizeAdjustment2": "False",
  "FFlagFeedbackEntryPointImprovedStrictnessCheck": "False",
  "FFlagDisableChromeDefaultOpen": "True",
  "FFlagDisableChromeFollowupFTUX": "True",
  "FFlagDisableChromeFollowupOcclusion": "True",
  "FFlagDisableChromeFollowupUnibar": "True",
  "FFlagDisableChromePinnedChat": "True",
  "FFlagDisableChromeUnibar": "True",
  "FIntRenderGrassDensityMax": "0",
  "FIntRenderGrassDensityMin": "0",
  "FFlagDebugDeterministicParticles": "False",
  "FFlagFixOutdatedParticles": "False",
  "FFlagFixOutdatedTimeScaleParticles": "False",
  "FFlagFixParticleAttachmentCulling": "False",
  "FFlagFixParticleEmissionBias": "False",
  "DFFlagHttpCacheCleanBasedOnMemory": "True",
  "FIntUGCValidationTorsoThresholdSide": "100",
  "FIntUGCValidationTorsoThresholdBack": "100",
  "FFlagEnableCameraByDefault": "False",
  "DFStringAnalyticsNS1ApplicationId": "opt-out",
  "FFlagLocServicePerformanceAnalyticsEnabled": "False",
  "FFlagEnableAccessibilitySettingsInExperienceMenu2": "True",
  "FFlagEnableAccessibilitySettingsEffectsInExperienceChat": "True",
  "FFlagFacialAnimationStreamingServiceUserSettingsOptInVideo": "False",
  "FIntUGCValidationLeftArmThresholdSide": "40",
  "FFlagFacialAnimationStreamingServiceUniverseSettingsEnableVideo": "False",
  "FFlagAudioDeviceTelemetry": "false",
  "DFFlagEnableMemProfilingOutsideClient": "False",
  "FStringTerrainMaterialTable2022": "",
  "FIntAbuseReportScreenshotMaxSize": "0",
  "FIntFlagUpdateVersion": "132",
  "DFFlagClientBaseNetworkMetrics": "False",
  "FIntScrollWheelDeltaAmount": "50",
  "DFFlagAddPublicGettersForGfxQualityAndFpsForTelemCounters2": "False",
  "DFIntWriteFullDmpPercent": "0",
  "FFlagEnableBatteryStateLogger": "False",
  "DFFlagGpuVsCpuBoundTelemetry": "False",
  "FFlagEnableAccessibilitySettingsAPIV2": "True",
  "FIntUGCValidationLeftArmThresholdFront": "27",
  "DFFlagAvatarChatServiceUserPermissionsAudioEligible": "False",
  "DFFlagAddUserIdToSessionTracking": "False",
  "FIntLinkBrowserTrackerToDeviceRollout": "0",
  "FIntUGCValidationRightLegThresholdSide": "38",
  "DFIntBrowserTrackerApiDeviceInitializeRolloutPercentage": "0",
  "FIntUGCValidationLeftArmThresholdBack": "23",
  "FFlagAvatarChatSettingsEnabled2": "False",
  "FFlagVoiceChatServiceManagerUseAvatarChat": "False",
  "FFlagDebugGraphicsDisableVulkan": "True",
  "FFlagDebugGraphicsDisableOpenGL": "True",
  "FFlagAddGameInstanceIdToSessionTracking": "False",
  "FFlagTrackWinWebLaunchFlow": "False",
  "FStringTerrainMaterialTablePre2022": "",
  "DFIntMinimalNetworkPrediction": "1",
  "FIntUGCValidationRightArmThresholdSide": "40",
  "FIntUGCValidationLeftLegThresholdSide": "36",
  "FIntUGCValidationLeftLegThresholdBack": "40",
  "FIntUGCValidationRightLegThresholdFront": "40",
  "FStringImmersiveAdsUniverseWhitelist": "0",
  "FFlagFacialAnimationStreamingServiceUserSettingsOptInAudio": "False",
  "DFIntLoginTelemetryHundredthsPercent": "0",
  "FFlagTrackMacWebLaunchFlow": "False",
  "DFIntStartupTracingInfluxRollout": "0",
  "FFlagDebugGraphicsDisableVulkan11": "True",
  "FIntUGCValidationLeftLegThresholdFront": "40",
  "FFlagDebugRenderingSetDeterministic": "True",
  "FIntUGCValidationRightLegThresholdBack": "40",
  "FFlagEnableAccessibilitySettingsEffectsInCoreScripts2": "True",
  "FIntUGCValidationRightArmThresholdBack": "23",
  "FFlagEnableAdsAPI": "False",
  "DFFlagPredictedOOM": "False",
  "FFlagAvatarChatServiceExposeClientFeaturesForVoiceChat": "False",
  "DFFlagDebugEnableInterpolationVisualizer": "true",
  "DFFlagAvatarChatServiceUserPermissionsAudioOptIn": "False",
  "FFlagReportFpsAndGfxQualityPercentiles": "False",
  "DFFlagEnableMemProfilingStorePlaceId": "False",
  "FIntUGCValidationTorsoThresholdFront": "100",
  "DFIntPredictedOOMPercent": "0",
  "DFFlagEnableGCapsHardwareTelemetry": "False",
  "DFStringAnalyticsNS1BeaconConfig": "https://opt-out.roblox.com",
  "FIntUGCValidationRightArmThresholdFront": "25",
  "FFlagFacialAnimationStreamingServiceUniverseSettingsEnableAudio": "False",
  "FIntRenderEnableGlobalInstancingD3D11Percent": "100",
  "FFlagGraphicsCheckComputeSupport": "True",
  "FFlagWindowsLaunchAnalytics": "False",
  "DFFlagEphemeralCounterInfluxReportingEnabled": "False",
  "FIntTaskSchedulerAutoThreadLimit": "8",
  "FFlagImmersiveAdsWhitelistDisabled": "False",
  "FFlagRenderDebugCheckThreading2": "True",
  "FFlagEnableBubbleChatFromChatService": "True",
  "FIntTaskSchedulerThreadMin": "3",
  "DFIntTimestepArbiterThresholdCFLThou": "300",
  "FFlagUserHideCharacterParticlesInFirstPerson": "True",
  "FFlagNewCameraControls": "True",
  "DFIntAssetPreloading": "9999999",
  "FIntRuntimeMaxNumOfThreads": "2400",
  "FFlagGuiHidingApiSupport2": "True",
  "FIntVRTouchControllerTransparency": "0",
  "FFlagLuaAppGenreUnderConstruction": "False",
  "FFlagEnableBetterHapticsResultHandling": "True",
  "FStringTencentAuthPath": "null",
  "FIntMeshContentProviderForceCacheSize": "26999999",
  "DFIntHardwareTelemetryHundredthsPercent": "0",
  "DFIntReportRecordingDeviceInfoRateHundredthsPercentage": "0",
  "FFlagCommitToGraphicsQualityFix": "True",
  "DFStringCrashUploadToBacktraceBaseUrl": "null",
  "FFlagTrackPlaceIdForCrashEnabled": "False",
  "DFStringCrashUploadToBacktraceWindowsPlayerToken": "null",
  "FFlagFixMeshPartScaling": "False",
  "DFStringCrashUploadToBacktraceMacPlayerToken": "null",
  "FFlagDebugCrashReports": "False",
  "FFlagHumanoidParallelFixTickleFloor2_PlaceFilter": "True",
  "FFlagFixMemoryPriorizationCrash": "True",
  "FFlagDebugForceChatDisabled": "False",
  "FFlagDebugGraphicsCrashOnLeaks": "False",
  "FFlagEnableInGameMenuChromeABTest": "True",
  "FFlagDebugGraphics": "False",
  "DFIntCrashReportingHundredthsPercentage": "0",
  "DFIntDetectCrashEarlyPercentage": "0",
  "FFlagEnableInGameMenuChromeABTest2": "False",
  "DFIntCrashUploadToBacktracePercentage": "0",
  "DFFlagCrashUploadFullDumps": "False",
  "DFIntFreeFallOrientationP": "300",
  "FIntNewDevConsoleMaxGraphCount": "2",
  "FIntNewDevConsoleMaxHttpCount": "2",
  "FIntNewDevConsoleMaxLogCount": "2",
  "DFIntGettingUpBalanceD": "50",
  "DFIntGettingUpBalanceP": "5000",
  "DFIntHumanoidFloorManualFrictionVelocityMultValue": "0",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagDebugDisplayFPS": "False",
  "FStringPartTexturePackTablePre2022": "{\u0022foil\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873266399\u0022,\u0022rbxassetid://9438410239\u0022],\u0022color\u0022:[238,238,238,255]},\u0022asphalt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9930003180\u0022,\u0022rbxassetid://9438410548\u0022],\u0022color\u0022:[227,227,228,234]},\u0022basalt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920482224\u0022,\u0022rbxassetid://9438413638\u0022],\u0022color\u0022:[160,160,158,238]},\u0022brick\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920482992\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[229,214,205,227]},\u0022cobblestone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9919719550\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,219,219,243]},\u0022concrete\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920484334\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[225,225,224,255]},\u0022crackedlava\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920485426\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[76,79,81,156]},\u0022diamondplate\u0022:{\u0022ids\u0022:[\u0022rbxassetid://10237721036\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[210,210,210,255]},\u0022fabric\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920517963\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[221,221,221,255]},\u0022glacier\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920518995\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[225,229,229,243]},\u0022glass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873284556\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[254,254,254,7]},\u0022granite\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920550720\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[210,206,200,255]},\u0022grass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920552044\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[196,196,189,241]},\u0022ground\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920554695\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[165,165,160,240]},\u0022ice\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920556429\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[235,239,241,248]},\u0022leafygrass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920558145\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[182,178,175,234]},\u0022limestone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920561624\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[250,248,243,250]},\u0022marble\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873292869\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[181,183,193,249]},\u0022metal\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920574966\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[226,226,226,255]},\u0022mud\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920578676\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[193,192,193,252]},\u0022pavement\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920580094\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,218,219,236]},\u0022pebble\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920581197\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[204,203,201,234]},\u0022plastic\u0022:{\u0022ids\u0022:[\u0022\u0022,\u0022rbxassetid://9475422736\u0022],\u0022color\u0022:[255,255,255,255]},\u0022rock\u0022:{\u0022ids\u0022:[\u0022rbxassetid://10129366149\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[211,211,210,248]},\u0022corrodedmetal\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920589512\u0022,\u0022rbxassetid://9439557520\u0022],\u0022color\u0022:[206,177,163,180]},\u0022salt\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920590478\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[249,249,249,255]},\u0022sand\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920591862\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[218,216,210,240]},\u0022sandstone\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920596353\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[241,234,230,246]},\u0022slate\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920600052\u0022,\u0022rbxassetid://9439613006\u0022],\u0022color\u0022:[235,234,235,254]},\u0022snow\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920620451\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[239,240,240,255]},\u0022wood\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920625499\u0022,\u0022rbxassetid://9439649548\u0022],\u0022color\u0022:[217,209,208,255]},\u0022woodplanks\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9920626896\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[207,208,206,254]}}",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableInGameMenuChromeABTest3": "False",
  "DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent": "0",
  "DFIntClientLightingEnvmapPlacementTelemetryHundredthsPercent": "100",
  "FFlagDebugEnableOctreeValidation": "False",
  "FFlagChromeBetaFeature": "False",
  "FFlagChromeCapturesToggle2": "False",
  "FFlagChromeObservableStateCheck": "False",
  "FFlagChromeUsePreferredTransparency": "False",
  "FFlagDisableChromeV3Baseline": "True",
  "FFlagDisableChromeV3Captures": "True",
  "FFlagDisableChromeV3DockedMic": "True",
  "FFlagDisableChromeV3Icon": "True",
  "FFlagDisableChromeV3StaticSelfView": "True",
  "FFlagAppChatRebrandIconUpdates": "False"
}

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
