### ISSUE TITLE
[BUG] an exeption occured while running bloxstrap

### ISSUE THREAD

**Issue by rvfy** [bloxstraplabs/bloxstrap#3928]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

i encounter a bug or something that i didnt fully understand on how to remove it,please help me download bloxstrap,thank you

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by totallyphysicallypossible** [comment]
update bloxstrap

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
