### ISSUE TITLE
[REQ] when will fast flags and other channels reopen?

### ISSUE THREAD

**Issue by ImMrJakob** [bloxstraplabs/bloxstrap#3929]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I need these channels asap and was wondering when they would reopen

**Comment by nabheyka880** [comment]
why would you want the channel changing

**Comment by ImMrJakob** [comment]
i dont want it to change i was just asking when the channels would re open
