### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by Skibidi-cr** [bloxstraplabs/bloxstrap#3931]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

help

### Bloxstrap Log

```text
help\
```

**Comment by nabheyka880** [comment]
update
we don't provide support for older versions
https://bloxstraplabs.com/

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.

**Comment by Skibidi-cr** [comment]
repeat wait() until game:IsLoaded() and game.Players.LocalPlayer
loadstring(game:HttpGet("
https://raw.githubusercontent.com/AnDepZaiHub/AnDepZaiHubBeta/refs/heads/main/AnDepZaiHubNewUpdated.lua
"))()

Vào 19:51, Th 7, 7 thg 12, 2024 Matt ***@***.***> đã viết:
