### ISSUE TITLE
[BUG] İ am opening roblox  freezing and crashing

### ISSUE THREAD

**Issue by ALPERENX1** [bloxstraplabs/bloxstrap#3936]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

İ am opening roblox and freezing and crashing

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
