### ISSUE TITLE
[BUG] Roblox refuses to launch on a fresh installation of Windows 11 Enterprise LTSC / IoT 

### ISSUE THREAD

**Issue by rabbithawk256** [bloxstraplabs/bloxstrap#3938]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I've done a fresh installation of Windows 11 LTSC IoT 2024 on brand new hardware, but Roblox refuses to launch - neither the client bootstrapper nor Bloxstrap work; in both cases, Roblox will open for a second (as shown by Task Manager) and close instantly, rendering itself unplayable.

A possible lead is the time of day on the system being out of sync by about half a day, now fixed by performing a re-sync to the Windows Time Service. I did read somewhere (can't remember where, sorry!) about this causing issues with the client - and the solution being to wait a few hours for it to resync.

I've already tried reinstalling both Bloxstrap and Roblox, along with restarting the machine.

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
