### ISSUE TITLE
[REQ] where is edit the menu ui Feature

### ISSUE THREAD

**Issue by ahmeddoleyhere** [bloxstraplabs/bloxstrap#3945]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In the old versions you had the feature to change the menu, where did it go?

**Comment by cocoandliza** [comment]
where its always been, the apperance section

**Comment by ahmeddoleyhere** [comment]
![image](https://github.com/user-attachments/assets/009db7fa-e0bd-46a4-acc8-21efc136d539)

**Comment by totallyphysicallypossible** [comment]
doesn't exist anymore, other options have either been removed or broken by roblox

**Comment by ahmeddoleyhere** [comment]
bruhh

**Comment by cocoandliza** [comment]
it still exists?

**Comment by ahmeddoleyhere** [comment]
No, it does not exist. I was asking because I had downloaded Blockstrap a long time ago, and I downloaded it again now and found that the option had disappeared.

**Comment by ahmeddoleyhere** [comment]
bruh i mean bloxstrap not block strap

**Comment by bluepilledgreat** [comment]
Removed due to stability issues.
