### ISSUE TITLE
[BUG] cant join roblox

### ISSUE THREAD

**Issue by thefemboylover** [bloxstraplabs/bloxstrap#3946]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v 2.8.1

### What problem did you encounter?

idk if this is a roblox issue or bloxstrap, when im joining a game it either isnt loaded like it should be, or give me error 0

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
