### ISSUE TITLE
[BUG] bloxtrap taking forever to install

### ISSUE THREAD

**Issue by liryxx** [bloxstraplabs/bloxstrap#3950]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

![{11D51681-BC84-4F32-B6DC-C0CBE8756250}](https://github.com/user-attachments/assets/af4b37c7-96df-4ea2-be10-dd23d0302669)

### Bloxstrap Log

```text
N/A
```

**Comment by totallyphysicallypossible** [comment]
update bloxstrap
