### ISSUE TITLE
[BUG] Doesn't work

### ISSUE THREAD

**Issue by jordaniwya** [bloxstraplabs/bloxstrap#3951]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

Says this whenever i press install
![image](https://github.com/user-attachments/assets/712324f8-cd12-44cd-b1f6-48cd6a319921)

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by totallyphysicallypossible** [comment]
update bloxstrap
