### ISSUE TITLE
[BUG] roblox failed to launch

### ISSUE THREAD

**Issue by cediiiiii** [bloxstraplabs/bloxstrap#3952]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

roblox failed to launch
![image_2024-12-08_234747677](https://github.com/user-attachments/assets/0f56ccd7-f403-4753-9d96-bf3e4c5ac9ef)

### Bloxstrap Log

```text
roblox failed to launch
```

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
