### ISSUE TITLE
[BUG] pixelized

### ISSUE THREAD

**Issue by NeedTechSupport** [bloxstraplabs/bloxstrap#3953]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

latest

### What problem did you encounter?

![image_2024-12-09_112145434](https://github.com/user-attachments/assets/10f92982-13bd-4030-9c00-7cfc66ab1f1e)
Hello whenever i launch the game the GUI is pixelized even the login screen on the desktop app

**Comment by totallyphysicallypossible** [comment]
did you change this by any chance
![image](https://github.com/user-attachments/assets/6855f87c-2f84-431b-9ccc-d9347d868596)
