### ISSUE TITLE
[BUG] Roblox Force reinstallation is greyed out and can't be turnt off

### ISSUE THREAD

**Issue by cscor1** [bloxstraplabs/bloxstrap#3956]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.81

### What problem did you encounter?

fix force roblox reinstallation being FORCED on and is grayed out so I can't turn it off
![image](https://github.com/user-attachments/assets/b777d737-0f93-4170-9f41-56d80eb61d7f)

### Bloxstrap Log

```text
N/A
```

**Comment by totallyphysicallypossible** [comment]
i swear to god how are there people actually thinking this is a bug
bloxstrap NEEDS TO INSTALL ROBLOX TO OPEN ROBLOX

**Comment by cscor1** [comment]
When I open roblox it still won't save my settings from when I played and resets everything constantly 

> bloxstrap needs to install roblox to open roblox, just install and play once and before you ask why, bloxstrap installs its own roblox instance seperate from roblox's own bootstrapper, you can find that in \Bloxstrap\Roblox\Player
