### ISSUE TITLE
[BUG] An exception occured while running bloxstrap

### ISSUE THREAD

**Issue by Ezzaa-star** [bloxstraplabs/bloxstrap#3958]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/520a3ebe-8c37-4723-8697-75120b0cbcc8)

### Bloxstrap Log

```text
N/A
```

**Comment by whyd0ineedausername** [comment]
update bloxstrap we dont support older versions
