### ISSUE TITLE
[BUG] What the fuck is that?

### ISSUE THREAD

**Issue by darkkalcor** [bloxstraplabs/bloxstrap#3965]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

Ваш файл аж 8 балов набирает это что блять? Я что как мелкий даун сижу на ратке?  Помогите пж. Вот ссылка на тест вашего лаунчера: https://tria.ge/241211-akd18awmft/behavioral1

**Comment by bluepilledgreat** [comment]
kid named false positive
