### ISSUE TITLE
[BUG] Dr

### ISSUE THREAD

**Issue by Baimgank** [bloxstraplabs/bloxstrap#3966]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### what problem did you encounter

the lightning doesnt work when using d3D10 (give me a solution because no one knows what my problem is i asked all roblox creator with bloxstrap, they didnt even know what is direct3D😭😭😭)

![IMG20241211113415](https://github.com/user-attachments/assets/8e3f68db-84d3-469e-81b3-a51687dd599c)

![IMG_20241211_113510](https://github.com/user-attachments/assets/1852ad83-1987-4292-bf79-d17007ff2a79)

**Comment by totallyphysicallypossible** [comment]
direct3d 10 doesn't support future lighting, also not a bloxstrap issue

**Comment by Baimgank** [comment]
> direct3d 10 doesn't support future lighting, also not a bloxstrap issue

but when i use d3D11 and a filter it look like this

![IMG_20241211_123744](https://github.com/user-attachments/assets/d886ef32-78fc-41c3-b958-cc575a4d738e)

**Comment by bluepilledgreat** [comment]
> and a filter
bro

**Comment by burgermuncha** [comment]
> > direct3d 10 doesn't support future lighting, also not a bloxstrap issue
> 
> but when i use d3D11 and a filter it look like this
> 
> ![IMG_20241211_123744](https://private-user-images.githubusercontent.com/164317153/394590961-d886ef32-78fc-41c3-b958-cc575a4d738e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTEzNTQsIm5iZiI6MTczMzkxMTA1NCwicGF0aCI6Ii8xNjQzMTcxNTMvMzk0NTkwOTYxLWQ4ODZlZjMyLTc4ZmMtNDFjMy1iOTU4LWNjNTc1YTRkNzM4ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwOTU3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTI3ZWNjZmJkYjQ0NjUyZWE0OGZkNmMzNGVmNTk3MDhiYTQ0ZWQwYjAxYTFlNzkxMDExYTljMzk2ODFhYmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8tQdKOnmqTvC_ZySQKv2ZICKcV1TQ02usyb34zqx7e0)

that looks like mine. idk why they can put filter on

**Comment by burgermuncha** [comment]
and the SSAO filter too right?
