### ISSUE TITLE
[BUG] im stuck in configuring roblox pls help a have 5 hours to fix it but it stuck im in 2.7.0

### ISSUE THREAD

**Issue by lakdim25** [bloxstraplabs/bloxstrap#3971]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.7.0

### What problem did you encounter?

![Screenshot 2024-12-11 071844](https://github.com/user-attachments/assets/ad2531ff-4188-4f92-9fbb-01cec3055dda)

![Screenshot 2024-12-11 071844](https://github.com/user-attachments/assets/d47d6418-2b4f-40bb-ba2c-3e97b56970dc)

### Bloxstrap Log

```text
12/11/2024 for 5 hours i try to find what is the problem plssss help me im tired 
pls
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com

**Comment by lakdim25** [comment]
but i need 2.7.0

**Comment by whyd0ineedausername** [comment]
no you dont update bloxstrap
