### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by mirsazul1313** [bloxstraplabs/bloxstrap#3977]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v 2.5.4

### What problem did you encounter?

i wsa installing normally bloxtrap and i got in the middle of the downlad an error     System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### Bloxstrap Log

```text
N/ABloxstrap_20241212T004230Z
```

**Comment by PakinDeReal** [comment]
soo.. update.

**Comment by PakinDeReal** [comment]
the latest version is 2.8.1 as for now

**Comment by lolasaman** [comment]
https://cdn.discordapp.com/attachments/1306241906157686878/1312279843349725204/caption.gif?ex=675bbd57&is=675a6bd7&hm=92a2671b26b2343cf49fd6d9deea47d558b3263ffd3ed033b478d855d2bdf8d1&

**Comment by lolasaman** [comment]
![ezgif-1-e5984f6676](https://github.com/user-attachments/assets/7cb28c44-65da-4652-b9d3-e19bb233e31e)
