### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Yanto689** [bloxstraplabs/bloxstrap#3979]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2,5,4

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

that's what appears on my device
![WhatsApp Image 2024-12-12 at 18 41 07_468e0433](https://github.com/user-attachments/assets/cb5b1383-d952-4e28-93a2-d0ed5d3a1f8d)
![WhatsApp Image 2024-12-12 at 18 41 07_468e0433](https://github.com/user-attachments/assets/9fc330dc-1873-4ffe-ad9f-d26cb1a56fca)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
CREATE ANOTHER FUCKING BUG REPORT I DARE YOU
