### ISSUE TITLE
Fake website in first line of search

### ISSUE THREAD

**Issue by mairellos** [bloxstraplabs/bloxstrap#3982]
Dear Bloxstrap creators,

I came to report a site that recently appeared on the first page of the search, being a blatant copy of the original. It is already known that the reliable links would be here on **GitHub** and at **https://bloxstraplabs.com/** , however, there is a site that ended up appearing suspicious and outside of what was reported: **https://bloxstrap.org/** is the site I am reporting. A copy that is possibly not authored by you. I say this so that I do not have future problems with new visitors to the application.

I patiently await a response about this site. With all due respect,

mairellos.

![Captura de tela 2024-12-12 113905](https://github.com/user-attachments/assets/da189daf-0ea4-4a89-b09a-3dcd7807c1d6)

**Comment by RealCalumPlays** [comment]
Seems to be an AdSense farm + Possible Malware. The executable it provides seems to be packed & obfuscated so its obviously not just reuploaded from GitHub. I would highly advise a warning be posted to the discord or GitHub warning users about this.

**Comment by Storm-930** [comment]
We already know this. This is likely older than when I started using Bloxstrap myself.

**Comment by bluepilledgreat** [comment]
there is nothing we can do about the fake websites

**Comment by Clairetee1223** [comment]
Just saying you can report the site to google as adware/malware and an illegal copy. 
Or put it in your website/github that the other is fake, because I went to that one first and now have to scan my entire pc for malware lol

This is an actual issue if people are going to that site and downloading malware or spyware without knowing.

**Comment by e-ave** [comment]
> Just saying you can report the site to google as adware/malware and an illegal copy. Or put it in your website/github that the other is fake, because I went to that one first and now have to scan my entire pc for malware lol
> 
> This is an actual issue if people are going to that site and downloading malware or spyware without knowing.

That website links to the official github page for the download, at least at this moment in time.
