### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kiezior** [bloxstraplabs/bloxstrap#3985]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

When i click install it says 
![obraz_2024-12-12_185617233](https://github.com/user-attachments/assets/bc70f0e1-019e-4802-83c4-fcf8ee7f2add)

### Bloxstrap Log

```text
N/A
```

**Comment by kiezior** [comment]
what should i do??

**Comment by whyd0ineedausername** [comment]
you should update bloxstrap we dont support older versions
https://bloxstraplabs.com

**Comment by kiezior** [comment]
what if i want to have multiple accs and its not on newer versions

**Comment by nabheyka880** [comment]
too bad

**Comment by whyd0ineedausername** [comment]
youre not gonna get multiple accounts

**Comment by bluepilledgreat** [comment]
> bro just stfu if ur not here to help me just get out

"bwo juwst stfuw if uww not hewe to hewp me juwst get ouwt 👉👈"

**Comment by nabheyka880** [comment]
> bro just stfu if ur not here to help me just get out

someone's mad

**Comment by kiezior** [comment]
i just asked if someone can help bc im new with the thing and u came to laugh at me

**Comment by gamerloch10** [comment]
Multi account launching is no longer supported and we don't give alternatives

**Comment by kiezior** [comment]
oh ok
