### ISSUE TITLE
[BUG] bloxstrap custom font not being removed

### ISSUE THREAD

**Issue by gitbloxstrap** [bloxstraplabs/bloxstrap#3988]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![Screenshot 2024-12-13 215049](https://github.com/user-attachments/assets/59199466-9c57-4bab-bc8d-c369a9cc3b0a)

**Comment by toast-ed** [comment]
force reinstall roblox

**Comment by bluepilledgreat** [comment]
^^^^^ pretty sure thats under "Bootstrapper"
