### ISSUE TITLE
[BUG] i cant see my activity in web discord11!!

### ISSUE THREAD

**Issue by HelloKerem** [bloxstraplabs/bloxstrap#3989]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

howa no work how tu fix11<wıdofvgbhoıgpçlßkrpb (opens the opera help-)

### Bloxstrap Log

```text
ğüğü
```

**Comment by nabheyka880** [comment]
the discord activity is only supposed to work for windows i think

**Comment by HelloKerem** [comment]
thats the thats!!!
thats the problema-

**Comment by HelloKerem** [comment]
ğüğü is a log

**Comment by toast-ed** [comment]
discord rpc only works on the windows and mac app as i know
