### ISSUE TITLE
[BUG]  Enemy Delay In PVP Games

### ISSUE THREAD

**Issue by dxnzzzz** [bloxstraplabs/bloxstrap#3990]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i got a issue,basically when im playing a pvp game , mostly blox fruits the enemy player has delay,idk if its bc my fflags or smth i will show the fflags tho
msaa 1x
disbale shadow = on
post procesing = on
terrain = on
freemate = 99999
ligthing tecno = voxel
preserve rendering = off
rendering = direct 11
texture quality = level 0
{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "FIntRenderShadowIntensity": "0",
  "FIntDebugForceMSAASamples": "1",
  "FFlagDisablePostFx": "True",
  "FIntTerrainArraySliceSize": "0",
  "DFIntTaskSchedulerTargetFps": "99999",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "FIntFullscreenTitleBarTriggerDelayMillis": "18000000",
  "DFIntTextureQualityOverride": "0",
  "FFlagDebugGraphicsPreferD3D11FL10": "False",
  "DFIntWaitOnUpdateNetworkLoopEndedMS": "100",
  "DFStringLightstepToken": "null",
  "FIntTerrainOTAMaxTextureSize": "12",
  "FIntRenderGrassDetailStrands": "0",
  "FIntRenderLocalLightUpdatesMin": "1",
  "DFIntCodecMaxOutgoingFrames": "10000",
  "FStringTerrainMaterialTablePre2022": "",
  "FIntRenderShadowmapBias": "0",
  "FFlagAdServiceEnabled": "False",
  "DFIntMaxProcessPacketsJobScaling": "10000",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FStringGamesUrlPath": "/games/",
  "FStringCoreScriptBacktraceErrorUploadToken": "null",
  "FIntDebugTextureManagerSkipMips": "2",
  "DFStringLightstepHTTPTransportUrlHost": "null",
  "FFlagFixGraphicsQuality": "True",
  "FIntRenderGrassHeightScaler": "0",
  "DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntFontSizePadding": "4",
  "DFStringCrashUploadToBacktraceBaseUrl": "null",
  "DFIntWaitOnRecvFromLoopEndedMS": "100",
  "FStringTopBarBadgeLearnMoreLink": "e.n.v.y",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagEnableInGameMenuChromeABTest2": "False",
  "FFlagEnableReportAbuseMenuRoactABTest2": "False",
  "DFIntCodecMaxIncomingPackets": "100",
  "DFStringCrashUploadToBacktraceMacPlayerToken": "null",
  "DFStringCrashUploadToBacktraceWindowsPlayerToken": "null",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "DFIntLightstepHTTPTransportHundredthsPercent2": "0",
  "DFStringTelemetryV2Url": "null",
  "FFlagDebugSkyGray": "True",
  "DFIntRakNetLoopMs": "1",
  "FFlagFastGPULightCulling3": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "DFStringHttpPointsReporterUrl": "null",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "DFStringRobloxAnalyticsURL": "null",
  "FFlagDebugDisableTelemetryV2Stat": "True",
  "DFStringAltTelegrafHTTPTransportUrl": "null",
  "DFIntCanHideGuiGroupId": "32380007",
  "DFStringLightstepHTTPTransportUrlPath": "null",
  "FFlagPreloadAllFonts": "False",
  "DFFlagEnableLightstepReporting2": "False",
  "DFStringAnalyticsEventStreamUrlEndpoint": "null",
  "DFIntRaknetBandwidthInfluxHundredthsPercentageV2": "10000",
  "DFStringAltHttpPointsReporterUrl": "null",
  "DFIntMaxProcessPacketsStepsPerCyclic": "5000",
  "DFIntMegaReplicatorNetworkQualityProcessorUnit": "10",
  "DFStringTelegrafHTTPTransportUrl": "null",
  "DFIntLargePacketQueueSizeCutoffMB": "1000",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FIntRenderLocalLightUpdatesMax": "1",
  "DFIntMaxProcessPacketsStepsAccumulated": "0",
  "DFIntS2PhysicsSenderRate": "38000",
  "FStringTerrainMaterialTable2022": "",
  "FFlagDebugGraphicsPreferD3D11": "True",
  "DFIntCSGLevelOfDetailSwitchingDistance": "0",
  "DFIntRakNetClockDriftAdjustmentPerPingMillisecond": "100",
  "DFIntDebugFRMQualityLevelOverride": "1",
  "FFlagEnableInGameMenuChromeABTest4": "False",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagDebugForceFutureIsBrightPhase2": "True",
  "DFIntPerformanceControlTextureQualityBestUtility": "-1",
  "FIntNewInGameMenuPercentRollout3": "0",
  "FFlagDebugCheckRenderThreading": "True",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "DFIntRenderingThrottleDelayInMS": "1",
  "DFIntRaknetBandwidthPingSendEveryXSeconds": "1",
  "DFIntConnectionMTUSize": "1200",
  "FFlagEnableInGameMenuChromeABTest3": "False",
  "DFIntRakNetResendRttMultiple": "1",
  "DFIntCSGLevelOfDetailSwitchingDistanceL34": "0",
  "FFlagDebugRenderingSetDeterministic": "True",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagDebugGraphicsPreferOpenGL": "True",
  "FIntScrollWheelDeltaAmount": "140",
  "DFFlagDebugPauseVoxelizer": "True",
  "FFlagEnableInGameMenuChrome": "True",
  "FIntRuntimeMaxNumOfThreads": "2400",
  "DFFlagDebugPerfMode": "False",
  "DFIntTextureCompositorActiveJobs": "0",
  "DFFlagDisableFastLogTelemetry": "True",
  "DFIntCSGLevelOfDetailSwitchingDistanceL12": "0",
  "FFlagNewLightAttenuation": "True",
  "FFlagEnableInGameMenuModernization": "True",
  "FFlagEnableInGameMenuControls": "True",
  "DFIntCSGLevelOfDetailSwitchingDistanceL23": "0",
  "DFIntMaxFrameBufferSize": "4",
  "DFFlagBrowserTrackerIdTelemetryEnabled": "False",
  "FFlagTaskSchedulerLimitTargetFpsTo2402": "False",
  "FIntTaskSchedulerThreadMin": "3",
  "FFlagGameBasicSettingsFramerateCap5": "True",
  "FFlagRenderDebugCheckThreading2": "True"

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
⍜⊑ ⋔⊬ ⎎⎍☊☍⟟⋏☌ ☌⍜⎅ ⌿⌰⟒⏃⌇⟒ ⟊⎍⌇⏁ ⎅⟒⌰⟒⏁⟒ ⏃⌰⌰ ⊬⍜⎍⍀ ⎎⏃⌇⏁ ⎎⌰⏃☌⌇ ⏃⋏⎅ ⋏⟒⎐⟒⍀ ⋔⏃☍⟒ ⏃ ⟟⌇⌇⎍⟒ ⍜⋏ ⏁⊑⟟⌇ ☌⟟⏁⊑⎍⏚ ⍀⟒⌿⍜⌇⟟⏁⍜⍀⊬ ⟒⎐⟒⍀ ⏃☌⏃⟟⋏. ⊬⍜⎍ ⏃⍀⟒ ⍙⏃⌇⏁⟟⋏☌ ⋔⊬ ⏁⟟⋔⟒ ⏚⊬ ⌿⍀⟒⌇⟒⋏⏁⟟⋏☌ ☊⌰⟟⟒⋏⏁ ⟟⌇⌇⎍⟒⌇ ⏁⊑⏃⏁ ⟟ ⎅⍜ ⋏⍜⏁ ☊⏃⍀⟒ ☊⏃⍀⟒ ⏃⏚⍜⎍⏁. ⏁⊑⟟⌇ ⟟⌇ ⟒⋏⏁⟟⍀⟒⌰⊬ ⊬⍜⎍⍀ ⎎⏃⎍⌰⏁, ⏁⊑⟒⍀⟒ ⟟⌇ ⋏⍜⏁⊑⟟⋏☌ ⟟ ☊⏃⋏ ⎅⍜ ⏃⏚⍜⎍⏁ ⊬⍜⎍⍀ ⌇⏁⎍⌿⟟⎅⟟⏁⊬. ⌿⌰⟒⏃⌇⟒ ⟊⎍⌇⏁ ⎅⟒⌰⟒⏁⟒ ⏃⌰⌰ ⊬⍜⎍⍀ ⎎⏃⌇⏁ ⎎⌰⏃☌⌇ ⏃⋏⎅ ⋏⟒⎐⟒⍀ ⟟⋏⌇⟒⍀⏁ ⏃⋏⊬ ⎎⏃⌇⏁ ⎎⌰⏃☌ ⌰⟟⌇⏁⌇ ⟒⎐⟒⍀ ⏃☌⏃⟟⋏. ☍⋏⍜⍙ ⍙⊑⏃⏁, ⟊⎍⌇⏁ ⎅⍜⋏'⏁ ⟟⋏⌇⟒⍀⏁ ⏃⋏⊬ ⎎⏃⌇⏁ ⎎⌰⏃☌⌇ ⟟⋏ ☌⟒⋏⟒⍀⏃⌰. ⏁⊑⟒ ⌿⍀⟒⌇⟒⏁⌇ ⏃⍀⟒ ☌⍜⍜⎅ ⟒⋏⍜⎍☌⊑, ⊬⍜⎍ ⎅⍜⋏'⏁ ⋏⟒⟒⎅ ⏁⍜ ⏚⟒ ⎎⟒⎅ ⎅⍜☌⌇⊑⟟⏁ ⏁⍜ ⌿⌰⏃⊬ ⍀⍜⏚⌰⍜⌖. ⎅⍜ ⋏⍜⏁ ⏁⍀⎍⌇⏁ ⏃⋏⊬ ⎎⏃⌇⏁ ⎎⌰⏃☌⌇ ⏁⊑⏃⏁ ⌿⟒⍜⌿⌰⟒ ☌⟟⎐⟒ ⊬⍜⎍. ⊑⍜⌿⟒⎎⎍⌰⌰⊬ ⏁⊑⟟⌇ ⟟⌇ ⋏⍜⏁ ⎅⟟⎎⎎⟟☊⎍⌰⏁ ⎎⍜⍀ ⊬⍜⎍⍀ ⌇⋔⏃⌰⌰ ⏚⍀⏃⟟⋏ ⏁⍜ ⎍⋏⎅⟒⍀⌇⏁⏃⋏⎅. ⊑⍜⌿⟒⎎⎍⌰⌰⊬ ⟟ ⊑⏃⎐⟒⋏'⏁ ⎎⍀⟟⟒⎅ ⊬⍜⎍⍀ ⌰⏃⌇⏁ ⍀⟒⋔⏃⟟⋏⟟⋏☌ ⏚⍀⏃⟟⋏ ☊⟒⌰⌰⌇ ⍙⟟⏁⊑ ⏁⊑⟟⌇ ⍀⟒⌇⌿⍜⋏⌇⟒.

**Comment by whyd0ineedausername** [comment]
delete your fflags
