### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by yonjustnpc** [bloxstraplabs/bloxstrap#3991]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4 

### What problem did you encounter?

![image](https://github.com/user-attachments
/assets/86f1f773-1235-4f86-a13a-ccd4d4e1acd0)
![image](https://github.com/user-attachments/assets/69d62923-1086-4348-aaeb-2b2d3fe31ecb)

### Bloxstrap Log

```text
N/A System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by nabheyka880** [comment]
update

**Comment by nabheyka880** [comment]
https://bloxstraplabs.com
