### ISSUE TITLE
[BUG]  System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by PaltaRellena** [bloxstraplabs/bloxstrap#4001]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

While I was updating my Bloxtrap, this error appeared.

### Bloxstrap Log

```text
N/A
```

**Comment by HelloKerem** [comment]
i loaf you when you did "I did not answer truthfully to all the above checkboxes."
pliz update your bloxstarp or else food your multi launches-
