### ISSUE TITLE
[BUG] Bloxstrap_20241215T090642Z

### ISSUE THREAD

**Issue by Ronnyb44** [bloxstraplabs/bloxstrap#4007]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4.exe

### What problem did you encounter?

[Bloxstrap_20241215T093102Z.log](https://github.com/user-attachments/files/18139702/Bloxstrap_20241215T093102Z.log)

### Bloxstrap Log

```text
N/A
```

**Comment by whyd0ineedausername** [comment]
update bloxstrap

**Comment by lolasaman** [comment]
holy fucking shit they should add "if youre on version 2.5.4 or below, update your bloxstrap"

**Comment by gamerloch10** [comment]
would be more like 2.8.0 or below, all versions under 2.8.1 don't work
