### ISSUE TITLE
[BUG] Blox Strap Isnt Launching

### ISSUE THREAD

**Issue by FallingFaithful** [bloxstraplabs/bloxstrap#4008]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.81

### What problem did you encounter?

When I try to Launch BloxStrap it doesnt work, it just says starting roblox then never launches the game

### Bloxstrap Log

```text
N/A
```

**Comment by FallingFaithful** [comment]
Oh also I found out something else, it works when I remove all fflags, but it doesn't launch when I have my fflags on.
{
  "FFlagDebugSkyGray": "True",
  "DFIntTaskSchedulerTargetFps": "200",
  "FLogNetwork": "7",
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FFlagDebugGraphicsDisableDirect3D11": "True",
  "FFlagGameBasicSettingsFramerateCap5": "False",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFFlagDebugPauseVoxelizer": "True",
  "FFlagDisablePostFx": "True",
  "FIntRenderShadowIntensity": "0",
  "DFFlagDisableDPIScale": "True",
  "FIntRenderShadowmapBias": "0",
  "FFlagDebugCheckRenderThreading": "True",
  "FFlagRenderDebugCheckThreading2": "True",
  "FIntRuntimeMaxNumOfThreads": "2400",
  "FFlagFixGraphicsQuality": "True",
  "FFlagCommitToGraphicsQualityFix": "True",
  "FIntRenderLocalLightFadeInMs": "0",
  "FIntRenderLocalLightUpdatesMin": "1",
  "FIntRenderLocalLightUpdatesMax": "1",
  "FFlagNewLightAttenuation": "True",
  "FFlagFastGPULightCulling3": "True",
  "DFIntCullFactorPixelThresholdShadowMapLowQuality": "2147483647",
  "DFIntCullFactorPixelThresholdShadowMapHighQuality": "2147483647",
  "FIntDebugForceMSAASamples": "4",
  "DFIntMaxFrameBufferSize": "4",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "DFIntTextureQualityOverride": "0",
  "DFIntTextureCompositorActiveJobs": "0",
  "FIntTerrainArraySliceSize": "4",
  "FIntUITextureMaxRenderTextureSize": "1024",
  "FIntTerrainOTAMaxTextureSize": "1024",
  "FFlagDebugRenderingSetDeterministic": "True",
  "FIntRobloxGuiBlurIntensity": "0",
  "DFIntCSGLevelOfDetailSwitchingDistance": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL12": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL23": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL34": "0",
  "FStringPartTexturePackTablePre2022": "{\u0022glass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://7547304948\u0022,\u0022rbxassetid://7546645118\u0022],\u0022color\u0022:[254,254,254,7]}}",
  "FStringPartTexturePackTable2022": "{\u0022glass\u0022:{\u0022ids\u0022:[\u0022rbxassetid://9873284556\u0022,\u0022rbxassetid://9438453972\u0022],\u0022color\u0022:[254,254,254,7]}}",
  "DFIntAnimationLodFacsDistanceMin": "0",
  "DFIntAnimationLodFacsDistanceMax": "0",
  "DFIntAnimationLodFacsVisibilityDenominator": "0",
  "FIntRenderGrassDetailStrands": "0",
  "FIntRenderGrassHeightScaler": "0",
  "FIntFRMMinGrassDistance": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FFlagGlobalWindRendering": "False",
  "FFlagGlobalWindActivated": "False",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagDebugDisableTelemetryV2Stat": "True"
}
(MY FFLAGS BTW)

**Comment by PikachuWolverine** [comment]
Clearly your flags are the issue. Do you even know what your flags do?

**Comment by Max01090** [comment]
hello, i have the same issue (it says roblox it launching and it open roblox like 10ms and it close it so please help me and if i need to send my flags how (idk what the flags is...) thanks !

**Comment by Max01090** [comment]
and i tried to unistall and reinstall and it doesn't work

**Comment by bluepilledgreat** [comment]
never use github ever again
