### ISSUE TITLE
(BUG) Exception File downloadation fail

### ISSUE THREAD

**Issue by AidenGameruj** [bloxstraplabs/bloxstrap#4011]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

 I was downloading a file until I got an error message saying "An exception occured while running bloxstrap"

### Bloxstrap Log

```text
[minecraft.zip](https://github.com/user-attachments/files/18142656/minecraft.zip)
```

**Comment by gamerloch10** [comment]
First of all make sure your on the latest version, 2nd what??

**Comment by bluepilledgreat** [comment]
porud owner of minecraft.zip
