### ISSUE TITLE
Mod Manager

### ISSUE THREAD

**Issue by toast-ed** [bloxstraplabs/bloxstrap#4017]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So my idea is that you can add normal folders that includes ExtraContent and Content and bloxstrap will apply the themes either every launch or every time roblox gets updated also any theme should be updated automaticly to the new atlas when new theme is applied it should still apply themes no matter a update or nothing, this will be a tab under the mods file opening

Features :
Switch for disabling or enabling the mods

A file icon to locate the mods place

the starting order (if you set the mod you want to load in like you got a theme but you dont like its mouse so you get a other mouse theme and make its loading order to 1 so it applies first

also a community workshop for themes (optional because bloxstrap might not have the servers required)

**Comment by bluepilledgreat** [comment]
duplicate suggestion
