### ISSUE TITLE
[BUG] I can't find the multi-task accounts

### ISSUE THREAD

**Issue by LoorsDoors** [bloxstraplabs/bloxstrap#4020]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I watched Sharkblox, tried his guide. I'm just trying to understand if bloxstraps has already provided multi-task accounts in it but when I installed the app I can't seem to find the multi-task anywhere. Please help

### Bloxstrap Log

```text
N/A
```

**Comment by PikachuWolverine** [comment]
Multi-task got removed.
