### ISSUE TITLE
[BUG] Bloxstrap crashes on Opening

### ISSUE THREAD

**Issue by s5t5** [bloxstraplabs/bloxstrap#4021]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Anytime i open bloxstrap it quickly flashes then shuts as shown in clip. I tried to drag or click it, nothing happened. I have also restarted my computer, and reinstalled it, nothing worked :(

clip-https://github.com/user-attachments/assets/b6e92b76-dc2e-446e-8679-16598f90cdd3

### Bloxstrap Log

```text
N/A
```

**Comment by PolishGaming** [comment]
like i want to install the 1.5.1 but it cant for some reason

**Comment by bluepilledgreat** [comment]
me asking new github accounts for logs, knowing damn well they will never log back in ever again.
