### ISSUE TITLE
Starborn 

### ISSUE THREAD

**Issue by paulacoookie** [bloxstraplabs/bloxstrap#4031]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

**
[starborn (1).zip](https://github.com/user-attachments/files/18187604/starborn.1.zip)
**
[starborn.zip](https://github.com/user-attachments/files/18187594/starborn.zip)

**Comment by paulacoookie** [comment]
P

**Comment by paulacoookie** [comment]
[starborn (1).zip](https://github.com/user-attachments/files/18187613/starborn.1.zip)

**Comment by nabheyka880** [comment]
what

**Comment by whyd0ineedausername** [comment]
what

**Comment by gamerloch10** [comment]
Is this a custom pack or something?
