### ISSUE TITLE
[BUG] max render distance issue

### ISSUE THREAD

**Issue by lazyy12233** [bloxstraplabs/bloxstrap#4035]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### What problem did you encounter?

i cant set max render distance at lower graphics 1 i tried everything but i got no idea 

### Bloxstrap Log

```text
N/A
```

**Comment by RyanLua** [comment]
What are the steps you are using and your FastFlags?
