### ISSUE TITLE
[BUG] uninstalling boxstrap caused launcher to be a background process

### ISSUE THREAD

**Issue by Tomader910** [bloxstraplabs/bloxstrap#4037]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

i uninstalled bloxstrapper and roblox fully, and reinstalled roblox, and now the launcher only opens as a background process, though roblox does launch normally. I would like to be able to see my launcher as i wanna know if roblox is broken or if its updating. how would i fix this?

### Bloxstrap Log

```text
N/A
```

**Comment by gamerloch10** [comment]
Update to the latest version

**Comment by Tomader910** [comment]
i wrote down whatever was off the top of my head, i had the latest version installed sorry for that error, i tried reinstalling bloxstrap from the latest version and uninstalling it, and the issue still happens

**Comment by bluepilledgreat** [comment]
send your log

**Comment by Tomader910** [comment]
from roblox or bloxstrap?

**Comment by Tomader910** [comment]
because as i said, i uninstalled bloxstrap which then made the launcher/bootstrapper not appear when launching roblox

**Comment by bluepilledgreat** [comment]
oh thats what you meant
not my problem
