### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Burntoe** [bloxstraplabs/bloxstrap#4045]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/f5123637-d90a-4542-85c0-7c6ca497c9e9)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
client issues are no longer accepted

**Comment by Burntoe** [comment]
bruh so what do i do about it ;-;

**Comment by AshBorn611** [comment]
i have same bug i can’t launch my blox strap and my roblox HELP
