### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sigma611** [bloxstraplabs/bloxstrap#4046]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
ef yu'r a reil sigma yu woold bee osing thr lates Verizon of bloxtrap
