### ISSUE TITLE
[BUG] System.IO.IOException: The process cannot access the file 'C:\Users\meisy\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.

### ISSUE THREAD

**Issue by toiletman2448** [bloxstraplabs/bloxstrap#4048]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.1

### What problem did you encounter?

cant launch
![image_2024-12-21_001416943](https://github.com/user-attachments/assets/c33481c0-2e96-4f36-ab3a-29cbea8d63dc)

**Comment by bluepilledgreat** [comment]
duplicate issue
