### ISSUE TITLE
[REQ] Add the "FoundationColors" theme switcher.

### ISSUE THREAD

**Issue by YellowTcat** [bloxstraplabs/bloxstrap#4051]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

As the title says. Please add the feature to enable/disable "FoundationColors" theme (the one with the blue play button and more dark colors)

**Comment by bluepilledgreat** [comment]
we're not adding flags that are likely to release soon
