### ISSUE TITLE
[BUG] FPS Capper not working 

### ISSUE THREAD

**Issue by SuchSunset** [bloxstraplabs/bloxstrap#4066]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

The fps capper in the engine settings tab doesn't work, when it's enabled or set to any setting other than 0, roblox continues to use the default capping system, which is the same result that I get from using the latest ver of RFU. I'm not sure if this is a problem of my roblox from my end or anything but I js want higher fps than 240 

### Bloxstrap Log

```text
N/A
```

**Comment by parknich** [comment]
does the same thing for me
