### ISSUE TITLE
[BUG] The setting to run multiple instances of roblox does not show up

### ISSUE THREAD

**Issue by SupremeBread21** [bloxstraplabs/bloxstrap#4068]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I am trying to run multiple instances of Roblox on the same device but the setting to do so does not appear. From what I understand it should show up right below the show Roblox account option.
![Screenshot 2024-12-22 195145](https://github.com/user-attachments/assets/cc8a68cf-ff95-4892-bed6-753d495d96d4)

### Bloxstrap Log

```text
N/A
```

**Comment by Aslkois** [comment]
Unfortunately, Bloxstrap has stopped the support for multiple instances as it could have "malicious intentions" as Byfron says. Therefore, Bloxstrap has removed it so they can stay on the safe side of Roblox.

**Comment by nabheyka880** [comment]
basically, it got removed cause people use it for farming

**Comment by SupremeBread21** [comment]
Got it, thank you guys!
