### ISSUE TITLE
[BUG] Im having trouble server hopping in some games like bloxfruit cuz it will always say "we're sorry roblox is temporarily unavailable." idk if the problem is from my pc or the bloxstrap itself. Give me some tips on how to fx this

### ISSUE THREAD

**Issue by RobloxBloxStrap** [bloxstraplabs/bloxstrap#4071]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

we're sorry roblox is temporarily unavailable

### Bloxstrap Log

```text
N/A
```

**Comment by alishahzain123** [comment]
bloxstrap is not working
