### ISSUE TITLE
[BUG] Issue with Persistent Fast Flags in Bloxstrap

### ISSUE THREAD

**Issue by regnma** [bloxstraplabs/bloxstrap#4072]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Hi, I am experiencing an issue with Bloxstrap where certain Fast Flags (specifically FLogNetwork and FFlagHandleAltEnterFullscreenManually) are not being removed, even after editing the configuration files directly. I have followed the instructions for clearing settings and reinstalled Bloxstrap multiple times, but the flags persist and continue to affect the performance and appearance of the game.

Here’s what I’ve done so far:

Edited the ClientAppSettings.json file to set the flags to "false" or removed them.
Deleted the configs folder in the Bloxstrap directory.
Tried reinstalling Bloxstrap and deleting all related files.
Made sure to run Bloxstrap with administrative privileges.
Despite all these attempts, the flags still remain active and are not removed.

Could you please help me resolve this issue or let me know how to clear these Fast Flags permanently?

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
you cant. they're set on launch.
