### ISSUE TITLE
[BUG] Connectivity error, my internet is fine tho.

### ISSUE THREAD

**Issue by OleMonkE** [bloxstraplabs/bloxstrap#4074]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

It just happened right now as of the time of posting this issue, my internet works fine but now i get this error message which is shown in the picture:
![{EEEF36E2-F050-4A1B-957D-A458F8B1D8C1}](https://github.com/user-attachments/assets/a2d6bb2c-ab08-4acb-b40f-a35c144f97a3)

i would like to know the reason of the issue and how i can fix it

### Bloxstrap Log

```text
System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.
```

**Comment by AXCWZ** [comment]
Hi, I am not the dev, take this advice as a grain of salt.

I have the same problem, whenever I open Roblox and join a game and leave, my internet completely goes wild, everything is running at high ping, every app that currently runs said I have no connection, I have to reconnect my WiFi for the internet is be back, and just now, I have tried deleting all the FastFlag that I do not need anymore out and my Roblox is now completely fine.

So I suggest backing up your FastFlag and deleting every FastFlag you currently have, if it doesn't help, then put your FastFlag back.
