### ISSUE TITLE
[BUG] I can't get rid of my fonts anymore, even if I delete and save it.

### ISSUE THREAD

**Issue by danielll12** [bloxstraplabs/bloxstrap#4075]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I can't get rid of my fonts anymore, even if I delete and save it. did you know guys how to fix?

**Comment by bluepilledgreat** [comment]
go to the settings, bootstrapper, and enable reinstall roblox
