### ISSUE TITLE
[BUG] .net error

### ISSUE THREAD

**Issue by manwken** [bloxstraplabs/bloxstrap#4080]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

I tried to install bloxstrap and .net is installed but it keeps say that i need to download .net but when i click yes, nothing opens
![image](https://github.com/user-attachments/assets/b6b853f3-59e4-433f-942d-6a00b9b2ecd0)
 

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
install the .net __desktop__ runtime

**Comment by manwken** [comment]
> install the .net **desktop** runtime

can u share link cause i dont find **desktop** i find .net runtime
