### ISSUE TITLE
bloxstrap just won't launch, regular roblox player also won't launch, but it's not a roblox issue because it works on every other device. I have a picture of the issue if that's helpful.

### ISSUE THREAD

**Issue by donttouchak** [bloxstraplabs/bloxstrap#4081]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

i tried to launch roblox through bloxstrap and it says starting roblox and the bar goes through about 4 times, then this error message comes up. i've tried deleting and redownloading everything, tried resetting pc, tried finding malware and couldn't find any in my pc. i've tried every step it says in the help page and nothing works.

![Screenshot 2024-12-23 193933](https://github.com/user-attachments/assets/570ab5ad-75c6-4a20-9d11-3fe1ebd2a03d)

### Bloxstrap Log

```text
N/A
```

**Comment by donttouchak** [comment]
why are u closing it nb helped me

**Comment by donttouchak** [comment]
even after new update i downloaded same thing happens

**Comment by bluepilledgreat** [comment]
> even after new update i downloaded same thing happens

client issues are no longer accepted. your client not working is not our problem. all we do is open the roblox executable, we don't develop the roblox client.
