### ISSUE TITLE
[BUG] an exception occured while running Bloxtrap

### ISSUE THREAD

**Issue by videopodcastsbi** [bloxstraplabs/bloxstrap#4083]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4exe

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/12687d88-cab9-4928-9928-f139be05bf54)

### Bloxstrap Log

```text
N/A
```

**Comment by zxc-commits** [comment]
![398497449-12687d88-cab9-4928-9928-f139be05bf54](https://github.com/user-attachments/assets/9a111a29-8461-4054-9d92-f47a364eda50) у менят такаеже проблема

**Comment by Undefined-TheQuiet** [comment]
[Bloxstrap_20241225T162153Z.log](https://github.com/user-attachments/files/18246684/Bloxstrap_20241225T162153Z.log)

**Comment by Undefined-TheQuiet** [comment]
i can't add the menu of today, pls do something
[Bloxstrap_20241225T164027Z.log](https://github.com/user-attachments/files/18246709/Bloxstrap_20241225T164027Z.log)

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/
