### ISSUE TITLE
[BUG] The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by QuackQuak** [bloxstraplabs/bloxstrap#4085]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

[Bloxstrap_20241226T023631Z.log](https://github.com/user-attachments/files/18249034/Bloxstrap_20241226T023631Z.log)
![image](https://github.com/user-attachments/assets/70a6b9b8-1cd8-4899-b895-c679af1f7722)
I'm using the latest version of Bloxstrap which of course i dowloaded on the right website. I tried to dowload Wave Excutor and then I can't open Bloxstrap anymore. I reinstalled Bloxstrap once and it still happen.

### Bloxstrap Log

```text
System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
```

**Comment by nabheyka880** [comment]
you have an executor named Wave installed
uninstall that and then update bloxstrap
https://bloxstraplabs.com/

**Comment by QuackQuak** [comment]
broblem fixed 👍 thanks :)
