### ISSUE TITLE
[BUG] I cant download bloxstrap

### ISSUE THREAD

**Issue by mlikkk** [bloxstraplabs/bloxstrap#4087]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

i cant download bloxstrap idk what to do
![Screenshot 2024-12-26 204500](https://github.com/user-attachments/assets/e456d327-8be8-492a-8570-02d806a3a77f)

### Bloxstrap Log

```text
N/A
```

**Comment by DimasGitHubOfficial** [comment]
reinstall then
