### ISSUE TITLE
[BUG] fix download link lol

### ISSUE THREAD

**Issue by Kullix** [bloxstraplabs/bloxstrap#4094]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

you sholuld probably update the official bloxstrap website (https://bloxstraplabs.com/) Lol Because my Bloxstrap is redirecting to it to Update Yet Its Not even Updated so mfs are forced to come here

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
give me a sec

**Comment by bluepilledgreat** [comment]
ok now its up to date
