### ISSUE TITLE
[BUG] I cannot open roblox

### ISSUE THREAD

**Issue by BoboHimake** [bloxstraplabs/bloxstrap#4099]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.4

### What problem did you encounter?

I cant open roblox. When I click to play a game, the bloxstrap thing just doesnt load.

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/

**Comment by truekvvrund** [comment]
> update https://bloxstraplabs.com/

bro i have same version and still not work

**Comment by nabheyka880** [comment]
what error pops up

**Comment by Zem23** [comment]
same at me btw
