### ISSUE TITLE
[BUG]why is my roblox not opening*

### ISSUE THREAD

**Issue by omgbugfox** [bloxstraplabs/bloxstrap#4104]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

why__

**Comment by nabheyka880** [comment]
you know maybe it would be useful if you posted atleast a log or a screenshot of an error if there is one or atleast explain the issue more

**Comment by Asiret** [comment]
its at my bloxtrap also it doesnt open roblox it closes imediatly after trying to open it

**Comment by DingusLing0** [comment]
it doesnt even show the bloxstrap opening it closes imediatly
