### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\gabri\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by kaneki213459** [bloxstraplabs/bloxstrap#4106]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

eu n consigo abrir o bloxtrap "Um erro ocorreu enquanto o bloxtrap estava sendo executado"

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
was roblox already running when this error appeared?
