### ISSUE TITLE
[BUG] System.IO.IOException: The process cannot access the file 'C:\Users\guens\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\WebView2Loader.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by lol1209** [bloxstraplabs/bloxstrap#4107]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

I put on test mode, tried to see if it worked, and then when it finished loading, the bloxstrap settings popped up in my screen again! i tried a 2nd time, did the same time, after countless times, it still did the same thing. please fix this!

### Bloxstrap Log

```text
![Screenshot 2024-12-26 182301](https://github.com/user-attachments/assets/21bff640-33ed-4d43-bf27-1fef58998faf)
```

**Comment by lol1209** [comment]
yes i did have a bloxstrap excetion imma show the image again ![Screenshot 2024-12-26 182301](https://github.com/user-attachments/assets/21bff640-33ed-4d43-bf27-1fef58998faf)

**Comment by bluepilledgreat** [comment]
can you send your log file?

**Comment by bluepilledgreat** [comment]
was roblox already running when this error appeared?

**Comment by lol1209** [comment]
no it wasnt open.

**Comment by lol1209** [comment]
i cant record since my laptop doesnt allow me to

**Comment by lol1209** [comment]
![Screenshot 2024-12-27 095624](https://github.com/user-attachments/assets/b02bc3d6-17a8-4210-bd86-af35414a17d4)

**Comment by lol1209** [comment]
![Screenshot 2024-12-27 095723](https://github.com/user-attachments/assets/9eb62aa5-5d6c-4794-8b6b-0ea5473199dd)
![Screenshot 2024-12-27 095902](https://github.com/user-attachments/assets/d821bd00-0edd-4c0a-bb57-0ea9e8726184)
![Screenshot 2024-12-27 095928](https://github.com/user-attachments/assets/3721e1bf-e2b1-4d65-9724-c235d2c37f33)

**Comment by lol1209** [comment]
ever since i turned on force roblox reinstallion it gave me a exception

**Comment by lol1209** [comment]
imma come back in like a hour or 30 minutes

**Comment by lol1209** [comment]
is there anyway to put this off
![Screenshot 2024-12-27 103738](https://github.com/user-attachments/assets/a9988bd6-1e14-4c52-95b3-552cad73acbc)

**Comment by lol1209** [comment]
i know im commenting too much but i just found this yesterday
![Screenshot 2024-12-27 104720](https://github.com/user-attachments/assets/c23e6d13-7e8e-45bd-a178-6194f651af82)

**Comment by lol1209** [comment]
the issue is fixed now. thank you for helping!
