### ISSUE TITLE
[BUG] am i blind or is there no multiple instances anymore? i got on my computer my bloxstrap wasnt working... i reinstalled now cant use more then one acc...

### ISSUE THREAD

**Issue by brxxxxxxxx** [bloxstraplabs/bloxstrap#4109]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.2

### What problem did you encounter?

please help why is this happening.. i need to use multiple accs to test my server.

**Comment by brxxxxxxxx** [comment]
i have tried just about everything can someone help

**Comment by bluepilledgreat** [comment]
its removed
