### ISSUE TITLE
[BUG] Blurred GUI

### ISSUE THREAD

**Issue by DimasGitHubOfficial** [bloxstraplabs/bloxstrap#4119]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

here i saw thumbnail, game icon, etc are blurred so heres the picture 
![Screenshot 2024-12-27 141125](https://github.com/user-attachments/assets/dddc92c6-fe0d-4f06-acf4-1608625e89a0)

### Bloxstrap Log

```text
N/A
```

**Comment by SonicGamer803** [comment]
roblox issue, its like mobile all over again
