### ISSUE TITLE
[BUG] i wont play my game fix ur stupid bloxtrap now!!!!

### ISSUE THREAD

**Issue by omgbugfox** [bloxstraplabs/bloxstrap#4120]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

fix it__

### Bloxstrap Log

```text
N/A
```

**Comment by nabheyka880** [comment]
i love it when you literally post a duplicate post without even literally explaning the issue more dude
btw do you have bloxshade installed? if so, uninstall it
also, please explain more your issue

**Comment by omgbugfox** [comment]
im not using bloxshade

**Comment by nabheyka880** [comment]
but do you have it installed
also you shouldn't be making a new post when you've already made 2 other posts
maybe just wait

**Comment by omgbugfox** [comment]
i dont have it already

**Comment by bluepilledgreat** [comment]
duplicate
