### ISSUE TITLE
[BUG] bloxstrap wont show region and unable to connect ipinfo.io (Error 429)

### ISSUE THREAD

**Issue by Random-User1-line** [bloxstraplabs/bloxstrap#4125]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

not showing server location querying

### Bloxstrap Log

```text
N/A
```

**Comment by Random-User1-line** [comment]
![image](https://github.com/user-attachments/assets/802c5f87-2220-4b1a-a980-68c47420b914)
this is the problem i encounter

**Comment by bluepilledgreat** [comment]
you have been ratelimited. there is nothing we can do.

**Comment by abdullahdevrel** [comment]
I work for IPinfo. We support up to 1,000 requests per day from each unique IP address. Are you using a VPN?

**Comment by Random-User1-line** [comment]
im not using vpn rn

**Comment by abdullahdevrel** [comment]
Hmm, interesting issue. This could be a configuration issue. We refresh the rate limit count every day. Try again and see if it works.
