### ISSUE TITLE
[BUG] Sometimes the roblox will only in white and roblox logo and I only can restart my computer to fix it.

### ISSUE THREAD

**Issue by binqilinRobert** [bloxstraplabs/bloxstrap#4126]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.2

### What problem did you encounter?

If I use the close button on top right corner,next time I use Roblox will dont have anything like games,friend list...
Also if the Roblox disconnet,and i need too restart my computer,too.
![螢幕擷取畫面 2024-12-27 223957](https://github.com/user-attachments/assets/234ab767-ccf3-4c93-909e-6e26d172f281)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
client issues are not our problem
