### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by lol1209** [bloxstraplabs/bloxstrap#4136]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.3

### What problem did you encounter?

it gave me a exception but this time it said i dont have access...
![Screenshot 2024-12-27 140905](https://github.com/user-attachments/assets/cbb398f3-1d70-4033-82d6-bfe02f1e9e4e)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Fixed in v2.8.4

**Comment by lol1209** [comment]
thank you!
