### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\Giedrius\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by SigmaOhio69** [bloxstraplabs/bloxstrap#4152]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.4

### What problem did you encounter?

Exception

### Bloxstrap Log

```text
System.UnauthorizedAccessException: Access to the path 'C:\Users\Giedrius\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.
```

**Comment by bluepilledgreat** [comment]
Fixed in 2.8.5
