### ISSUE TITLE
[BUG] System.IO.IOException: The process cannot access the file 'C:\Users\star21\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\WebView2Loader.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by mike44994499** [bloxstraplabs/bloxstrap#4162]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

V2.8.4

### What problem did you encounter?

i cant open my roblox 
my English is bad sry

### Bloxstrap Log

```text
System.IO.IOException: The process cannot access the file 'C:\Users\star21\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\WebView2Loader.dll' because it is being used by another process.
```

**Comment by bluepilledgreat** [comment]
Fixed in 2.8.5
