### ISSUE TITLE
[BUG] BSOD when launching bloxtrap

### ISSUE THREAD

**Issue by FixLive2** [bloxstraplabs/bloxstrap#4183]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.4

### What problem did you encounter?

every time i launch bloxtrap i'm getting BSOD,pls fix it

### Bloxstrap Log

```text
N/A
```

**Comment by gamerloch10** [comment]
I don't think this is a bloxstrap issue
