### ISSUE TITLE
[BUG] When I open, "Launch Roblox" why does it only Launches me, "Roblox Game Cilent"

### ISSUE THREAD

**Issue by emiwemy** [bloxstraplabs/bloxstrap#4184]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

"Everytime whenever I open my bloxstrap it started to launches roblox game cilent. I tried reading all the instructions and I looked up on google and youtube but their arent even simlar of what im looking for please help because I actually need fps."

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
I'm assuming you're looking for the settings. It's right below it.
![image](https://github.com/user-attachments/assets/4806b85c-ca39-4b6c-b8b8-124e0936dd57)

**Comment by emiwemy** [comment]
hai sorry for texting but, im talking about when I'm using bloxstrap and I
decided to open my bloxstrap it will automatically open my, "Roblox Game
Cilent," But thank you for trying but if you have any ideas to fix this,
please let me know.
