### ISSUE TITLE
[REQ] Add an OPTION to use new version structure

### ISSUE THREAD

**Issue by IzeAack** [bloxstraplabs/bloxstrap#4185]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I am NOT talking about version- but I am talking about Roblox\Player.
The reason why I want this is because I made a batch script that relies on the new version structure.

**Comment by bluepilledgreat** [comment]
Sorry but no, I'm not supporting two separate version structures.
I plan to add more arguments to custom integrations next update. See #800.
For now, I recommend either parsing State.json and getting the version guid through that, or pick the first directory in the Versions folder with RobloxPlayerBeta.exe.

**Comment by BRanulf** [comment]
I want this too.
Because I am using nvidia filter. Otherwise, every time the game updates, I need to reconfigure the filters.
