### ISSUE TITLE
[REQ] Completely disable roblox VR on startup

### ISSUE THREAD

**Issue by CrystalFx** [bloxstraplabs/bloxstrap#4189]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Could we get a feature (or have a fastflag listed) that completely gets rid of the VR toggle inside of roblox's menu in-game? Not sure if anyone else has this issue but changing the global setting in appdata doesn't affect it nor does restarting roblox (as they recommend when you switch it off) work, it's getting quite annoying especially with nvidia software not realizing its just roblox instead of "roblox VR"
![0A5C3F40-0002-45CC-9B47-D65AF67D5B8B](https://github.com/user-attachments/assets/3cb65d80-d285-417e-8764-19cff89f6a81)

**Comment by DimasGitHubOfficial** [comment]
you need to restart it

**Comment by DimasGitHubOfficial** [comment]
@pizzaboxer

**Comment by gamerloch10** [comment]
pizzabloxer doesn't work on bloxstrap anymore

**Comment by CrystalFx** [comment]
@DimasGitHubOfficial ive restarted my roblox tons of times and it doesn't work, i explained that in the initial post

**Comment by DimasGitHubOfficial** [comment]
hmm i will ask this in discord....

**Comment by DimasGitHubOfficial** [comment]
"nvidia will always call it roblox vr" - Lyx

**Comment by DimasGitHubOfficial** [comment]
"i dont even have that button listed and it still calls itself roblox vr" - Lyx

**Comment by DimasGitHubOfficial** [comment]
"however
FFlagAlwaysShowVRToggleV3 can be set to False
if you just wanna hide the thing" - Lyx

**Comment by DimasGitHubOfficial** [comment]
"nvidia is just like that yeah idk why it does that
not roblox" - Dusk

**Comment by CrystalFx** [comment]
weird cause whenever i first installed my nvidia driver it never did that

**Comment by lokzz** [comment]
nvidia drivers =/= nvidia capture app
