### ISSUE TITLE
Make the installation of Web Edge View optional

### ISSUE THREAD

**Issue by Luximoz** [bloxstraplabs/bloxstrap#625]
I don't want to have to uninstall it every time I want to play Roblox just to be free from that spyware, I used to use a trick to make it think it would execute the installer when it would just execute a blank EXE by using the "Modifications" folder... But it seems like that trick no longer works......

**Comment by CurrencyDev** [comment]
If you mean Hyperion no it can't be removed perm unless you make a script that checks for hyperions existence and deletes it if its there

**Comment by pizzaboxer** [comment]
...but why?

**Comment by nakoyasha** [comment]
> No, I actually meant Web Edge View, Roblox keeps trying to reinstall it when lauching a game if it detects that it isn't installed, even though Roblox works perfectly fine without it, but now that we're talking about Hyperion, do you happen to know where is it installed? ![image](https://user-images.githubusercontent.com/94522544/264695581-9604c427-506b-4ff2-9f77-2da931be7051.png)

... are you really using windows 7 in 2023?
besides, what's the point? I doubt there's any reason for microsoft to shove their trackers into something like wv2

**Comment by PlayerValley** [comment]
been thinking of it not install webview2 if "disable desktop app" is checked, just a thought i threw at the wall

**Comment by pizzaboxer** [comment]
> been thinking of it not install webview2 if "disable desktop app" is checked, just a thought i threw at the wall

Fair point, though it has its uses outside of the Desktop app too, like the Voice chat beta badge.

**Comment by Luximoz** [comment]
> > No, I actually meant Web Edge View, Roblox keeps trying to reinstall it when lauching a game if it detects that it isn't installed, even though Roblox works perfectly fine without it, but now that we're talking about Hyperion, do you happen to know where is it installed? ![image](https://user-images.githubusercontent.com/94522544/264695581-9604c427-506b-4ff2-9f77-2da931be7051.png)
> 
> ... are you really using windows 7 in 2023? besides, what's the point? I doubt there's any reason for microsoft to shove their trackers into something like wv2

Well, sorry to disappoint, but they actually have telemetry in WebView, and they always have a reason to put their tracker anywhere they can with the reason being about money, also it doesn't matter if I use Windows 7 or not, most stuff still support it anyway.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/916

> ...but why?

> > even though Roblox works perfectly fine without it,

> The desktop app doesn't completely work without it.

Oh, well, I don't use the desktop app to browse the site, like most people still do on PC these days, I also don't have voice chat enabled, but if you don't use any of those features then there isn't a point to have WebView. 
Even Roblox Studio redirects you to the website with a prompt to allow Studio to log in if you don't have WebView.

**Comment by Da-nu** [comment]
I would like to mention a toggle to not try and not install webview would help with running bloxstrap under wine. The installer right now is completely borked so bloxstrap gets stuck on Installing Webview unless I manually kill it.

**Comment by pizzaboxer** [comment]
Yes, that's what I was referring to when I said "helping things a bit with Linux".
