### ISSUE TITLE
[BUG] Emoji font trying to be applied when Roblox is already running

### ISSUE THREAD

**Issue by Reymund0xD** [bloxstraplabs/bloxstrap#773]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231012T230305Z.log](https://github.com/pizzaboxer/bloxstrap/files/12887730/Bloxstrap_20231012T230305Z.log)

**Comment by Reymund0xD** [comment]
A problem with the fonts/TwemojiMozilla.ttf because it is being used by another process.

**Comment by Reymund0xD** [comment]
Also Bloxstrap Ain't Launching

**Comment by pizzaboxer** [comment]
Known issue, make sure Roblox isn't running in the background first and then launch.
