### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Not enough quota is available to process this command.

### ISSUE THREAD

**Issue by rblxSioFi** [bloxstraplabs/bloxstrap#788]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have no clue what this even means, but if it helps, I went into my System Tray and saw the bloxstrap icon and right clicked it and it popped up with this error, and I realized I didn't even have Roblox open when I did this.

Here is the log file it highlighted in my explorer:

![image](https://github.com/pizzaboxer/bloxstrap/assets/89963996/96e246e6-be8c-4c93-a306-cbd6716edad5)

[Bloxstrap_20231012T122246Z.log](https://github.com/pizzaboxer/bloxstrap/files/12920700/Bloxstrap_20231012T122246Z.log)

This thing also popped up before the latest bloxstrap update, but I decided to not report it because I thought someone else would have gotten it already, but it seems to still be happening even after the latest update, so maybe no one has. Either way, here you go I guess. It's also very likely ZCanary contributes to the issue, but I don't know.

**Comment by pizzaboxer** [comment]
Oh, I've actually seen this issue before. It's some weirid bug where the application doesn't properly close and instead somehow screws up something with memory. I was never able to get a proper log file for it, so this is nice.

Does this happen every single time you use it?

**Comment by pizzaboxer** [comment]
> No, from what I recall this doesn't happen often, which would explain why it only occurred to me twice.

Oh, right.

Also thank you for the extra details, but I don't need those as I already have a rough idea on why this happens. Has nothing to do with Roblox, it's purely my bad code. Though, actually fixing it is gonna be tough since it could be happening anywhere when it tries to clean up, especially when it happens extremely rarely.

**Comment by rblxSioFi** [comment]
Alright.

Also I apologize, going the little extra mile is a habit of mine.

I wish you luck on fixing the bug. It doesn't stop Bloxstrap from working properly luckily.

**Comment by pizzaboxer** [comment]
Assumed to be fixed
