### ISSUE TITLE
[REQ] Join last server

### ISSUE THREAD

**Issue by ms-gitblox** [bloxstraplabs/bloxstrap#887]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I am requesting a new feature similar to the "Copy Invite Deeplink" feature that exists in the system tray.
This new feature would work something like this:
1. When the user joins, Bloxstrap saves the deeplink.
2. A new option is added to the system tray icon (Join last server).
3. When clicked it should make you join the last server you were in.

This feature could come in handy if you get kicked (internet issues etc.)

**Comment by pizzaboxer** [comment]
I like that feature, I'll consider that.

**Comment by FFFadal** [comment]
> I like that idea, I'll consider that as a feature.

this is actually a good idea fr

**Comment by ShadowCodeX-debug** [comment]
Reminds me of RAM (Roblox Account Manager). Had so many cool things like a region show option inside of a game browser with a server browser as well.
