### ISSUE TITLE
[BUG] Unable to open Roblox - only with Bloxstrap

### ISSUE THREAD

**Issue by ClaytonTDM** [bloxstraplabs/bloxstrap#975]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm unable to run Roblox using Bloxstrap after installing NTVDMx64. The process is in task manager, but there's no window.
![image](https://github.com/pizzaboxer/bloxstrap/assets/71360210/de465773-c7b2-45a1-ad9a-cbd3dee269ed)
I've tried reinstalling + rebooting, it didn't work.

**Comment by goofinglor** [comment]
i uninstalled bloxstrap and reinstalled the normal roblox. it seemed to work for me.

**Comment by pizzaboxer** [comment]
> I'm unable to run Roblox using Bloxstrap after installing NTVDMx64

I have a feeling that you've already just pointed out the cause of your issue here. As I asked in the preliminary instructions, [does it happen without Bloxstrap?](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap)

**Comment by pizzaboxer** [comment]
Can I see the list of FastFlags you have configured in the menu?

**Comment by ClaytonTDM** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/71360210/84329763-1d2a-40aa-b92f-1b174beaf9a0)
![image](https://github.com/pizzaboxer/bloxstrap/assets/71360210/7b05f43c-2c2d-484b-add6-16ced7932d32)

**Comment by pizzaboxer** [comment]
> Uninstalling NTVDMx64 fixes it though

...Yet somehow Roblox by itself works completely fine with it installed?

**Comment by ClaytonTDM** [comment]
Yup...

**Comment by pizzaboxer** [comment]
Just throwing this out there, does disabling all your integrations change anything?

**Comment by ClaytonTDM** [comment]
Nope

**Comment by pizzaboxer** [comment]
I'm not really sure if there's even anything I can do here, but at this point I just want to ensure that your Roblox install is identical to the stock one. Go to the folder where Bloxstrap is installed to (typically `%localappdata%\Bloxstrap`), send the contents of State.json here. Then, go into the version folder, delete the ClientSettings folder, and then start RobloxPlayerBeta.exe manually. See if anything different happens.

**Comment by ClaytonTDM** [comment]
[State.json](https://github.com/pizzaboxer/bloxstrap/files/13465641/State.json)
Nothing happened.

**Comment by pizzaboxer** [comment]
Can you send me a copy of your Bloxstrap installation folder? Throw everything into a .zip archive, upload it somewhere, send a link to it here.

**Comment by ClaytonTDM** [comment]
https://sourceforge.net/projects/nxvdm/

**Comment by TheRabbit75** [comment]
This is happening to me; I have tried re-installing it myself aswell it works on ONE game then when I leave it, (sometimes it doesnt even do one game) it does the same thing, appears in the background but no window.

**Comment by TheRabbit75** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/69687216/9982eacd-c961-47d1-bc8c-69971b52e4d2)

**Comment by pizzaboxer** [comment]
@TheRabbit75 As far as I'm concerned you're talking about something completely different. Open a separate issue for it.

**Comment by DimaLeon2000** [comment]
> > Uninstalling NTVDMx64 fixes it though
> 
> ...Yet somehow Roblox by itself works completely fine with it installed?

How was it possible? Was it something to do with the latter's ldntvdm.dll interfering with the former?

**Comment by ClaytonTDM** [comment]
> > > Uninstalling NTVDMx64 fixes it though
> > 
> > 
> > ...Yet somehow Roblox by itself works completely fine with it installed?
> 
> How was it possible? Was it something to do with the latter's ldntvdm.dll interfering with the former?

Not sure. Installing ntvdm seems to affect cmd/conhost as well, changing it to the legacy console. (probably unrelated, but just throwing that out there)

**Comment by bluepilledgreat** [comment]
Is this still occurring?

**Comment by bluepilledgreat** [comment]
Client issues are no longer accepted.
