### ISSUE TITLE
[BUG] Items out of place

### ISSUE THREAD

**Issue by Wireframescript** [bloxstraplabs/bloxstrap#979]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Was playing tower defense X and some items appear out of place and i can go through them  but they wont go away from the screen 
![image](https://github.com/pizzaboxer/bloxstrap/assets/151986943/667cd216-fad9-44c3-9a4a-ced8ce6e30f9)
![inthenameofgod](https://github.com/pizzaboxer/bloxstrap/assets/151986943/054a9391-85c6-4fda-99bc-ea54e269c895)

**Comment by Wireframescript** [comment]
Video to help with the issue
https://github.com/pizzaboxer/bloxstrap/assets/151986943/6bb18074-ac6d-4daf-9d45-ca9124275c68

**Comment by Wireframescript** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/151986943/7421a165-582c-424a-9291-3759ffb1c6f2)

https://github.com/pizzaboxer/bloxstrap/assets/151986943/7ef5e340-848d-4f9b-b007-08367a7f5590

Not to mention it also glitches some animations in the game

**Comment by pizzaboxer** [comment]
Can I see the list of FastFlags you have configured in the Bloxstrap menu? Show a picture of the flag editor.

**Comment by Wireframescript** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/151986943/c6c9924b-c2c2-4a80-89fc-3a9faefea514)
![image](https://github.com/pizzaboxer/bloxstrap/assets/151986943/823fe051-11aa-4d53-99f9-7a12765adb6b)

**Comment by pizzaboxer** [comment]
I'm inclined to believe that this isn't really my problem. Does this happen every time that you play a game?

**Comment by Wireframescript** [comment]
Yep, it happens in any game i get, when i unistall bloxstrap it becomes normal, but when im playing with bloxstrap the game glitches like that

**Comment by pizzaboxer** [comment]
What about if you set your rendering framerate to zero?

**Comment by Wireframescript** [comment]
Still the same issue, i might have found the issue, when i open bloxstrap menu and change the render to voxel, it really glitches the models out making it that way, but if i put on future everythings on place

**Comment by pizzaboxer** [comment]
How about you just keep it set to "chosen by game"?

**Comment by pizzaboxer** [comment]
Sorry for not responding earlier. I just want to further clarify on this: if you delete all the flags you have configured, like the ones you showed in the picture earlier (so it's back to stock settings), does it continue to happen?

**Comment by bluepilledgreat** [comment]
I'm assuming that this issue is now resolved. If not, please ask for the issue to be reopened.
